//! The freestanding aarch64 test kernel: build one isolated EL0 program,
//! install a `MemMap` producer over its live address space, and route the
//! program's allocator-issued `mem_map`/`mem_unmap` syscalls through it
//! (PI P6e-3b prerequisite — `plans/PI.md`).

use core::cell::UnsafeCell;
use core::num::NonZeroU16;
use core::panic::PanicInfo;
use core::sync::atomic::{AtomicUsize, Ordering};

use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_abi::{
    i32_from_register, CapabilityId, CapabilityQuery, Errno, MapFlags, SyscallNumber,
    SYSCALL_MAX_ARGS,
};
use tairix_arch_aarch64::context_hal::ContextSwitchHal;
use tairix_arch_aarch64::kernel_arch::timer_frequency_hz;
use tairix_arch_aarch64::paging::{
    self, activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool,
};
use tairix_arch_aarch64::userentry::USER_MODE;
use tairix_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, SERIAL_SINK,
};
use tairix_arch_api::fatal::KernelFault;
use tairix_arch_api::BOOT_CPU;
use tairix_fdt::Fdt;
use tairix_itest_finisher::fail_code;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel_core::UserThreadEntry;
use tairix_kernel_core::{
    spawn_image, spawn_user_kthread, MemMap, SpawnMode, SpawnRequest, Yielder,
};
use tairix_kernel_mem::{
    map_anonymous, page_count_for, unmap_anonymous, AddressSpace, AnonError, DirectPhysMap, Frame,
    PhysAddr, Retire, Unpublished, UserStack,
};
use tairix_kernel_sched_eevdf::{Priority, Scheduler, SchedulerConfig};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level};

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// Gigabytes of identity map the EL0 address space provides: `[0, 2 GiB)`
/// covers the `virt` board's device MMIO (GiB 0) and the RAM base at GiB 1
/// where this kernel runs. [`USER_BIAS`] (64 GiB) and the heap arena (96 GiB)
/// sit far above, on freshly walked tables.
const IDENTITY_GIB: usize = 2;

/// User stack base (1 MiB into the high user region) and size.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (256 KiB).
const USER_STACK_PAGES: u64 = 64;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// Physical frames the test hands the spawn build and the heap's anonymous
/// maps. The heap draws frames monotonically (unmaps return them to a no-op
/// sink, not the pool), so this covers the *cumulative* page traffic of the
/// fixture's Box + growing-Vec + reallocation, plus the high-arena page-table
/// frames — comfortably bounded under a few hundred.
const FRAME_COUNT: usize = 512;

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4290);
const TEST_SPAWNED: EventId = EventId(4291);
const TEST_PASS: EventId = EventId(4292);
const TEST_FAIL: EventId = EventId(4293);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_GIC: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_PARSE: NonZeroU16 = fail_point!(4);
const FAIL_BUILD: NonZeroU16 = fail_point!(5);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(6);
const FAIL_SPAWN: NonZeroU16 = fail_point!(7);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(8);
const FAIL_UNEXPECTED_SYSCALL: NonZeroU16 = fail_point!(9);
const FAIL_FAULT: NonZeroU16 = fail_point!(10);
/// The fixture verified every value and exited cleanly, but no range ever
/// reached `mem_unmap` — the release path went untested.
const FAIL_NO_UNMAP: NonZeroU16 = fail_point!(11);
/// The fixture exited cleanly but a release it asked for was refused, so its
/// arena never shrank.
const FAIL_REFUSED_UNMAP: NonZeroU16 = fail_point!(12);
/// Base finisher for a non-zero `exit` from the fixture (a verification
/// failure); the program's exit code is added so the failing step is
/// identifiable.
const FAIL_EXIT_BASE: NonZeroU16 = fail_point!(100);

/// Size of the test's bump heap (startup block buffers + the user kthread's
/// kernel stack + control block). Lives in `.bss` (zeroed by the trampoline).
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the EL0 address space.
static PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Physical-frame backing store the spawn builder and the heap's anonymous maps
/// draw user pages from. `align(4096)` so each `PAGE_SIZE` slice is a valid page
/// frame; identity-mapped (its physical address equals its kernel virtual
/// address), so the builders reach it through [`DirectPhysMap::identity`].
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Hand out the next identity-mapped physical frame, or `None` when exhausted.
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(base)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn heap_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires. It does not widen the program's
/// own authority.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The live EL0 address space the anonymous map/unmap mutate, plus the kernel
/// direct-physical map used to zero frames on map and on free.
struct LiveSpace {
    space: AddressSpace<ArchAddressSpace>,
    physmap: DirectPhysMap,
}

/// The `MemMap` producer the test installs: it maps and unmaps anonymous `RW`
/// memory in the retained live EL0 space through the architecture-neutral
/// `kernel/mem` producer (`map_anonymous`/`unmap_anonymous`), exactly the seam
/// the production handler reaches (`plans/SPAWN.md` SP5b).
struct AnonProducer {
    inner: UnsafeCell<Option<LiveSpace>>,
    /// Ranges handed back through `mem_unmap`. The arena is resized in
    /// granules, so no *individual* free need reach the syscall — but the
    /// fixture's pressure-band trim must, and a run where it never arrived has
    /// left `mem_unmap` untested rather than proved it.
    unmaps: AtomicUsize,
    /// Releases the producer refused. A refusal is not a benign miss: the
    /// heap keeps the pages and asks again when the arena next moves, so a
    /// run that refuses is a run whose arena never shrinks. Counting them is
    /// what makes the release *succeed* part of the assertion rather than
    /// just arriving.
    refusals: AtomicUsize,
}

// SAFETY: the test runs on a single CPU and the producer is reached only
// synchronously from the cooperative syscall-dispatch callback (never from
// interrupt context, never cross-CPU, never re-entrantly — one `svc` is
// serviced at a time), so the interior `&mut` the methods take out can never
// alias. This mirrors the single-CPU cooperative discipline the rest of the
// vertical relies on (the access is genuinely exclusive).
unsafe impl Sync for AnonProducer {}

impl AnonProducer {
    const fn new() -> Self {
        Self {
            inner: UnsafeCell::new(None),
            unmaps: AtomicUsize::new(0),
            refusals: AtomicUsize::new(0),
        }
    }

    /// Ranges released through `mem_unmap` so far.
    fn unmaps(&self) -> usize {
        self.unmaps.load(Ordering::Relaxed)
    }

    /// Releases refused so far.
    fn refusals(&self) -> usize {
        self.refusals.load(Ordering::Relaxed)
    }

    /// Tear down the pages of `[base, base + len)`, whichever mappings the
    /// heap obtained them in.
    fn release(&self, base: u64, len: usize, retire: &mut dyn Retire) -> Result<(), Errno> {
        let page_count = page_count_for(len).map_err(anon_to_errno)?;
        let live = self.live()?;
        unmap_anonymous(
            &mut live.space,
            &live.physmap,
            base,
            page_count,
            retire,
            &mut |_frame| {},
        )
        .map_err(anon_to_errno)
    }

    /// Install the retained live space. Called once at boot, before the
    /// dispatch callback can fire.
    ///
    /// # Safety
    ///
    /// Must be called exactly once on the boot CPU before any `mem_map`/
    /// `mem_unmap` is dispatched, so no `&mut` from [`Self::live`] is live.
    unsafe fn install(&self, live: LiveSpace) {
        // SAFETY: see the function contract; single CPU, called once before
        // any dispatch, so nothing aliases the cell.
        unsafe { *self.inner.get() = Some(live) };
    }

    /// Borrow the retained live space mutably, or [`Errno::NotImplemented`]
    /// if none was installed (fail closed).
    fn live(&self) -> Result<&mut LiveSpace, Errno> {
        // SAFETY: see the `unsafe impl Sync` justification — the dispatch path
        // is single-CPU and non-reentrant, so this exclusive borrow is unique.
        let slot = unsafe { &mut *self.inner.get() };
        slot.as_mut().ok_or(Errno::NotImplemented)
    }
}

/// The single installed producer.
static PRODUCER: AnonProducer = AnonProducer::new();

/// Map an [`AnonError`] onto a stable [`Errno`] for the syscall result, folding
/// allocator exhaustion onto [`Errno::OutOfMemory`] and a
/// not-mapped range onto [`Errno::NotFound`] (fail closed).
fn anon_to_errno(err: AnonError) -> Errno {
    match err {
        AnonError::ZeroLength => Errno::LengthOutOfRange,
        AnonError::Unaligned | AnonError::Overflow => Errno::OutOfRange,
        AnonError::OutOfMemory => Errno::OutOfMemory,
        AnonError::NotMapped => Errno::NotFound,
        AnonError::PhysUnmapped | AnonError::Map(_) => Errno::BadAddress,
        // `AnonError` is `#[non_exhaustive]`; a future variant maps to the
        // generic bad-address error rather than being silently dropped.
        _ => Errno::BadAddress,
    }
}

impl MemMap for AnonProducer {
    fn reserve(&self, len: usize, flags: MapFlags, addr_hint: u64) -> Result<u64, Errno> {
        // This harness is an arch-mechanism proving ground that drives
        // `map`/`unmap` directly (the demand-paged reserve-then-fault-in
        // policy lives in `kernel/core` and is covered by its host tests),
        // so a reservation here simply performs the eager map.
        self.map(len, flags, addr_hint)
    }

    fn commit(&self, _pages: u64) -> Result<(), Errno> {
        // This proving-ground producer maps eagerly and tracks no
        // no-overcommit budget, so a headroom reservation is a no-op that
        // permits the (rare) stack-growth path to proceed to `map`.
        Ok(())
    }

    fn map(&self, len: usize, flags: MapFlags, addr_hint: u64) -> Result<u64, Errno> {
        let page_count = page_count_for(len).map_err(anon_to_errno)?;
        // The `tairix-rt` heap always maps with FIXED placement at the next
        // base of its own growable arena, so this producer maps exactly there
        // (a placement allocator is the production concern, not this proving
        // ground).
        if !flags.is_fixed() {
            return Err(Errno::NotImplemented);
        }
        let live = self.live()?;
        map_anonymous(
            &mut live.space,
            &live.physmap,
            addr_hint,
            page_count,
            next_frame,
            |_frame| {},
        )
        .map_err(anon_to_errno)?;
        Ok(addr_hint)
    }

    fn unmap(&self, base: u64, len: usize, retire: &mut dyn Retire) -> Result<(), Errno> {
        let result = self.release(base, len, retire);
        let counter = if result.is_ok() {
            &self.unmaps
        } else {
            &self.refusals
        };
        counter.fetch_add(1, Ordering::Relaxed);
        result
    }
}

/// Encode a `Result<u64, Errno>` into the syscall return register following the
/// `abi-v1` signed convention: a non-negative value on success, `-errno` on
/// error (the encoding `tairix_rt::mem_map`/`mem_unmap` decode).
fn encode(result: Result<u64, Errno>) -> u64 {
    match result {
        Ok(value) => value,
        Err(err) => {
            let neg = -i64::from(err.as_i32());
            neg as u64
        }
    }
}

/// The syscall-dispatch callback the EL0 program's `svc` traps reach.
///
/// `mem_map`/`mem_unmap` (issued by the heap allocator inside `tairix-rt`) are
/// routed through the installed [`PRODUCER`] (the `MemMap` seam). An `exit`
/// reports the result: code 0 is the success the fixture reaches only after
/// every allocation, write, read-back, and free succeeded (PASS); a non-zero
/// code is a verification failure reported with its code. Any other syscall is
/// unexpected and fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: `args_ptr` points at the live `[u64; SYSCALL_MAX_ARGS]` the
    // exception handler built from the saved register frame; reading it for the
    // duration of this call is sound.
    let args = unsafe { &*args_ptr };
    let call = SyscallNumber::from_register(number).ok();

    if call == Some(SyscallNumber::MEM_MAP) {
        let len = args[0] as usize;
        if len == 0 {
            return encode(Err(Errno::LengthOutOfRange));
        }
        // The flags slot is a 32-bit word; `from_bits` then refuses any
        // reserved bit, so a bad word fails closed.
        #[allow(clippy::cast_possible_truncation)]
        let flags = match MapFlags::from_bits(args[1] as u32) {
            Ok(flags) => flags,
            Err(err) => return encode(Err(err)),
        };
        encode(PRODUCER.map(len, flags, args[2]))
    } else if call == Some(SyscallNumber::MEM_UNMAP) {
        let base = args[0];
        let len = args[1] as usize;
        if len == 0 {
            return encode(Err(Errno::LengthOutOfRange));
        }
        // This kernel serves no copy path, so the page table is the only view.
        encode(PRODUCER.unmap(base, len, &mut Unpublished).map(|()| 0))
    } else if call == Some(SyscallNumber::EXIT) {
        let exit_code = i32_from_register(args[0]);
        if exit_code == 0 {
            if PRODUCER.refusals() > 0 {
                // The heap asked for a range the producer would not release.
                // It keeps those pages and stops asking until the arena
                // moves, so the arena silently never shrinks — and on the
                // real syscall path, where the refusal came from the handler
                // rather than the mechanism, that was a frame's worth of
                // refused syscalls per teardown.
                note(
                    TEST_FAIL,
                    "heap test: a release the heap asked for was refused",
                );
                qemu_exit::exit_failure(FAIL_REFUSED_UNMAP);
            }
            if PRODUCER.unmaps() == 0 {
                // The fixture verifies its own values, so a clean exit says
                // nothing about the release path: without this a granule wide
                // enough to swallow the whole fixture would leave `mem_unmap`
                // uncovered and the run would still pass.
                note(
                    TEST_FAIL,
                    "heap test: fixture exited 0 but never released a range through mem_unmap",
                );
                qemu_exit::exit_failure(FAIL_NO_UNMAP);
            }
            note(
                TEST_PASS,
                "heap test: EL0 program allocated, grew, freed, reused, trimmed, and exited 0",
            );
            qemu_exit::exit_success();
        }
        note(TEST_FAIL, "heap test: fixture exited non-zero");
        qemu_exit::exit_failure(fail_code(FAIL_EXIT_BASE, exit_code));
    } else {
        note(TEST_FAIL, "heap test: fixture issued an unexpected syscall");
        qemu_exit::exit_failure(FAIL_UNEXPECTED_SYSCALL);
    }
}

/// The fault handler: the fixture never faults on the success path (it frees
/// its allocations cleanly and exits), so any fault is a failure (never returns).
fn on_fault(_trap: KernelFault) -> ! {
    note(TEST_FAIL, "heap test: unexpected fault");
    qemu_exit::exit_failure(FAIL_FAULT);
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `tairix_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 heap test: starting");

    // Enable FP/SIMD at EL1 before any code that may use it (the `rxe` decoder
    // and the image fills compile to NEON `memcpy`/`memcmp`).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    // P3/P4: discover the board from the embedded `virt` device tree.
    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Parse the build-time `rxe` blob against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        qemu_exit::exit_failure(FAIL_PARSE);
    };

    // Build the EL0 address space and activate it (so the user mappings, and
    // later the heap arena, land in the active translation regime).
    let Some(arch) = ArchAddressSpace::new_identity_gigapages(&PAGE_TABLES, IDENTITY_GIB) else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    let root_phys = arch.root_phys();
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, heap,
    // frame pool, and device MMIO (all within `[0, 2 GiB)` on `virt`), so
    // switching it does not move the ground under the running code. Boot CPU.
    unsafe { arch.switch() };

    let mut space = AddressSpace::new(arch);
    // SAFETY: the boot code identity-maps this window and never unmaps it.
    let physmap = unsafe { DirectPhysMap::identity((IDENTITY_GIB as u64) << 30) }
        .expect("the boot direct map addresses its window");
    let request = SpawnRequest {
        image: &image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"heap"],
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once the space is reactivated (via `pre_resume`) and
    // the trap path is installed. Frames are drawn from `FRAME_POOL`.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => qemu_exit::exit_failure(FAIL_BUILD),
    };

    // Retain the live space behind the `MemMap` producer so the program's
    // `mem_map`/`mem_unmap` syscalls mutate exactly the active address space.
    // SAFETY: called once on the boot CPU before the dispatch callback (and
    // thus any `mem_map`) can fire.
    unsafe { PRODUCER.install(LiveSpace { space, physmap }) };

    // Bring up the EL1 vectors + GICv2 and install the dispatch + fault
    // callbacks. Interrupts stay masked — the cooperative `step` loop is the
    // only scheduling mechanism.
    // SAFETY: called once on the boot CPU with a stack established and the MMU
    // enabled (the address-space build switched it on).
    unsafe {
        exceptions::init_vectors();
        tairix_itest_gic::init_boot_cpu().expect("the GIC comes up");
    }
    syscall_entry::set_dispatch_callback(dispatch);
    if tairix_arch_api::fault::set_fault_handler(on_fault).is_err() {
        qemu_exit::exit_failure(FAIL_FAULT);
    }

    // Build the live scheduler over the arch port.
    // Per-CPU bookkeeping backing for this single-CPU vertical.
    static ARCH_STORAGE: tairix_arch_aarch64::Aarch64ArchStorage<1> =
        tairix_arch_aarch64::Aarch64ArchStorage::new();
    let arch = Arc::new(tairix_arch_aarch64::Aarch64Arch::new(
        &ARCH_STORAGE,
        BOOT_CPU,
        counter_hz,
    ));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    // Admit the EL0 program as a resumable user kthread: its `pre_resume` hook
    // reactivates its page-table root before every switch-in (isolation),
    // and its work body `enter_user`s into EL0.
    let cs = ContextSwitchHal::new();
    let pre_resume = move |_stack_top: u64| {
        // SAFETY: the MMU is enabled and `root_phys` is the L1 root of a space
        // that identity-maps the low kernel window — `activate_user_root`'s
        // contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: the entered space is active (the `pre_resume` hook just
        // reactivated it) and the EL1 trap vector + dispatch callback are
        // installed, so the program's `svc`s are handled.
        unsafe {
            UserThreadEntry {
                port: &USER_MODE,
                regs: entry,
            }
            .enter(yielder)
        }
    };
    if spawn_user_kthread(&sched, cs, BOOT_CPU, Priority::Normal, pre_resume, work).is_err() {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(TEST_SPAWNED, "aarch64 heap test: EL0 program spawned");

    // Drive `step` until the program runs to its `exit` (PASS/FAIL reported in
    // the dispatch callback). A never-draining loop times out (fail-loud).
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }

    // Reaching here means the program drained without ever calling `exit` —
    // the workload stalled or returned without the runtime's `exit`.
    if steps >= MAX_STEPS {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }
    qemu_exit::exit_failure(FAIL_DEADLOCK);
}
