//! Build-time generator for the Stage 4 QEMU integration test fixture.
//!
//! The freestanding `x86_64-tairix-none` binary that runs under QEMU
//! cannot pull `ed25519-dalek` in directly (the charter forbids
//! hand-rolled crypto; `lib/crypto` is the only auditable surface that
//! exposes verification). This `build.rs` runs on the host where
//! `ed25519-dalek` is available, signs a synthetic `.rxe` manifest
//! with a deterministic test seed, and emits a Rust source file the
//! main bin pulls in via `include!`. The emitted file declares two
//! consts:
//!
//! * `MOCK_IMAGE: &[u8]` — the signed driver image bytes.
//! * `TRUSTED_SIGNER_PUBKEY: [u8; 32]` — the host's trust-anchor key
//!   that the binary registers on its `HostConfig`.
//!
//! Re-running `build.rs` produces byte-identical output for the same
//! seed; the test is therefore deterministic.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;
use tairix_abi::{DriverKind, DriverManifest, DRIVER_MANIFEST_MAGIC};
use tairix_crypto::Ed25519SecretKey;

const TEST_SEED: [u8; 32] = [
    0x42, 0x6e, 0x47, 0x2c, 0x90, 0x12, 0xd1, 0x35, 0x99, 0xa0, 0x77, 0x80, 0x6a, 0xa3, 0x21, 0x18,
    0x73, 0xd6, 0xc0, 0x55, 0xe2, 0xb1, 0x47, 0x83, 0x18, 0x44, 0x91, 0x55, 0xee, 0x66, 0x9c, 0x0a,
];

/// SHA-256 fingerprint of the host's syscall table. Tests do not need
/// to track the real value; what matters is that both sides agree, so
/// we generate a fixed pattern and feed the same one into the host's
/// `HostConfig` from the bin.
const SYS_HASH: [u8; 32] = [0x11; 32];

fn main() {
    tairix_itest_harness::emit_target_cfg();
    println!("cargo:rerun-if-changed=build.rs");

    tairix_itest_harness::link_x86_64_kernel_layout();

    let signing_key = Ed25519SecretKey::from_seed(&TEST_SEED);
    let signer_pubkey: [u8; 32] = *signing_key.public_key().as_bytes();

    let caps: &[u16] = &[/* no capabilities requested */];
    let mut manifest = DriverManifest {
        magic: DRIVER_MANIFEST_MAGIC,
        abi_version: tairix_abi::ABI_VERSION_CURRENT,
        kind: DriverKind::UserSpace,
        bind_key_count: 0,
        capability_count: u16::try_from(caps.len()).expect("caps fit in u16"),
        syscall_table_hash: SYS_HASH,
        signer_pubkey,
        signature: [0u8; 64],
    };
    let encoded = manifest.to_le_bytes();
    let mut signed_message = Vec::with_capacity(DriverManifest::WIRE_LEN - 64 + caps.len() * 2);
    signed_message.extend_from_slice(&encoded[..DriverManifest::WIRE_LEN - 64]);
    for c in caps {
        signed_message.extend_from_slice(&c.to_le_bytes());
    }
    let sig = signing_key.sign(&signed_message);
    manifest.signature = *sig.as_bytes();

    let mut image: Vec<u8> = Vec::new();
    image.extend_from_slice(&manifest.to_le_bytes());
    for c in caps {
        image.extend_from_slice(&c.to_le_bytes());
    }
    // No opaque payload bytes are needed: the spawner in the bin
    // returns its single registered entry regardless of payload
    // content.

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    out.push_str("/// Signed mock `.rxe` image bytes.\n");
    out.push_str("pub const MOCK_IMAGE: &[u8] = &[");
    for (i, b) in image.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n\n");
    out.push_str("/// Trust-anchor public key the host's `HostConfig` is wired to accept.\n");
    out.push_str("pub const TRUSTED_SIGNER_PUBKEY: [u8; 32] = [");
    for (i, b) in signer_pubkey.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n\n");
    out.push_str("/// SHA-256 fingerprint of the host's syscall table.\n");
    out.push_str("pub const SYSCALL_TABLE_HASH: [u8; 32] = [");
    for (i, b) in SYS_HASH.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR set by cargo");
    let path = PathBuf::from(out_dir).join("mock_fixture.rs");
    fs::write(&path, out).expect("write mock_fixture.rs");
}
