//! The freestanding aarch64 test kernel: prove the per-service account
//! ceiling binds a lying manifest end to end (`plans/USERS.md` U4).
//!
//! Every syscall here runs the production `KernelDispatchHook` /
//! `KernelSyscallHandlers` path: the chassis installs the hook through a
//! `DispatchCallbackSlot`, wires the **real compiled system identity table**
//! (`tairix_kernel_core::system_identity_table`) into the spawn-as-user
//! seam, seeds the hardware tree backing `hw_tree_read`, and registers the
//! `svc` role under a manifest that requests devmgr's ceiling plus every
//! sibling service's defining capability. The parent role is spawned
//! through the production `InitSpawnCtx::spawn_driver_process` seam with
//! `CAP_PROC_SPAWN` + `CAP_SPAWN_AS_USER`; it switches `svc` into the
//! devmgr account through the production `spawn` syscall and propagates its
//! verdict. The chassis reaps the parent and PASSes only on exit 0.

use core::num::NonZeroU16;
use core::panic::PanicInfo;

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::hwtree::{HwDeviceClass, HwNode, HW_NODE_ROOT};
use tairix_abi::{CapabilityId, Errno, WaitFlags, WaitStatus, SYSCALL_MAX_ARGS};
use tairix_arch_aarch64::kernel_arch::timer_frequency_hz;
use tairix_arch_aarch64::paging::{
    configure_device_gigapages, configure_kernel_gigapages, install_boot_physmap,
    AddressSpace as ArchAddressSpace, PageTablePool, GIGAPAGE_MASK_WORDS,
};
use tairix_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, Aarch64Arch,
    Aarch64ArchStorage, SERIAL_SINK,
};
use tairix_arch_api::BOOT_CPU;
use tairix_caps::CapabilitySet;
use tairix_fdt::Fdt;
use tairix_itest_finisher::fail_code;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel::aarch64::arch_wrapper::{Aarch64BinArch, UART_ONLY_CONSOLES};
use tairix_kernel::aarch64::spawn_producer::{AARCH64_PROCESS_SPAWN, USER_IMAGE_BIAS};
use tairix_kernel::dispatch_core::{dispatch_via_slot, read_raw_args, resolve_user_fault_via_slot};
use tairix_kernel::hwtree_store::{HW_TREE, HW_TREE_SOURCE};
use tairix_kernel_core::{
    AddressSpaceRegistry, BootReserve, DispatchCallbackSlot, EmbeddedProgram, InitSpawnCtx,
    KernelArch, KernelDispatchHook, KernelInitSpawner, KernelProcessWait, LateIdentity, LiveMemMap,
    ProcessWait, ProgramRegistry, RandomReserve, SchedWaitQueueArch, NULL_DMA_ALLOC_FACILITY,
    NULL_MMIO_MAP_FACILITY, NULL_SEAT_REGISTRY, NULL_SHARED_MEM_FACILITY,
};
use tairix_kernel_ipc::PortRegistry;
use tairix_kernel_irq::{IrqTable, UnsupportedController};
use tairix_kernel_mem::{
    BootMemoryMap, FrameAllocator, MemoryRegion, PhysAddr, RegionKind, PAGE_SIZE,
};
use tairix_kernel_sched_cfq::{Scheduler, SchedulerConfig};
use tairix_kernel_sec::{CapTable, ProcessId};
use tairix_log::{log, Event, EventId, Level};
use tairix_sync::RwLock;

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// Gigabytes of identity map the boot address space provides: `[0, 2 GiB)`
/// covers the `virt` board's device MMIO (GiB 0) and the RAM base at GiB 1
/// where this kernel, its heap, and the frame pool live.
const IDENTITY_GIB: usize = 2;

/// Physical frames the production spawn producer draws from: two spawned
/// processes (image, eagerly committed stack top, page tables,
/// identity-window tables) with generous headroom (16 MiB).
const FRAME_COUNT: usize = 4096;

/// Longest decimal argument the rows below need (`u32::MAX` is 10 digits).
const DEC_MAX: usize = 10;

/// Render `value` as a fixed-width, zero-padded decimal byte string at
/// compile time. Leading zeroes are harmless: the fixture's parser accepts
/// them, and a fixed width lets the argument live in a `static` the
/// registry row borrows.
const fn dec_bytes(mut value: u32) -> [u8; DEC_MAX] {
    let mut out = [b'0'; DEC_MAX];
    let mut i = DEC_MAX;
    while i > 0 {
        i -= 1;
        out[i] = b'0' + (value % 10) as u8;
        value /= 10;
        if value == 0 {
            break;
        }
    }
    out
}

/// The devmgr service uid as a decimal argument-vector value — resolved
/// from the one compiled account set, never a copied constant.
static DEVMGR_UID_ARG: [u8; DEC_MAX] = dec_bytes(tairix_users::DEVMGR_UID.0);

/// The sibling services' defining capabilities the `svc` manifest lies
/// about: login's spawn-as-user + users-read pair, seatmgr's seat
/// administration, and sysinfod's privileged introspection primitive.
const SIBLING_CAPS: [CapabilityId; 4] = [
    CapabilityId::SPAWN_AS_USER,
    CapabilityId::USERS_READ,
    CapabilityId::SEAT_ADMIN,
    CapabilityId::SYSINFO_INTROSPECT,
];

/// The `svc` row's manifest length: devmgr's whole ceiling plus the
/// sibling capabilities above.
const SVC_MANIFEST_LEN: usize = tairix_users::DEVMGR_CEILING.len() + SIBLING_CAPS.len();

/// Concatenate devmgr's ceiling and [`SIBLING_CAPS`] at compile time, so
/// the lying manifest imports the one ceiling definition rather than
/// copying its members.
const fn svc_manifest() -> [CapabilityId; SVC_MANIFEST_LEN] {
    let mut out = [SIBLING_CAPS[0]; SVC_MANIFEST_LEN];
    let mut i = 0;
    while i < tairix_users::DEVMGR_CEILING.len() {
        out[i] = tairix_users::DEVMGR_CEILING[i];
        i += 1;
    }
    let mut j = 0;
    while j < SIBLING_CAPS.len() {
        out[i + j] = SIBLING_CAPS[j];
        j += 1;
    }
    out
}

/// The `svc` role's deliberately over-wide manifest request.
static SVC_MANIFEST: [CapabilityId; SVC_MANIFEST_LEN] = svc_manifest();

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4470);
const TEST_SPAWNED: EventId = EventId(4471);
const TEST_PASS: EventId = EventId(4472);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_GIC: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_FRAMES: NonZeroU16 = fail_point!(4);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(5);
const FAIL_SPAWN: NonZeroU16 = fail_point!(6);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(7);
const FAIL_NO_DISPATCH: NonZeroU16 = fail_point!(8);
const FAIL_HOOK_INSTALL: NonZeroU16 = fail_point!(9);
const FAIL_RESOLVER_INSTALL: NonZeroU16 = fail_point!(10);
const FAIL_BIAS: NonZeroU16 = fail_point!(11);
const FAIL_POLL: NonZeroU16 = fail_point!(12);
const FAIL_DRAINED: NonZeroU16 = fail_point!(13);
const FAIL_PARENT_STOPPED: NonZeroU16 = fail_point!(14);
const FAIL_IDENTITY: NonZeroU16 = fail_point!(15);
/// The direct physical map could not be installed over the board's RAM.
const FAIL_PHYSMAP: NonZeroU16 = fail_point!(16);
/// The hardware tree refused its seed.
const FAIL_TREE_SEED: NonZeroU16 = fail_point!(17);
/// Base finisher for a non-zero parent exit; the parent's diagnostic exit
/// code is added so the failing role/site is identifiable in the finisher.
const FAIL_EXIT_BASE: NonZeroU16 = fail_point!(100);

/// Size of the test's bump heap. Lives in `.bss` (zeroed by the trampoline).
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the kernel's own boot identity map.
static BOOT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Identity-mapped physical-frame backing store the live [`FrameAllocator`]
/// serves the spawn producer and the stack-growth fault path from; inside
/// the 2 GiB identity window the producer's page-table walk requires.
#[repr(C, align(4096))]
struct FramePool([u8; PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; PAGE_SIZE * FRAME_COUNT]);

/// The dispatch-callback slot the production [`KernelDispatchHook`] is
/// installed into (one slot per binary, set once). Both the syscall
/// callback and the user-fault resolver resolve through it.
static DISPATCH_SLOT: DispatchCallbackSlot = DispatchCallbackSlot::new();

/// Per-CPU storage backing the scheduler's arch handle.
static SCHED_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// Per-CPU storage backing the dispatch hook + spawn ctx arch handle.
static HOOK_ARCH_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// This vertical binds no IRQ lines; the fail-closed controller mirrors
/// what `kernel/core::init` installs when a port exposes no routing.
static IRQ_CONTROLLER: UnsupportedController = UnsupportedController;

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn service_ceiling_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// The syscall-dispatch callback every program's `svc` traps reach. It
/// mirrors the production bin-crate callback (`dispatch_aarch64`): read the
/// kernel-stack args frame and forward through the resident production
/// [`KernelDispatchHook`] via the shared `dispatch_via_slot` bridge. An
/// empty slot or a missing caller context fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the exception trampoline lays the frame out on the kernel
    // stack and only invokes us with a valid pointer; the array lives at
    // least until we return.
    let args = unsafe { read_raw_args(args_ptr) };
    match dispatch_via_slot(&DISPATCH_SLOT, number, args) {
        Some(value) => value,
        None => qemu_exit::exit_failure(FAIL_NO_DISPATCH),
    }
}

/// The user-fault resolver the EL1 data-abort path calls for every EL0
/// data abort: the exact production glue (`production_user_fault`), bound
/// to this vertical's own slot so an in-span stack-growth fault runs the
/// resident production hook's `resolve_stack_fault` path and an
/// unresolvable fault kills the faulting task through the production
/// fault-exit path.
// The callback matches the arch `UserFaultResolveFn` type (a bare safe
// `extern "C" fn`); the raw pointer is only forwarded into the guarded
// `unsafe` call below, which narrows it with `as_ref`.
#[allow(clippy::not_unsafe_ptr_arg_deref)]
extern "C" fn service_ceiling_user_fault(
    far: u64,
    write: bool,
    regs: *const tairix_arch_api::backtrace::UserRegisterFrame,
) -> bool {
    // SAFETY: the trap handler builds the frame on its kernel stack and
    // holds it live across this call, or passes null; the slot helper
    // narrows the pointer with `as_ref` and never dereferences null.
    unsafe { resolve_user_fault_via_slot(&DISPATCH_SLOT, far, write, regs) }
}

/// The capability set the parent runs under: `CAP_PROC_SPAWN` for its
/// `spawn` call and `CAP_SPAWN_AS_USER` for the identity switch into the
/// devmgr account — exactly the pair PID 1 `init` holds for the same job.
/// The switch resolves the child's ceiling from the installed identity
/// table, never from this set, so the parent's grant does not widen the
/// child.
fn parent_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::PROC_SPAWN);
    caps.insert(CapabilityId::SPAWN_AS_USER);
    caps
}

/// The program registry the production `spawn` syscall resolves the
/// parent's switch against: one `svc` row whose manifest deliberately
/// requests devmgr's whole ceiling plus every sibling service's defining
/// capability ([`SVC_MANIFEST`]). The intersection with devmgr's compiled
/// ceiling — resolved from the installed identity table — is exactly what
/// this vertical proves.
static CHILD_PROGRAMS: [EmbeddedProgram; 1] = [EmbeddedProgram {
    path: b"/bin/sc-svc",
    rxe: PROGRAM_RXE,
    caps: &SVC_MANIFEST,
    args: &[b"sc", b"svc"],
}];

/// The registry over [`CHILD_PROGRAMS`].
static PROGRAMS: ProgramRegistry = ProgramRegistry::new(&CHILD_PROGRAMS);

/// Bring the board up: FP/SIMD on, the `virt` device tree discovered
/// (timer rate, GICv2 bases), the identity-gigapage masks configured from
/// the board facts, the identity MMU + EL1 vectors enabled, the GIC
/// initialised, and the dispatch callback + user-fault resolver installed.
/// Returns the discovered generic-timer rate.
fn bring_up_board() -> u64 {
    // Enable FP/SIMD at EL1 before any code the compiler may lower to NEON
    // (the `rxe` decoder, the spawn image fills, the log formatter).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Configure the board's gigapage facts, exactly as the production boot
    // path derives them from discovery: Device GiB 0 is the `virt` MMIO
    // window, and GiB 1 holds both this kernel's image and its RAM. The
    // production spawn producer sizes every child's identity window from
    // these masks, so driving it under the unconfigured defaults would
    // request a window reaching the user bias and the spawn would fail
    // closed.
    let mut device_mask = [0u64; GIGAPAGE_MASK_WORDS];
    device_mask[0] = 0b01;
    configure_device_gigapages(device_mask);
    let mut ram_mask = [0u64; GIGAPAGE_MASK_WORDS];
    ram_mask[0] = 0b10;
    configure_kernel_gigapages(ram_mask);
    // The production spawn producer reaches a child's page tables through
    // the direct physical map in the kernel translation regime, so the
    // chassis stands it up over the same RAM before driving the producer.
    if !install_boot_physmap(&ram_mask) {
        qemu_exit::exit_failure(FAIL_PHYSMAP);
    }

    // Enable the identity MMU + EL1 vectors before any atomic
    // read-modify-write runs: the frame allocator, the scheduler, and every
    // registry the test builds use atomics, which are UNPREDICTABLE on
    // MMU-off Device-typed memory (`plans/PI.md` P6c-2).
    let Some(boot_space) =
        ArchAddressSpace::new_identity_gigapages(&BOOT_PAGE_TABLES, IDENTITY_GIB)
    else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
    // heap, the frame pool, and the device MMIO (all within `[0, 2 GiB)` on
    // the `virt` board), so switching it does not move the ground under the
    // running code; `init_vectors` runs once on the boot CPU with a stack
    // established.
    unsafe {
        boot_space.switch();
        exceptions::init_vectors();
    }
    // The boot space's tables live in the static `BOOT_PAGE_TABLES` pool
    // and the handle carries no `Drop`, so letting it fall out of scope
    // leaves the active translation regime untouched for the kernel's
    // lifetime (the kernel never returns).
    // SAFETY: called once on the boot CPU after the GIC bases were
    // discovered above.
    unsafe {
        gic::init();
    }
    syscall_entry::set_dispatch_callback(dispatch);
    // Bind the production user-fault resolver to this vertical's slot so a
    // fixture stack-growth fault resolves exactly as in production.
    if tairix_arch_api::fault::set_user_fault_resolver(service_ceiling_user_fault).is_err() {
        qemu_exit::exit_failure(FAIL_RESOLVER_INSTALL);
    }
    counter_hz
}

/// The leaked-`'static` kernel subsystems the production dispatch hook and
/// spawn context borrow — the vertical's analogue of `KernelState`, lifted
/// by one-shot `Box::leak` publishes exactly as `kernel_core::kernel_main`
/// does (a one-shot publish, not a global mutable static).
struct Subsystems {
    frames: &'static FrameAllocator,
    sched: &'static Scheduler<Aarch64BinArch>,
    arch: &'static Aarch64BinArch,
    caps: &'static RwLock<CapTable>,
    peer_watch: &'static tairix_kernel_core::PeerWatch,
    ipc: &'static RwLock<PortRegistry>,
    aspaces: &'static RwLock<AddressSpaceRegistry>,
    rng: &'static RwLock<Box<dyn RandomReserve + Send + Sync>>,
    irq_table: &'static IrqTable,
}

/// Build the live kernel subsystems: the `kernel/mem` frame allocator over
/// the identity-mapped pool (so the spawn producer and the demand-fault
/// path draw their frames from the production path), the scheduler over
/// the production `KernelArch` wrapper, and the capability / port /
/// address-space / random / IRQ state the production hook borrows.
fn leak_subsystems(counter_hz: u64) -> Subsystems {
    let mut memory_map = BootMemoryMap::new();
    memory_map.push(MemoryRegion {
        start: PhysAddr::new(core::ptr::addr_of!(FRAME_POOL) as u64),
        length: (PAGE_SIZE * FRAME_COUNT) as u64,
        kind: RegionKind::Usable,
    });
    let Ok(frames) = FrameAllocator::new(&memory_map) else {
        qemu_exit::exit_failure(FAIL_FRAMES);
    };
    let frames: &'static FrameAllocator = Box::leak(Box::new(frames));

    let sched_arch = Arc::new(Aarch64BinArch::new(Aarch64Arch::new(
        &SCHED_STORAGE,
        BOOT_CPU,
        counter_hz,
    )));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), sched_arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    Subsystems {
        frames,
        sched: Box::leak(Box::new(sched)),
        arch: Box::leak(Box::new(Aarch64BinArch::new(Aarch64Arch::new(
            &HOOK_ARCH_STORAGE,
            BOOT_CPU,
            counter_hz,
        )))),
        caps: Box::leak(Box::new(RwLock::new(CapTable::new()))),
        peer_watch: Box::leak(Box::new(tairix_kernel_core::PeerWatch::new())),
        ipc: Box::leak(Box::new(RwLock::new(PortRegistry::new()))),
        aspaces: Box::leak(Box::new(RwLock::new(AddressSpaceRegistry::new()))),
        rng: Box::leak(Box::new(RwLock::new(
            Box::new(BootReserve::new()) as Box<dyn RandomReserve + Send + Sync>
        ))),
        irq_table: Box::leak(Box::new(IrqTable::new(0))),
    }
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `tairix_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 service-ceiling test: starting");

    let counter_hz = bring_up_board();

    // The fixture `rxe`'s baked relocations must target the bias the
    // production producer maps every child at; a drifted constant would
    // admit a child whose pointers do not match its mapping (fail closed).
    if USER_BIAS != USER_IMAGE_BIAS {
        qemu_exit::exit_failure(FAIL_BIAS);
    }

    let sys = leak_subsystems(counter_hz);

    // Install the real compiled system identity table — the same table the
    // boot `sec` phase installs — so the parent's spawn-as-user switch
    // resolves devmgr's group set and capability ceiling from kernel
    // policy, never a test fabrication.
    let identity: &'static LateIdentity = Box::leak(Box::new(LateIdentity::new()));
    let Ok(table) = tairix_kernel_core::system_identity_table(&SERIAL_SINK) else {
        qemu_exit::exit_failure(FAIL_IDENTITY);
    };
    if identity.install(table).is_err() {
        qemu_exit::exit_failure(FAIL_IDENTITY);
    }

    // Seed the hardware tree with one node so the svc role's positive
    // `hw_tree_read` check reads a genuinely populated snapshot. The
    // node's content is irrelevant to the proof; a distinctive id keeps
    // the serial transcript legible.
    if HW_TREE
        .seed(alloc::vec![HwNode::new(
            0x0CE1,
            HW_NODE_ROOT,
            HwDeviceClass::Other
        )])
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_TREE_SEED);
    }

    // Publish the wait-queue arch hook so parked waiters (the parent in
    // `wait`) are genuinely unparked by their wake events — the same
    // adapter the production boot path installs.
    let wait_arch = SchedWaitQueueArch::leak(sys.sched, sys.arch);
    if tairix_kernel_core::waitq::install_wait_arch(wait_arch).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // The scheduler-side process-wait producer: records every parent/child
    // link the production spawn paths register and backs the production
    // `wait` syscall the parent blocks in.
    let wait_producer: &'static KernelProcessWait<Aarch64BinArch> =
        Box::leak(Box::new(KernelProcessWait::new(sys.arch)));

    // The production live-space producer: serves the `mem_map` pair (the
    // `tairix-rt` heap) and the one-page-per-fault backing the
    // stack-growth resolver maps through it.
    let live: &'static LiveMemMap<Aarch64BinArch> = Box::leak(Box::new(LiveMemMap::new(sys.arch)));

    // Publish the production dispatch hook: every syscall the programs
    // issue — the parent's `spawn` + `wait`, the svc role's `hw_tree_read`
    // and its four refused sibling attempts, and both `exit`s — runs the
    // production caller-context resolution and handler path. The identity
    // seam resolves the spawn-as-user switch; the hardware tree backs the
    // positive check; every other backing stays fail-closed, which is
    // irrelevant to the refused attempts because the dispatcher's
    // capability gate answers first.
    let hook: &'static KernelDispatchHook<'static, Aarch64BinArch> = Box::leak(Box::new(
        KernelDispatchHook::new(
            sys.sched,
            sys.caps,
            sys.arch,
            &SERIAL_SINK,
            sys.irq_table,
            &IRQ_CONTROLLER,
            sys.ipc,
            sys.aspaces,
            sys.rng,
            &UART_ONLY_CONSOLES,
            sys.frames,
            sys.frames,
            &PROGRAMS,
            wait_producer,
            &NULL_SEAT_REGISTRY,
            live,
            &NULL_MMIO_MAP_FACILITY,
            &NULL_DMA_ALLOC_FACILITY,
        )
        .with_peer_watch(sys.peer_watch)
        .with_identity(identity)
        .with_hw_tree(&HW_TREE_SOURCE),
    ));
    if DISPATCH_SLOT.install_dispatcher(hook).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // Spawn the parent role through the production runtime-spawn seam
    // (`KernelSpawnCtx` assembly inside `KernelInitSpawner`), recorded
    // against the kernel supervisor identity so this chassis can reap it.
    // Publish the launch-services bundle the deferred child-load path reads:
    // the arch image builder builds each admitted child's image on the
    // child's own first slice, off this chassis's cooperative drive. The one
    // shared build+publish the production boot path uses.
    let _ = tairix_kernel_core::spawn_services::install_over(
        sys.arch,
        sys.frames,
        &SERIAL_SINK,
        &tairix_kernel_core::NULL_FILESYSTEM,
        None,
        sys.aspaces,
        sys.caps,
        sys.peer_watch,
        wait_producer,
        &AARCH64_PROCESS_SPAWN,
    );

    let init_ctx = KernelInitSpawner::new(
        sys.frames,
        &SERIAL_SINK,
        sys.sched,
        sys.caps,
        sys.peer_watch,
        sys.aspaces,
        sys.arch,
        wait_producer,
        sys.irq_table,
        &NULL_SHARED_MEM_FACILITY,
        KernelArch::cross_cpu_tlb_shootdown(sys.arch),
    );
    let Ok(parent_pid) = init_ctx.spawn_driver_process(
        "/bin/sc-parent",
        PROGRAM_RXE,
        parent_caps(),
        &[],
        &[b"sc", b"parent", &DEVMGR_UID_ARG],
        None,
    ) else {
        qemu_exit::exit_failure(FAIL_SPAWN);
    };
    note(
        TEST_SPAWNED,
        "aarch64 service-ceiling test: parent spawned through the production seam",
    );
    drive_until_the_parent_exits(&sys, wait_producer, parent_pid)
}

/// The budget-bounded cooperative drive: step the scheduler and poll the wait
/// producer for the parent's exit between steps. The parent switches svc into
/// the devmgr account through the production spawn + wait; a parent exit of 0
/// is the PASS, anything else names the failing site through its diagnostic
/// code.
fn drive_until_the_parent_exits(
    sys: &Subsystems,
    wait_producer: &KernelProcessWait<Aarch64BinArch>,
    parent_pid: u64,
) -> ! {
    // A task id never exceeds the ABI's pid bound, so reinterpreting it as
    // the signed pid the wait ABI carries is exact.
    let parent_pid = parent_pid.cast_signed();
    let mut steps = 0u64;
    while steps < MAX_STEPS {
        let _ = sys.sched.step(BOOT_CPU);
        steps += 1;

        // Deliver any wake a handler deferred while the task ran — the same
        // between-dispatches service the production loop performs; without
        // it the child's `exit` never unparks the parent blocked in `wait`.
        let _ = tairix_kernel_core::waitq::drain_pending_wakes();

        match wait_producer.poll(ProcessId(0), parent_pid, WaitFlags::empty()) {
            Ok(reaped) => match reaped.status {
                WaitStatus::Exited(0) => {
                    note(
                        TEST_PASS,
                        "aarch64 service-ceiling test: the devmgr ceiling bound the lying manifest",
                    );
                    qemu_exit::exit_success();
                }
                WaitStatus::Exited(code) => {
                    qemu_exit::exit_failure(fail_code(FAIL_EXIT_BASE, code));
                }
                WaitStatus::Stopped(_) => {
                    qemu_exit::exit_failure(FAIL_PARENT_STOPPED);
                }
            },
            Err(Errno::WouldBlock) => {}
            Err(_) => qemu_exit::exit_failure(FAIL_POLL),
        }

        // A fully drained workload without a reapable parent means the
        // parent vanished down a path that never recorded its exit; fail
        // with a distinct finisher rather than spinning out the watchdog.
        if sys.sched.live_task_count() == 0 {
            qemu_exit::exit_failure(FAIL_DRAINED);
        }
    }
    qemu_exit::exit_failure(FAIL_DEADLOCK)
}
