//! The freestanding aarch64 test kernel: build child, parent, and intake EL0
//! programs, install a `KernelProcessSignal` producer over the shared
//! `KernelProcessWait` bookkeeping and the live scheduler, and prove
//!
//! * the parent terminates its own child with a signal and reaps the
//!   signalled status (`plans/SPAWN.md` `SP7b`), and
//! * a foreground `^C` pushed through the **real console line discipline**
//!   reaches an opted-in process's signal intake as an observable event
//!   instead of terminating it, while a second undrained `^C` escalates to
//!   the default terminate and reaps 130 (`plans/STRESSTEST.md` ST3).

use core::num::NonZeroU16;
use core::panic::PanicInfo;
use core::sync::atomic::{AtomicBool, AtomicU64, AtomicUsize, Ordering};

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_abi::{
    CapabilityId, CapabilityQuery, Errno, ProcId, Signal, SignalIntakeOp, SyscallNumber, WaitFlags,
    WaitStatus, WaitStatusRecord, SYSCALL_MAX_ARGS,
};
use tairix_arch_aarch64::context_hal::ContextSwitchHal;
use tairix_arch_aarch64::kernel_arch::timer_frequency_hz;
use tairix_arch_aarch64::paging::{
    self, activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool,
};
use tairix_arch_aarch64::userentry::UserMode;
use tairix_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, Aarch64Arch,
    Aarch64ArchStorage, SERIAL_SINK,
};
use tairix_arch_api::{EnterUser, BOOT_CPU};
use tairix_fdt::Fdt;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel_core::foreground::ForegroundOwner;
use tairix_kernel_core::{
    drain_pending_foreground, install_foreground_signal, install_gate, intake_enable, intake_take,
    reschedule_current, spawn_image, spawn_user_kthread, ConsoleDevice, ConsoleInput,
    KernelProcessSignal, KernelProcessWait, ProcessSignal, ProcessWait, RescheduleAction,
    SpawnMode, SpawnRequest, Yielder, NULL_CONSOLE, NULL_CONSOLE_READ,
};
use tairix_kernel_mem::{
    copy_out, AddressSpace, DirectPhysMap, Frame, PhysAddr, PhysMap, UserAddressSpace, UserStack,
    VirtAddr,
};
use tairix_kernel_sched_cfq::{Priority, Scheduler, SchedulerConfig};
use tairix_kernel_sec::{ProcessId, TaskId};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level};
use tairix_sync::SpinLock;

// `CHILD_RXE`, `PARENT_RXE`, and `USER_BIAS`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// Gigabytes of identity map each EL0 address space provides.
const IDENTITY_GIB: usize = 2;

/// User stack base (1 MiB into the high user region) and size.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (256 KiB) — generous headroom for `tairix-rt`'s heap arena.
const USER_STACK_PAGES: u64 = 64;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to each program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// Physical frames the test hands each spawn build (three EL0 spaces).
const FRAME_COUNT: usize = 384;

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4300);
const TEST_SPAWNED: EventId = EventId(4301);
const TEST_PASS: EventId = EventId(4302);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_GIC: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_PARSE: NonZeroU16 = fail_point!(4);
const FAIL_BUILD: NonZeroU16 = fail_point!(5);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(6);
const FAIL_SPAWN: NonZeroU16 = fail_point!(7);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(8);
const FAIL_NO_CURRENT: NonZeroU16 = fail_point!(9);
const FAIL_UNEXPECTED_SYSCALL: NonZeroU16 = fail_point!(10);
const FAIL_COPY_STATUS: NonZeroU16 = fail_point!(11);
const FAIL_PARENT_BAD_EXIT: NonZeroU16 = fail_point!(12);
const FAIL_NO_PRODUCER: NonZeroU16 = fail_point!(13);
const FAIL_INTAKE_SELF_EXIT: NonZeroU16 = fail_point!(14);
const FAIL_INTAKE_BAD_REAP: NonZeroU16 = fail_point!(15);
const FAIL_INTAKE_INCOMPLETE: NonZeroU16 = fail_point!(16);
const FAIL_FOREGROUND: NonZeroU16 = fail_point!(17);

/// Set once the parent reaped a child carrying the expected signalled status.
static REAP_OK: AtomicBool = AtomicBool::new(false);
/// Set once a `WaitFlags::STOPPED` wait reported the child stopped — the
/// SP9 half of the vertical (stop overlay + stopped wait report).
static STOP_OBSERVED: AtomicBool = AtomicBool::new(false);
/// Set once the parent exited 0 with both flags above verified.
static PARENT_OK: AtomicBool = AtomicBool::new(false);
/// Scheduler task id of the parent (the program that sends the signal + waits).
static PARENT_TID: AtomicU64 = AtomicU64::new(u64::MAX);
/// Scheduler task id of the intake role (`plans/STRESSTEST.md` ST3).
static INTAKE_TID: AtomicU64 = AtomicU64::new(u64::MAX);
/// Set once the intake role's `signal_intake(Enable)` syscall landed — the
/// gate before the first `^C` is pushed (a `^C` before the opt-in would
/// terminate the program the test is about to observe with).
static INTAKE_ENABLED: AtomicBool = AtomicBool::new(false);
/// Set once the intake role's `Take` drained the first observed `Interrupt`
/// — the proof the `^C` was observed, not fatal.
static INTAKE_OBSERVED: AtomicBool = AtomicBool::new(false);
/// The `^C` saga's progress: bytes pushed through the console so far (0–3).
static CTRL_C_SENT: AtomicU64 = AtomicU64::new(0);
/// Set once the escalated intake role was reaped with `Exited(130)`.
static INTAKE_REAPED: AtomicBool = AtomicBool::new(false);

/// Synthetic supervisor task id the intake role is registered under, so the
/// chassis can reap its escalated termination through the shared wait
/// bookkeeping. Never admitted on the scheduler, so it collides with no
/// real task.
const SUPERVISOR: u64 = 0xF00D;

/// The console the `^C` saga pushes through: a real [`ConsoleDevice`] whose
/// cooked-mode input filter (the production line discipline) maps the
/// interrupt byte to a queued foreground [`Signal::Interrupt`]. Write/read
/// are the null devices — only the input filter is under test.
static CONSOLE: ConsoleDevice = ConsoleDevice::new(&NULL_CONSOLE, &NULL_CONSOLE_READ);

/// Size of the test's bump heap. Lives in `.bss` (zeroed by the trampoline).
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Per-space page-table pools (one per EL0 address space).
static PAGE_TABLES_CHILD: PageTablePool = PageTablePool::new();
static PAGE_TABLES_PARENT: PageTablePool = PageTablePool::new();
static PAGE_TABLES_INTAKE: PageTablePool = PageTablePool::new();

/// Physical-frame backing store the spawn builders allocate user pages from.
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame, shared by both builds.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Hand out the next identity-mapped physical frame, or `None` when exhausted.
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(base)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn signal_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires. It does not widen either program's own authority.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The single installed process-wait producer (owns the parent/child +
/// exit-status bookkeeping), set once before the dispatch callback can fire.
static WAIT_PRODUCER: SpinLock<Option<&'static KernelProcessWait<Aarch64Arch>>> =
    SpinLock::new(None);
/// The single installed process-signal producer (authorises + delivers a
/// signal over the wait bookkeeping and the live scheduler).
#[allow(clippy::type_complexity)]
static SIGNAL_PRODUCER: SpinLock<
    Option<&'static KernelProcessSignal<Aarch64Arch, Scheduler<Aarch64Arch>>>,
> = SpinLock::new(None);
/// The live scheduler, leaked `'static` so the dispatch callback can resolve
/// the current task id.
static SCHED: SpinLock<Option<&'static Scheduler<Aarch64Arch>>> = SpinLock::new(None);
/// The parent's frozen address space + direct map, used to copy the reaped
/// child's exit status out to the parent's `status` pointer.
#[allow(clippy::type_complexity)]
static PARENT_SPACE: SpinLock<
    Option<(
        Box<dyn UserAddressSpace + Send + Sync>,
        Box<dyn PhysMap + Send + Sync>,
    )>,
> = SpinLock::new(None);

/// Resolve the scheduler's current task id on [`BOOT_CPU`], failing the test if
/// none is set (it always is inside a dispatched task's `svc`).
fn current_task_id() -> u64 {
    let sched = match *SCHED.lock() {
        Some(s) => s,
        None => qemu_exit::exit_failure(FAIL_NO_CURRENT),
    };
    match sched.current_task(BOOT_CPU) {
        Some(id) => id,
        None => qemu_exit::exit_failure(FAIL_NO_CURRENT),
    }
}

/// Encode a `Result<u64, Errno>` into the syscall return register following the
/// `abi-v1` signed convention (non-negative on success, `-errno` on error).
fn encode(result: Result<u64, Errno>) -> u64 {
    match result {
        Ok(value) => value,
        Err(err) => (-i64::from(err.as_i32())) as u64,
    }
}

/// The syscall-dispatch callback both EL0 programs' `svc` traps reach.
///
/// `signal` is routed through the installed [`SIGNAL_PRODUCER`] exactly as the
/// production handler does: the pid is resolved against the parent's own
/// children and the signal is then delivered to that target, terminating it on
/// the scheduler and recording the signal's `128 + n` status. This fixture
/// runs a single principal and keeps no capability table, so a pid that is not
/// the caller's child has no owner to compare against and fails closed here;
/// the cross-principal rule the production handler adds on top is covered by
/// its own host tests. `wait` is routed through the [`WAIT_PRODUCER`],
/// which reaps the now-terminated child; the callback copies the recorded
/// status out to the parent's `status` pointer. `yield` reschedules the caller
/// (the child's steady state). `exit` records the caller's code and reaps it; a
/// parent that exits 0 after a verified reap is the PASS. Any other syscall is
/// unexpected and fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: `args_ptr` points at the live `[u64; SYSCALL_MAX_ARGS]` the
    // exception handler built from the saved register frame.
    let args = unsafe { &*args_ptr };
    let call = SyscallNumber::from_register(number).ok();
    let cur = current_task_id();

    if call == Some(SyscallNumber::SIGNAL) {
        let signaller = match *SIGNAL_PRODUCER.lock() {
            Some(s) => s,
            None => qemu_exit::exit_failure(FAIL_NO_PRODUCER),
        };
        // The slot is decoded exactly as the dispatcher decodes it: a pid
        // occupies the whole register.
        let pid = args[0].cast_signed();
        // The slot is a 32-bit word, and the typed decode below refuses any
        // value it does not name.
        #[allow(clippy::cast_possible_truncation)]
        let signal = match Signal::from_u32(args[1] as u32) {
            Ok(signal) => signal,
            Err(err) => return encode(Err(err)),
        };
        encode(
            signaller
                .resolve_child(ProcessId(cur), pid)
                .and_then(|target| signaller.signal_task(target, signal))
                .map(|()| 0),
        )
    } else if call == Some(SyscallNumber::WAIT) {
        let producer = match *WAIT_PRODUCER.lock() {
            Some(p) => p,
            None => qemu_exit::exit_failure(FAIL_NO_PRODUCER),
        };
        // The slot is decoded exactly as the dispatcher decodes it: a pid
        // occupies the whole register.
        let pid = args[0].cast_signed();
        // Decode the flags fail-closed, exactly as the production dispatcher
        // does (a reserved bit never reaches the producer).
        #[allow(clippy::cast_possible_truncation)]
        let flags = match WaitFlags::from_bits(args[2] as u32) {
            Ok(flags) => flags,
            Err(err) => return encode(Err(err)),
        };
        match producer.wait(ProcessId(cur), TaskId(cur), pid, flags) {
            Ok(reported) => {
                // Copy the typed status record out to the parent's `status`
                // pointer through the validated boundary, exactly as the
                // production `wait` handler does.
                if !copy_status_to_parent(args[1], reported.status) {
                    qemu_exit::exit_failure(FAIL_COPY_STATUS);
                }
                match reported.status {
                    // The SP9 half: the stop was observed without a reap.
                    WaitStatus::Stopped(Signal::Stop) => {
                        STOP_OBSERVED.store(true, Ordering::SeqCst);
                    }
                    // The parent expects Terminate's POSIX-familiar 143.
                    WaitStatus::Exited(code)
                        if Signal::Terminate.termination_status() == Some(code) =>
                    {
                        REAP_OK.store(true, Ordering::SeqCst);
                    }
                    _ => {}
                }
                encode(Ok(u64::from(reported.pid)))
            }
            Err(err) => encode(Err(err)),
        }
    } else if call == Some(SyscallNumber::SIGNAL_INTAKE) {
        // Route through the real kernel-core intake bookkeeping — the same
        // functions the production handler drives — keyed by the
        // kernel-trusted current task id. The chassis flags gate the `^C`
        // saga on the fixture's actual progress.
        #[allow(clippy::cast_possible_truncation)]
        let op = match SignalIntakeOp::from_u32(args[0] as u32) {
            Ok(op) => op,
            Err(err) => return encode(Err(err)),
        };
        match op {
            SignalIntakeOp::Enable => {
                intake_enable(cur);
                INTAKE_ENABLED.store(true, Ordering::SeqCst);
                0
            }
            SignalIntakeOp::Disable => encode(tairix_kernel_core::intake_disable(cur).map(|()| 0)),
            SignalIntakeOp::Take => match intake_take(cur) {
                Ok(signal) => {
                    if signal == Signal::Interrupt {
                        INTAKE_OBSERVED.store(true, Ordering::SeqCst);
                    }
                    encode(Ok(u64::from(signal.as_u32())))
                }
                Err(err) => encode(Err(err)),
            },
        }
    } else if call == Some(SyscallNumber::YIELD) {
        // The child gives up the CPU each iteration; reschedule it and resume
        // on the next dispatch (until the parent terminates it).
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Yield);
        0
    } else if call == Some(SyscallNumber::EXIT) {
        // The slot is decoded exactly as the dispatcher decodes it: the
        // register carries the argument sign-extended to 32 bits.
        #[allow(clippy::cast_possible_truncation)]
        let code = args[0] as i32;
        if cur == PARENT_TID.load(Ordering::SeqCst) {
            // The parent stopped and resumed the child (observing the stop
            // through a STOPPED wait), then terminated it, verified the
            // signalled status, and returned 0. The overall PASS also needs
            // the intake saga (raised from the step loop), so only record
            // the parent half here and reap the parent.
            if code == 0 && REAP_OK.load(Ordering::SeqCst) && STOP_OBSERVED.load(Ordering::SeqCst) {
                PARENT_OK.store(true, Ordering::SeqCst);
                let _ = reschedule_current(BOOT_CPU, RescheduleAction::Exit);
                return 0;
            }
            qemu_exit::exit_failure(FAIL_PARENT_BAD_EXIT);
        }
        if cur == INTAKE_TID.load(Ordering::SeqCst) {
            // The intake role never exits on its own (its success path ends
            // in the escalated termination); a self-exit is a distinct
            // fixture diagnostic (30/31) — fail loudly.
            qemu_exit::exit_failure(FAIL_INTAKE_SELF_EXIT);
        }
        // Any other task exiting on its own is unexpected (the child is
        // terminated by the signal, not by a self-exit): reap it and continue.
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Exit);
        0
    } else {
        note(
            TEST_START,
            "signal test: fixture issued an unexpected syscall",
        );
        qemu_exit::exit_failure(FAIL_UNEXPECTED_SYSCALL);
    }
}

/// Copy the typed wait-status record out to the parent's `status` pointer
/// through the retained frozen parent space. Returns `false` on a
/// faulting or unmapped pointer (fail closed).
fn copy_status_to_parent(status_va: u64, status: WaitStatus) -> bool {
    let guard = PARENT_SPACE.lock();
    let Some((space, physmap)) = guard.as_ref() else {
        return false;
    };
    let bytes = WaitStatusRecord::encode(status).to_ne_bytes();
    copy_out(
        space.as_ref(),
        physmap.as_ref(),
        VirtAddr::new(status_va),
        &bytes,
    )
    .is_ok()
}

/// Build one isolated EL0 address space from `rxe` over the per-space `pool`
/// with the given startup `args`, returning its stage-1 root and the entry
/// register state. Activates the space and builds the image through the audited
/// `spawn_image` caller.
fn build_el0_space(
    pool: &'static PageTablePool,
    rxe: &[u8],
    args: &[&[u8]],
) -> (u64, tairix_arch_api::UserEntry) {
    let Ok(image) = LoadImage::parse(rxe, &SYSCALL_TABLE_HASH) else {
        qemu_exit::exit_failure(FAIL_PARSE);
    };
    let Some(arch) = ArchAddressSpace::new_identity_gigapages(pool, IDENTITY_GIB) else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    let root_phys = arch.root_phys();
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, heap,
    // frame pool, and device MMIO (all within `[0, 2 GiB)` on `virt`), so
    // switching it does not move the ground under the running code. Boot CPU.
    unsafe { arch.switch() };

    let mut space = AddressSpace::new(arch);
    // SAFETY: the boot code identity-maps this window and never unmaps it.
    let physmap = unsafe { DirectPhysMap::identity((IDENTITY_GIB as u64) << 30) }
        .expect("the boot direct map addresses its window");
    let request = SpawnRequest {
        image: &image,
        image_bytes: rxe,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args,
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once its space is reactivated (via `pre_resume`) and
    // the EL1 trap path is installed. Frames are drawn from `FRAME_POOL`.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => qemu_exit::exit_failure(FAIL_BUILD),
    };

    // Retain the *parent's* frozen space so the `wait` handler can copy the
    // reaped child's status out to the parent's `status` pointer. Only the
    // parent calls `wait`, so only its space is kept.
    if core::ptr::eq(pool, &PAGE_TABLES_PARENT) {
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());
        let pm: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);
        *PARENT_SPACE.lock() = Some((frozen, pm));
    }

    (root_phys, entry)
}

/// Admit `entry` as a resumable user kthread whose `pre_resume` hook reactivates
/// `root_phys` before every switch-in (isolation). Returns its task id.
fn admit(sched: &Scheduler<Aarch64Arch>, root_phys: u64, entry: tairix_arch_api::UserEntry) -> u64 {
    let cs = ContextSwitchHal::new();
    let user_mode = UserMode::new();
    let pre_resume = move |_stack_top: u64| {
        // SAFETY: the MMU is enabled and `root_phys` is the L1 root of a space
        // that identity-maps the low kernel window — `activate_user_root`'s
        // contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |_yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: the entered space is active (the `pre_resume` hook just
        // reactivated it) and the EL1 trap vector + dispatch callback are
        // installed, so the program's `svc`s are handled.
        unsafe { user_mode.enter_user(entry) }
    };
    let Ok(id) = spawn_user_kthread(sched, cs, BOOT_CPU, Priority::Normal, pre_resume, work) else {
        qemu_exit::exit_failure(FAIL_SPAWN)
    };
    // Before the dispatch loop runs anything, as every admission gives a thread
    // its kill gate before it can run: a signal reaches only a gated thread.
    if install_gate(id, ProcessId(id)).is_err() {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    id
}

/// Format `value` as decimal into `buf`, returning the written slice. Used to
/// pass the child's scheduler-assigned PID to the parent as a startup argument.
fn u64_to_decimal(mut value: u64, buf: &mut [u8; 20]) -> &[u8] {
    if value == 0 {
        buf[0] = b'0';
        return &buf[..1];
    }
    let mut i = buf.len();
    while value > 0 {
        i -= 1;
        buf[i] = b'0' + (value % 10) as u8;
        value /= 10;
    }
    &buf[i..]
}

/// Drive the ST3 `^C` saga one step from the cooperative loop (dispatcher
/// context — exactly where the production dispatch loop drains deferred
/// foreground deliveries).
///
/// The saga is gated on the fixture's actual progress so no `^C` can race
/// the opt-in: (1) once the intake role has **enabled** its intake, push
/// the first `^C` byte through the real console line discipline and drain
/// the deferred delivery — the opted-in target records it, observably and
/// non-fatally; (2) once the fixture **drained** that observation (and, no
/// longer draining, went quiet), push the second `^C` — recorded pending;
/// (3) push the third `^C` — the occupied slot escalates to the default
/// terminate; (4) poll the shared wait bookkeeping under the synthetic
/// supervisor until the escalated 130 reap lands. A wrong reaped status
/// fails the test loudly.
fn drive_intake_saga(wait_producer: &KernelProcessWait<Aarch64Arch>) {
    if INTAKE_REAPED.load(Ordering::SeqCst) {
        return;
    }
    let sent = CTRL_C_SENT.load(Ordering::SeqCst);
    let push_ctrl_c = |stage: u64| {
        // The interrupt byte, through the production cooked-mode input
        // filter (foreground set, producer installed), then the deferred
        // dispatcher-context delivery drain — the real `^C` path end to end.
        let _ = ConsoleInput::push(&CONSOLE, &[0x03]);
        let _ = drain_pending_foreground();
        CTRL_C_SENT.store(stage, Ordering::SeqCst);
    };
    match sent {
        0 if INTAKE_ENABLED.load(Ordering::SeqCst) => push_ctrl_c(1),
        1 if INTAKE_OBSERVED.load(Ordering::SeqCst) => push_ctrl_c(2),
        2 => push_ctrl_c(3),
        3 => {
            let intake_tid = INTAKE_TID.load(Ordering::SeqCst);
            let Ok(pid) = i64::try_from(intake_tid) else {
                qemu_exit::exit_failure(FAIL_INTAKE_BAD_REAP);
            };
            match wait_producer.poll(ProcessId(SUPERVISOR), pid, WaitFlags::NONBLOCK) {
                Ok(reported) => {
                    if reported.status
                        == WaitStatus::Exited(match Signal::Interrupt.termination_status() {
                            Some(code) => code,
                            None => qemu_exit::exit_failure(FAIL_INTAKE_BAD_REAP),
                        })
                    {
                        INTAKE_REAPED.store(true, Ordering::SeqCst);
                    } else {
                        // Terminated, but not by the escalated Interrupt —
                        // a wrong disposition is a loud failure.
                        qemu_exit::exit_failure(FAIL_INTAKE_BAD_REAP);
                    }
                }
                // Still running (the escalation has not landed yet) — poll
                // again on the next loop iteration.
                Err(_) => {}
            }
        }
        _ => {}
    }
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls.
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 signal test: starting");

    // Enable FP/SIMD at EL1 before any code that may use it.
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    // P3/P4: discover the board from the embedded `virt` device tree.
    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Bring up the EL1 vectors + GICv2 and install the dispatch callback.
    // SAFETY: called once on the boot CPU with a stack established and the MMU
    // enabled (the address-space builds switch it on below).
    // Build the child space first so we know its task id before laying out the
    // parent's startup arguments.
    let (child_root, child_entry) = build_el0_space(&PAGE_TABLES_CHILD, CHILD_RXE, &[b"signal"]);

    unsafe {
        exceptions::init_vectors();
        tairix_itest_gic::init_boot_cpu().expect("the GIC comes up");
    }
    syscall_entry::set_dispatch_callback(dispatch);

    // Build the live scheduler and both producers, leaking each `'static` so
    // the dispatch callback can reach them.
    static SCHED_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();
    let arch = Arc::new(Aarch64Arch::new(&SCHED_STORAGE, BOOT_CPU, counter_hz));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };
    let sched: &'static Scheduler<Aarch64Arch> = Box::leak(Box::new(sched));
    *SCHED.lock() = Some(sched);

    static PRODUCER_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();
    let producer_arch: &'static Aarch64Arch = Box::leak(Box::new(Aarch64Arch::new(
        &PRODUCER_STORAGE,
        BOOT_CPU,
        counter_hz,
    )));
    let wait_producer: &'static KernelProcessWait<Aarch64Arch> =
        Box::leak(Box::new(KernelProcessWait::new(producer_arch)));
    *WAIT_PRODUCER.lock() = Some(wait_producer);
    // The signal producer composes over the same wait bookkeeping and the live
    // scheduler — one source of truth for the parent/child relationship. This
    // vertical registers no capability records, so it wires no thread-group
    // table either: each target is the single-threaded process its PID names,
    // which is exactly what this fixture builds.
    let signal_producer: &'static KernelProcessSignal<Aarch64Arch, Scheduler<Aarch64Arch>> =
        Box::leak(Box::new(KernelProcessSignal::without_thread_groups(
            wait_producer,
            sched,
        )));
    *SIGNAL_PRODUCER.lock() = Some(signal_producer);

    // Admit the child, then lay out the parent's startup arguments with the
    // child's scheduler-assigned PID as arg 1 (arg 0 is the program name), and
    // admit the parent. Record the parent/child link so the parent may signal
    // and reap it.
    let child_tid = admit(sched, child_root, child_entry);
    let mut pid_buf = [0u8; 20];
    let pid_arg = u64_to_decimal(child_tid, &mut pid_buf);
    let (parent_root, parent_entry) =
        build_el0_space(&PAGE_TABLES_PARENT, PARENT_RXE, &[b"signal", pid_arg]);
    let parent_tid = admit(sched, parent_root, parent_entry);
    PARENT_TID.store(parent_tid, Ordering::SeqCst);
    if wait_producer
        .register_child(
            ProcessId(parent_tid),
            ProcessId(child_tid),
            tairix_kernel_core::ChildListing::Listed,
        )
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }

    // The ST3 intake role: admitted like the others, registered under the
    // synthetic supervisor so its escalated termination is reapable, and
    // marked foreground on the real console so the cooked line discipline
    // intercepts the pushed `^C` bytes for it.
    let (intake_root, intake_entry) =
        build_el0_space(&PAGE_TABLES_INTAKE, INTAKE_RXE, &[b"signal"]);
    let intake_tid = admit(sched, intake_root, intake_entry);
    INTAKE_TID.store(intake_tid, Ordering::SeqCst);
    if wait_producer
        .register_child(
            ProcessId(SUPERVISOR),
            ProcessId(intake_tid),
            tairix_kernel_core::ChildListing::Listed,
        )
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    // The foreground delivery hook: the same producer the `signal` syscall
    // uses, installed exactly as the production boot path installs it.
    if install_foreground_signal(signal_producer).is_err() {
        qemu_exit::exit_failure(FAIL_FOREGROUND);
    }
    // No capability table is wired here, so the intake role has no distinct
    // process instance: the kernel sentinel is what the delivery gate will
    // resolve for it, and recording the same value is what lets the `^C`
    // through to the mechanics this vertical proves.
    if CONSOLE
        .grant_foreground(
            ProcessId(SUPERVISOR),
            ForegroundOwner {
                process: ProcessId(intake_tid),
                instance: ProcId::KERNEL,
            },
        )
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_FOREGROUND);
    }
    note(
        TEST_SPAWNED,
        "aarch64 signal test: parent + child + intake spawned",
    );

    // Cooperative dispatch loop, driving the `^C` saga between steps (the
    // dispatcher-context slot where the production loop drains deferred
    // foreground deliveries). A never-draining loop times out.
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        drive_intake_saga(wait_producer);
        steps += 1;
    }
    if steps >= MAX_STEPS {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }
    // Every task is gone; the escalated reap may land on this final poll.
    drive_intake_saga(wait_producer);

    // PASS needs both halves: the parent's verified SP7b/SP9 script and the
    // ST3 intake saga (observed `^C`, then the escalated 130 reap).
    if PARENT_OK.load(Ordering::SeqCst) && INTAKE_REAPED.load(Ordering::SeqCst) {
        note(
            TEST_PASS,
            "signal test: parent script verified; foreground ^C observed by the intake and the second undrained ^C escalated to the 130 reap",
        );
        qemu_exit::exit_success();
    }
    if !PARENT_OK.load(Ordering::SeqCst) {
        qemu_exit::exit_failure(FAIL_PARENT_BAD_EXIT);
    }
    qemu_exit::exit_failure(FAIL_INTAKE_INCOMPLETE);
}
