[package]
name = "tairix-drv-bus-mmio"
description = "TAIRiX memory-mapped-IO bus driver (DTB-driven enumeration for aarch64/riscv64 `virt`-style platforms)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
tairix-abi = { path = "../../../lib/abi", version = "=0.0.0" }
tairix-fdt = { path = "../../../lib/fdt", version = "=0.0.0" }
tairix-virtio = { path = "../../../lib/virtio", version = "=0.0.0" }

[dev-dependencies]
tairix-fdt = { path = "../../../lib/fdt", version = "=0.0.0", features = ["test-fixtures"] }

[lints]
workspace = true
