//! FAT32 boot-partition authoring.
//!
//! The boot partition is laid down by the real in-tree FAT32 driver
//! (`tairix-drv-fs-fat32`) — the same code that mounts it on the running
//! system — so the author and the consumer share one on-disk definition. It carries exactly what the Pi GPU bootloader
//! reads: the verified firmware blobs, the generated `config.txt`, and the
//! flat `kernel8.img`. It also carries the volume's plaintext
//! [`UnlockDescriptor`](tairix_drv_fs_arxfs::UnlockDescriptor) — the
//! salt + iteration count the bootstrap reads *before* anything is
//! decrypted, to turn the operator passphrase into the encrypted root's
//! volume key.

use tairix_abi::driver::filesystem::{FilesystemRead, FilesystemWrite, NodeKind};
use tairix_drv_fs_fat32::Fat32;

use crate::device::MemBlock;
use crate::firmware::FirmwareFile;
use crate::overlay::{pwm_audio_overlay, JACK_PINS, PWM_AUDIO_OVERLAY, PWM_AUDIO_OVERLAY_PATH};
use crate::MkimageError;

/// Name of the kernel image the firmware loads (`config.txt` `kernel=`).
pub const KERNEL_IMG_NAME: &str = "kernel8.img";

/// Name of the generated firmware configuration file.
pub const CONFIG_TXT_NAME: &str = "config.txt";

/// Name of the root volume's plaintext key-derivation descriptor. The bootstrap reads it off this partition *before*
/// mounting the encrypted root, derives the volume key from the operator
/// passphrase under the descriptor's salt + iteration count, and only
/// then opens the root. It carries no secret — only the public KDF
/// parameters (see
/// [`UnlockDescriptor`](tairix_drv_fs_arxfs::UnlockDescriptor)).
///
/// The literal is defined once beside the descriptor it names; the writer
/// here and the boot-path reader import the same constant so the contract
/// cannot drift.
pub use tairix_drv_fs_arxfs::ROOT_UNLOCK_NAME;

/// Render the `config.txt` the Pi firmware boots TAIRiX with.
///
/// The knobs are the P0 facts of record (`docs/src/platform/aarch64.md`,
/// "Boot protocol"): AArch64 cores, the TAIRiX kernel image, a held UART
/// clock for a stable early console, the PL011 `UART0` routed to the
/// GPIO 14/15 header (`dtoverlay=disable-bt`), the PL011 reference clock
/// pinned to the 48 MHz the kernel's divisor arithmetic assumes
/// (`init_uart_clock=48000000`, `tairix_arch_aarch64::uart_init`), and the
/// `console_baud` line rate (8 data bits, no parity, 1 stop bit — 8,N,1 is
/// the firmware's fixed PL011 framing).
///
/// `console_baud` is the early-boot `init_uart_baud`; the caller supplies the
/// kernel architecture port's `CONSOLE_BAUD`, so the firmware and the
/// kernel's reprogrammed line share one definition.
/// `armstub=armstub8.bin` is emitted only when the (optional) stub is
/// among the build inputs.
///
/// `disable_overscan=1` zeroes the firmware's default per-edge overscan
/// margins (48 px on an HDMI CEA mode). They inset the surface the firmware
/// reports and allocates, and every TAIRiX display surface sizes itself from
/// that one answer, so leaving them on frames the console *and* the desktop
/// in an unusable black border.
///
/// The headphone jack's pins go to PWM1, and the first-party overlay names
/// that block for its driver ([`crate::overlay`]).
#[must_use]
pub fn config_txt(with_armstub: bool, console_baud: u32) -> String {
    let mut text = format!(
        "# Generated by tairix-mkimage; do not hand-edit on the card.\n\
         # Knobs of record: docs/src/platform/aarch64.md, \"Boot protocol\".\n\
         arm_64bit=1\n\
         kernel=kernel8.img\n\
         enable_uart=1\n\
         dtoverlay=disable-bt\n\
         disable_overscan=1\n\
         init_uart_clock=48000000\n\
         init_uart_baud={console_baud}\n\
         {JACK_PINS}\n\
         dtoverlay={PWM_AUDIO_OVERLAY}\n",
    );
    if with_armstub {
        text.push_str("armstub=armstub8.bin\n");
    }
    text
}

/// The boot partition's fixed BPB volume serial. Fixed (not minted per
/// image) so builds stay bit-reproducible; the boot partition is read by
/// the firmware and the kernel's unlock path only and is never published
/// into the volume forest, so the serial carries no identity duty.
const BOOT_FAT_SERIAL: u32 = 0x5253_4F53; // "RSOS"

/// Author the FAT32 boot partition: format `sectors` sectors and plant the
/// firmware blobs, the first-party overlays, `config.txt`, `kernel8.img`,
/// and the root volume's
/// `unlock_descriptor` (the encoded
/// [`UnlockDescriptor`](tairix_drv_fs_arxfs::UnlockDescriptor) bytes, at
/// [`ROOT_UNLOCK_NAME`]).
///
/// # Errors
///
/// [`MkimageError::BootPartition`] if formatting or any plant write fails,
/// or [`MkimageError::Overlay`] if an overlay cannot be written.
pub fn build_boot_partition(
    sectors: u64,
    firmware: &[FirmwareFile],
    kernel8: &[u8],
    unlock_descriptor: &[u8],
    console_baud: u32,
) -> Result<Vec<u8>, MkimageError> {
    let dev = MemBlock::new(sectors).map_err(MkimageError::BootPartition)?;
    let mut fs = Fat32::format(dev, BOOT_FAT_SERIAL).map_err(MkimageError::BootPartition)?;

    let with_armstub = firmware.iter().any(|f| f.name == "armstub8.bin");
    let config = config_txt(with_armstub, console_baud);

    for file in firmware {
        plant(&mut fs, &file.name, &file.bytes)?;
    }
    plant(&mut fs, PWM_AUDIO_OVERLAY_PATH, &pwm_audio_overlay()?)?;
    plant(&mut fs, CONFIG_TXT_NAME, config.as_bytes())?;
    plant(&mut fs, KERNEL_IMG_NAME, kernel8)?;
    plant(&mut fs, ROOT_UNLOCK_NAME, unlock_descriptor)?;

    fs.flush().map_err(MkimageError::BootPartition)?;
    Ok(fs.into_block().into_bytes())
}

/// Write one boot-partition file at the slash-separated path `name`,
/// creating (or reusing) each intermediate directory — the firmware's
/// fixed `overlays/` directory holds the device-tree overlays the
/// generated `config.txt` applies.
fn plant(fs: &mut Fat32<MemBlock>, name: &str, bytes: &[u8]) -> Result<(), MkimageError> {
    let mut dir = fs.root();
    let mut parts = name.split('/').peekable();
    while let Some(part) = parts.next() {
        if parts.peek().is_some() {
            dir = match fs.lookup(dir, part.as_bytes()) {
                Ok(existing) => existing,
                Err(_) => fs
                    .create(dir, part.as_bytes(), NodeKind::Directory)
                    .map_err(MkimageError::BootPartition)?,
            };
        } else {
            fs.create(dir, part.as_bytes(), NodeKind::RegularFile)
                .map_err(MkimageError::BootPartition)?;
            let written = fs
                .write_at(dir, part.as_bytes(), 0, bytes)
                .map_err(MkimageError::BootPartition)?;
            if written != bytes.len() {
                return Err(MkimageError::BootPartition(
                    tairix_abi::DriverError::DeviceFault,
                ));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::device::SECTOR_BYTES;

    const TEST_SECTORS: u64 = 131_072; // 64 MiB, the production boot size.

    fn test_firmware() -> Vec<FirmwareFile> {
        vec![
            FirmwareFile {
                name: "start4.elf".into(),
                bytes: vec![0x11; 4096],
            },
            FirmwareFile {
                name: "fixup4.dat".into(),
                bytes: vec![0x22; 64],
            },
            FirmwareFile {
                name: "bcm2711-rpi-4-b.dtb".into(),
                bytes: vec![0x33; 1024],
            },
            FirmwareFile {
                name: "overlays/disable-bt.dtbo".into(),
                bytes: vec![0x55; 256],
            },
        ]
    }

    fn read_back(fs: &mut Fat32<MemBlock>, name: &str) -> Vec<u8> {
        let mut node = fs.root();
        for part in name.split('/') {
            node = fs
                .lookup(node, part.as_bytes())
                .expect("path component present");
        }
        let mut out = vec![0u8; 1 << 20];
        let n = fs.read_at(node, 0, &mut out).expect("file reads");
        out.truncate(n);
        out
    }

    #[test]
    fn plants_firmware_config_and_kernel() {
        let kernel8 = vec![0x44u8; 8192];
        let unlock = [0x66u8; 28];
        let bytes = build_boot_partition(TEST_SECTORS, &test_firmware(), &kernel8, &unlock, 57_600)
            .expect("boot partition builds");
        assert_eq!(
            bytes.len(),
            usize::try_from(TEST_SECTORS).expect("fits") * SECTOR_BYTES
        );

        let dev = MemBlock::from_bytes(bytes).expect("whole sectors");
        let mut fs = Fat32::open(dev).expect("the driver mounts its own product");
        assert_eq!(read_back(&mut fs, "start4.elf"), vec![0x11; 4096]);
        assert_eq!(read_back(&mut fs, "fixup4.dat"), vec![0x22; 64]);
        assert_eq!(read_back(&mut fs, "bcm2711-rpi-4-b.dtb"), vec![0x33; 1024]);
        assert_eq!(
            read_back(&mut fs, "overlays/disable-bt.dtbo"),
            vec![0x55; 256]
        );
        assert_eq!(read_back(&mut fs, KERNEL_IMG_NAME), kernel8);
        assert_eq!(read_back(&mut fs, ROOT_UNLOCK_NAME), unlock.to_vec());

        let config = read_back(&mut fs, CONFIG_TXT_NAME);
        let config = core::str::from_utf8(&config).expect("config.txt is UTF-8");
        assert!(config.contains("arm_64bit=1"));
        assert!(config.contains("kernel=kernel8.img"));
        assert!(config.contains("enable_uart=1"));
        assert!(config.contains("init_uart_clock=48000000"));
        // The caller-supplied baud is written verbatim (here the debug rate).
        assert!(config.contains("init_uart_baud=57600"));
        assert!(config.contains("dtoverlay=disable-bt"));
        assert!(config.contains("disable_overscan=1"));
        assert!(config.contains("gpio=40,41=a0\ndtoverlay=tairix-pwm-audio\n"));
        assert!(!config.contains("armstub="));
        assert_eq!(
            read_back(&mut fs, PWM_AUDIO_OVERLAY_PATH),
            pwm_audio_overlay().expect("the overlay"),
            "the overlay config.txt applies is planted where the firmware looks"
        );
    }

    /// The firmware's default per-edge overscan margins inset the surface it
    /// reports and allocates, framing every TAIRiX display surface — console
    /// and desktop alike — in a black border.
    #[test]
    fn disables_the_firmware_overscan_border() {
        assert!(config_txt(false, crate::CONSOLE_BAUD).contains("disable_overscan=1\n"));
    }

    #[test]
    fn emits_the_armstub_knob_only_when_the_stub_is_an_input() {
        let mut firmware = test_firmware();
        firmware.push(FirmwareFile {
            name: "armstub8.bin".into(),
            bytes: vec![0x55; 256],
        });
        let bytes = build_boot_partition(
            TEST_SECTORS,
            &firmware,
            &[0x44u8; 16],
            &[0x66u8; 28],
            crate::CONSOLE_BAUD,
        )
        .expect("boot partition builds");

        let dev = MemBlock::from_bytes(bytes).expect("whole sectors");
        let mut fs = Fat32::open(dev).expect("mounts");
        let config = read_back(&mut fs, CONFIG_TXT_NAME);
        let config = core::str::from_utf8(&config).expect("config.txt is UTF-8");
        assert!(config.contains("armstub=armstub8.bin"));
        assert_eq!(read_back(&mut fs, "armstub8.bin"), vec![0x55; 256]);
    }

    #[test]
    fn fails_closed_when_the_partition_cannot_hold_the_content() {
        // A device too small to even format must error, never panic.
        assert!(build_boot_partition(
            8,
            &test_firmware(),
            &[0x44u8; 16],
            &[0x66u8; 28],
            crate::CONSOLE_BAUD,
        )
        .is_err());
    }
}
