//! The freestanding aarch64 test kernel: spawn one runaway EL0 spinner and
//! prove the production generic-timer IRQ involuntarily preempts it
//! (`plans/PI.md` D2b-2b-A P-1).

use core::num::NonZeroU16;
use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU64, AtomicUsize, Ordering};

use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_abi::{CapabilityId, CapabilityQuery, SyscallNumber, SYSCALL_MAX_ARGS};
use tairix_arch_aarch64::context_hal::ContextSwitchHal;
use tairix_arch_aarch64::kernel_arch::timer_frequency_hz;
use tairix_arch_aarch64::paging::{
    self, activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool,
};
use tairix_arch_aarch64::preempt::{self, PreemptStorage};
use tairix_arch_aarch64::userentry::UserMode;
use tairix_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, SERIAL_SINK,
};
use tairix_arch_api::{CpuId, EnterUser, BOOT_CPU};
use tairix_fdt::Fdt;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel_core::{
    reschedule_current, spawn_image, spawn_kthread, spawn_user_kthread, RescheduleAction,
    SpawnMode, SpawnRequest, Yielder,
};
use tairix_kernel_mem::{AddressSpace, DirectPhysMap, Frame, PhysAddr, UserStack};
use tairix_kernel_sched_eevdf::{Priority, Scheduler, SchedulerConfig};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level};

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// Preemption quantum rate (slices/second) — the shared production rate
/// [`DEFAULT_PREEMPT_QUANTUM_HZ`](tairix_arch_api::timer::DEFAULT_PREEMPT_QUANTUM_HZ),
/// a ~10 ms slice so a contended runaway spinner is preempted promptly
/// under QEMU TCG. TAIRiX is tickless: the one-shot is
/// armed to one quantum only while the spinner shares the CPU with the
/// competitor kthread, and disarmed once the spinner is the sole runnable
/// task.
const PREEMPT_TICK_HZ: u64 = tairix_arch_api::timer::DEFAULT_PREEMPT_QUANTUM_HZ;

/// Number of involuntary preemptions the competitor waits to observe
/// before it exits, handing the CPU to the now-sole spinner. One is
/// enough to prove the contended one-shot fires; the long uninterrupted
/// remainder of the spin then proves the sole-task timer is disarmed.
const TARGET_PREEMPTIONS: u64 = 1;

/// Slack the sole-task disarm check tolerates over the hand-off snapshot.
/// The disarm is exact in principle, but the generic timer is wall-clock:
/// under an oversubscribed host (the concurrent QEMU matrix) the
/// competitor's last armed one-shot can fire once at the contended→sole
/// boundary before the sole spinner's `set_preemption(false)` disarms it.
/// A genuine periodic-timer regression would instead add *hundreds* of
/// ticks over the long sole run, so this small bound stays immune to the
/// benign boundary fire while still failing loudly on a re-armed periodic
/// tick (no flaky tests;).
const SOLE_PREEMPT_SLACK: u64 = 16;

/// Gigabytes of identity map the EL0 address space provides: `[0, 2 GiB)`
/// covers the `virt` board device MMIO (GiB 0) and the RAM base at GiB 1 where
/// this kernel runs, so switching into the space never moves the ground under
/// the running kernel.
const IDENTITY_GIB: usize = 2;

/// User stack base (1 MiB into the high user region) and size.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (256 KiB).
const USER_STACK_PAGES: u64 = 64;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// Physical frames the spawn build draws from: the program's segments, its
/// user stack, and the startup block, with headroom.
const FRAME_COUNT: usize = 256;

/// `step`-loop watchdog: maximum iterations before declaring the workload
/// stuck. Each iteration is one preemption quantum; sized generously for TCG.
const MAX_STEPS: u64 = 50_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4280);
const TEST_SPAWNED: EventId = EventId(4281);
const TEST_PASS: EventId = EventId(4282);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_GIC_NOT_DISCOVERED: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_PARSE: NonZeroU16 = fail_point!(4);
const FAIL_BUILD: NonZeroU16 = fail_point!(5);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(6);
const FAIL_SPAWN: NonZeroU16 = fail_point!(7);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(8);
const FAIL_NO_PREEMPT: NonZeroU16 = fail_point!(9);
const FAIL_PREEMPT_STORAGE: NonZeroU16 = fail_point!(10);
const FAIL_UNEXPECTED_SYSCALL: NonZeroU16 = fail_point!(11);
const FAIL_SOLE_PREEMPTED: NonZeroU16 = fail_point!(12);
const FAIL_SPAWN_COMPETITOR: NonZeroU16 = fail_point!(13);

/// Count of involuntary timer-driven preemptions of the running EL0 task.
static PREEMPTIONS: AtomicU64 = AtomicU64::new(0);
/// `exit` syscalls observed (the spinner exits exactly once on completion).
static EXITS: AtomicU64 = AtomicU64::new(0);
/// [`PREEMPTIONS`] snapshot captured by the competitor kthread at the
/// instant it exits (handing the CPU to the now-sole spinner); `u64::MAX`
/// until recorded. After the run, `PREEMPTIONS == PREEMPTIONS_AT_SOLE`
/// proves the sole spinner took **no** further timer interrupt — the
/// tickless disarm.
static PREEMPTIONS_AT_SOLE: AtomicU64 = AtomicU64::new(u64::MAX);

/// Bump-heap size: the spawn caller allocates the startup-vector block buffer
/// and the user kthread's kernel stack + control block from it.
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the EL0 address space's stage-1 hierarchy.
static PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Per-CPU preemption backing for the single boot CPU (`PreemptStorage<1>` covers a single-core slice).
static PREEMPT_STORAGE: PreemptStorage<1> = PreemptStorage::new();

/// Physical-frame backing store the spawn builder allocates user pages from.
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Hand out the next identity-mapped physical frame from [`FRAME_POOL`], or
/// `None` when the pool is exhausted (the spawn builder then fails closed).
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    // The pool is identity-mapped, so its kernel virtual address is also its
    // physical address.
    let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(base)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn preempt_el0_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The EL0-preemption callback the timer IRQ path invokes for a tick taken
/// from EL0 — the production dispatch shape verbatim: it
/// suspends the running user task back to the scheduler via
/// `reschedule_current(_, Yield)`, the involuntary analogue of a `yield`
/// syscall. It records each preemption so the test can prove at least one
/// fired against the never-yielding spinner.
extern "C" fn preempt_dispatch(cpu: CpuId) {
    PREEMPTIONS.fetch_add(1, Ordering::SeqCst);
    let _ = reschedule_current(cpu, RescheduleAction::Yield);
}

/// The syscall-dispatch callback the spinner's final `exit` `svc` reaches.
///
/// The spinner issues no `yield`; its only syscall is the `exit` that
/// `tairix-rt` routes `main`'s return through. Any other syscall is unexpected
/// and fails the test loudly.
extern "C" fn dispatch(number: u64, _args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    let call = SyscallNumber::from_register(number).ok();
    if call == Some(SyscallNumber::EXIT) {
        EXITS.fetch_add(1, Ordering::SeqCst);
        // Reap the caller: this switches back to the dispatcher and never
        // resumes the task, so the `0` below is unreachable.
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Exit);
        0
    } else {
        note(TEST_START, "fixture program issued an unexpected syscall");
        qemu_exit::exit_failure(FAIL_UNEXPECTED_SYSCALL);
    }
}

/// Build the isolated EL0 address space from the fixture `image` over
/// [`PAGE_TABLES`], returning its stage-1 root and the entry register state.
fn build_el0_space(image: &LoadImage) -> (u64, tairix_arch_api::UserEntry) {
    let Some(arch) = ArchAddressSpace::new_identity_gigapages(&PAGE_TABLES, IDENTITY_GIB) else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // Capture the root before the arch space is moved into the `kernel/mem`
    // wrapper, so the `pre_resume` hook can reactivate `TTBR0_EL1` with it.
    let root_phys = arch.root_phys();
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
    // heap, the frame pool, and the device MMIO (all within `[0, 2 GiB)` on the
    // `virt` board), so enabling it does not move the ground under the running
    // code — exactly `AddressSpace::switch`'s contract. Called on the boot CPU.
    unsafe { arch.switch() };

    let mut space = AddressSpace::new(arch);
    // SAFETY: the boot code identity-maps this window and never unmaps it.
    let physmap = unsafe { DirectPhysMap::identity((IDENTITY_GIB as u64) << 30) }
        .expect("the boot direct map addresses its window");
    let request = SpawnRequest {
        image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"el0"],
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once its space is reactivated (via the `pre_resume`
    // hook) and the EL1 trap path is installed. The frame source draws
    // identity-mapped frames from `FRAME_POOL`.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => qemu_exit::exit_failure(FAIL_BUILD),
    };
    (root_phys, entry)
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `tairix_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 EL0 preemption test: starting");

    // Enable FP/SIMD at EL1 before any code that may use it (the `rxe` decoder
    // and `build_process_image`'s fills compile to NEON `memcpy`/`memcmp`).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    // P3/P4: discover the board from the embedded `virt` device tree.
    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC_NOT_DISCOVERED);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC_NOT_DISCOVERED);
    }

    // Parse the build-time `rxe` blob once against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        qemu_exit::exit_failure(FAIL_PARSE);
    };

    // Build the isolated EL0 address space (it leaves its own space active).
    let (root_phys, entry) = build_el0_space(&image);

    // Bring up the EL1 vectors + GICv2 and install the dispatch callback so the
    // spinner's `exit` `svc` is handled.
    // SAFETY: called once on the boot CPU with a stack established and the MMU
    // enabled (the address-space build switched it on).
    unsafe {
        exceptions::init_vectors();
        gic::init();
    }
    syscall_entry::set_dispatch_callback(dispatch);

    // Set up the production tickless preemption path verbatim: register the per-CPU storage, install the EL0-preemption
    // callback, record the per-quantum interval, and enable the timer PPI —
    // but leave the timer **disarmed**. EL0 runs preemptible
    // (`SPSR_EL0T_PREEMPTIBLE`); the scheduler arms the one-shot to one
    // quantum only when it dispatches the spinner onto a CPU that still has
    // the competitor kthread queued (`Aarch64Arch::set_preemption`), and a
    // tick taken while the spinner is in EL0 then drives `preempt_dispatch`.
    if PREEMPT_STORAGE.register().is_err() {
        qemu_exit::exit_failure(FAIL_PREEMPT_STORAGE);
    }
    preempt::set_preempt_callback(preempt_dispatch);
    let interval = preempt::interval_for_hz(counter_hz, PREEMPT_TICK_HZ);
    // SAFETY: the boot CPU (id 0); the preempt callback is installed (above),
    // the per-CPU storage is registered (above), the EL1 vector table is
    // installed (`init_vectors`), and the GIC is up (`gic::init`). This
    // records the quantum, enables the timer PPI, and leaves the timer
    // disarmed; the scheduler arms the first one-shot on its next dispatch
    // onto a contended CPU.
    unsafe {
        preempt::init_local_preempt(BOOT_CPU, interval);
    }

    // Build the live scheduler over the arch port. Per-CPU bookkeeping backing
    // for this single-CPU vertical.
    static ARCH_STORAGE: tairix_arch_aarch64::Aarch64ArchStorage<1> =
        tairix_arch_aarch64::Aarch64ArchStorage::new();
    let arch = Arc::new(tairix_arch_aarch64::Aarch64Arch::new(
        &ARCH_STORAGE,
        BOOT_CPU,
        counter_hz,
    ));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    // Admit the **competitor** first: a kernel kthread that yields until it
    // observes the spinner preempted at least [`TARGET_PREEMPTIONS`] times,
    // records the preemption count at that instant, and exits — handing the
    // CPU to the now-sole spinner. While it is queued (Ready), every spinner
    // dispatch has a competitor, so the scheduler arms the one-shot and the
    // runaway spinner is involuntarily preempted (the contention case). Once
    // it exits, the spinner is the sole runnable task, so the scheduler
    // disarms and the spinner runs its remaining millions of iterations with
    // **no** further timer interrupt — the tickless sole-task case, checked after the loop.
    let competitor = move |yielder: &mut Yielder<ContextSwitchHal>| {
        while PREEMPTIONS.load(Ordering::SeqCst) < TARGET_PREEMPTIONS {
            yielder.yield_now();
        }
        PREEMPTIONS_AT_SOLE.store(PREEMPTIONS.load(Ordering::SeqCst), Ordering::SeqCst);
    };
    if spawn_kthread(
        &sched,
        ContextSwitchHal::new(),
        BOOT_CPU,
        Priority::Normal,
        competitor,
    )
    .is_err()
    {
        qemu_exit::exit_failure(FAIL_SPAWN_COMPETITOR);
    }

    // Admit the spinner as a resumable user kthread: its `pre_resume` hook
    // reactivates its page-table root (isolation), and its work body
    // `enter_user`s into EL0.
    let cs = ContextSwitchHal::new();
    let user_mode = UserMode::new();
    let pre_resume = move |_stack_top: u64| {
        // SAFETY: the MMU is enabled and `root_phys` is the L1 root of a space
        // that identity-maps the low kernel window the running kernel executes
        // from — exactly `activate_user_root`'s contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |_yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: the entered space is active (the `pre_resume` hook just
        // reactivated it) and the EL1 trap vector + dispatch callback are
        // installed, so the program's `exit` `svc` is handled.
        unsafe { user_mode.enter_user(entry) }
    };
    if spawn_user_kthread(&sched, cs, BOOT_CPU, Priority::Normal, pre_resume, work).is_err() {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(TEST_SPAWNED, "aarch64 EL0 preemption test: spinner spawned");

    // Dispatch loop: drive `step` until both tasks finish. While the
    // competitor is queued, each spinner dispatch arms the one-shot and the
    // never-yielding spinner is involuntarily preempted (the preempt callback
    // `reschedule_current`s back here). Once the competitor exits, the lone
    // spinner runs disarmed to completion and `exit`s. A preemption that
    // never fires would leave the contended `step` spinning forever inside
    // EL0 and the harness would time out (fail-loud).
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }
    if sched.live_task_count() != 0 {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }
    // Contention case: the competitor recorded the preemption count when it
    // handed off the sole CPU, and that count must be at least
    // `TARGET_PREEMPTIONS` — proving the timer one-shot fired and preempted
    // the runaway EL0 task while the CPU was contended.
    let at_sole = PREEMPTIONS_AT_SOLE.load(Ordering::SeqCst);
    if at_sole == u64::MAX || at_sole < TARGET_PREEMPTIONS {
        qemu_exit::exit_failure(FAIL_NO_PREEMPT);
    }
    // Sole-task (tickless / NO_HZ) case: after the competitor exited, the
    // sole spinner ran millions of iterations to completion with the
    // one-shot disarmed, so essentially no further preemption fired — at
    // most the benign contended→sole boundary fire (`SOLE_PREEMPT_SLACK`).
    // A re-armed periodic tick would have added hundreds.
    if PREEMPTIONS.load(Ordering::SeqCst) > at_sole.saturating_add(SOLE_PREEMPT_SLACK) {
        qemu_exit::exit_failure(FAIL_SOLE_PREEMPTED);
    }
    // The spinner resumed correctly after each preemption and ran to its
    // final `exit` exactly once.
    if EXITS.load(Ordering::SeqCst) != 1 {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }

    note(
        TEST_PASS,
        "aarch64 EL0 preemption test: contended runaway task preempted; sole task ran tickless",
    );
    qemu_exit::exit_success();
}
