//! The freestanding x86_64 test kernel: prove the demand-grown user stack
//! end to end (`plans/SPAWN.md` `SP11e`;
//! `docs/src/architecture/memory.md` §7c).
//!
//! The chassis runs the **shared production board bring-up**
//! (`tairix_kernel::x86_64::boot::bring_up_bsp`) — the exact per-CPU
//! table / `#PF` entry / NXE / LAPIC calibration / ACPI / `syscall`+TSS /
//! IO-APIC sequence the production `boot()` pipeline runs, including the
//! production syscall-dispatch callback and user-fault resolver — and then
//! installs the production `KernelDispatchHook` into the production
//! `DISPATCH_SLOT` those callbacks already resolve through. Every syscall
//! and every ring-3 data fault therefore runs the production path: the
//! production `LiveMemMap` producer (backing both `mem_map` and the
//! stack-growth fault path), a real `KernelProcessWait`, and a
//! `ProgramRegistry` carrying the three child roles, their numeric
//! parameters derived from the one shared `spawn_layout` policy. The
//! parent role is spawned through the production
//! `InitSpawnCtx::spawn_driver_process` seam; it spawns and reaps the
//! children through the production `spawn` + `wait` syscalls:
//!
//! * `grow` — recurses far past the eagerly committed stack top, verifying
//!   every frame's bytes survive the fault-driven growth, exits 0;
//! * `limit` — lowers its own `StackBytes` soft bound via `rlimit_set`,
//!   then recurses past it: the growth path refuses the bound and the
//!   kernel fault-kills it, exit 139;
//! * `guard` — reads the unmapped guard page below the reserved span:
//!   fault-killed, exit 139 (the structural defence stays).
//!
//! The chassis reaps the parent through the producer's non-blocking poll
//! and PASSes only on a parent exit of 0. The x86_64 `isa-debug-exit`
//! device carries no per-site failure code, so every failure site logs a
//! distinct message (and the parent's diagnostic exit code as a field)
//! before flipping the failure exit.

use core::panic::PanicInfo;

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::{CapabilityId, Errno, WaitFlags, WaitStatus};
use tairix_arch_api::BOOT_CPU;
use tairix_arch_x86_64::kernel_arch::{X86_64Arch, X86_64ArchStorage};
use tairix_arch_x86_64::paging::KERNEL_VMA_BASE;
use tairix_arch_x86_64::qemu_exit;
use tairix_caps::CapabilitySet;
use tairix_kernel::kalloc::{Heap, HEAP_BYTES};
use tairix_kernel::spawn_layout::{
    CHILD_USER_BIAS, USER_STACK_COMMIT_PAGES, USER_STACK_RESERVE_PAGES,
};
use tairix_kernel::x86_64::boot::{bring_up_bsp, BspBringUp};
use tairix_kernel::x86_64::serial_sink::COM1_CONSOLES;
use tairix_kernel::x86_64::spawn_producer::X86_64_PROCESS_SPAWN;
use tairix_kernel::{
    handle_panic_via_kernel_core, BinArch, FreeListAllocator, DISPATCH_SLOT, SERIAL_SINK,
};
use tairix_kernel_core::{
    AddressSpaceRegistry, BootReserve, EmbeddedProgram, InitSpawnCtx, KernelArch,
    KernelDispatchHook, KernelInitSpawner, KernelProcessWait, LiveMemMap, ProcessWait,
    ProgramRegistry, RandomReserve, SchedWaitQueueArch, NULL_DMA_ALLOC_FACILITY,
    NULL_MMIO_MAP_FACILITY, NULL_SEAT_REGISTRY, NULL_SHARED_MEM_FACILITY,
};
use tairix_kernel_ipc::PortRegistry;
use tairix_kernel_irq::{IrqTable, UnsupportedController};
use tairix_kernel_mem::{
    BootMemoryMap, FrameAllocator, MemoryRegion, PhysAddr, RegionKind, PAGE_SIZE,
};
use tairix_kernel_sched_eevdf::{Scheduler, SchedulerConfig};
use tairix_kernel_sec::{CapTable, ProcessId};
use tairix_log::{log, Event, EventId, Field, FieldValue, Level};
use tairix_sync::RwLock;

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// Physical frames the production spawn producer and the stack-growth
/// fault path draw from: four spawned processes (image, eagerly committed
/// stack top, page tables, kernel stacks) plus the demand-grown stack
/// pages — the `grow` child alone faults in [`GROW_TARGET_BYTES`] of
/// stack. Sized from that appetite with generous headroom (16 MiB).
const FRAME_COUNT: usize = 4096;

/// Bytes of live stack the `grow` child must reach: sixteen times the
/// eagerly committed top — decisively past it (and past the whole formerly
/// fixed 288-page stack) while comfortably inside the reserved span and the
/// default `StackBytes` bound. Derived from the one shared policy constant,
/// never a second hand-picked number.
const GROW_TARGET_BYTES: u64 = USER_STACK_COMMIT_PAGES * PAGE_SIZE as u64 * 16;

/// The `StackBytes` soft bound the `limit` child imposes on itself: twice
/// the eagerly committed top, so growth genuinely starts (the commit is
/// inside the bound) and is then refused strictly before [`GROW_TARGET_BYTES`].
const LIMIT_BOUND_BYTES: u64 = USER_STACK_COMMIT_PAGES * PAGE_SIZE as u64 * 2;

/// Bytes of the reserved stack span, handed to the `guard` child so it can
/// derive the guard page below the span from its own stack top — the one
/// shared policy constant, never a copy.
const RESERVE_BYTES: u64 = USER_STACK_RESERVE_PAGES * PAGE_SIZE as u64;

/// Longest decimal argument the rows below need (`u64::MAX` is 20 digits).
const DEC_MAX: usize = 20;

/// Render `value` as a fixed-width, zero-padded decimal byte string at
/// compile time. Leading zeroes are harmless: the fixture's parser accepts
/// them, and a fixed width lets the argument live in a `static` the
/// registry row borrows.
const fn dec_bytes(mut value: u64) -> [u8; DEC_MAX] {
    let mut out = [b'0'; DEC_MAX];
    let mut i = DEC_MAX;
    while i > 0 {
        i -= 1;
        out[i] = b'0' + (value % 10) as u8;
        value /= 10;
        if value == 0 {
            break;
        }
    }
    out
}

/// [`GROW_TARGET_BYTES`] as a decimal argument-vector value.
static GROW_TARGET_ARG: [u8; DEC_MAX] = dec_bytes(GROW_TARGET_BYTES);
/// [`LIMIT_BOUND_BYTES`] as a decimal argument-vector value.
static LIMIT_BOUND_ARG: [u8; DEC_MAX] = dec_bytes(LIMIT_BOUND_BYTES);
/// [`RESERVE_BYTES`] as a decimal argument-vector value.
static RESERVE_ARG: [u8; DEC_MAX] = dec_bytes(RESERVE_BYTES);

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4366);
const TEST_SPAWNED: EventId = EventId(4367);
const TEST_PASS: EventId = EventId(4368);
/// Every failure site logs through this id with a distinct message (the
/// x86_64 `isa-debug-exit` device carries no per-site exit code).
const TEST_FAIL: EventId = EventId(4369);

/// Static heap for the free-list allocator (per the production bin); the
/// chassis subsystems, the spawn producer's boxed state, and the demand-
/// grown bookkeeping allocate from it.
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// Physical-frame backing store the live [`FrameAllocator`] serves the
/// spawn producer and the stack-growth fault path from. `align(4096)` so
/// each `PAGE_SIZE` slice is a valid page frame. A higher-half kernel
/// static, so its physical address is its virtual address minus
/// [`KERNEL_VMA_BASE`] — inside the low identity window the producer's
/// page-table walk and each child's own root require.
#[repr(C, align(4096))]
struct FramePool([u8; PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; PAGE_SIZE * FRAME_COUNT]);

/// Per-CPU storage backing the scheduler's arch handle.
static SCHED_ARCH_STORAGE: X86_64ArchStorage<1> = X86_64ArchStorage::new();

/// Per-CPU storage backing the dispatch hook + spawn ctx arch handle.
static HOOK_ARCH_STORAGE: X86_64ArchStorage<1> = X86_64ArchStorage::new();

/// This vertical binds no IRQ lines; the fail-closed controller mirrors
/// what `kernel/core::init` installs when a port exposes no routing.
static IRQ_CONTROLLER: UnsupportedController = UnsupportedController;

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Log the failure site and flip the QEMU failure exit. The
/// `isa-debug-exit` device carries no per-site code, so the message is the
/// site identifier the transcript preserves.
fn fail(message: &'static str) -> ! {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Error,
            id: TEST_FAIL,
            message,
            fields: &[],
        },
    );
    qemu_exit::exit_failure()
}

/// Forward to the shared x86_64 panic bridge (logs to COM1 and parks the
/// CPU; the run then times out and the harness reports the failure).
#[panic_handler]
fn stack_grow_qemu_x86_64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_kernel_core(info)
}

/// The capability set the fixture programs run under: `PROC_SPAWN` for the
/// parent's `spawn` only. The parent's set doubles as the inherited
/// ceiling the production spawn intersects each child's manifest request
/// with, so a child's effective set is exactly its registry row's request
/// — and the children request nothing (stack growth, `rlimit_set`
/// lowering, and faulting need no capability).
fn parent_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::PROC_SPAWN);
    caps
}

/// The program registry the production `spawn` syscall resolves the
/// parent's child paths against: one `rxe` image, three rows, each pinning
/// its role and its policy-derived numeric parameters through the
/// registered default argument vector.
static CHILD_PROGRAMS: [EmbeddedProgram; 3] = [
    EmbeddedProgram {
        path: b"/bin/sg-grow",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"sg", b"grow", &GROW_TARGET_ARG],
    },
    EmbeddedProgram {
        path: b"/bin/sg-limit",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"sg", b"limit", &LIMIT_BOUND_ARG, &GROW_TARGET_ARG],
    },
    EmbeddedProgram {
        path: b"/bin/sg-guard",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"sg", b"guard", &RESERVE_ARG],
    },
];

/// The registry over [`CHILD_PROGRAMS`].
static PROGRAMS: ProgramRegistry = ProgramRegistry::new(&CHILD_PROGRAMS);

/// The leaked-`'static` kernel subsystems the production dispatch hook and
/// spawn context borrow — the vertical's analogue of `KernelState`, lifted
/// by one-shot `Box::leak` publishes exactly as `kernel_core::kernel_main`
/// does (a one-shot publish, not a global mutable static).
struct Subsystems {
    frames: &'static FrameAllocator,
    sched: &'static Scheduler<BinArch>,
    arch: &'static BinArch,
    caps: &'static RwLock<CapTable>,
    peer_watch: &'static tairix_kernel_core::PeerWatch,
    ipc: &'static RwLock<PortRegistry>,
    aspaces: &'static RwLock<AddressSpaceRegistry>,
    rng: &'static RwLock<Box<dyn RandomReserve + Send + Sync>>,
    irq_table: &'static IrqTable,
}

/// Build the live kernel subsystems: the `kernel/mem` frame allocator over
/// the dedicated pool (so the spawn producer and the demand-fault path draw
/// their frames from the production path), the scheduler over the
/// production `BinArch` wrapper, and the capability / port / address-space
/// / random / IRQ state the production hook borrows. The two arch handles
/// are built from the same board facts the bring-up discovered.
fn leak_subsystems(board: &BspBringUp) -> Subsystems {
    let mut memory_map = BootMemoryMap::new();
    memory_map.push(MemoryRegion {
        // The pool is a higher-half kernel static; its physical address is
        // its virtual address minus the kernel window base, inside the low
        // identity window every child root maps.
        start: PhysAddr::new(core::ptr::addr_of!(FRAME_POOL) as u64 - KERNEL_VMA_BASE),
        length: (PAGE_SIZE * FRAME_COUNT) as u64,
        kind: RegionKind::Usable,
    });
    let Ok(frames) = FrameAllocator::new(&memory_map) else {
        fail("stack-grow test: frame allocator construction failed");
    };
    let frames: &'static FrameAllocator = Box::leak(Box::new(frames));

    let Ok(sched_arch) = X86_64Arch::new(
        &SCHED_ARCH_STORAGE,
        0,
        board.bsp_lapic_id,
        &board.cpu_to_lapic,
    ) else {
        fail("stack-grow test: scheduler arch handle construction failed");
    };
    let sched_arch = Arc::new(BinArch::new(
        sched_arch,
        board.calibration,
        board.irq_routing,
    ));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), sched_arch) else {
        fail("stack-grow test: scheduler construction failed");
    };

    let Ok(hook_arch) = X86_64Arch::new(
        &HOOK_ARCH_STORAGE,
        0,
        board.bsp_lapic_id,
        &board.cpu_to_lapic,
    ) else {
        fail("stack-grow test: hook arch handle construction failed");
    };

    Subsystems {
        frames,
        sched: Box::leak(Box::new(sched)),
        arch: Box::leak(Box::new(BinArch::new(
            hook_arch,
            board.calibration,
            board.irq_routing,
        ))),
        caps: Box::leak(Box::new(RwLock::new(CapTable::new()))),
        peer_watch: Box::leak(Box::new(tairix_kernel_core::PeerWatch::new())),
        ipc: Box::leak(Box::new(RwLock::new(PortRegistry::new()))),
        aspaces: Box::leak(Box::new(RwLock::new(AddressSpaceRegistry::new()))),
        rng: Box::leak(Box::new(RwLock::new(
            Box::new(BootReserve::new()) as Box<dyn RandomReserve + Send + Sync>
        ))),
        irq_table: Box::leak(Box::new(IrqTable::new(0))),
    }
}

/// Boot entry point — the symbol the arch crate's boot trampoline calls.
#[no_mangle]
pub extern "C" fn kernel_main(boot_info: u64) -> ! {
    note(TEST_START, "x86_64 stack-grow test: starting");

    // The shared production board bring-up: per-CPU tables, the dedicated
    // `#PF` entry, NXE, LAPIC calibration, ACPI, the production dispatch
    // callback + user-fault resolver (both resolving through the
    // production `DISPATCH_SLOT` this chassis fills below), `syscall`/TSS
    // entry, and the masked IO-APIC routing.
    let board = match bring_up_bsp(boot_info, &SERIAL_SINK) {
        Ok(board) => board,
        Err(_) => fail("stack-grow test: board bring-up failed"),
    };

    // The fixture `rxe`'s baked relocations must target the bias the
    // production producer maps every child at; a drifted constant would
    // admit a child whose pointers do not match its mapping (fail closed).
    if USER_BIAS != CHILD_USER_BIAS {
        fail("stack-grow test: fixture bias drifted from the spawn layout");
    }

    let sys = leak_subsystems(&board);

    // Publish the wait-queue arch hook so parked waiters (the parent in
    // `wait`) are genuinely unparked by their wake events — the same
    // adapter the production boot path installs.
    let wait_arch = SchedWaitQueueArch::leak(sys.sched, sys.arch);
    if tairix_kernel_core::waitq::install_wait_arch(wait_arch).is_err() {
        fail("stack-grow test: wait-queue arch install failed");
    }

    // The scheduler-side process-wait producer: records every parent/child
    // link the production spawn paths register and backs the production
    // `wait` syscall the parent blocks in.
    let wait_producer: &'static KernelProcessWait<BinArch> =
        Box::leak(Box::new(KernelProcessWait::new(sys.arch)));

    // The production live-space producer: serves the `mem_map` pair (the
    // `tairix-rt` heap) and — the point of this vertical — the one-page-
    // per-fault backing the stack-growth resolver maps through it.
    let live: &'static LiveMemMap<BinArch> = Box::leak(Box::new(LiveMemMap::new(sys.arch)));

    // Publish the production dispatch hook into the production
    // `DISPATCH_SLOT` — the exact slot `bring_up_bsp`'s installed
    // `production_dispatch` / `production_user_fault` callbacks resolve
    // through — so every syscall the programs issue (`spawn`, `wait`,
    // `rlimit_set`, `exit`) and every user-fault resolution runs the
    // production caller-context resolution and handler path.
    let hook: &'static KernelDispatchHook<'static, BinArch> = Box::leak(Box::new(
        KernelDispatchHook::new(
            sys.sched,
            sys.caps,
            sys.arch,
            &SERIAL_SINK,
            sys.irq_table,
            &IRQ_CONTROLLER,
            sys.ipc,
            sys.aspaces,
            sys.rng,
            &COM1_CONSOLES,
            sys.frames,
            sys.frames,
            &PROGRAMS,
            wait_producer,
            // No seat / MMIO / DMA surface in this vertical; those
            // producers stay fail-closed. No filesystem or file-map
            // producer either: the only faults this vertical exists to
            // exercise are stack growth, the `StackBytes` bound, and the
            // below-span guard.
            &NULL_SEAT_REGISTRY,
            live,
            &NULL_MMIO_MAP_FACILITY,
            &NULL_DMA_ALLOC_FACILITY,
        )
        .with_peer_watch(sys.peer_watch),
    ));
    if DISPATCH_SLOT.install_dispatcher(hook).is_err() {
        fail("stack-grow test: dispatch hook install failed");
    }

    // Spawn the parent role through the production runtime-spawn seam
    // (`KernelSpawnCtx` assembly inside `KernelInitSpawner`), recorded
    // against the kernel supervisor identity so this chassis can reap it.
    // Publish the launch-services bundle the deferred child-load path reads:
    // the arch image builder builds each admitted child's image on the
    // child's own first slice, off this chassis's cooperative drive. The one
    // shared build+publish the production boot path uses.
    let _ = tairix_kernel_core::spawn_services::install_over(
        sys.arch,
        sys.frames,
        &SERIAL_SINK,
        &tairix_kernel_core::NULL_FILESYSTEM,
        None,
        sys.aspaces,
        sys.caps,
        sys.peer_watch,
        wait_producer,
        &X86_64_PROCESS_SPAWN,
    );

    let init_ctx = KernelInitSpawner::new(
        sys.frames,
        &SERIAL_SINK,
        sys.sched,
        sys.caps,
        sys.peer_watch,
        sys.aspaces,
        sys.arch,
        wait_producer,
        sys.irq_table,
        &IRQ_CONTROLLER,
        &NULL_SHARED_MEM_FACILITY,
        KernelArch::cross_cpu_tlb_shootdown(sys.arch),
    );
    let Ok(parent_pid) = init_ctx.spawn_driver_process(
        "/bin/sg-parent",
        PROGRAM_RXE,
        parent_caps(),
        &[],
        &[b"sg", b"parent"],
        None,
    ) else {
        fail("stack-grow test: parent spawn failed");
    };
    note(
        TEST_SPAWNED,
        "x86_64 stack-grow test: parent spawned through the production seam",
    );

    // The budget-bounded cooperative drive: step the scheduler and poll the
    // wait producer for the parent's exit between steps. The parent runs
    // the whole grow / limit / guard sequence through production spawn +
    // wait; a parent exit of 0 is the PASS, anything else names the failing
    // site through the logged diagnostic exit code.
    // A task id never exceeds the ABI's pid bound, so reinterpreting it as
    // the signed pid the wait ABI carries is exact.
    let parent_pid = parent_pid.cast_signed();
    let mut steps = 0u64;
    while steps < MAX_STEPS {
        let _ = sys.sched.step(BOOT_CPU);
        steps += 1;

        // Deliver any wake a handler deferred while the task ran — the same
        // between-dispatches service the production loop performs; without
        // it a child's `exit` never unparks the parent blocked in `wait`.
        let _ = tairix_kernel_core::waitq::drain_pending_wakes();

        match wait_producer.poll(ProcessId(0), parent_pid, WaitFlags::empty()) {
            Ok(reaped) => match reaped.status {
                WaitStatus::Exited(0) => {
                    note(
                        TEST_PASS,
                        "x86_64 stack-grow test: parent verified all three children and exited 0",
                    );
                    qemu_exit::exit_success();
                }
                WaitStatus::Exited(code) => {
                    // The parent's diagnostic exit code names the failing
                    // role/site; log it as a field before the (code-less)
                    // x86_64 failure exit.
                    log(
                        &SERIAL_SINK,
                        &Event {
                            level: Level::Error,
                            id: TEST_FAIL,
                            message: "stack-grow test: parent exited non-zero",
                            fields: &[Field {
                                key: "parent_exit_code",
                                value: FieldValue::SignedInt(i64::from(code)),
                            }],
                        },
                    );
                    qemu_exit::exit_failure();
                }
                WaitStatus::Stopped(_) => {
                    fail("stack-grow test: parent stopped instead of exiting");
                }
            },
            Err(Errno::WouldBlock) => {}
            Err(_) => fail("stack-grow test: wait poll failed"),
        }

        // A fully drained workload without a reapable parent means the
        // parent vanished down a path that never recorded its exit; fail
        // with a distinct message rather than spinning out the watchdog.
        if sys.sched.live_task_count() == 0 {
            fail("stack-grow test: workload drained without a reapable parent");
        }
    }
    fail("stack-grow test: watchdog expired (deadlock)");
}
