//! The freestanding riscv64 RV-X3 test kernel: build the **parent** U-mode
//! program, admit it under the live scheduler on the `virt` board, and route
//! its `CAP_PROC_SPAWN`-gated `spawn` `ecall` to a riscv64 `ProcessSpawn`
//! producer that builds the **child** (session) a fresh, hardware-isolated Sv39
//! space through the identity window **without** switching the running parent's
//! `satp`, admitting it **Ready** concurrently (`plans/PI.md` RV-X3, the
//! riscv64 sibling of the `aarch64`/`x86_64` `spawn_session` verticals).

use core::num::NonZeroU16;
use core::panic::PanicInfo;
use core::sync::atomic::{AtomicPtr, AtomicU32, AtomicU64, AtomicUsize, Ordering};

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_abi::{CapabilityId, CapabilityQuery, Errno, SyscallNumber, SYSCALL_MAX_ARGS};
use tairix_arch_api::{UserEntry, BOOT_CPU};
use tairix_arch_riscv64::context_hal::ContextSwitchHal;
use tairix_arch_riscv64::fdt::Fdt;
use tairix_arch_riscv64::paging::{self, activate_user_root, AddressSpace as ArchAddressSpace};
use tairix_arch_riscv64::userentry::USER_MODE;
use tairix_arch_riscv64::{
    handle_panic_via_serial, qemu_exit, syscall_entry, trap, RiscvArch, RiscvArchStorage,
    SERIAL_SINK,
};
use tairix_itest_finisher::fail_point;
use tairix_kalloc::{FreeListAllocator, Heap, HEAP_BYTES};
use tairix_kernel_core::UserThreadEntry;
use tairix_kernel_core::{
    reschedule_current, spawn_image, spawn_user_kthread, RescheduleAction, SpawnMode, SpawnRequest,
    Yielder,
};
use tairix_kernel_mem::{AddressSpace, DirectPhysMap, Frame, PhysAddr, UserStack};
use tairix_kernel_sched_eevdf::{Priority, Scheduler, SchedulerConfig};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level};

// `PARENT_RXE`/`CHILD_RXE: &[u8]`, `USER_BIAS: u64`, and `YIELDS_PER_TASK: u64`,
// generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// Tasks the test expects to reach `exit`: the parent and the one child it
/// spawns.
const EXPECTED_EXITS: u64 = 2;

/// Gigabytes of identity map each U-mode address space provides: `[0, 4 GiB)`
/// covers the `virt` board's low MMIO and the RAM base where this kernel runs,
/// so neither building the child nor switching into a task moves the ground
/// under the running kernel. [`USER_BIAS`] (64 GiB) sits far above, on freshly
/// walked Sv39 tables.
const IDENTITY_GIGABYTES: usize = 4;

/// User stack base (1 MiB into the high user region) and size. `tairix-rt`
/// carves scratch space off the stack, so it must comfortably exceed it.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB > the runtime's scratch span plus call frames).
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up, well
/// clear of the program image and the stack).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to each program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// Physical frames the test hands the two spawn builds (image segments + the
/// user stacks + the startup blocks for both programs, with headroom). The
/// page-table frames come from the per-space [`paging::PageTablePool`]s, not
/// from here.
const FRAME_COUNT: usize = 640;

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript (clear of the `4000..5000`
/// `kernel/core` boot range).
const TEST_START: EventId = EventId(4328);
const TEST_SPAWNED: EventId = EventId(4329);
const TEST_PASS: EventId = EventId(4330);
const TEST_FAIL: EventId = EventId(4331);

/// `SiFive` Test failure codes, distinct per failure site.
const FAIL_NO_TIMEBASE: NonZeroU16 = fail_point!(1);
const FAIL_UNEXPECTED_HART: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_PARSE: NonZeroU16 = fail_point!(4);
const FAIL_BUILD: NonZeroU16 = fail_point!(5);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(6);
const FAIL_SPAWN: NonZeroU16 = fail_point!(7);
const FAIL_UNEXPECTED_SYSCALL: NonZeroU16 = fail_point!(8);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(9);
const FAIL_EXIT_COUNT: NonZeroU16 = fail_point!(10);
const FAIL_NO_SPAWN: NonZeroU16 = fail_point!(11);
const FAIL_YIELD_COUNT: NonZeroU16 = fail_point!(12);

/// Number of concurrent `spawn`s the producer completed. PASS requires one (the
/// parent's spawn of the session).
static SPAWNS: AtomicU64 = AtomicU64::new(0);
/// Total `yield` syscalls observed across the parent and the child. PASS
/// requires every task's full build-pinned count, proving each genuinely ran
/// (not merely was admitted).
static YIELDS: AtomicU64 = AtomicU64::new(0);
/// Total `exit` syscalls observed across the parent and the child.
static EXITS: AtomicU64 = AtomicU64::new(0);

/// Set once the round-trip has been driven so a re-entry cannot re-run it.
static TEST_DRIVEN: AtomicU32 = AtomicU32::new(0);

/// Static boot heap, in the linker's NOLOAD `.heap` section so the boot
/// trampoline neither zeroes nor counts it in the usable memory map. The two
/// user kthreads' kernel stacks + control blocks and the spawn builders'
/// startup-vector blocks allocate from it.
#[link_section = ".heap"]
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// Per-space page-table pools: one for the parent and one for the spawned
/// child. Each backs an Sv39 hierarchy whose root [`activate_user_root`]
/// reinstalls (via `satp`) before every switch into its task, so the two tasks
/// stay hardware-isolated. A `.bss` reserve, monotonic and
/// never freed.
static PARENT_PAGE_TABLES: paging::PageTablePool = paging::PageTablePool::new();
static CHILD_PAGE_TABLES: paging::PageTablePool = paging::PageTablePool::new();

/// Physical-frame backing store the spawn builders draw user pages from.
/// `align(4096)` so each `PAGE_SIZE` slice is a valid page frame; identity-
/// mapped (its physical address equals its kernel virtual address), so the
/// builders reach it through [`DirectPhysMap::identity`]. A single monotonic
/// cursor ([`FRAME_CURSOR`]) hands disjoint frames to both the parent build and
/// the child build, so the two address spaces never share a data frame.
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame, shared by both
/// program builds.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// The live scheduler the runtime `spawn` producer admits the child onto. The
/// producer runs from the `extern "C"` dispatch callback (reached during a
/// `step` of the parent), which cannot capture `kernel_main`'s local `&sched`,
/// so the leaked-`'static` scheduler is published here for it. Null until
/// [`kernel_main`] installs it; the producer fails closed on null.
static SCHEDULER: AtomicPtr<Scheduler<RiscvArch>> = AtomicPtr::new(core::ptr::null_mut());

/// Hand out the next identity-mapped physical frame from [`FRAME_POOL`], or
/// `None` when the pool is exhausted (the spawn builder then fails closed).
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    // The pool is identity-mapped, so its kernel virtual address is also its
    // physical address.
    let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(base)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared riscv64 panic bridge (parks the hart; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn spawn_session_qemu_riscv64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn builder requires. It does not widen either
/// program's own authority; it only authorises the *act* of spawning. The child's effective authority is its own (empty)
/// manifest request, never the parent's (no ambient
/// authority).
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// Build one isolated U-mode address space from `image` over the per-space
/// page-table `pool`, returning its Sv39 root and the entry register state. If
/// `activate` is set the new space is switched in (`satp`) so its mappings land
/// in it; otherwise the caller's `satp` stays active and the build writes the
/// child's pages through the caller's identity window (the concurrent-producer
/// path — never moving the running parent out from under itself). Builds the
/// image through the production capability-checked, audited `spawn_image`
/// caller. Returns `None` on any error so the caller maps it to a fail-closed
/// outcome.
fn build_user_space(
    pool: &'static paging::PageTablePool,
    image_bytes: &'static [u8],
    image: &LoadImage,
    args: &[&[u8]],
    activate: bool,
) -> Option<(u64, UserEntry)> {
    let arch = ArchAddressSpace::new_identity_gigapages(pool, IDENTITY_GIGABYTES)?;
    // Capture the `satp` root before the arch space is moved into the
    // `kernel/mem` wrapper, so the per-task `pre_resume` hook can reactivate it
    // on every switch.
    let root_phys = arch.root_phys();
    if activate {
        // SAFETY: the identity map covers the kernel's current `pc`, `sp`, heap,
        // frame pool, and device MMIO (all within `[0, 4 GiB)` on `virt`), so
        // the `satp` switch does not move the ground under the running code.
        // Boot hart, called once for the parent before any task runs.
        unsafe { arch.switch() };
    }

    let mut space = AddressSpace::new(arch);
    // SAFETY: the boot code identity-maps this window and never unmaps it.
    let physmap = unsafe { DirectPhysMap::identity((IDENTITY_GIGABYTES as u64) << 30) }
        .expect("the boot direct map addresses its window");
    let request = SpawnRequest {
        image,
        image_bytes,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args,
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once its space is reactivated (via the `pre_resume`
    // hook) and the trap path is installed. The frame source draws identity-
    // mapped frames from `FRAME_POOL`. When `activate` is false the build
    // reaches the child's tables + frames through the caller's identity window
    // (the pool and frames are in `[0, 4 GiB)`), so the child's space need not
    // be active to be built (the cross-port producer discipline).
    let entry = unsafe {
        spawn_image(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    }
    .ok()?;
    // Dropping `space` here frees nothing: its page tables live in the
    // `'static` `pool` and its frames in the `'static` `FRAME_POOL`; only the
    // captured `root_phys` is needed to reactivate the space later.
    Some((root_phys, entry))
}

/// Admit a freshly built U-mode space onto `scheduler` as a resumable user
/// kthread. Its `pre_resume` hook reactivates *its own* `satp` root before
/// every switch-in (isolation); its work body `enter_user`s into U-mode.
/// The kernel-stack top the hook is handed (`_top`) is unused on riscv64:
/// `sscratch` is per-task hardware state armed by `userentry::enter_user` and
/// re-armed by the RV1 trap vector from each task's own kernel-stack frame on
/// every U-return, so a trap from the resumed task always lands on *its* kernel
/// stack with no dispatcher-side repointing. Returns the new task id (its PID)
/// or `None` on a scheduler-full admission failure.
fn admit(scheduler: &Scheduler<RiscvArch>, root_phys: u64, entry: UserEntry) -> Option<u64> {
    let pre_resume = move |_top: u64| {
        // SAFETY: paging is enabled and `root_phys` is the Sv39 root of a space
        // that maps the low identity window the running dispatcher executes
        // from — exactly `activate_user_root`'s contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: by the time this body runs the task has been dispatched, so
        // its `pre_resume` hook reactivated `satp`, and the trap vector +
        // dispatch callback are installed; the program's first `ecall` is
        // handled. `build_process_image` mapped the entry/stack as user pages.
        unsafe {
            UserThreadEntry {
                port: &USER_MODE,
                regs: entry,
            }
            .enter(yielder)
        }
    };
    spawn_user_kthread(
        scheduler,
        ContextSwitchHal::new(),
        BOOT_CPU,
        Priority::Normal,
        pre_resume,
        work,
    )
    .ok()
}

/// The runtime `spawn` producer reached from the dispatch callback: build the
/// child (session) a fresh, hardware-isolated Sv39 space **without** switching
/// the running parent's `satp`, admit it **Ready** concurrently, and return its
/// PID — or a negative `-errno` following the signed `abi-v1` convention. This
/// is the riscv64 cross-port equal of `Aarch64ProcessSpawn` / the x86_64
/// producer; the per-process page-table reserve and the frame pool bound how
/// many children this proving vertical builds, and exhaustion fails closed.
fn spawn_session() -> i64 {
    let sched_ptr = SCHEDULER.load(Ordering::Acquire);
    if sched_ptr.is_null() {
        return -i64::from(Errno::NotImplemented.as_i32());
    }
    // SAFETY: `SCHEDULER` is published once by `kernel_main` with the leaked
    // `'static` scheduler before any task runs and is never mutated again; the
    // single-hart cooperative model means no concurrent access.
    let scheduler = unsafe { &*sched_ptr };

    let Ok(image) = LoadImage::parse(CHILD_RXE, &SYSCALL_TABLE_HASH) else {
        return -i64::from(Errno::BadMagic.as_i32());
    };
    // The child's tables are built through the caller's (parent's) identity
    // window — `activate = false` — so the running parent keeps its own `satp`
    // (a true concurrent spawn, never moving the parent out from under itself).
    let Some((root_phys, entry)) =
        build_user_space(&CHILD_PAGE_TABLES, CHILD_RXE, &image, &[b"session"], false)
    else {
        return -i64::from(Errno::NoSpace.as_i32());
    };
    match admit(scheduler, root_phys, entry) {
        Some(pid) => {
            SPAWNS.fetch_add(1, Ordering::SeqCst);
            // The PID is the new task id; the signed convention returns it
            // verbatim for a success (a non-negative value).
            pid_to_signed(pid)
        }
        None => -i64::from(Errno::NoSpace.as_i32()),
    }
}

/// Encode a successful spawn's PID as the signed `abi-v1` result (a PID is a
/// scheduler task id well within `i64::MAX`, so this never wraps in practice).
#[allow(clippy::cast_possible_wrap)]
fn pid_to_signed(pid: u64) -> i64 {
    pid as i64
}

/// The signed `spawn` result re-encoded into the unsigned register the syscall
/// ABI carries (a negative value is `-errno`; the caller's `tairix_rt::spawn`
/// wrapper recovers the `i64` from the same bit pattern).
#[allow(clippy::cast_sign_loss)]
fn spawn_result_bits() -> u64 {
    spawn_session() as u64
}

/// The syscall-dispatch callback both U-mode tasks' `ecall` traps reach.
///
/// It mirrors the production bin-crate callback (`dispatch_via_slot`): a
/// `spawn` from the parent is routed to the concurrent producer
/// ([`spawn_session`]) and its signed result returned to the caller, which
/// keeps running; a rescheduling syscall (`yield`/`exit`) is suspended back to
/// the dispatcher through [`reschedule_current`], so the parent and child
/// timeshare the hart. Any other syscall is unexpected from the fixture
/// programs and fails the test loudly.
extern "C" fn dispatch(number: u64, _args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    let call = SyscallNumber::from_register(number).ok();
    if call == Some(SyscallNumber::SPAWN) {
        // Build the child + admit it Ready; return the signed result to the
        // parent, which resumes in U-mode and keeps running.
        spawn_result_bits()
    } else if call == Some(SyscallNumber::YIELD) {
        YIELDS.fetch_add(1, Ordering::SeqCst);
        // Suspend the caller; control returns here when it is next dispatched.
        // A `false` would mean no user kthread is published on this CPU — never
        // the case here, since both tasks are user kthreads.
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Yield);
        0
    } else if call == Some(SyscallNumber::EXIT) {
        EXITS.fetch_add(1, Ordering::SeqCst);
        // Reap the caller: this switches back to the dispatcher and never
        // resumes the task, so the `0` below is unreachable.
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Exit);
        0
    } else {
        note(TEST_FAIL, "fixture program issued an unexpected syscall");
        qemu_exit::exit_failure(FAIL_UNEXPECTED_SYSCALL);
    }
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls.
#[no_mangle]
pub extern "C" fn kernel_main(hartid: u64, dtb: u64) -> ! {
    if TEST_DRIVEN
        .compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire)
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_POOL);
    }

    note(TEST_START, "riscv64 RV-X3 test: building the parent image");

    // Read the timer frequency from the firmware tree. Fail closed (finisher)
    // if it is omitted rather than guessing a divisor.
    // SAFETY: `dtb` is the verbatim `a1` pointer OpenSBI handed the boot hart;
    // `boot.s` forwards it unchanged.
    let Some(timebase) = (unsafe { Fdt::from_ptr(dtb as *const u8) })
        .ok()
        .and_then(|f| f.timebase_frequency())
    else {
        qemu_exit::exit_failure(FAIL_NO_TIMEBASE);
    };

    // The single-hart slice only brings up logical CPU 0 on hart 0.
    if hartid != u64::from(BOOT_CPU) {
        qemu_exit::exit_failure(FAIL_UNEXPECTED_HART);
    }

    // Parse + build the parent image. `build_user_space` activates the parent
    // space, so the kernel runs under a translation regime mapping the low
    // kernel window; the child is later built through this same identity
    // window without switching `satp`.
    let Ok(parent_image) = LoadImage::parse(PARENT_RXE, &SYSCALL_TABLE_HASH) else {
        qemu_exit::exit_failure(FAIL_PARSE);
    };
    let Some((parent_root, parent_entry)) = build_user_space(
        &PARENT_PAGE_TABLES,
        PARENT_RXE,
        &parent_image,
        &[b"parent"],
        true,
    ) else {
        qemu_exit::exit_failure(FAIL_BUILD);
    };

    // Install the trap vector + the syscall-dispatch callback before any user
    // task runs. The vector lives in the kernel's identity window present in
    // both spaces, so it is reachable whichever space is active.
    // SAFETY: called once on the boot hart with a stack established; only the
    // tasks' `ecall`s reach the vector (interrupts stay masked, so the
    // scheduler's self-IPI stays pending and the dispatch is the cooperative
    // `step` loop below).
    unsafe { trap::init_traps() };
    syscall_entry::set_dispatch_callback(dispatch);

    // Build the live scheduler over the production arch handle and leak it to
    // `'static`, then publish it so the producer (reached from the dispatch
    // callback) can admit the child onto it. Interrupts stay masked, so
    // dispatch is the cooperative `step` loop below.
    // Single-hart slice: one per-CPU slot, owned by an allocator-free
    // `static` backing.
    static STORAGE: RiscvArchStorage<1> = RiscvArchStorage::new();
    let arch = Arc::new(RiscvArch::new(&STORAGE, BOOT_CPU, timebase));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };
    let sched: &'static Scheduler<RiscvArch> = Box::leak(Box::new(sched));
    SCHEDULER.store(
        (sched as *const Scheduler<RiscvArch>).cast_mut(),
        Ordering::Release,
    );

    // Admit the parent as a resumable user kthread. The child is admitted later
    // by the producer when the parent issues its `spawn` `ecall`.
    if admit(sched, parent_root, parent_entry).is_none() {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(TEST_SPAWNED, "riscv64 RV-X3 test: parent admitted");

    // Cooperative dispatch loop: drive `step` until both tasks have exited.
    // The parent's `spawn` builds + admits the child mid-loop (a concurrent
    // spawn); thereafter both ping-pong with the dispatcher through real
    // U-mode↔kernel context switches on their own kernel stacks (the RV1
    // park-safe path). A switch that never resumed its task would stall the
    // drain and the harness would time out (fail-loud).
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }
    if sched.live_task_count() != 0 {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }
    if SPAWNS.load(Ordering::SeqCst) == 0 {
        qemu_exit::exit_failure(FAIL_NO_SPAWN);
    }
    // Each of the two tasks yields its full build-pinned count, proving both
    // genuinely ran (not merely were admitted): the parent before its `exit`
    // and the child before its.
    if YIELDS.load(Ordering::SeqCst) != EXPECTED_EXITS * YIELDS_PER_TASK {
        qemu_exit::exit_failure(FAIL_YIELD_COUNT);
    }
    if EXITS.load(Ordering::SeqCst) != EXPECTED_EXITS {
        qemu_exit::exit_failure(FAIL_EXIT_COUNT);
    }

    note(
        TEST_PASS,
        "riscv64 RV-X3 test: parent spawned the session concurrently; both exited",
    );
    qemu_exit::exit_success();
}
