//! The freestanding riscv64 test kernel: spawn one runaway U-mode spinner and
//! prove the production supervisor-timer interrupt involuntarily preempts it
//! (`plans/PI.md` D2b-2b-A P-1b, the riscv64 sibling of
//! `preempt_el0_qemu_aarch64`).

use core::num::NonZeroU16;
use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU32, AtomicU64, AtomicUsize, Ordering};

use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_abi::{CapabilityId, CapabilityQuery, SyscallNumber, SYSCALL_MAX_ARGS};
use tairix_arch_api::{CpuId, EnterUser, UserEntry, BOOT_CPU};
use tairix_arch_riscv64::context_hal::ContextSwitchHal;
use tairix_arch_riscv64::fdt::Fdt;
use tairix_arch_riscv64::paging::{self, activate_user_root, AddressSpace as ArchAddressSpace};
use tairix_arch_riscv64::preempt::{self, PreemptStorage};
use tairix_arch_riscv64::userentry::UserMode;
use tairix_arch_riscv64::{
    handle_panic_via_serial, qemu_exit, syscall_entry, trap, RiscvArch, RiscvArchStorage,
    SERIAL_SINK,
};
use tairix_itest_finisher::fail_point;
use tairix_kalloc::{FreeListAllocator, Heap, HEAP_BYTES};
use tairix_kernel_core::{
    reschedule_current, spawn_image, spawn_kthread, spawn_user_kthread, RescheduleAction,
    SpawnMode, SpawnRequest, Yielder,
};
use tairix_kernel_mem::{AddressSpace, DirectPhysMap, Frame, PhysAddr, UserStack};
use tairix_kernel_sched_eevdf::{Priority, Scheduler, SchedulerConfig};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level};

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// Preemption-quantum rate (slices/second) — the shared production rate
/// [`DEFAULT_PREEMPT_QUANTUM_HZ`](tairix_arch_api::timer::DEFAULT_PREEMPT_QUANTUM_HZ),
/// a ~10 ms slice so a contended runaway spinner is preempted promptly
/// under QEMU TCG. TAIRiX is tickless: the one-shot is
/// armed to one quantum only while the spinner shares the hart with the
/// competitor kthread, and disarmed once the spinner is the sole task.
const PREEMPT_TICK_HZ: u64 = tairix_arch_api::timer::DEFAULT_PREEMPT_QUANTUM_HZ;

/// Involuntary preemptions the competitor waits to observe before it
/// exits, handing the hart to the now-sole spinner (see the aarch64
/// vertical). One proves the contended one-shot fires; the long
/// uninterrupted remainder proves the sole-task disarm.
const TARGET_PREEMPTIONS: u64 = 1;

/// Slack the sole-task disarm check tolerates over the hand-off snapshot.
/// The disarm is exact in principle, but riscv64's aclint timer is
/// wall-clock: under an oversubscribed host (the concurrent QEMU matrix)
/// the competitor's last armed one-shot can fire once at the
/// contended→sole boundary before the sole spinner's `set_preemption(false)`
/// disarms it. A genuine periodic-timer regression would instead add
/// *hundreds* of ticks over the long sole run, so this small bound stays
/// immune to the benign boundary fire while still failing loudly on a
/// re-armed periodic tick (no flaky tests;).
const SOLE_PREEMPT_SLACK: u64 = 16;

/// Gigabytes of identity map the U-mode address space provides: `[0, 4 GiB)`
/// covers the `virt` board's low MMIO and the RAM base where this kernel runs,
/// so switching into the space never moves the ground under the running kernel.
/// [`USER_BIAS`] (64 GiB) sits far above, on freshly walked Sv39 tables.
const IDENTITY_GIGABYTES: usize = 4;

/// User stack base (1 MiB into the high user region) and size. `tairix-rt`
/// carves scratch space off the stack, so it must comfortably exceed it.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB > the runtime's scratch span plus call frames).
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// Physical frames the spawn build draws from: the program's segments, its
/// user stack, and the startup block, with headroom. The page-table frames
/// come from the per-space [`paging::PageTablePool`], not from here.
const FRAME_COUNT: usize = 384;

/// `step`-loop watchdog: maximum iterations before declaring the workload
/// stuck. Each iteration is one preemption quantum; sized generously for TCG.
const MAX_STEPS: u64 = 50_000_000;

/// Stable audit-event ids for the QEMU transcript (clear of the `4000..5000`
/// `kernel/core` boot range).
const TEST_START: EventId = EventId(4328);
const TEST_SPAWNED: EventId = EventId(4329);
const TEST_PASS: EventId = EventId(4330);
const TEST_FAIL: EventId = EventId(4331);

/// `SiFive` Test failure codes, distinct per failure site.
const FAIL_NO_TIMEBASE: NonZeroU16 = fail_point!(1);
const FAIL_UNEXPECTED_HART: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_PARSE: NonZeroU16 = fail_point!(4);
const FAIL_BUILD: NonZeroU16 = fail_point!(5);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(6);
const FAIL_SPAWN: NonZeroU16 = fail_point!(7);
const FAIL_UNEXPECTED_SYSCALL: NonZeroU16 = fail_point!(8);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(9);
const FAIL_NO_PREEMPT: NonZeroU16 = fail_point!(10);
const FAIL_PREEMPT_STORAGE: NonZeroU16 = fail_point!(11);
const FAIL_EXIT_COUNT: NonZeroU16 = fail_point!(12);
const FAIL_SOLE_PREEMPTED: NonZeroU16 = fail_point!(13);
const FAIL_SPAWN_COMPETITOR: NonZeroU16 = fail_point!(14);

/// Count of involuntary timer-driven preemptions of the running U-mode task.
static PREEMPTIONS: AtomicU64 = AtomicU64::new(0);
/// `exit` syscalls observed (the spinner exits exactly once on completion).
static EXITS: AtomicU64 = AtomicU64::new(0);
/// [`PREEMPTIONS`] snapshot captured by the competitor kthread when it
/// exits (handing the hart to the now-sole spinner); `u64::MAX` until
/// recorded. `PREEMPTIONS == PREEMPTIONS_AT_SOLE` after the run proves the
/// sole spinner took **no** further timer interrupt (tickless disarm).
static PREEMPTIONS_AT_SOLE: AtomicU64 = AtomicU64::new(u64::MAX);

/// Set once the round-trip has been driven so a re-entry cannot re-run it.
static TEST_DRIVEN: AtomicU32 = AtomicU32::new(0);

/// Static boot heap, in the linker's NOLOAD `.heap` section so the boot
/// trampoline neither zeroes nor counts it in the usable memory map. The user
/// kthread's kernel stack + control block and the spawn caller's
/// startup-vector block allocate from it.
#[link_section = ".heap"]
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// Page-table pool backing the U-mode address space's Sv39 hierarchy.
static PAGE_TABLES: paging::PageTablePool = paging::PageTablePool::new();

/// Per-hart preemption backing for the single boot hart (`PreemptStorage<1>` covers a single-hart slice).
static PREEMPT_STORAGE: PreemptStorage<1> = PreemptStorage::new();

/// Physical-frame backing store the spawn builder allocates user pages from.
/// `align(4096)` so each `PAGE_SIZE` slice is a valid page frame; identity-
/// mapped (its physical address equals its kernel virtual address), so the
/// builder reaches it through [`DirectPhysMap::identity`].
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Hand out the next identity-mapped physical frame from [`FRAME_POOL`], or
/// `None` when the pool is exhausted (the spawn builder then fails closed).
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    // The pool is identity-mapped, so its kernel virtual address is also its
    // physical address.
    let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(base)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared riscv64 panic bridge (parks the hart; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn preempt_el0_qemu_riscv64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The U-mode-preemption callback the timer trap path invokes for a tick taken
/// from U-mode — the production dispatch shape verbatim: it
/// suspends the running user task back to the scheduler via
/// `reschedule_current(_, Yield)`, the involuntary analogue of a `yield`
/// syscall. It records each preemption so the test can prove at least one fired
/// against the never-yielding spinner.
extern "C" fn preempt_dispatch(cpu: CpuId) {
    PREEMPTIONS.fetch_add(1, Ordering::SeqCst);
    let _ = reschedule_current(cpu, RescheduleAction::Yield);
}

/// The syscall-dispatch callback the spinner's final `exit` `ecall` reaches.
///
/// The spinner issues no `yield`; its only syscall is the `exit` that
/// `tairix-rt` routes `main`'s return through. Any other syscall is unexpected
/// and fails the test loudly.
extern "C" fn dispatch(number: u64, _args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    let call = SyscallNumber::from_register(number).ok();
    if call == Some(SyscallNumber::EXIT) {
        EXITS.fetch_add(1, Ordering::SeqCst);
        // Reap the caller: this switches back to the dispatcher and never
        // resumes the task, so the `0` below is unreachable.
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Exit);
        0
    } else {
        note(TEST_FAIL, "fixture program issued an unexpected syscall");
        qemu_exit::exit_failure(FAIL_UNEXPECTED_SYSCALL);
    }
}

/// Build the isolated U-mode address space from the fixture `image` over
/// [`PAGE_TABLES`], returning its Sv39 root and the entry register state.
fn build_user_space(image: &LoadImage) -> (u64, UserEntry) {
    let Some(arch) = ArchAddressSpace::new_identity_gigapages(&PAGE_TABLES, IDENTITY_GIGABYTES)
    else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // Capture the `satp` root before the arch space is moved into the
    // `kernel/mem` wrapper, so the `pre_resume` hook can reactivate it.
    let root_phys = arch.root_phys();
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, heap,
    // frame pool, and device MMIO (all within `[0, 4 GiB)` on `virt`), so the
    // `satp` switch does not move the ground under the running code. Boot hart.
    unsafe { arch.switch() };

    let mut space = AddressSpace::new(arch);
    // SAFETY: the boot code identity-maps this window and never unmaps it.
    let physmap = unsafe { DirectPhysMap::identity((IDENTITY_GIGABYTES as u64) << 30) }
        .expect("the boot direct map addresses its window");
    let request = SpawnRequest {
        image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"el0"],
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once its space is reactivated (via the `pre_resume`
    // hook) and the trap path is installed. The frame source draws identity-
    // mapped frames from `FRAME_POOL`.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => qemu_exit::exit_failure(FAIL_BUILD),
    };
    (root_phys, entry)
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls.
#[no_mangle]
pub extern "C" fn kernel_main(hartid: u64, dtb: u64) -> ! {
    if TEST_DRIVEN
        .compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire)
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_POOL);
    }

    note(TEST_START, "riscv64 U-mode preemption test: starting");

    // Read the timer frequency from the firmware tree. Fail closed (finisher)
    // if it is omitted rather than guessing a divisor.
    // SAFETY: `dtb` is the verbatim `a1` pointer OpenSBI handed the boot hart;
    // `boot.s` forwards it unchanged.
    let Some(timebase) = (unsafe { Fdt::from_ptr(dtb as *const u8) })
        .ok()
        .and_then(|f| f.timebase_frequency())
    else {
        qemu_exit::exit_failure(FAIL_NO_TIMEBASE);
    };

    // The single-hart slice only brings up logical CPU 0 on hart 0.
    if hartid != u64::from(BOOT_CPU) {
        qemu_exit::exit_failure(FAIL_UNEXPECTED_HART);
    }

    // Parse the build-time `rxe` blob once against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        qemu_exit::exit_failure(FAIL_PARSE);
    };

    // Build the isolated U-mode address space (it leaves its own space active).
    let (root_phys, entry) = build_user_space(&image);

    // Install the trap vector + the syscall-dispatch callback before any user
    // task runs. Crucially this uses `install_trap_vector`, NOT `init_traps`:
    // `sstatus.SIE` stays clear, so the kernel (the S-mode `step` loop below)
    // is never preempted — only the U-mode spinner is (a supervisor-timer
    // interrupt is taken in U-mode by the privilege rule U < S, regardless of
    // `SIE`). This mirrors the production riscv64 boot, which arms preemption
    // without enabling `sstatus.SIE`.
    // SAFETY: called once on the boot hart with a stack established and the MMU
    // enabled (the address-space build switched it on).
    unsafe { trap::install_trap_vector() };
    syscall_entry::set_dispatch_callback(dispatch);

    // Set up the production tickless preemption path verbatim: register the per-hart storage, install the U-mode-preemption
    // callback, record the per-quantum interval, and enable `sie.STIE` — but
    // leave the timer **disarmed**. The scheduler arms the one-shot to one
    // quantum only when it dispatches the spinner onto a hart that still has
    // the competitor kthread queued (`RiscvArch::set_preemption`).
    if PREEMPT_STORAGE.register().is_err() {
        qemu_exit::exit_failure(FAIL_PREEMPT_STORAGE);
    }
    preempt::set_preempt_callback(preempt_dispatch);
    let interval = preempt::interval_for_hz(timebase, PREEMPT_TICK_HZ);
    // SAFETY: the boot hart (id 0); the preempt callback is installed (above),
    // the per-hart storage is registered (above), and the trap vector is
    // installed (`install_trap_vector`). It records the quantum, enables
    // `sie.STIE`, and leaves the timer disarmed; `sstatus.SIE` stays clear, so
    // no tick is taken until the spinner runs in U-mode, and the scheduler
    // arms the first one-shot on its next dispatch onto a contended hart.
    unsafe {
        preempt::init_local_preempt(BOOT_CPU, interval);
    }

    // Build the live scheduler over the production arch handle. Single-hart
    // slice: one per-CPU slot, owned by an allocator-free `static` backing.
    static STORAGE: RiscvArchStorage<1> = RiscvArchStorage::new();
    let arch = Arc::new(RiscvArch::new(&STORAGE, BOOT_CPU, timebase));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    // Admit the **competitor** first: a kernel kthread that yields until it
    // observes the spinner preempted at least [`TARGET_PREEMPTIONS`] times,
    // records the count, and exits — handing the hart to the now-sole
    // spinner. While it is queued the scheduler arms the one-shot, so the
    // runaway spinner is preempted (contention case); once it exits the sole
    // spinner runs disarmed to completion (tickless case).
    let competitor = move |yielder: &mut Yielder<ContextSwitchHal>| {
        while PREEMPTIONS.load(Ordering::SeqCst) < TARGET_PREEMPTIONS {
            yielder.yield_now();
        }
        PREEMPTIONS_AT_SOLE.store(PREEMPTIONS.load(Ordering::SeqCst), Ordering::SeqCst);
    };
    if spawn_kthread(
        &sched,
        ContextSwitchHal::new(),
        BOOT_CPU,
        Priority::Normal,
        competitor,
    )
    .is_err()
    {
        qemu_exit::exit_failure(FAIL_SPAWN_COMPETITOR);
    }

    // Admit the spinner as a resumable user kthread: its `pre_resume` hook
    // reactivates its page-table root (isolation), and its work body
    // `enter_user`s into U-mode.
    let cs = ContextSwitchHal::new();
    let user_mode = UserMode::new();
    let pre_resume = move |_top: u64| {
        // SAFETY: paging is enabled and `root_phys` is the Sv39 root of a space
        // that maps the low identity window the running dispatcher executes
        // from — exactly `activate_user_root`'s contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |_yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: by the time this body runs the task has been dispatched, so
        // its `pre_resume` hook reactivated `satp`, and the trap vector +
        // dispatch callback are installed; the program's `exit` `ecall` is
        // handled. `build_process_image` mapped the entry/stack as user pages.
        unsafe { user_mode.enter_user(entry) }
    };
    if spawn_user_kthread(&sched, cs, BOOT_CPU, Priority::Normal, pre_resume, work).is_err() {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(
        TEST_SPAWNED,
        "riscv64 U-mode preemption test: spinner spawned",
    );

    // Dispatch loop: drive `step` until both tasks finish. While the
    // competitor is queued, each spinner dispatch arms the one-shot and the
    // never-yielding spinner is preempted; once the competitor exits, the
    // lone spinner runs disarmed to completion and `exit`s. A preemption
    // that never fires would leave the contended `step` spinning forever in
    // U-mode and the harness would time out (fail-loud).
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }
    if sched.live_task_count() != 0 {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }
    // Contention case: the competitor recorded the preemption count at
    // hand-off, and it must be at least `TARGET_PREEMPTIONS` — proving the
    // timer one-shot fired and preempted the runaway U-mode task.
    let at_sole = PREEMPTIONS_AT_SOLE.load(Ordering::SeqCst);
    if at_sole == u64::MAX || at_sole < TARGET_PREEMPTIONS {
        qemu_exit::exit_failure(FAIL_NO_PREEMPT);
    }
    // Sole-task (tickless) case: after the competitor exited, the sole
    // spinner ran millions of iterations to completion with the one-shot
    // disarmed, so essentially no further preemption fired — at most the
    // benign contended→sole boundary fire (`SOLE_PREEMPT_SLACK`). A
    // re-armed periodic tick would have added hundreds.
    if PREEMPTIONS.load(Ordering::SeqCst) > at_sole.saturating_add(SOLE_PREEMPT_SLACK) {
        qemu_exit::exit_failure(FAIL_SOLE_PREEMPTED);
    }
    if EXITS.load(Ordering::SeqCst) != 1 {
        qemu_exit::exit_failure(FAIL_EXIT_COUNT);
    }

    note(
        TEST_PASS,
        "riscv64 U-mode preemption test: contended runaway task preempted; sole task ran tickless",
    );
    qemu_exit::exit_success();
}
