//! The freestanding riscv64 test kernel: prove the **production**
//! demand-paged file-mapping path end to end on the `virt` board — the
//! riscv64 twin of `file_map_qemu_aarch64` (`plans/APPS.md` M1 remainder;
//! `docs/src/architecture/memory.md` §7o).
//!
//! Unlike the bespoke micro-kernel harnesses, every syscall and every user
//! fault here runs the production `KernelDispatchHook` /
//! `KernelSyscallHandlers` path: the chassis installs the hook through a
//! `DispatchCallbackSlot`, binds the production user-fault resolver to the
//! same slot, wires the production `LiveMemMap` producer (both `mem_map`
//! and `file_map`), a read-only in-guest filesystem double serving one
//! fixture file, a real `KernelProcessWait`, and a `ProgramRegistry`
//! carrying the three child roles. The parent role is spawned through the
//! production `InitSpawnCtx::spawn_driver_process` seam; it spawns and
//! reaps the children through the production `spawn` + `wait` syscalls:
//!
//! * `verify` — demand-faults first/interior/EOF-straddle pages,
//!   read-verifies the fixture bytes and the zero fill, proves the mapping
//!   survives `fs_close`, hands an **untouched** mapped page to `fs_open`
//!   (the copy-path fault-resolution proof), unmaps, exits 0;
//! * `wild` — maps, unmaps, then reads the unmapped base: fault-killed,
//!   exit 139;
//! * `store` — maps, faults a page resident, stores to it: the read-only
//!   write-fault gate kills it, exit 139.
//!
//! The chassis reaps the parent through the producer's non-blocking poll
//! and PASSes only on a parent exit of 0.

use core::num::NonZeroU16;
use core::panic::PanicInfo;

use alloc::boxed::Box;
use alloc::string::String;
use alloc::sync::Arc;

use tairix_abi::driver::filesystem::DirVisit;
use tairix_abi::{
    CapabilityId, CapabilityQuery, DirEntry, Errno, FileKind, FileStat, OpenFlags, RealpathMode,
    RenameFlags, UnlinkFlags, WaitFlags, WaitStatus, SYSCALL_MAX_ARGS,
};
use tairix_arch_api::BOOT_CPU;
use tairix_arch_riscv64::fdt::Fdt;
use tairix_arch_riscv64::{
    handle_panic_via_serial, qemu_exit, syscall_entry, trap, RiscvArch, RiscvArchStorage,
    SERIAL_SINK,
};
use tairix_caps::CapabilitySet;
use tairix_itest_finisher::fail_code;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel::dispatch_core::{dispatch_via_slot, read_raw_args, resolve_user_fault_via_slot};
use tairix_kernel::riscv64::boot::{self as boot_riscv64, RiscvBinArch, RISCV_UART_CONSOLES};
use tairix_kernel::riscv64::spawn_producer::{CHILD_USER_BIAS, RISCV_PROCESS_SPAWN};
use tairix_kernel_core::fs::{FinalLink, Listing};
use tairix_kernel_core::{
    AddressSpaceRegistry, BootReserve, DispatchCallbackSlot, EmbeddedProgram, FilesystemService,
    InitSpawnCtx, KernelArch, KernelDispatchHook, KernelInitSpawner, KernelProcessWait, LiveMemMap,
    ProcessWait, ProgramRegistry, RandomReserve, SchedWaitQueueArch, NULL_DMA_ALLOC_FACILITY,
    NULL_MMIO_MAP_FACILITY, NULL_SEAT_REGISTRY, NULL_SHARED_MEM_FACILITY,
};
use tairix_kernel_ipc::PortRegistry;
use tairix_kernel_irq::{IrqTable, UnsupportedController};
use tairix_kernel_mem::{
    BootMemoryMap, FrameAllocator, MemoryRegion, PhysAddr, RegionKind, PAGE_SIZE,
};
use tairix_kernel_sched_eevdf::{Scheduler, SchedulerConfig};
use tairix_kernel_sec::{CapTable, ProcessId};
use tairix_log::{log, Event, EventId, Level};
use tairix_sync::RwLock;

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// `FIXTURE_PATH: &str` and `FIXTURE_CONTENT: &[u8]`, generated by `build.rs`
// from the shared single definition (`tairix_itest_harness::filemap_fixture`).
include!(concat!(env!("OUT_DIR"), "/fm_fixture.rs"));

/// Physical frames the production spawn producer and the file-mapping
/// producer draw from: four spawned processes (image, stack, page tables —
/// each a full `tairix-rt` program with a 256 KiB stack and its own
/// identity-window tables) plus the demand-faulted file pages. Sized from
/// the observed per-process appetite with generous headroom (16 MiB).
const FRAME_COUNT: usize = 4096;

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4350);
const TEST_SPAWNED: EventId = EventId(4351);
const TEST_PASS: EventId = EventId(4352);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_FDT: NonZeroU16 = fail_point!(2);
const FAIL_UNEXPECTED_HART: NonZeroU16 = fail_point!(3);
const FAIL_FRAMES: NonZeroU16 = fail_point!(4);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(5);
const FAIL_SPAWN: NonZeroU16 = fail_point!(6);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(7);
const FAIL_NO_DISPATCH: NonZeroU16 = fail_point!(8);
const FAIL_HOOK_INSTALL: NonZeroU16 = fail_point!(9);
const FAIL_RESOLVER_INSTALL: NonZeroU16 = fail_point!(10);
const FAIL_BIAS: NonZeroU16 = fail_point!(11);
const FAIL_POLL: NonZeroU16 = fail_point!(12);
const FAIL_DRAINED: NonZeroU16 = fail_point!(13);
const FAIL_PARENT_STOPPED: NonZeroU16 = fail_point!(14);
const FAIL_PAGING: NonZeroU16 = fail_point!(15);
/// Base finisher for a non-zero parent exit; the parent's diagnostic exit
/// code is added so the failing role/site is identifiable in the finisher.
const FAIL_EXIT_BASE: NonZeroU16 = fail_point!(100);

/// Size of the test's bump heap. Lives in `.bss` (zeroed by the trampoline).
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Identity-mapped physical-frame backing store the live [`FrameAllocator`]
/// serves the spawn producer and the file-mapping producer from; inside
/// the 4 GiB identity window the producer's Sv39 page-table walk requires
/// (the `virt` board's RAM base at 2 GiB sits within it).
#[repr(C, align(4096))]
struct FramePool([u8; PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; PAGE_SIZE * FRAME_COUNT]);

/// The dispatch-callback slot the production [`KernelDispatchHook`] is
/// installed into (one slot per binary, set once). Both the syscall
/// callback and the user-fault resolver resolve through it.
static DISPATCH_SLOT: DispatchCallbackSlot = DispatchCallbackSlot::new();

/// Per-CPU storage backing the scheduler's arch handle.
static SCHED_STORAGE: RiscvArchStorage<1> = RiscvArchStorage::new();

/// Per-CPU storage backing the dispatch hook + spawn ctx arch handle.
static HOOK_ARCH_STORAGE: RiscvArchStorage<1> = RiscvArchStorage::new();

/// This vertical binds no IRQ lines; the fail-closed controller mirrors
/// what `kernel/core::init` installs when a port exposes no routing.
static IRQ_CONTROLLER: UnsupportedController = UnsupportedController;

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared riscv64 panic bridge (parks the hart; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn file_map_qemu_riscv64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// The syscall-dispatch callback every program's `ecall` traps reach. It
/// mirrors the production bin-crate callback (`dispatch_riscv64`): read the
/// kernel-stack args frame and forward through the resident production
/// [`KernelDispatchHook`] via the shared `dispatch_via_slot` bridge. An
/// empty slot or a missing caller context fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the trap trampoline lays the frame out on the kernel
    // stack and only invokes us with a valid pointer; the array lives at
    // least until we return.
    let args = unsafe { read_raw_args(args_ptr) };
    match dispatch_via_slot(&DISPATCH_SLOT, number, args) {
        Some(value) => value,
        None => qemu_exit::exit_failure(FAIL_NO_DISPATCH),
    }
}

/// The user-fault resolver the S-mode trap path calls for every U-mode
/// load/store page fault: the exact production glue
/// (`production_user_fault`), bound to this vertical's own slot so a load
/// fault runs the resident production hook's `resolve_file_fault` path and
/// a store (or unresolvable load) kills the faulting task through the
/// production fault-exit path.
// The callback matches the arch `UserFaultResolveFn` type (a bare safe
// `extern "C" fn`); the raw pointer is only forwarded into the guarded
// `unsafe` call below, which narrows it with `as_ref`.
#[allow(clippy::not_unsafe_ptr_arg_deref)]
extern "C" fn file_map_user_fault(
    stval: u64,
    write: bool,
    regs: *const tairix_arch_api::backtrace::UserRegisterFrame,
) -> bool {
    // SAFETY: the trap handler builds the frame on its kernel stack and
    // holds it live across this call, or passes null; the slot helper
    // narrows the pointer with `as_ref` and never dereferences null.
    unsafe { resolve_user_fault_via_slot(&DISPATCH_SLOT, stval, write, regs) }
}

/// The in-guest read-only filesystem double: serves exactly the one
/// fixture file the shared definition emits, under the caller-blind
/// `FilesystemService` seam the production handlers consume. Everything
/// else fails closed — a mutation is `PermissionDenied` (the double is
/// read-only), an unknown path is `NotFound`, and the surfaces this
/// vertical never exercises are `NotImplemented` (an inert interface
/// announces itself, mirroring `NullFilesystemService`).
struct FixtureFs;

impl FilesystemService for FixtureFs {
    fn open(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        path: &str,
        flags: OpenFlags,
    ) -> Result<(), Errno> {
        if path != FIXTURE_PATH {
            return Err(Errno::NotFound);
        }
        if flags.is_write() {
            return Err(Errno::PermissionDenied);
        }
        Ok(())
    }

    fn read(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        path: &str,
        offset: u64,
        buf: &mut [u8],
    ) -> Result<usize, Errno> {
        if path != FIXTURE_PATH {
            return Err(Errno::NotFound);
        }
        let len = FIXTURE_CONTENT.len() as u64;
        if offset >= len {
            return Ok(0);
        }
        let available = usize::try_from(len - offset).map_err(|_| Errno::OutOfRange)?;
        let n = buf.len().min(available);
        let start = usize::try_from(offset).map_err(|_| Errno::OutOfRange)?;
        buf[..n].copy_from_slice(&FIXTURE_CONTENT[start..start + n]);
        Ok(n)
    }

    fn write(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _path: &str,
        _offset: u64,
        _append: bool,
        _data: &[u8],
    ) -> Result<usize, Errno> {
        Err(Errno::PermissionDenied)
    }

    fn readdir(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _path: &str,
        _final_link: FinalLink,
        _at: &mut Listing,
        _each: &mut dyn FnMut(&DirEntry<'_>) -> DirVisit,
    ) -> Result<(), Errno> {
        Err(Errno::NotImplemented)
    }

    fn symlink(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _target: &str,
        _path: &str,
    ) -> Result<(), Errno> {
        Err(Errno::NotImplemented)
    }

    fn link(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _existing: &str,
        _link: &str,
        _existing_link: FinalLink,
    ) -> Result<(), Errno> {
        // The fixture's flat map holds one name per entry; a second name for
        // one node is not something it can represent.
        Err(Errno::NotImplemented)
    }

    fn readlink(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _path: &str,
    ) -> Result<String, Errno> {
        Err(Errno::NotImplemented)
    }

    fn realpath(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _path: &str,
        _mode: RealpathMode,
    ) -> Result<String, Errno> {
        Err(Errno::NotImplemented)
    }

    fn stat(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        path: &str,
        _final_link: FinalLink,
    ) -> Result<FileStat, Errno> {
        if path != FIXTURE_PATH {
            return Err(Errno::NotFound);
        }
        let len = FIXTURE_CONTENT.len() as u64;
        Ok(FileStat {
            kind: FileKind::Regular,
            nlink: 1,
            size: len,
            allocated: len,
            mode: 0o444,
            uid: 0,
            gid: 0,
            id: tairix_abi::FileId::NONE,
            times: tairix_abi::NodeTimes::default(),
            content_gen: tairix_abi::driver::filesystem::NodeInfo::NO_CONTENT_GEN,
        })
    }

    fn truncate(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _path: &str,
        _size: u64,
    ) -> Result<(), Errno> {
        Err(Errno::PermissionDenied)
    }

    fn sync(&self, _uid: u32, _caps: &dyn CapabilityQuery) -> Result<(), Errno> {
        Err(Errno::NotImplemented)
    }

    fn mkdir(&self, _uid: u32, _caps: &dyn CapabilityQuery, _path: &str) -> Result<(), Errno> {
        Err(Errno::PermissionDenied)
    }

    fn unlink(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _path: &str,
        _flags: UnlinkFlags,
    ) -> Result<(), Errno> {
        Err(Errno::PermissionDenied)
    }

    fn rename(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _from: &str,
        _to: &str,
        _flags: RenameFlags,
    ) -> Result<(), Errno> {
        Err(Errno::PermissionDenied)
    }

    fn set_mode(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _path: &str,
        _mode: u32,
    ) -> Result<(), Errno> {
        Err(Errno::PermissionDenied)
    }

    // The fixture stores no extended attributes; every attribute call
    // answers the typed unsupported-backing refusal.
    fn attr_get(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _path: &str,
        _key: &[u8],
        _value_out: &mut [u8],
    ) -> Result<usize, Errno> {
        Err(Errno::NotSupported)
    }

    fn attr_set(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _path: &str,
        _key: &[u8],
        _value: &[u8],
    ) -> Result<(), Errno> {
        Err(Errno::NotSupported)
    }

    fn attr_list(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _path: &str,
        _index: u64,
        _key_out: &mut [u8],
    ) -> Result<Option<usize>, Errno> {
        Err(Errno::NotSupported)
    }

    fn attr_remove(
        &self,
        _uid: u32,
        _caps: &dyn CapabilityQuery,
        _path: &str,
        _key: &[u8],
    ) -> Result<(), Errno> {
        Err(Errno::NotSupported)
    }
}

/// The single installed filesystem double.
static FIXTURE_FS: FixtureFs = FixtureFs;

/// The capability set the fixture programs run under: `FS_ACCESS` for the
/// children's `fs_open`/`file_map`, and `PROC_SPAWN` for the parent's
/// `spawn`. The parent's set doubles as the inherited ceiling the
/// production spawn intersects each child's manifest request with, so a
/// child's effective set is exactly its registry row's request.
fn parent_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::PROC_SPAWN);
    caps.insert(CapabilityId::FS_ACCESS);
    caps
}

/// The child roles' manifest capability request: file access only — a
/// child spawns nothing.
static CHILD_CAPS: &[CapabilityId] = &[CapabilityId::FS_ACCESS];

/// The program registry the production `spawn` syscall resolves the
/// parent's child paths against: one `rxe` image, three rows, each pinning
/// its role through the registered default argument vector.
static CHILD_PROGRAMS: [EmbeddedProgram; 3] = [
    EmbeddedProgram {
        path: b"/bin/fm-verify",
        rxe: PROGRAM_RXE,
        caps: CHILD_CAPS,
        args: &[b"fm", b"verify"],
    },
    EmbeddedProgram {
        path: b"/bin/fm-wild",
        rxe: PROGRAM_RXE,
        caps: CHILD_CAPS,
        args: &[b"fm", b"wild"],
    },
    EmbeddedProgram {
        path: b"/bin/fm-store",
        rxe: PROGRAM_RXE,
        caps: CHILD_CAPS,
        args: &[b"fm", b"store"],
    },
];

/// The registry over [`CHILD_PROGRAMS`].
static PROGRAMS: ProgramRegistry = ProgramRegistry::new(&CHILD_PROGRAMS);

/// Bring the board up: parse the live `virt` device tree OpenSBI passed in
/// `a1` for the timebase, install the S-mode trap vector, and install the
/// dispatch callback + user-fault resolver. The kernel itself runs with
/// bring paging up through the one production sequence
/// (`boot_riscv64::enable_paging_and_direct_map`) — the boot identity space
/// plus the direct physical map — because the production spawn producer
/// reaches each child's Sv39 tables *through* that map. Returns the
/// discovered timebase.
fn bring_up_board(dtb: u64) -> u64 {
    // SAFETY: `dtb` is the verbatim `a1` pointer from OpenSBI; it addresses
    // a valid flattened device tree that lives for the life of the guest.
    let Ok(fdt) = (unsafe { Fdt::from_ptr(dtb as *const u8) }) else {
        qemu_exit::exit_failure(FAIL_FDT);
    };
    let Some(timebase_hz) = fdt.timebase_frequency() else {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    };
    if timebase_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }

    // Bring paging up before the trap vector, so the handler address the
    // vector names resolves under the regime that will be in force. A
    // refusal is fatal: the producer cannot reach a child's tables without
    // the map.
    // SAFETY: `dtb` is the verbatim `a1` pointer (as above), and this is the
    // boot hart's single call.
    if boot_riscv64::enable_paging_and_direct_map(dtb).is_err() {
        qemu_exit::exit_failure(FAIL_PAGING);
    }

    // Install the trap vector + the callbacks before any user task runs.
    // SAFETY: called once on the boot hart with a stack established.
    unsafe { trap::init_traps() };
    syscall_entry::set_dispatch_callback(dispatch);
    // Bind the production user-fault resolver to this vertical's slot — the
    // demand-paging heart this test exists to prove.
    if tairix_arch_api::fault::set_user_fault_resolver(file_map_user_fault).is_err() {
        qemu_exit::exit_failure(FAIL_RESOLVER_INSTALL);
    }
    timebase_hz
}

/// The leaked-`'static` kernel subsystems the production dispatch hook and
/// spawn context borrow — the vertical's analogue of `KernelState`, lifted
/// by one-shot `Box::leak` publishes exactly as `kernel_core::kernel_main`
/// does (a one-shot publish, not a global mutable static).
struct Subsystems {
    frames: &'static FrameAllocator,
    sched: &'static Scheduler<RiscvBinArch>,
    arch: &'static RiscvBinArch,
    caps: &'static RwLock<CapTable>,
    peer_watch: &'static tairix_kernel_core::PeerWatch,
    ipc: &'static RwLock<PortRegistry>,
    aspaces: &'static RwLock<AddressSpaceRegistry>,
    rng: &'static RwLock<Box<dyn RandomReserve + Send + Sync>>,
    irq_table: &'static IrqTable,
}

/// Build the live kernel subsystems: the `kernel/mem` frame allocator over
/// the identity-mapped pool (so the spawn producer and the demand-fault
/// path draw their frames from the production path), the scheduler over
/// the production `KernelArch` wrapper, and the capability / port /
/// address-space / random / IRQ state the production hook borrows.
fn leak_subsystems(counter_hz: u64) -> Subsystems {
    let mut memory_map = BootMemoryMap::new();
    memory_map.push(MemoryRegion {
        start: PhysAddr::new(core::ptr::addr_of!(FRAME_POOL) as u64),
        length: (PAGE_SIZE * FRAME_COUNT) as u64,
        kind: RegionKind::Usable,
    });
    let Ok(frames) = FrameAllocator::new(&memory_map) else {
        qemu_exit::exit_failure(FAIL_FRAMES);
    };
    let frames: &'static FrameAllocator = Box::leak(Box::new(frames));

    let sched_arch = Arc::new(RiscvBinArch::new(
        RiscvArch::new(&SCHED_STORAGE, BOOT_CPU, counter_hz),
        None,
    ));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), sched_arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    Subsystems {
        frames,
        sched: Box::leak(Box::new(sched)),
        arch: Box::leak(Box::new(RiscvBinArch::new(
            RiscvArch::new(&HOOK_ARCH_STORAGE, BOOT_CPU, counter_hz),
            None,
        ))),
        caps: Box::leak(Box::new(RwLock::new(CapTable::new()))),
        peer_watch: Box::leak(Box::new(tairix_kernel_core::PeerWatch::new())),
        ipc: Box::leak(Box::new(RwLock::new(PortRegistry::new()))),
        aspaces: Box::leak(Box::new(RwLock::new(AddressSpaceRegistry::new()))),
        rng: Box::leak(Box::new(RwLock::new(
            Box::new(BootReserve::new()) as Box<dyn RandomReserve + Send + Sync>
        ))),
        irq_table: Box::leak(Box::new(IrqTable::new(0))),
    }
}

/// Boot entry point — the symbol the arch crate's boot trampoline calls
/// with the boot hart id in `a0` and the device-tree pointer in `a1`.
#[no_mangle]
pub extern "C" fn kernel_main(hartid: u64, dtb: u64) -> ! {
    note(TEST_START, "riscv64 file-map test: starting");

    if hartid != u64::from(BOOT_CPU) {
        qemu_exit::exit_failure(FAIL_UNEXPECTED_HART);
    }
    let counter_hz = bring_up_board(dtb);

    // The fixture `rxe`'s baked relocations must target the bias the
    // production producer maps every child at; a drifted constant would
    // admit a child whose pointers do not match its mapping (fail closed).
    if USER_BIAS != CHILD_USER_BIAS {
        qemu_exit::exit_failure(FAIL_BIAS);
    }

    let sys = leak_subsystems(counter_hz);

    // Publish the wait-queue arch hook so parked waiters (the parent in
    // `wait`) are genuinely unparked by their wake events — the same
    // adapter the production boot path installs.
    let wait_arch = SchedWaitQueueArch::leak(sys.sched, sys.arch);
    if tairix_kernel_core::waitq::install_wait_arch(wait_arch).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // The scheduler-side process-wait producer: records every parent/child
    // link the production spawn paths register and backs the production
    // `wait` syscall the parent blocks in.
    let wait_producer: &'static KernelProcessWait<RiscvBinArch> =
        Box::leak(Box::new(KernelProcessWait::new(sys.arch)));

    // The production live-space producer: serves the `mem_map` pair (the
    // `tairix-rt` heap) and — the point of this vertical — the `file_map`
    // reserve / demand-fault `map_page` / sparse `release` triple.
    let live: &'static LiveMemMap<RiscvBinArch> = Box::leak(Box::new(LiveMemMap::new(sys.arch)));

    // Publish the production dispatch hook: every syscall the programs
    // issue — `spawn`, `wait`, `fs_open`, `fs_close`, `file_map`,
    // `file_unmap`, `exit` — and every user-fault resolution runs the
    // production caller-context resolution and handler path.
    let hook: &'static KernelDispatchHook<'static, RiscvBinArch> = Box::leak(Box::new(
        KernelDispatchHook::new(
            sys.sched,
            sys.caps,
            sys.arch,
            &SERIAL_SINK,
            sys.irq_table,
            &IRQ_CONTROLLER,
            sys.ipc,
            sys.aspaces,
            sys.rng,
            &RISCV_UART_CONSOLES,
            sys.frames,
            sys.frames,
            &PROGRAMS,
            wait_producer,
            // No seat / MMIO / DMA surface in this vertical; those
            // producers stay fail-closed.
            &NULL_SEAT_REGISTRY,
            live,
            &NULL_MMIO_MAP_FACILITY,
            &NULL_DMA_ALLOC_FACILITY,
        )
        .with_peer_watch(sys.peer_watch)
        .with_file_map(live)
        .with_filesystem(&FIXTURE_FS),
    ));
    if DISPATCH_SLOT.install_dispatcher(hook).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // Spawn the parent role through the production runtime-spawn seam
    // (`KernelSpawnCtx` assembly inside `KernelInitSpawner`), recorded
    // against the kernel supervisor identity so this chassis can reap it.
    // Publish the launch-services bundle the deferred child-load path reads:
    // the arch image builder builds each admitted child's image on the
    // child's own first slice, off this chassis's cooperative drive. The one
    // shared build+publish the production boot path uses.
    let _ = tairix_kernel_core::spawn_services::install_over(
        sys.arch,
        sys.frames,
        &SERIAL_SINK,
        &tairix_kernel_core::NULL_FILESYSTEM,
        None,
        sys.aspaces,
        sys.caps,
        sys.peer_watch,
        wait_producer,
        &RISCV_PROCESS_SPAWN,
    );

    let init_ctx = KernelInitSpawner::new(
        sys.frames,
        &SERIAL_SINK,
        sys.sched,
        sys.caps,
        sys.peer_watch,
        sys.aspaces,
        sys.arch,
        wait_producer,
        sys.irq_table,
        &IRQ_CONTROLLER,
        &NULL_SHARED_MEM_FACILITY,
        KernelArch::cross_cpu_tlb_shootdown(sys.arch),
    );
    let Ok(parent_pid) = init_ctx.spawn_driver_process(
        "/bin/fm-parent",
        PROGRAM_RXE,
        parent_caps(),
        &[],
        &[b"fm", b"parent"],
        None,
    ) else {
        qemu_exit::exit_failure(FAIL_SPAWN);
    };
    note(
        TEST_SPAWNED,
        "riscv64 file-map test: parent spawned through the production seam",
    );

    // The budget-bounded cooperative drive: step the scheduler and poll the
    // wait producer for the parent's exit between steps. The parent runs
    // the whole verify / wild / store sequence through production spawn +
    // wait; a parent exit of 0 is the PASS, anything else names the failing
    // site through its diagnostic code.
    // A task id never exceeds the ABI's pid bound, so reinterpreting it as
    // the signed pid the wait ABI carries is exact.
    let parent_pid = parent_pid.cast_signed();
    let mut steps = 0u64;
    while steps < MAX_STEPS {
        let _ = sys.sched.step(BOOT_CPU);
        steps += 1;

        // Deliver any wake a handler deferred while the task ran — the same
        // between-dispatches service the production loop performs; without
        // it a child's `exit` never unparks the parent blocked in `wait`.
        let _ = tairix_kernel_core::waitq::drain_pending_wakes();

        match wait_producer.poll(ProcessId(0), parent_pid, WaitFlags::empty()) {
            Ok(reaped) => match reaped.status {
                WaitStatus::Exited(0) => {
                    note(
                        TEST_PASS,
                        "riscv64 file-map test: parent verified all three children and exited 0",
                    );
                    qemu_exit::exit_success();
                }
                WaitStatus::Exited(code) => {
                    qemu_exit::exit_failure(fail_code(FAIL_EXIT_BASE, code));
                }
                WaitStatus::Stopped(_) => {
                    qemu_exit::exit_failure(FAIL_PARENT_STOPPED);
                }
            },
            Err(Errno::WouldBlock) => {}
            Err(_) => qemu_exit::exit_failure(FAIL_POLL),
        }

        // A fully drained workload without a reapable parent means the
        // parent vanished down a path that never recorded its exit; fail
        // with a distinct finisher rather than spinning out the watchdog.
        if sys.sched.live_task_count() == 0 {
            qemu_exit::exit_failure(FAIL_DRAINED);
        }
    }
    qemu_exit::exit_failure(FAIL_DEADLOCK);
}
