//! The x86_64 mem_map test kernel: boot the production pipeline, then on
//! `BootCompleted` build one isolated ring-3 program, install a `MemMap`
//! producer over its live address space, and route the program's
//! `mem_map`/`mem_unmap` syscalls through it (`plans/SPAWN.md` `SP5b-2`, the
//! x86_64 sibling of `mem_map_qemu_{aarch64,riscv64}`).

use core::cell::UnsafeCell;
use core::panic::PanicInfo;
use core::sync::atomic::{AtomicBool, AtomicU32, AtomicUsize, Ordering};

use tairix_abi::rxe::LoadImage;
use tairix_abi::{CapabilityId, CapabilityQuery, Errno, MapFlags, SyscallNumber, SYSCALL_MAX_ARGS};
use tairix_arch_api::fatal::KernelFault;
use tairix_arch_api::EnterUser;
use tairix_arch_x86_64::paging::{self, KERNEL_VMA_BASE};
use tairix_arch_x86_64::userentry::UserMode;
use tairix_arch_x86_64::{fault, qemu_exit, syscall_entry};
use tairix_kernel::kalloc::{Heap, HEAP_BYTES};
use tairix_kernel::{
    boot, handle_panic_via_kernel_core, FreeListAllocator, SerialSink, SERIAL_SINK,
};
use tairix_kernel_core::{spawn_image, MemMap, SpawnMode, SpawnRequest};
use tairix_kernel_mem::{
    map_anonymous, page_count_for, unmap_anonymous, AddressSpace, AnonError, DirectPhysMap, Frame,
    PhysAddr, Retire, Unpublished, UserStack,
};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level, Sink};

// `PROGRAM_RXE: &[u8]`, `USER_BIAS: u64`, `REGION_VA: u64`, and
// `REGION_LEN: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// `EventId` emitted when every boot init phase completed.
const BOOT_COMPLETED_EVENT_ID: EventId = EventId(4004);

/// Stable audit-event ids for the QEMU transcript (clear of the `4000..5000`
/// `kernel/core` boot range).
const TEST_START: EventId = EventId(4274);
const TEST_SPAWNED: EventId = EventId(4275);
const TEST_PASS: EventId = EventId(4276);
const TEST_FAIL: EventId = EventId(4277);

/// User stack base (1 MiB into the high user region) and size. `tairix-rt`
/// carves scratch space off the stack, so it must comfortably exceed it.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB > the runtime's scratch span plus call frames).
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up, well
/// clear of the program image and the stack).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// `IA32_EFER` MSR number and its No-Execute-Enable bit (bit 11).
const IA32_EFER: u32 = 0xC000_0080;
const EFER_NXE: u64 = 1 << 11;

/// Physical frames the test hands the spawn build and the anonymous map.
const FRAME_COUNT: usize = 320;

/// `true` once a `mem_map` call returned `Ok` to the program.
static MAP_OK: AtomicBool = AtomicBool::new(false);
/// `true` once a `mem_unmap` call returned `Ok` to the program.
static UNMAP_OK: AtomicBool = AtomicBool::new(false);

/// Set once the round-trip has been driven so a duplicate `BootCompleted`
/// cannot re-enter the test logic.
static TEST_DRIVEN: AtomicU32 = AtomicU32::new(0);

/// Static heap for the bump allocator (per the production bin); the boot
/// pipeline and the spawn caller's startup-vector block allocate from it.
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// Page-table pool backing the new address space (lives in `.bss`).
static PAGE_TABLE_POOL: paging::PageTablePool = paging::PageTablePool::new();

/// Physical-frame backing store the spawn builder and the anonymous map draw
/// user pages from. `align(4096)` so each `PAGE_SIZE` slice is a valid page
/// frame. A higher-half kernel static, so its physical address is its virtual
/// address minus [`KERNEL_VMA_BASE`]; the builders reach it through a
/// [`DirectPhysMap`] with that same offset.
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Hand out the next physical frame from [`FRAME_POOL`], or `None` when
/// exhausted. The pool is a higher-half kernel static, so its physical address
/// is its virtual address minus [`KERNEL_VMA_BASE`].
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    let virt = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(virt - KERNEL_VMA_BASE)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared bridge in `tairix_kernel`.
#[panic_handler]
fn mem_map_qemu_x86_64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_kernel_core(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires. It does not widen the program's
/// own authority.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The live user address space the anonymous map/unmap mutate, plus the kernel
/// direct-physical map used to zero frames on map and on free.
struct LiveSpace {
    space: AddressSpace<paging::AddressSpace>,
    physmap: DirectPhysMap,
}

/// The `MemMap` producer the test installs: it maps and unmaps anonymous `RW`
/// memory in the retained live user space through the architecture-neutral
/// `kernel/mem` producer (`map_anonymous`/`unmap_anonymous`), exactly the seam
/// the production handler reaches (`plans/SPAWN.md` SP5b).
struct AnonProducer {
    inner: UnsafeCell<Option<LiveSpace>>,
}

// SAFETY: the test runs on a single CPU and the producer is reached only
// synchronously from the cooperative syscall-dispatch callback (never from
// interrupt context, never cross-CPU, never re-entrantly — one `syscall` is
// serviced at a time), so the interior `&mut` the methods take out can never
// alias (the access is genuinely exclusive).
unsafe impl Sync for AnonProducer {}

impl AnonProducer {
    const fn new() -> Self {
        Self {
            inner: UnsafeCell::new(None),
        }
    }

    /// Install the retained live space. Called once at boot, before the
    /// program is entered and so before the dispatch callback can fire.
    ///
    /// # Safety
    ///
    /// Must be called exactly once on the boot CPU before any `mem_map`/
    /// `mem_unmap` is dispatched, so no `&mut` from [`Self::live`] is live.
    unsafe fn install(&self, live: LiveSpace) {
        // SAFETY: see the function contract; single CPU, called once before
        // any dispatch, so nothing aliases the cell.
        unsafe { *self.inner.get() = Some(live) };
    }

    /// Borrow the retained live space mutably, or [`Errno::NotImplemented`]
    /// if none was installed (fail closed).
    fn live(&self) -> Result<&mut LiveSpace, Errno> {
        // SAFETY: see the `unsafe impl Sync` justification — the dispatch path
        // is single-CPU and non-reentrant, so this exclusive borrow is unique.
        let slot = unsafe { &mut *self.inner.get() };
        slot.as_mut().ok_or(Errno::NotImplemented)
    }
}

/// The single installed producer.
static PRODUCER: AnonProducer = AnonProducer::new();

/// Map an [`AnonError`] onto a stable [`Errno`] for the syscall result, folding
/// allocator exhaustion onto [`Errno::OutOfMemory`] and a
/// not-mapped range onto [`Errno::NotFound`] (fail closed).
fn anon_to_errno(err: AnonError) -> Errno {
    match err {
        AnonError::ZeroLength => Errno::LengthOutOfRange,
        AnonError::Unaligned | AnonError::Overflow => Errno::OutOfRange,
        AnonError::OutOfMemory => Errno::OutOfMemory,
        AnonError::NotMapped => Errno::NotFound,
        AnonError::PhysUnmapped | AnonError::Map(_) => Errno::BadAddress,
        // `AnonError` is `#[non_exhaustive]`; a future variant maps to the
        // generic bad-address error rather than being silently dropped.
        _ => Errno::BadAddress,
    }
}

impl MemMap for AnonProducer {
    fn reserve(&self, len: usize, flags: MapFlags, addr_hint: u64) -> Result<u64, Errno> {
        // This harness is an arch-mechanism proving ground that drives
        // `map`/`unmap` directly (the demand-paged reserve-then-fault-in
        // policy lives in `kernel/core` and is covered by its host tests),
        // so a reservation here simply performs the eager map.
        self.map(len, flags, addr_hint)
    }

    fn commit(&self, _pages: u64) -> Result<(), Errno> {
        // This proving-ground producer maps eagerly and tracks no
        // no-overcommit budget, so a headroom reservation is a no-op that
        // permits the (rare) stack-growth path to proceed to `map`.
        Ok(())
    }

    fn map(&self, len: usize, flags: MapFlags, addr_hint: u64) -> Result<u64, Errno> {
        let page_count = page_count_for(len).map_err(anon_to_errno)?;
        // The fixture maps with FIXED placement so the kernel's fault check
        // knows the exact base; this producer maps only there (a placement
        // allocator is the production concern, not this proving ground).
        if !flags.is_fixed() {
            return Err(Errno::NotImplemented);
        }
        let live = self.live()?;
        map_anonymous(
            &mut live.space,
            &live.physmap,
            addr_hint,
            page_count,
            next_frame,
            |_frame| {},
        )
        .map_err(anon_to_errno)?;
        Ok(addr_hint)
    }

    fn unmap(&self, base: u64, len: usize, retire: &mut dyn Retire) -> Result<(), Errno> {
        let page_count = page_count_for(len).map_err(anon_to_errno)?;
        let live = self.live()?;
        unmap_anonymous(
            &mut live.space,
            &live.physmap,
            base,
            page_count,
            retire,
            &mut |_frame| {},
        )
        .map_err(anon_to_errno)
    }
}

/// Encode a `Result<u64, Errno>` into the syscall return register following the
/// `abi-v1` signed convention: a non-negative value on success, `-errno` on
/// error (the encoding `tairix_rt::mem_map`/`mem_unmap` decode).
fn encode(result: Result<u64, Errno>) -> u64 {
    match result {
        Ok(value) => value,
        Err(err) => {
            let neg = -i64::from(err.as_i32());
            neg as u64
        }
    }
}

/// The syscall-dispatch callback the ring-3 program's `syscall` traps reach.
///
/// `mem_map`/`mem_unmap` are routed through the installed [`PRODUCER`]; a
/// returned `Ok` records the corresponding progress flag so the fault observer
/// can confirm the program completed the map→verify→unmap sequence before
/// faulting. An `exit` means the fixture took a verification failure branch
/// (the success path is the deliberate fault, not an exit), so it fails the
/// test. Any other syscall is unexpected and fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the `IA32_LSTAR` entry stub built the `[u64; SYSCALL_MAX_ARGS]`
    // array on the kernel stack and passes a pointer valid for this call
    // (`syscall_entry` contract).
    let args = unsafe { *args_ptr };

    if number == u64::from(SyscallNumber::MEM_MAP.as_u16()) {
        let len = args[0] as usize;
        if len == 0 {
            return encode(Err(Errno::LengthOutOfRange));
        }
        // The flags slot is a 32-bit word; `from_bits` then refuses any
        // reserved bit, so a bad word fails closed.
        #[allow(clippy::cast_possible_truncation)]
        let flags = match MapFlags::from_bits(args[1] as u32) {
            Ok(flags) => flags,
            Err(err) => return encode(Err(err)),
        };
        let result = PRODUCER.map(len, flags, args[2]);
        if result.is_ok() {
            MAP_OK.store(true, Ordering::SeqCst);
        }
        encode(result)
    } else if number == u64::from(SyscallNumber::MEM_UNMAP.as_u16()) {
        let base = args[0];
        let len = args[1] as usize;
        if len == 0 {
            return encode(Err(Errno::LengthOutOfRange));
        }
        // This kernel serves no copy path, so the page table is the only view.
        let result = PRODUCER.unmap(base, len, &mut Unpublished).map(|()| 0);
        if result.is_ok() {
            UNMAP_OK.store(true, Ordering::SeqCst);
        }
        encode(result)
    } else if number == u64::from(SyscallNumber::EXIT.as_u16()) {
        // The success path is the deliberate fault-on-use-after-unmap, never an
        // exit; an exit therefore means the fixture hit a verification failure
        // branch. Fail loudly.
        note(TEST_FAIL, "mem_map test: fixture exited before faulting");
        qemu_exit::exit_failure();
    } else {
        note(
            TEST_FAIL,
            "mem_map test: fixture issued an unexpected syscall",
        );
        qemu_exit::exit_failure();
    }
}

/// The fault observer: a not-present page fault on the released region — after
/// a successful map and unmap — is the use-after-unmap the test proves, so it
/// reports PASS. Anything else is a failure (never returns).
fn on_fault(trap: KernelFault) -> ! {
    let region_end = REGION_VA.wrapping_add(REGION_LEN);
    if trap.syndrome.is_some_and(fault::is_not_present)
        && MAP_OK.load(Ordering::SeqCst)
        && UNMAP_OK.load(Ordering::SeqCst)
        && trap
            .address
            .is_some_and(|address| address >= REGION_VA && address < region_end)
    {
        note(
            TEST_PASS,
            "mem_map test: ring 3 mapped, verified, unmapped, then faulted on use",
        );
        qemu_exit::exit_success();
    }
    note(TEST_FAIL, "mem_map test: unexpected fault");
    qemu_exit::exit_failure();
}

/// Outer audit sink: replays every event to serial (so the QEMU transcript
/// captures the boot timeline) and, on the single [`BOOT_COMPLETED_EVENT_ID`],
/// drives [`run_round_trip`].
struct BootCompletedSink;

impl Sink for BootCompletedSink {
    fn write_event(&self, event: &Event<'_>) {
        SerialSink::new().write_event(event);

        if event.id == BOOT_COMPLETED_EVENT_ID
            && TEST_DRIVEN
                .compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire)
                .is_ok()
        {
            run_round_trip();
        }
    }
}

static AUDIT_SINK: BootCompletedSink = BootCompletedSink;

/// Build the ring-3 image, retain it behind the `MemMap` producer, install the
/// dispatch callback + fault observer, and drop into it. Never returns.
fn run_round_trip() -> ! {
    note(TEST_START, "x86_64 mem_map test: building the ring-3 image");

    // Enable `IA32_EFER.NXE` so the W^X No-Execute leaf bit the adapter sets on
    // data/rodata pages is honoured rather than reserved.
    // SAFETY: reading and writing `IA32_EFER` is the documented enable
    // sequence; it runs once on the BSP and only sets bit 11, preserving
    // `SCE`/`LME`/`LMA` the boot pipeline established.
    unsafe {
        let lo: u32;
        let hi: u32;
        core::arch::asm!(
            "rdmsr",
            in("ecx") IA32_EFER,
            out("eax") lo,
            out("edx") hi,
            options(nostack, preserves_flags),
        );
        let efer = (((hi as u64) << 32) | lo as u64) | EFER_NXE;
        core::arch::asm!(
            "wrmsr",
            in("ecx") IA32_EFER,
            in("eax") efer as u32,
            in("edx") (efer >> 32) as u32,
            options(nostack, preserves_flags),
        );
    }

    // Fresh address space (low 32 MiB identity + higher-half kernel window) and
    // activate it before any user mapping is added.
    let Some(arch) = paging::AddressSpace::new_boot_identity(&PAGE_TABLE_POOL) else {
        note(TEST_FAIL, "mem_map test: page-table pool exhausted");
        qemu_exit::exit_failure();
    };
    // SAFETY: the new space carries the live identity window and the
    // higher-half kernel window, so the executing RIP, the current stack, the
    // per-CPU `swapgs` TLS, the page-table pool, the frame pool,
    // `dispatch`/`on_fault`, and the timer ISR's LAPIC MMIO access all stay
    // mapped across the CR3 switch.
    unsafe { arch.switch() };
    syscall_entry::set_dispatch_callback(dispatch);

    // Parse the build-time `rxe` blob against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        note(TEST_FAIL, "mem_map test: fixture rxe image failed to parse");
        qemu_exit::exit_failure();
    };

    let mut space = AddressSpace::new(arch);
    // SAFETY: the boot code installs this direct map and never unmaps it.
    let physmap = unsafe { DirectPhysMap::new(KERNEL_VMA_BASE, 1 << 30) }
        .expect("the boot direct map addresses its window");
    let request = SpawnRequest {
        image: &image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"mem-map"],
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered below, once the space is the active regime (we `switch`ed to
    // it above), the GDT user selectors / TSS / `syscall` entry were installed
    // during boot, and the dispatch callback + fault observer are installed.
    // Frames are drawn from `FRAME_POOL`.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => {
            note(TEST_FAIL, "mem_map test: spawn_image failed");
            qemu_exit::exit_failure();
        }
    };

    // Retain the live space behind the `MemMap` producer so the program's
    // `mem_map`/`mem_unmap` syscalls mutate exactly the active address space.
    // `spawn_image` has returned, so the `&mut space` borrow is released and
    // moving `space` here cannot alias it (the CR3 root is unchanged — the
    // tables live in the static `PAGE_TABLE_POOL`).
    // SAFETY: called once on the boot CPU before `enter_user` (and thus any
    // `mem_map`) can fire.
    unsafe { PRODUCER.install(LiveSpace { space, physmap }) };

    note(TEST_SPAWNED, "x86_64 mem_map test: ring-3 program spawned");

    // Drop into the program. `enter_user` `iretq`s into ring 3; the program's
    // `syscall`s reach `dispatch` and its deliberate use-after-unmap raises a
    // page fault `on_fault` reports as PASS. Reaching past it is a closed
    // failure.
    // SAFETY: the entered space is the active regime and the trap path +
    // dispatch callback + fault observer are installed, so the program's
    // `syscall`s and its deliberate fault are handled; `build_process_image`
    // mapped the entry/stack as user pages.
    unsafe { UserMode::new().enter_user(entry) };
}

/// The symbol the arch crate's boot trampoline calls.
#[no_mangle]
pub extern "C" fn kernel_main(multiboot_info: u64) -> ! {
    // Claim the set-once fatal-fault slot before `boot` publishes the
    // production reporter into it: this vertical *is* the observer of its
    // own deliberate post-unmap fault, so it owns the machine's fatal
    // policy for this image and must be first. `on_fault` fail-closes on
    // any fault outside the mapped-then-unmapped region, so owning the
    // slot from here never hides an unexpected one.
    if tairix_arch_api::fault::set_fault_handler(on_fault).is_err() {
        note(TEST_FAIL, "mem_map test: fault observer already installed");
        qemu_exit::exit_failure();
    }
    boot(
        multiboot_info,
        &ALLOCATOR,
        &SERIAL_SINK,
        &AUDIT_SINK,
        tairix_log::Level::Info,
    )
}
