//! The x86_64 P-1c test kernel: boot the production pipeline, then on
//! `BootCompleted` build one isolated ring-3 spinner and prove the production
//! LAPIC-timer IRQ involuntarily preempts it (`plans/PI.md` D2b-2b-A P-1c).

extern crate alloc;

use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU32, AtomicU64, AtomicUsize, Ordering};

use tairix_abi::rxe::LoadImage;
use tairix_abi::{CapabilityId, CapabilityQuery, SyscallNumber, SYSCALL_MAX_ARGS};
use tairix_arch_api::{EnterUser, UserEntry, BOOT_CPU};
use tairix_arch_x86_64::context_hal::ContextSwitchHal;
use tairix_arch_x86_64::kernel_arch::{X86_64Arch, X86_64ArchStorage};
use tairix_arch_x86_64::paging::{self, activate_user_root, KERNEL_VMA_BASE};
use tairix_arch_x86_64::userentry::UserMode;
use tairix_arch_x86_64::{preempt, qemu_exit, syscall_entry};
use tairix_kernel::kalloc::{Heap, HEAP_BYTES};
use tairix_kernel::{
    boot, handle_panic_via_kernel_core, FreeListAllocator, SerialSink, SERIAL_SINK,
};
use tairix_kernel_core::{
    reschedule_current, spawn_image, spawn_kthread, spawn_user_kthread, RescheduleAction,
    SpawnMode, SpawnRequest, Yielder,
};
use tairix_kernel_mem::{AddressSpace, DirectPhysMap, Frame, PhysAddr, UserStack};
use tairix_kernel_sched_eevdf::{Priority, Scheduler, SchedulerConfig};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level, Sink};

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// `EventId` emitted when every boot init phase completed.
const BOOT_COMPLETED_EVENT_ID: EventId = EventId(4004);

/// Stable audit-event ids for the QEMU transcript (free range).
const TEST_START: EventId = EventId(4335);
const TEST_SPAWNED: EventId = EventId(4336);
const TEST_PASS: EventId = EventId(4337);
const TEST_FAIL: EventId = EventId(4338);

/// User stack base (1 MiB into the high user region) and size.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (256 KiB).
const USER_STACK_PAGES: u64 = 64;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// `IA32_EFER` MSR number and its No-Execute-Enable bit (bit 11).
const IA32_EFER: u32 = 0xC000_0080;
const EFER_NXE: u64 = 1 << 11;

/// Physical frames the spawn build draws from.
const FRAME_COUNT: usize = 256;

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 50_000_000;

/// Involuntary preemptions the competitor waits to observe before it
/// exits, handing the CPU to the now-sole spinner (see the aarch64
/// vertical). One proves the contended LAPIC one-shot fires; the long
/// uninterrupted remainder proves the sole-task disarm.
const TARGET_PREEMPTIONS: u64 = 1;

/// Slack the sole-task disarm check tolerates over the hand-off snapshot.
/// The disarm is exact in principle, but under an oversubscribed host
/// (the concurrent QEMU matrix) the competitor's last armed LAPIC one-shot
/// can fire once at the contended→sole boundary before the sole spinner's
/// `set_preemption(false)` disarms it. A genuine periodic-timer regression
/// would instead add *hundreds* of ticks over the long sole run, so this
/// small bound stays immune to the benign boundary fire while still
/// failing loudly on a re-armed periodic tick.
const SOLE_PREEMPT_SLACK: u64 = 16;

/// Count of involuntary timer-driven preemptions of the running ring-3 task.
static PREEMPTIONS: AtomicU64 = AtomicU64::new(0);
/// `exit` syscalls observed (the spinner exits exactly once on completion).
static EXITS: AtomicU64 = AtomicU64::new(0);
/// [`PREEMPTIONS`] snapshot captured by the competitor kthread when it
/// exits (handing the CPU to the now-sole spinner); `u64::MAX` until
/// recorded. `PREEMPTIONS == PREEMPTIONS_AT_SOLE` after the run proves the
/// sole spinner took **no** further LAPIC-timer interrupt (tickless
/// disarm).
static PREEMPTIONS_AT_SOLE: AtomicU64 = AtomicU64::new(u64::MAX);

/// Set once the round-trip has been driven so a duplicate `BootCompleted`
/// cannot re-enter the test logic.
static TEST_DRIVEN: AtomicU32 = AtomicU32::new(0);

/// Static heap for the bump allocator.
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// Per-space page-table pool backing the spinner's PML4 hierarchy.
static PAGE_TABLE_POOL: paging::PageTablePool = paging::PageTablePool::new();

/// Physical-frame backing store the spawn builder draws user pages from.
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Hand out the next physical frame from [`FRAME_POOL`], or `None` when
/// exhausted. The pool is a higher-half kernel static, so its physical address
/// is its virtual address minus [`KERNEL_VMA_BASE`].
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    let virt = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(virt - KERNEL_VMA_BASE)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared bridge in `tairix_kernel`.
#[panic_handler]
fn preempt_el0_qemu_x86_64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_kernel_core(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The ring-3-preemption callback the LAPIC-timer ISR invokes for a tick taken
/// from ring 3 — the production dispatch shape verbatim: it
/// suspends the running user task back to the scheduler via
/// `reschedule_current(_, Yield)`, the involuntary analogue of a `yield`
/// syscall. It records each preemption so the test can prove at least one fired
/// against the never-yielding spinner.
extern "C" fn preempt_dispatch(cpu: u32) {
    PREEMPTIONS.fetch_add(1, Ordering::SeqCst);
    let _ = reschedule_current(cpu, RescheduleAction::Yield);
}

/// The syscall-dispatch callback the spinner's final `exit` reaches.
///
/// The spinner issues no `yield`; its only syscall is the `exit` that
/// `tairix-rt` routes `main`'s return through. Any other syscall is unexpected
/// and fails the test loudly.
extern "C" fn dispatch(number: u64, _args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    let call = SyscallNumber::from_register(number).ok();
    if call == Some(SyscallNumber::EXIT) {
        EXITS.fetch_add(1, Ordering::SeqCst);
        // Reap the caller: this switches back to the dispatcher and never
        // resumes the task, so the `0` below is unreachable.
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Exit);
        0
    } else {
        note(TEST_FAIL, "fixture program issued an unexpected syscall");
        qemu_exit::exit_failure();
    }
}

/// Outer audit sink: replays every event to serial and, on the single
/// [`BOOT_COMPLETED_EVENT_ID`], drives [`run_preempt`].
struct BootCompletedSink;

impl Sink for BootCompletedSink {
    fn write_event(&self, event: &Event<'_>) {
        SerialSink::new().write_event(event);

        if event.id == BOOT_COMPLETED_EVENT_ID
            && TEST_DRIVEN
                .compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire)
                .is_ok()
        {
            run_preempt();
        }
    }
}

static AUDIT_SINK: BootCompletedSink = BootCompletedSink;

/// Build the isolated ring-3 address space from the validated `image` over
/// [`PAGE_TABLE_POOL`], returning its PML4 root and the entry register state.
/// Fails the test loudly on any error.
fn build_el0_space(image: &LoadImage) -> (u64, UserEntry) {
    let Some(arch_space) = paging::AddressSpace::new_boot_identity(&PAGE_TABLE_POOL) else {
        note(TEST_FAIL, "P-1c test: page-table pool exhausted");
        qemu_exit::exit_failure();
    };
    let root_phys = arch_space.pml4_phys();
    // SAFETY: the new space carries the live identity window and the
    // higher-half kernel window, so the executing RIP, the current stack, the
    // per-CPU `swapgs` TLS, the page-table pool, the frame pool, the heap,
    // `dispatch`, and every LAPIC MMIO access stay mapped across the CR3
    // switch.
    unsafe { arch_space.switch() };

    let mut space = AddressSpace::new(arch_space);
    // SAFETY: the boot code installs this direct map and never unmaps it.
    let physmap = unsafe { DirectPhysMap::new(KERNEL_VMA_BASE, 1 << 30) }
        .expect("the boot direct map addresses its window");
    let request = SpawnRequest {
        image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"el0"],
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once the task is dispatched and its `pre_resume` hook
    // has reloaded CR3. The GDT user selectors / TSS / `syscall` entry were
    // installed during boot, and the dispatch callback is installed by the
    // caller. Frames are drawn from `FRAME_POOL` through the shared cursor.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => {
            note(TEST_FAIL, "P-1c test: spawn_image failed");
            qemu_exit::exit_failure();
        }
    };
    (root_phys, entry)
}

/// Build the ring-3 image, install the production preempt path, admit the task
/// as a resumable user kthread, and drive the cooperative `step` loop until it
/// is preempted and exits. Never returns (it exits the VM on PASS or FAIL).
fn run_preempt() -> ! {
    note(TEST_START, "x86_64 P-1c test: building ring-3 spinner");

    // Enable `IA32_EFER.NXE` so the W^X No-Execute leaf bit the adapter sets on
    // data/rodata pages is honoured rather than reserved.
    // SAFETY: reading and writing `IA32_EFER` is the documented enable
    // sequence; it runs once on the BSP and only sets bit 11, preserving
    // `SCE`/`LME`/`LMA` the boot pipeline established.
    unsafe {
        let lo: u32;
        let hi: u32;
        core::arch::asm!(
            "rdmsr",
            in("ecx") IA32_EFER,
            out("eax") lo,
            out("edx") hi,
            options(nostack, preserves_flags),
        );
        let efer = (((hi as u64) << 32) | lo as u64) | EFER_NXE;
        core::arch::asm!(
            "wrmsr",
            in("ecx") IA32_EFER,
            in("eax") efer as u32,
            in("edx") (efer >> 32) as u32,
            options(nostack, preserves_flags),
        );
    }

    syscall_entry::set_dispatch_callback(dispatch);

    // Arm the production tickless ring-3-preemption path verbatim: install the ring-3-preemption callback the
    // LAPIC-timer ISR forwards each user-mode tick to. The production boot
    // programmed the LAPIC timer **one-shot and disarmed**
    // (`preempt::init_local_preempt`); the scheduler arms the one-shot to
    // one quantum only when it dispatches the spinner onto a CPU that still
    // has the competitor kthread queued (`X86_64Arch::set_preemption`), and
    // ring 3 runs preemptible (`userentry`'s `IF`-set `RFLAGS`), so a tick
    // taken while the spinner runs drives `preempt_dispatch`.
    preempt::set_preempt_callback(preempt_dispatch);

    // Parse the build-time `rxe` blob once against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        note(TEST_FAIL, "P-1c test: fixture rxe image failed to parse");
        qemu_exit::exit_failure();
    };

    // Build the isolated ring-3 address space (it leaves its own space active).
    let (root_phys, entry) = build_el0_space(&image);

    // Build the live scheduler over the production arch handle. Interrupts stay
    // masked in the kernel (no `sti`), so the cooperative `step` loop drives
    // dispatch and the only ticks taken are in ring 3.
    let bsp_id = tairix_arch_x86_64::apic::local_apic_id();
    let cpu_to_lapic: [Option<u32>; 1] = [Some(bsp_id)];
    static ARCH_STORAGE: X86_64ArchStorage<1> = X86_64ArchStorage::new();
    let Ok(arch) = X86_64Arch::new(&ARCH_STORAGE, 0, bsp_id, &cpu_to_lapic) else {
        note(TEST_FAIL, "P-1c test: X86_64Arch::new failed");
        qemu_exit::exit_failure();
    };
    let arch = alloc::sync::Arc::new(arch);
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        note(TEST_FAIL, "P-1c test: Scheduler::new failed");
        qemu_exit::exit_failure();
    };

    // Admit the **competitor** first: a kernel kthread that yields until it
    // observes the spinner preempted at least [`TARGET_PREEMPTIONS`] times,
    // records the count, and exits — handing the CPU to the now-sole
    // spinner. While it is queued the scheduler arms the one-shot, so the
    // runaway spinner is preempted (contention case); once it exits the sole
    // spinner runs disarmed to completion (tickless case).
    let competitor = move |yielder: &mut Yielder<ContextSwitchHal>| {
        while PREEMPTIONS.load(Ordering::SeqCst) < TARGET_PREEMPTIONS {
            yielder.yield_now();
        }
        PREEMPTIONS_AT_SOLE.store(PREEMPTIONS.load(Ordering::SeqCst), Ordering::SeqCst);
    };
    if spawn_kthread(
        &sched,
        ContextSwitchHal::new(),
        BOOT_CPU,
        Priority::Normal,
        competitor,
    )
    .is_err()
    {
        note(TEST_FAIL, "P-1c test: spawn competitor kthread failed");
        qemu_exit::exit_failure();
    }

    // Admit the spinner as a resumable user kthread. Its `pre_resume` hook runs
    // on the dispatcher's context immediately before every switch-in: it
    // repoints the per-CPU `syscall` entry stack AND the `TSS.RSP0` trap stack
    // at *this* task's own kernel stack (the value the seam hands it), then
    // reloads CR3 to the task's own root (isolation). Repointing `TSS.RSP0`
    // is what makes the involuntary timer IRQ (delivered through the IDT
    // interrupt gate, which reads `TSS.RSP0`) land on the spinner's own kernel
    // stack rather than the boot trap stack.
    let cs = ContextSwitchHal::new();
    let user_mode = UserMode::new();
    let pre_resume = move |kernel_stack_top: u64| {
        // `set_kernel_rsp0` repoints **both** the spinner's `syscall` entry
        // stack (`gs:0`) and its trap entry stack (`TSS.RSP0`) at its own
        // kernel stack — the latter is what makes the involuntary LAPIC-timer
        // preemption (delivered through the IDT interrupt gate, which reads
        // `TSS.RSP0`) land on the spinner's own kernel stack rather than the
        // boot trap stack (one per-task kernel stack for both
        // entry kinds). A rejected value leaves the slots unchanged and the
        // next entry faults loudly (fail closed).
        if syscall_entry::set_kernel_rsp0(BOOT_CPU as usize, kernel_stack_top).is_err() {
            note(
                TEST_FAIL,
                "P-1c test: set_kernel_rsp0 rejected the stack top",
            );
            qemu_exit::exit_failure();
        }
        // SAFETY: paging is enabled and `root_phys` is the PML4 of the task's
        // space, which maps the low identity + higher-half kernel window the
        // running dispatcher executes from — exactly `activate_user_root`'s
        // contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |_yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: by the time this body runs the task has been dispatched, so
        // its `pre_resume` hook reloaded CR3 + repointed both entry stacks, and
        // the GDT user selectors / TSS / `syscall` entry + dispatch callback
        // are installed; the program's `exit` `syscall` is handled.
        unsafe { user_mode.enter_user(entry) }
    };
    if spawn_user_kthread(&sched, cs, BOOT_CPU, Priority::Normal, pre_resume, work).is_err() {
        note(TEST_FAIL, "P-1c test: spawn_user_kthread failed");
        qemu_exit::exit_failure();
    }
    note(TEST_SPAWNED, "x86_64 P-1c test: ring-3 spinner spawned");

    // Dispatch loop: drive `step` until both tasks finish. While the
    // competitor is queued, each spinner dispatch arms the one-shot and the
    // never-yielding spinner is preempted; once the competitor exits, the
    // lone spinner runs disarmed to completion and `exit`s. A preemption
    // that never fires would leave the contended `step` spinning forever in
    // ring 3 and the harness would time out (fail-loud).
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }
    if sched.live_task_count() != 0 {
        note(
            TEST_FAIL,
            "P-1c test: deadlock — task remained after MAX_STEPS",
        );
        qemu_exit::exit_failure();
    }
    // Contention case: the competitor recorded the preemption count at
    // hand-off, and it must be at least `TARGET_PREEMPTIONS` — proving the
    // LAPIC one-shot fired and preempted the runaway ring-3 task.
    let at_sole = PREEMPTIONS_AT_SOLE.load(Ordering::SeqCst);
    if at_sole == u64::MAX || at_sole < TARGET_PREEMPTIONS {
        note(TEST_FAIL, "P-1c test: task ran but was never preempted");
        qemu_exit::exit_failure();
    }
    // Sole-task (tickless) case: after the competitor exited, the sole
    // spinner ran millions of iterations to completion with the one-shot
    // disarmed, so no further preemption may have fired.
    if PREEMPTIONS.load(Ordering::SeqCst) > at_sole.saturating_add(SOLE_PREEMPT_SLACK) {
        note(
            TEST_FAIL,
            "P-1c test: sole task kept being preempted (timer not disarmed)",
        );
        qemu_exit::exit_failure();
    }
    if EXITS.load(Ordering::SeqCst) != 1 {
        note(TEST_FAIL, "P-1c test: task did not exit exactly once");
        qemu_exit::exit_failure();
    }

    note(
        TEST_PASS,
        "x86_64 P-1c test: contended runaway task preempted; sole task ran tickless",
    );
    qemu_exit::exit_success();
}

/// The symbol the arch crate's boot trampoline calls.
#[no_mangle]
pub extern "C" fn kernel_main(multiboot_info: u64) -> ! {
    boot(
        multiboot_info,
        &ALLOCATOR,
        &SERIAL_SINK,
        &AUDIT_SINK,
        tairix_log::Level::Info,
    )
}
