//! x86_64 PID 1 (`init`) spawn seam — `plans/PI.md` X3a.
//!
//! [`X86_64InitSpawn`] implements the architecture-neutral
//! [`tairix_kernel_core::InitSpawn`] hook the boot pipeline installs into the
//! [`tairix_kernel_core::BootInfo`] hand-off (`boot::try_boot` →
//! `BootInfo::with_init`). It is the cross-port sibling of the aarch64
//! `init_spawn` seam: once every init phase has succeeded and
//! `kernel_core::kernel_main` has emitted
//! [`tairix_kernel_core::AuditEvent::BootCompleted`], the core invokes
//! [`InitSpawn::spawn_init`]; this implementation builds the embedded `init`
//! (`Run`) program's ring-3 image through the production, capability-checked,
//! audited spawn caller ([`tairix_kernel_core::spawn_image`]) and admits it as
//! a **resumable user kthread** ([`InitSpawnCtx::admit_init`]). PID 1 then runs
//! under the live scheduler `kernel_main` drains; its `yield`/`exit` syscalls
//! suspend it back through the Arch-HAL context switch.
//!
//! The image, its relocation bias ([`INIT_USER_BIAS`]), and the kernel's
//! syscall CFI tag are baked at build time (`build.rs` →
//! `tairix_itest_harness::elf2rxe`), exactly like the aarch64 seam and the
//! proven `spawn_el0_resume_qemu_x86_64` fixture, so there is one conversion
//! path. Spawning `init` is *not* a privileged bypass: the
//! program receives only the authority its manifest requests intersected with
//! its user's grants; this seam only authorises the
//! *act* of spawning under `CAP_PROC_SPAWN`.
//!
//! # x86_64 specifics versus the aarch64 sibling
//!
//! * The address space is built from
//!   [`ArchAddressSpace::new_process_root`]: the higher-half kernel window
//!   the trampoline established plus the direct physical map the boot path
//!   sized from the discovered memory map, and no identity map. The seam
//!   switches to it while building the image, so everything it then touches
//!   — the page-table walk's table recovery, the live allocator's image
//!   frames, the scheduler's LAPIC register writes — is reached either in
//!   the kernel image's own window or through that map.
//! * The `pre_resume` hook does two things (the aarch64 hook only the first):
//!   reload CR3 to PID 1's own PML4 ([`activate_user_root`], isolation) and
//!   repoint the per-CPU `syscall` entry stack at PID 1's own kernel stack
//!   ([`syscall_entry::set_kernel_rsp0`]) — the gap aarch64 fills implicitly
//!   through `SP_EL1` (`plans/PI.md` §X). A rejected stack top leaves the slot
//!   unchanged and the next syscall faults loudly (fail closed).
//! * PID 1's kernel stack comes from the window-backed tier
//!   ([`tairix_kernel_core::kstack::alloc_kernel_stack`]), whose guard slot is
//!   unmapped in every root at once, so a kernel-stack overrun faults under
//!   PID 1's CR3 without this seam touching its PML4.
//! * Physical frames are reached through the port's one direct physical map
//!   ([`ConfiguredPhysMap`]), whose extent is the discovered RAM.

use core::sync::atomic::{AtomicBool, Ordering};

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_arch_x86_64::paging::{activate_user_root, AddressSpace as ArchAddressSpace};
use tairix_arch_x86_64::syscall_entry;
use tairix_arch_x86_64::userentry::{set_user_thread_pointer, USER_MODE};
use tairix_kernel_core::{
    spawn_image, InitSpawn, InitSpawnCtx, ProcessResume, ProcessSpace, SpawnMode, UserThreadEntry,
};
use tairix_kernel_mem::{AddressSpace, PhysMap, UserAddressSpace};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;

use crate::spawn_layout;
use crate::x86_64::spawn_producer::{page_table_source, ConfiguredPhysMap};

// `INIT_RXE: &[u8]` and `INIT_USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/init_rxe.rs"));

/// PID 1's four fixed guarded-window bases (`plans/PI.md` 5d-0-ii (b′)/(c)),
/// derived from the one shared offset set the retained [`LiveSpace`](tairix_kernel_mem::LiveSpace)'s
/// window allocators are configured with.
const WINDOWS: spawn_layout::WindowBases = spawn_layout::window_bases(INIT_USER_BIAS);

/// Set once PID 1 has been spawned so a re-entry cannot re-run the path.
static INIT_SPAWNED: AtomicBool = AtomicBool::new(false);

/// A pre-dispatch service the seam admits alongside PID 1, *before*
/// `admit_init` diverges into the dispatch loop. Production wires the
/// root-unlock kthread; a QEMU vertical can wire its own in-kernel service
/// (e.g. the DMA-fault driver) by building the seam with
/// [`X86_64InitSpawn::with_pre_dispatch`].
///
/// A stand-in for root unlock owns what root unlock settles on every path:
/// releasing console 0 to `login` (`CONSOLE0_GATE`), resolving the late
/// users database (`LATE_USERS_DB`) and the application store's readiness
/// (`APP_STORE`). Until it does, `login` and every store-bundle spawn stay
/// parked, so a vertical that settles none judges its run on its own
/// witnesses alone.
pub type PreDispatch = fn(&'static (dyn InitSpawnCtx + Sync));

/// The x86_64 PID 1 spawn seam installed into the
/// [`tairix_kernel_core::BootInfo`] hand-off by `boot::try_boot`. One PID 1
/// build and one `admit_init`, with a pluggable [`PreDispatch`].
pub struct X86_64InitSpawn {
    pre_dispatch: PreDispatch,
}

/// Production pre-dispatch: admit the in-kernel root-unlock service
/// (`plans/ARCHSUPPORT.md` A2).
fn root_unlock_pre_dispatch(ctx: &'static (dyn InitSpawnCtx + Sync)) {
    let _started = crate::x86_64::root_unlock::spawn_if_present(ctx);
}

/// The single, `'static` production [`X86_64InitSpawn`] the boot path borrows.
pub static X86_64_INIT_SPAWN: X86_64InitSpawn =
    X86_64InitSpawn::with_pre_dispatch(root_unlock_pre_dispatch);

impl X86_64InitSpawn {
    /// The seam whose pre-dispatch step runs `pre_dispatch`. The PID 1 build
    /// and `admit_init` are the same for every seam; only the service admitted
    /// before the dispatch loop diverges.
    #[must_use]
    pub const fn with_pre_dispatch(pre_dispatch: PreDispatch) -> Self {
        Self { pre_dispatch }
    }
}

impl InitSpawn for X86_64InitSpawn {
    fn spawn_init(&self, ctx: &'static (dyn InitSpawnCtx + Sync)) {
        // Spawn PID 1 at most once; a spurious re-entry falls through to the
        // caller's fail-closed halt rather than building a second image.
        if INIT_SPAWNED
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }

        // PID 1's hierarchy is drawn from the kernel's live frame allocator
        // through the same source every runtime spawn uses. A part without
        // 1 GiB pages costs one page directory per gigabyte of the identity
        // window, so a fixed `.bss` reserve here would be a ceiling that a
        // machine with enough RAM outgrows — the aarch64 sibling can keep its
        // reserve because its stage-1 format always has 1 GiB blocks and its
        // cost is flat. A context with no `'static` allocator cannot build
        // PID 1 at all and falls through to the caller's fail-closed halt.
        let Some(static_frames) = ctx.static_frames() else {
            return;
        };
        let Ok(table_frames) = page_table_source(static_frames) else {
            return;
        };

        // Build PID 1's PML4: the higher-half kernel window and the direct
        // physical map, through which the page-table walk's table recovery,
        // the live allocator's image frames, and the scheduler's LAPIC
        // register writes all resolve under PID 1's CR3 (the production
        // `kernel_main` drain runs on PID 1's root once `pre_resume` has
        // reloaded it). Fail closed on frame exhaustion.
        let Some(arch) = ArchAddressSpace::new_process_root(table_frames) else {
            return;
        };
        // Capture PID 1's PML4 root before the arch space is moved into the
        // `kernel/mem` wrapper, so the `pre_resume` hook can reload CR3 with
        // it before every switch into PID 1 (`plans/SPAWN.md` SP2). It is a
        // plain `u64`, so the boxed hook stays `Send`.
        let init_root_phys = arch.pml4_phys();

        // PID 1's kernel stack: a run of the shared kernel remap window whose
        // guard slot is unmapped in every root at once, so the stack stays
        // mapped and guarded across the switch below without touching `arch`.
        let Some(kernel_stack) = tairix_kernel_core::kstack::alloc_kernel_stack() else {
            return;
        };

        // SAFETY: the new space maps the higher-half kernel window and the
        // direct physical map, so the executing RIP, the current kernel
        // stack, the per-CPU `swapgs` TLS, the page-table pool, the live
        // frame allocator's frames, the heap, the dispatch path, and every
        // LAPIC access stay mapped across the CR3 switch — exactly
        // `AddressSpace::switch`'s contract. Called once on the boot CPU.
        // The `admit_init` contract requires the image be built into the
        // active space, so the switch precedes `spawn_image` below.
        unsafe { arch.switch() };

        let mut space = AddressSpace::new(arch);
        let physmap = ConfiguredPhysMap;

        // Parse the build-time `init` `rxe` blob against the kernel's own
        // compiled-in syscall CFI tag. A mismatch fails closed.
        let Ok(image) = LoadImage::parse(INIT_RXE, &SYSCALL_TABLE_HASH) else {
            return;
        };

        // Place the stack and startup block above the image's mapped top,
        // and derive the span record the stack-growth fault path backs
        // pages inside, through the one shared per-spawn derivation. An
        // image too large for the user region fails the boot closed.
        let Some((request, stack_span)) =
            spawn_layout::init_request(&image, INIT_RXE, INIT_USER_BIAS)
        else {
            return;
        };

        // Authorise + build the ring-3 image (emits `ProcessSpawned`) without
        // entering yet — PID 1 must be registered with the scheduler /
        // capability table / address-space registry *first* so its first
        // syscall resolves a caller context (`plans/PI.md` P6c-3).
        // SAFETY: building the image is itself safe; the returned `UserEntry`
        // is only entered below, once `space` is active (just switched to)
        // and the ring-3 trap path is installed. The frame source draws
        // first-GiB RAM frames from the kernel's live allocator. A returning
        // `Err` drops back to the caller's fail-closed halt.
        let frames = ctx.frames();
        let Ok(entry) = (unsafe {
            spawn_image(
                &spawn_layout::SpawnAuthority,
                SpawnMode::General,
                ctx.audit(),
                &mut space,
                &physmap,
                &request,
                move || frames.alloc(spawn_layout::SPAWN_IMAGE_CLASS).ok(),
            )
        }) else {
            return;
        };

        // PID 1's switch-in hook (`plans/SPAWN.md` SP2): the core runs it on
        // the dispatcher's context immediately before every switch into any
        // thread of PID 1. It reloads CR3 to PID 1's own root (isolation),
        // repoints the per-CPU `syscall` entry stack at the switching-in
        // thread's own kernel stack, and reinstalls that thread's thread
        // pointer. It captures only the `u64` root, so it is `Send`.
        let pre_resume: ProcessResume = Arc::new(move |stack_top: u64, tls_base: u64| {
            // `set_kernel_rsp0` repoints **both** PID 1's `syscall` entry
            // stack (`gs:0`) and its trap entry stack (`TSS.RSP0`) at PID 1's
            // own kernel stack — the latter is what makes an involuntary
            // LAPIC-timer preemption (P-1c), delivered through the IDT
            // interrupt gate which reads `TSS.RSP0`, land on PID 1's own stack
            // (one per-task kernel stack for both entry
            // kinds). A rejected value leaves the slots unchanged and the next
            // entry faults loudly (fail closed).
            // The one CPU production x86_64 runs; a second needs the resuming
            // CPU named here (`plans/OPEN-DEFECTS.md` D378).
            let _ = syscall_entry::set_kernel_rsp0(tairix_arch_api::BOOT_CPU as usize, stack_top);
            // The `FS` base is privileged on this port, so the kernel — not
            // the thread — maintains it: every switch-in reinstalls the
            // switching-in thread's own value (`plans/THREADS.md` decision 7).
            // SAFETY: this runs at CPL 0 on the dispatcher's context, on the
            // CPU about to enter that thread, which is exactly
            // `set_user_thread_pointer`'s contract.
            unsafe { set_user_thread_pointer(tls_base) };
            // SAFETY: paging is enabled and `init_root_phys` is the PML4 of
            // PID 1's space, which maps the low identity + higher-half kernel
            // window the running dispatcher executes from — exactly
            // `activate_user_root`'s contract.
            unsafe { activate_user_root(init_root_phys) };
        });

        // Freeze the just-built mappings into the registry-storable,
        // `Send + Sync` snapshot the kernel-wide address-space registry holds
        // (the live arch `space` is not `Sync`), and box the direct map that
        // backs it, so PID 1's `stream_write` can copy its banner out of user
        // memory. Freezing *after* `spawn_image` captures every mapped page —
        // segments, stack, and the startup-vector block.
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());

        // PID 1's process address space (`plans/PI.md` 5d-0-ii (b′)): the
        // *same* arch space the snapshot above was frozen from, zeroing
        // anonymous frames through the same identity direct map the image
        // build used (PID 1's CR3 carries it). A window the allocator rejects,
        // or a CPU set that cannot be allocated, retains none and PID 1's `mem_map` / `mmio_map` fail closed.
        let live: Option<Arc<ProcessSpace>> = spawn_layout::process_space(
            space,
            ctx.space_tlb(),
            ConfiguredPhysMap,
            static_frames,
            &WINDOWS,
            super::USER_VA_TOP,
            &pre_resume,
            &USER_MODE,
        );

        let physmap: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);

        // Admit the seam's pre-dispatch service onto the boot CPU's run queue
        // before `admit_init` diverges into the dispatch loop: production brings
        // up the root-unlock kthread, a QEMU vertical its own in-kernel service.
        (self.pre_dispatch)(ctx);

        // Register PID 1's caps + address space, publish it as the current
        // task, and dispatch it — `admit_init` drains the run queue until PID
        // 1 has exited, then returns so `kernel_main` halts fail-closed.
        // SAFETY: the image was built into and `space` switched to active
        // above, and the trap path is installed, per the
        // `InitSpawnCtx::admit_init` contract; `frozen` faithfully describes
        // the active mappings, `physmap` backs them, `kernel_stack` is a
        // region exclusive to PID 1 that stays mapped for the task's lifetime,
        // and `live` retains the same arch space `frozen` was taken from.
        unsafe {
            ctx.admit_init(
                spawn_layout::init_caps(),
                frozen,
                physmap,
                stack_span,
                kernel_stack,
                pre_resume,
                live,
                UserThreadEntry {
                    port: &USER_MODE,
                    regs: entry,
                },
            );
        }
    }
}
