//! The freestanding riscv64 RV-X4 test kernel: build a child and a parent
//! U-mode program, register their parent/child link with a `KernelProcessWait`
//! producer, and prove the parent reaps the child's exit code under the live
//! scheduler on the `virt` board (`plans/PI.md` RV-X4, the riscv64 sibling of
//! `wait_qemu_aarch64` / `_x86_64`).

use core::num::NonZeroU16;
use core::panic::PanicInfo;
use core::sync::atomic::{AtomicBool, AtomicU64, AtomicUsize, Ordering};

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_abi::{
    CapabilityId, CapabilityQuery, Errno, SyscallNumber, WaitFlags, WaitStatus, WaitStatusRecord,
    SYSCALL_MAX_ARGS,
};
use tairix_arch_api::{EnterUser, UserEntry, BOOT_CPU};
use tairix_arch_riscv64::context_hal::ContextSwitchHal;
use tairix_arch_riscv64::fdt::Fdt;
use tairix_arch_riscv64::paging::{self, activate_user_root, AddressSpace as ArchAddressSpace};
use tairix_arch_riscv64::userentry::UserMode;
use tairix_arch_riscv64::{
    handle_panic_via_serial, qemu_exit, syscall_entry, trap, RiscvArch, RiscvArchStorage,
    SERIAL_SINK,
};
use tairix_itest_finisher::fail_point;
use tairix_kalloc::{FreeListAllocator, Heap, HEAP_BYTES};
use tairix_kernel_core::{
    reschedule_current, spawn_image, spawn_user_kthread, KernelProcessWait, ProcessWait,
    RescheduleAction, SpawnMode, SpawnRequest, Yielder,
};
use tairix_kernel_mem::{
    copy_out, AddressSpace, DirectPhysMap, Frame, PhysAddr, PhysMap, UserAddressSpace, UserStack,
    VirtAddr,
};
use tairix_kernel_sched_cfq::{Priority, Scheduler, SchedulerConfig};
use tairix_kernel_sec::{ProcessId, TaskId};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level};
use tairix_sync::SpinLock;

// `CHILD_RXE`/`PARENT_RXE: &[u8]`, `USER_BIAS: u64`, and `CHILD_EXIT_CODE: i32`,
// generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// Gigabytes of identity map each U-mode address space provides: `[0, 4 GiB)`
/// covers the `virt` board's low MMIO and the RAM base where this kernel runs.
/// [`USER_BIAS`] (64 GiB) sits far above, on freshly walked Sv39 tables.
const IDENTITY_GIGABYTES: usize = 4;

/// User stack base (1 MiB into the high user region) and size.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (1.125 MiB > the runtime's scratch span plus call frames).
const USER_STACK_PAGES: u64 = 288;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to each program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// Physical frames the test hands the two builds (image segments + the user
/// stacks + the startup blocks for both programs, with headroom). Page-table
/// frames come from the per-space [`paging::PageTablePool`]s, not from here.
const FRAME_COUNT: usize = 640;

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript (clear of the boot range).
const TEST_START: EventId = EventId(4332);
const TEST_SPAWNED: EventId = EventId(4333);
const TEST_PASS: EventId = EventId(4334);

/// `SiFive` Test failure codes, distinct per failure site.
const FAIL_NO_TIMEBASE: NonZeroU16 = fail_point!(1);
const FAIL_UNEXPECTED_HART: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_PARSE: NonZeroU16 = fail_point!(4);
const FAIL_BUILD: NonZeroU16 = fail_point!(5);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(6);
const FAIL_SPAWN: NonZeroU16 = fail_point!(7);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(8);
const FAIL_NO_CURRENT: NonZeroU16 = fail_point!(9);
const FAIL_UNEXPECTED_SYSCALL: NonZeroU16 = fail_point!(10);
const FAIL_COPY_STATUS: NonZeroU16 = fail_point!(11);
const FAIL_PARENT_BAD_EXIT: NonZeroU16 = fail_point!(12);
const FAIL_NO_PRODUCER: NonZeroU16 = fail_point!(13);

/// Set once the producer reaped a child whose code matched [`CHILD_EXIT_CODE`].
static REAP_OK: AtomicBool = AtomicBool::new(false);
/// Scheduler task id of the parent (the program that calls `wait`).
static PARENT_TID: AtomicU64 = AtomicU64::new(u64::MAX);
/// Set once the round-trip has been driven so a re-entry cannot re-run it.
static TEST_DRIVEN: AtomicU64 = AtomicU64::new(0);

/// Static boot heap, in the linker's NOLOAD `.heap` section so the boot
/// trampoline neither zeroes nor counts it in the usable memory map. The two
/// user kthreads' kernel stacks + control blocks and the spawn builders'
/// startup-vector blocks allocate from it.
#[link_section = ".heap"]
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// Per-space page-table pools: one for the child and one for the parent. Each
/// backs an Sv39 hierarchy whose root [`activate_user_root`] reinstalls (via
/// `satp`) before every switch into its task, so the two tasks stay
/// hardware-isolated. A `.bss` reserve, monotonic and never
/// freed.
static CHILD_PAGE_TABLES: paging::PageTablePool = paging::PageTablePool::new();
static PARENT_PAGE_TABLES: paging::PageTablePool = paging::PageTablePool::new();

/// Physical-frame backing store the spawn builders draw user pages from.
/// `align(4096)` so each `PAGE_SIZE` slice is a valid page frame; identity-
/// mapped (its physical address equals its kernel virtual address), so the
/// builders reach it through [`DirectPhysMap::identity`]. A single monotonic
/// cursor ([`FRAME_CURSOR`]) hands disjoint frames to both builds, so the two
/// address spaces never share a data frame.
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame, shared by both builds.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Hand out the next identity-mapped physical frame from [`FRAME_POOL`], or
/// `None` when the pool is exhausted (the spawn builder then fails closed).
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    // The pool is identity-mapped, so its kernel virtual address is also its
    // physical address.
    let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(base)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared riscv64 panic bridge (parks the hart; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn wait_qemu_riscv64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires. It does not widen either program's
/// own authority.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The single installed process-wait producer, set once before the dispatch
/// callback can fire.
static PRODUCER: SpinLock<Option<&'static KernelProcessWait<RiscvArch>>> = SpinLock::new(None);
/// The live scheduler, leaked `'static` so the dispatch callback can resolve
/// the current task id.
static SCHED: SpinLock<Option<&'static Scheduler<RiscvArch>>> = SpinLock::new(None);
/// The parent's frozen address space + direct map, used to copy the reaped
/// child's exit code out to the parent's `status` pointer.
#[allow(clippy::type_complexity)]
static PARENT_SPACE: SpinLock<
    Option<(
        Box<dyn UserAddressSpace + Send + Sync>,
        Box<dyn PhysMap + Send + Sync>,
    )>,
> = SpinLock::new(None);

/// Resolve the scheduler's current task id on [`BOOT_CPU`], failing the test if
/// none is set (it always is inside a dispatched task's `ecall`).
fn current_task_id() -> u64 {
    let sched = match *SCHED.lock() {
        Some(s) => s,
        None => qemu_exit::exit_failure(FAIL_NO_CURRENT),
    };
    match sched.current_task(BOOT_CPU) {
        Some(id) => id,
        None => qemu_exit::exit_failure(FAIL_NO_CURRENT),
    }
}

/// Encode a `Result<u64, Errno>` into the syscall return register following the
/// `abi-v1` signed convention (non-negative on success, `-errno` on error).
fn encode(result: Result<u64, Errno>) -> u64 {
    match result {
        Ok(value) => value,
        Err(err) => (-i64::from(err.as_i32())) as u64,
    }
}

/// The syscall-dispatch callback both U-mode programs' `ecall` traps reach.
///
/// `wait` is routed through the installed [`PRODUCER`] (the `ProcessWait` seam,
/// exactly as the production handler does): the producer parks the parent until
/// the child is reapable, then the callback copies the reaped exit code out to
/// the parent's `status` pointer and records whether the round-trip matched.
/// `exit` records the caller's exit code with the producer and reaps the caller
/// (`reschedule_current`); a parent that exits 0 after a verified reap is the
/// PASS. Any other syscall is unexpected and fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: `args_ptr` points at the live `[u64; SYSCALL_MAX_ARGS]` the trap
    // handler built from the saved register frame.
    let args = unsafe { &*args_ptr };
    let call = SyscallNumber::from_register(number).ok();
    let producer = match *PRODUCER.lock() {
        Some(p) => p,
        None => qemu_exit::exit_failure(FAIL_NO_PRODUCER),
    };
    let cur = current_task_id();

    if call == Some(SyscallNumber::WAIT) {
        // The slot is decoded exactly as the dispatcher decodes it: a pid
        // occupies the whole register.
        let pid = args[0].cast_signed();
        // Decode the flags fail-closed, exactly as the production dispatcher
        // does (a reserved bit never reaches the producer).
        #[allow(clippy::cast_possible_truncation)]
        let flags = match WaitFlags::from_bits(args[2] as u32) {
            Ok(flags) => flags,
            Err(err) => return encode(Err(err)),
        };
        match producer.wait(ProcessId(cur), TaskId(cur), pid, flags) {
            Ok(reaped) => {
                // Copy the typed status record out to the parent's `status`
                // pointer through the validated boundary, exactly as the
                // production `wait` handler does.
                if !copy_status_to_parent(args[1], reaped.status) {
                    qemu_exit::exit_failure(FAIL_COPY_STATUS);
                }
                if reaped.status == WaitStatus::Exited(CHILD_EXIT_CODE) {
                    REAP_OK.store(true, Ordering::SeqCst);
                }
                encode(Ok(u64::from(reaped.pid)))
            }
            Err(err) => encode(Err(err)),
        }
    } else if call == Some(SyscallNumber::EXIT) {
        // The slot is decoded exactly as the dispatcher decodes it: the
        // register carries the argument sign-extended to 32 bits.
        #[allow(clippy::cast_possible_truncation)]
        let code = args[0] as i32;
        producer.record_exit(ProcessId(cur), code);
        if cur == PARENT_TID.load(Ordering::SeqCst) {
            // The parent verified the reaped code and returned 0 on success.
            if code == 0 && REAP_OK.load(Ordering::SeqCst) {
                note(
                    TEST_PASS,
                    "wait test: parent reaped the child, read its code, and exited 0",
                );
                qemu_exit::exit_success();
            }
            qemu_exit::exit_failure(FAIL_PARENT_BAD_EXIT);
        }
        // The child (or a parent on the failure path): reap the caller. This
        // switches back to the dispatcher and never resumes the task.
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Exit);
        0
    } else {
        note(
            TEST_START,
            "wait test: fixture issued an unexpected syscall",
        );
        qemu_exit::exit_failure(FAIL_UNEXPECTED_SYSCALL);
    }
}

/// Copy the typed wait-status record out to the parent's `status`
/// pointer through the retained frozen parent space. Returns `false` on a
/// faulting or unmapped pointer (fail closed).
fn copy_status_to_parent(status_va: u64, status: WaitStatus) -> bool {
    let guard = PARENT_SPACE.lock();
    let Some((space, physmap)) = guard.as_ref() else {
        return false;
    };
    let bytes = WaitStatusRecord::encode(status).to_ne_bytes();
    copy_out(
        space.as_ref(),
        physmap.as_ref(),
        VirtAddr::new(status_va),
        &bytes,
    )
    .is_ok()
}

/// Build one isolated U-mode address space from `rxe` over the per-space
/// `pool`, returning its Sv39 root and the entry register state. Activates the
/// space (its `satp`) and builds the image through the audited `spawn_image`
/// caller. When `pool` is the parent's pool, retains its frozen view + direct
/// map so the `wait` handler can copy the reaped child's exit code out to the
/// parent's `status` pointer.
fn build_user_space(pool: &'static paging::PageTablePool, rxe: &'static [u8]) -> (u64, UserEntry) {
    let Ok(image) = LoadImage::parse(rxe, &SYSCALL_TABLE_HASH) else {
        qemu_exit::exit_failure(FAIL_PARSE);
    };
    let Some(arch) = ArchAddressSpace::new_identity_gigapages(pool, IDENTITY_GIGABYTES) else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // Capture the `satp` root before the arch space is moved into the
    // `kernel/mem` wrapper, so the per-task `pre_resume` hook can reactivate it.
    let root_phys = arch.root_phys();
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, heap,
    // frame pool, and device MMIO (all within `[0, 4 GiB)` on `virt`), so the
    // `satp` switch does not move the ground under the running code. Boot hart.
    unsafe { arch.switch() };

    let mut space = AddressSpace::new(arch);
    // SAFETY: the boot code identity-maps this window and never unmaps it.
    let physmap = unsafe { DirectPhysMap::identity((IDENTITY_GIGABYTES as u64) << 30) }
        .expect("the boot direct map addresses its window");
    let request = SpawnRequest {
        image: &image,
        image_bytes: rxe,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"wait"],
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once its space is reactivated (via `pre_resume`) and
    // the trap path is installed. Frames are drawn from `FRAME_POOL`.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => qemu_exit::exit_failure(FAIL_BUILD),
    };

    // Retain the *parent's* frozen space so the `wait` handler can copy the
    // reaped child's exit code out to the parent's `status` pointer. Only the
    // parent calls `wait`, so only its space is kept.
    if core::ptr::eq(pool, &PARENT_PAGE_TABLES) {
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());
        let pm: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);
        *PARENT_SPACE.lock() = Some((frozen, pm));
    }

    (root_phys, entry)
}

/// Admit `entry` as a resumable user kthread whose `pre_resume` hook reactivates
/// `root_phys` before every switch-in (isolation). Returns its task id.
/// The kernel-stack top the hook is handed (`_top`) is unused on riscv64:
/// `sscratch` is per-task hardware state armed by `userentry::enter_user` and
/// re-armed by the RV1 trap vector from each task's own kernel-stack frame on
/// every U-return, so a trap from the resumed task always lands on *its* kernel
/// stack with no dispatcher-side repointing.
fn admit(sched: &Scheduler<RiscvArch>, root_phys: u64, entry: UserEntry) -> u64 {
    let cs = ContextSwitchHal::new();
    let user_mode = UserMode::new();
    let pre_resume = move |_top: u64| {
        // SAFETY: paging is enabled and `root_phys` is the Sv39 root of a space
        // that maps the low identity window the running dispatcher executes
        // from — exactly `activate_user_root`'s contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |_yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: by the time this body runs the task has been dispatched, so
        // its `pre_resume` hook reactivated `satp`, and the trap vector +
        // dispatch callback are installed; the program's `ecall`s are handled.
        unsafe { user_mode.enter_user(entry) }
    };
    match spawn_user_kthread(sched, cs, BOOT_CPU, Priority::Normal, pre_resume, work) {
        Ok(id) => id,
        Err(_) => qemu_exit::exit_failure(FAIL_SPAWN),
    }
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls.
#[no_mangle]
pub extern "C" fn kernel_main(hartid: u64, dtb: u64) -> ! {
    if TEST_DRIVEN
        .compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire)
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_POOL);
    }

    note(TEST_START, "riscv64 RV-X4 wait test: starting");

    // Read the timer frequency from the firmware tree. Fail closed (finisher)
    // if it is omitted rather than guessing a divisor.
    // SAFETY: `dtb` is the verbatim `a1` pointer OpenSBI handed the boot hart;
    // `boot.s` forwards it unchanged.
    let Some(timebase) = (unsafe { Fdt::from_ptr(dtb as *const u8) })
        .ok()
        .and_then(|f| f.timebase_frequency())
    else {
        qemu_exit::exit_failure(FAIL_NO_TIMEBASE);
    };

    // The single-hart slice only brings up logical CPU 0 on hart 0.
    if hartid != u64::from(BOOT_CPU) {
        qemu_exit::exit_failure(FAIL_UNEXPECTED_HART);
    }

    // Build the two isolated U-mode address spaces (child first; the parent
    // build leaves its space active, which is fine — each task's `pre_resume`
    // reactivates the correct root on dispatch).
    let (child_root, child_entry) = build_user_space(&CHILD_PAGE_TABLES, CHILD_RXE);
    let (parent_root, parent_entry) = build_user_space(&PARENT_PAGE_TABLES, PARENT_RXE);

    // Install the trap vector + the syscall-dispatch callback before any user
    // task runs. The vector lives in the kernel's identity window present in
    // both spaces, so it is reachable whichever space is active.
    // SAFETY: called once on the boot hart with a stack established; only the
    // tasks' `ecall`s reach the vector (interrupts stay masked, so dispatch is
    // the cooperative `step` loop below).
    unsafe { trap::init_traps() };
    syscall_entry::set_dispatch_callback(dispatch);

    // Build the live scheduler and the process-wait producer, leaking both
    // `'static` so the dispatch callback can reach them.
    // Single-hart slice: one per-CPU slot each, owned by an allocator-free
    // `static` backing.
    static SCHED_STORAGE: RiscvArchStorage<1> = RiscvArchStorage::new();
    let arch = Arc::new(RiscvArch::new(&SCHED_STORAGE, BOOT_CPU, timebase));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };
    let sched: &'static Scheduler<RiscvArch> = Box::leak(Box::new(sched));
    *SCHED.lock() = Some(sched);

    static PRODUCER_STORAGE: RiscvArchStorage<1> = RiscvArchStorage::new();
    let producer_arch: &'static RiscvArch = Box::leak(Box::new(RiscvArch::new(
        &PRODUCER_STORAGE,
        BOOT_CPU,
        timebase,
    )));
    let producer: &'static KernelProcessWait<RiscvArch> =
        Box::leak(Box::new(KernelProcessWait::new(producer_arch)));
    *PRODUCER.lock() = Some(producer);

    // Admit the child and the parent as resumable user kthreads, then record
    // the parent/child link with the producer so the parent may reap it.
    let child_tid = admit(sched, child_root, child_entry);
    let parent_tid = admit(sched, parent_root, parent_entry);
    PARENT_TID.store(parent_tid, Ordering::SeqCst);
    if producer
        .register_child(ProcessId(parent_tid), ProcessId(child_tid))
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(
        TEST_SPAWNED,
        "riscv64 RV-X4 wait test: parent + child spawned",
    );

    // Cooperative dispatch loop. The parent's `wait` parks it until the child
    // exits; the parent's verified `exit(0)` is the PASS (raised from the
    // dispatch callback). A never-draining loop times out (fail-loud).
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }

    // Reaching here means the workload drained without the parent's verified
    // exit raising PASS — a missed reap or a stall.
    if steps >= MAX_STEPS {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }
    qemu_exit::exit_failure(FAIL_PARENT_BAD_EXIT);
}
