//! The freestanding aarch64 test kernel for the FIX-IO IO2 block-transport
//! fault vertical (`plans/FIX-IO.md` IO2).
//!
//! Every syscall the fixture issues runs the production `KernelDispatchHook`
//! / `KernelSyscallHandlers` path: the chassis brings the `virt` board up,
//! leaks the live subsystems, installs the production hook through a
//! `DispatchCallbackSlot`, and spawns the fixture through the production
//! `InitSpawnCtx::spawn_driver_process` seam. So the ticketed call endpoint,
//! the per-request deadline, the reply wait-set, and the reap/cancel paths the
//! fixture exercises are all the shipped kernel objects, not a bespoke shim.
//!
//! Two chassis-specific pieces earn their place here:
//!
//! * **the wait-queue arch adapter**, so a parked waiter is genuinely unparked
//!   by its wake event rather than by a fail-safe no-op; and
//! * **the timed-wake sweep in the drive loop**, standing in for the timer
//!   interrupt a production port takes. The fixture's whole point is a request
//!   that fails closed at an elapsed deadline, and nothing else in a chassis
//!   would ever notice that deadline pass.
//!
//! The chassis reaps the fixture and PASSes only on exit 0; any other exit
//! becomes a finisher code naming the fixture's own failing step.

use core::num::NonZeroU16;
use core::panic::PanicInfo;

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::{CapabilityId, Errno, WaitFlags, WaitStatus, SYSCALL_MAX_ARGS};
use tairix_arch_aarch64::kernel_arch::timer_frequency_hz;
use tairix_arch_aarch64::paging::{
    configure_device_gigapages, configure_kernel_gigapages, install_boot_physmap,
    AddressSpace as ArchAddressSpace, PageTablePool, GIGAPAGE_MASK_WORDS,
};
use tairix_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, Aarch64Arch,
    Aarch64ArchStorage, SERIAL_SINK,
};
use tairix_arch_api::BOOT_CPU;
use tairix_caps::CapabilitySet;
use tairix_fdt::Fdt;
use tairix_itest_finisher::fail_code;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel::aarch64::arch_wrapper::{Aarch64BinArch, UART_ONLY_CONSOLES};
use tairix_kernel::aarch64::spawn_producer::{AARCH64_PROCESS_SPAWN, USER_IMAGE_BIAS};
use tairix_kernel::dispatch_core::{dispatch_via_slot, read_raw_args, resolve_user_fault_via_slot};
use tairix_kernel_core::{
    AddressSpaceRegistry, BootReserve, DispatchCallbackSlot, EmbeddedProgram, InitSpawnCtx,
    KernelArch, KernelDispatchHook, KernelInitSpawner, KernelProcessWait, LiveMemMap, ProcessWait,
    ProgramRegistry, RandomReserve, SchedWaitQueueArch, NULL_DMA_ALLOC_FACILITY,
    NULL_MMIO_MAP_FACILITY, NULL_SEAT_REGISTRY, NULL_SHARED_MEM_FACILITY,
};
use tairix_kernel_ipc::PortRegistry;
use tairix_kernel_irq::{IrqTable, UnsupportedController};
use tairix_kernel_mem::{
    BootMemoryMap, FrameAllocator, MemoryRegion, PhysAddr, RegionKind, PAGE_SIZE,
};
use tairix_kernel_sched_cfq::{Scheduler, SchedulerConfig};
use tairix_kernel_sec::{CapTable, ProcessId};
use tairix_log::{log, Event, EventId, Level};
use tairix_sync::RwLock;

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// Gigabytes of identity map the boot address space provides: `[0, 2 GiB)`
/// covers the `virt` board's device MMIO (GiB 0) and the RAM base at GiB 1
/// where this kernel, its heap, and the frame pool live.
const IDENTITY_GIB: usize = 2;

/// Physical frames the production spawn producer draws from: one spawned
/// process (image, eagerly committed stack top, page tables, identity-window
/// tables) with generous headroom (16 MiB).
const FRAME_COUNT: usize = 4096;

/// Wall-clock budget, in monotonic nanoseconds, before the chassis declares
/// the workload deadlocked.
///
/// This is a *time* budget rather than a scheduler-step count because the
/// fixture legitimately parks for its wedged request's deadline, during which
/// the drive loop steps an empty run queue at a rate no test should depend on.
/// It is more than an order of magnitude above the fixture's own worst case
/// (its wedged wake ceiling), so it can only be reached by a genuine hang.
const WATCHDOG_NS: u64 = 30_000_000_000;

/// Scheduler steps between watchdog clock reads, so the budget check costs
/// nothing measurable on the drive loop.
const STEPS_PER_CLOCK_READ: u64 = 1024;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4480);
const TEST_SPAWNED: EventId = EventId(4481);
const TEST_PASS: EventId = EventId(4482);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_GIC: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_FRAMES: NonZeroU16 = fail_point!(4);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(5);
const FAIL_SPAWN: NonZeroU16 = fail_point!(6);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(7);
const FAIL_NO_DISPATCH: NonZeroU16 = fail_point!(8);
const FAIL_HOOK_INSTALL: NonZeroU16 = fail_point!(9);
const FAIL_RESOLVER_INSTALL: NonZeroU16 = fail_point!(10);
const FAIL_BIAS: NonZeroU16 = fail_point!(11);
const FAIL_POLL: NonZeroU16 = fail_point!(12);
const FAIL_DRAINED: NonZeroU16 = fail_point!(13);
const FAIL_FIXTURE_STOPPED: NonZeroU16 = fail_point!(14);
/// The direct physical map could not be installed over the board's RAM.
const FAIL_PHYSMAP: NonZeroU16 = fail_point!(15);
/// Base finisher for a non-zero fixture exit; the fixture's diagnostic exit
/// code is added so the failing step is identifiable in the finisher.
const FAIL_EXIT_BASE: NonZeroU16 = fail_point!(100);

/// Size of the test's bump heap. Lives in `.bss` (zeroed by the trampoline).
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the kernel's own boot identity map.
static BOOT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Identity-mapped physical-frame backing store the live [`FrameAllocator`]
/// serves the spawn producer and the stack-growth fault path from; inside
/// the 2 GiB identity window the producer's page-table walk requires.
#[repr(C, align(4096))]
struct FramePool([u8; PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; PAGE_SIZE * FRAME_COUNT]);

/// The dispatch-callback slot the production [`KernelDispatchHook`] is
/// installed into (one slot per binary, set once). Both the syscall
/// callback and the user-fault resolver resolve through it.
static DISPATCH_SLOT: DispatchCallbackSlot = DispatchCallbackSlot::new();

/// Per-CPU storage backing the scheduler's arch handle.
static SCHED_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// Per-CPU storage backing the dispatch hook + spawn ctx arch handle.
static HOOK_ARCH_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// This vertical binds no IRQ lines; the fail-closed controller mirrors
/// what `kernel/core::init` installs when a port exposes no routing.
static IRQ_CONTROLLER: UnsupportedController = UnsupportedController;

/// The fixture spawns nothing, so the registry the production `spawn` syscall
/// would resolve against is empty. Leaving it empty keeps the vertical's
/// surface to the block transport it is about.
static CHILD_PROGRAMS: [EmbeddedProgram; 0] = [];

/// The registry over [`CHILD_PROGRAMS`].
static PROGRAMS: ProgramRegistry = ProgramRegistry::new(&CHILD_PROGRAMS);

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn blkio_fault_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// The syscall-dispatch callback every program's `svc` traps reach. It
/// mirrors the production bin-crate callback (`dispatch_aarch64`): read the
/// kernel-stack args frame and forward through the resident production
/// [`KernelDispatchHook`] via the shared `dispatch_via_slot` bridge. An
/// empty slot or a missing caller context fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the exception trampoline lays the frame out on the kernel
    // stack and only invokes us with a valid pointer; the array lives at
    // least until we return.
    let args = unsafe { read_raw_args(args_ptr) };
    match dispatch_via_slot(&DISPATCH_SLOT, number, args) {
        Some(value) => value,
        None => qemu_exit::exit_failure(FAIL_NO_DISPATCH),
    }
}

/// The user-fault resolver the EL1 data-abort path calls for every EL0
/// data abort: the exact production glue, bound to this vertical's own slot
/// so an in-span stack-growth fault runs the resident production hook's
/// `resolve_stack_fault` path and an unresolvable fault kills the faulting
/// task through the production fault-exit path.
// The callback matches the arch `UserFaultResolveFn` type (a bare safe
// `extern "C" fn`); the raw pointer is only forwarded into the guarded
// `unsafe` call below, which narrows it with `as_ref`.
#[allow(clippy::not_unsafe_ptr_arg_deref)]
extern "C" fn blkio_fault_user_fault(
    far: u64,
    write: bool,
    regs: *const tairix_arch_api::backtrace::UserRegisterFrame,
) -> bool {
    // SAFETY: the trap handler builds the frame on its kernel stack and
    // holds it live across this call, or passes null; the slot helper
    // narrows the pointer with `as_ref` and never dereferences null.
    unsafe { resolve_user_fault_via_slot(&DISPATCH_SLOT, far, write, regs) }
}

/// The capability set the fixture runs under: `CAP_IPC_ENDPOINT` alone, the
/// authority a serving block driver needs to bind the endpoints it publishes.
/// Everything else the fixture calls — the ticketed post/reap/cancel trio, the
/// wait-set, and the monotonic clock — is unprivileged by design, so granting
/// more would be authority the vertical does not need.
fn fixture_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::IPC_ENDPOINT);
    caps
}

/// Bring the board up: FP/SIMD on, the `virt` device tree discovered
/// (timer rate, GICv2 bases), the identity-gigapage masks configured from
/// the board facts, the identity MMU + EL1 vectors enabled, the GIC
/// initialised, and the dispatch callback + user-fault resolver installed.
/// Returns the discovered generic-timer rate.
fn bring_up_board() -> u64 {
    // Enable FP/SIMD at EL1 before any code the compiler may lower to NEON
    // (the `rxe` decoder, the spawn image fills, the log formatter).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Configure the board's gigapage facts, exactly as the production boot
    // path derives them from discovery: Device GiB 0 is the `virt` MMIO
    // window, and GiB 1 holds both this kernel's image and its RAM. The
    // production spawn producer sizes every child's identity window from
    // these masks, so driving it under the unconfigured defaults would
    // request a window reaching the user bias and the spawn would fail
    // closed.
    let mut device_mask = [0u64; GIGAPAGE_MASK_WORDS];
    device_mask[0] = 0b01;
    configure_device_gigapages(device_mask);
    let mut ram_mask = [0u64; GIGAPAGE_MASK_WORDS];
    ram_mask[0] = 0b10;
    configure_kernel_gigapages(ram_mask);
    // The production spawn producer reaches a child's page tables through
    // the direct physical map in the kernel translation regime, so the
    // chassis stands it up over the same RAM before driving the producer.
    if !install_boot_physmap(&ram_mask) {
        qemu_exit::exit_failure(FAIL_PHYSMAP);
    }

    // Enable the identity MMU + EL1 vectors before any atomic
    // read-modify-write runs: the frame allocator, the scheduler, and every
    // registry the test builds use atomics, which are UNPREDICTABLE on
    // MMU-off Device-typed memory (`plans/PI.md` P6c-2).
    let Some(boot_space) =
        ArchAddressSpace::new_identity_gigapages(&BOOT_PAGE_TABLES, IDENTITY_GIB)
    else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
    // heap, the frame pool, and the device MMIO (all within `[0, 2 GiB)` on
    // the `virt` board), so switching it does not move the ground under the
    // running code; `init_vectors` runs once on the boot CPU with a stack
    // established.
    unsafe {
        boot_space.switch();
        exceptions::init_vectors();
    }
    // The boot space's tables live in the static `BOOT_PAGE_TABLES` pool
    // and the handle carries no `Drop`, so letting it fall out of scope
    // leaves the active translation regime untouched for the kernel's
    // lifetime (the kernel never returns).
    // SAFETY: called once on the boot CPU after the GIC bases were
    // discovered above.
    unsafe {
        tairix_itest_gic::init_boot_cpu().expect("the GIC comes up");
    }
    syscall_entry::set_dispatch_callback(dispatch);
    // Bind the production user-fault resolver to this vertical's slot so a
    // fixture stack-growth fault resolves exactly as in production.
    if tairix_arch_api::fault::set_user_fault_resolver(blkio_fault_user_fault).is_err() {
        qemu_exit::exit_failure(FAIL_RESOLVER_INSTALL);
    }
    counter_hz
}

/// The leaked-`'static` kernel subsystems the production dispatch hook and
/// spawn context borrow — the vertical's analogue of `KernelState`, lifted
/// by one-shot `Box::leak` publishes exactly as `kernel_core::kernel_main`
/// does (a one-shot publish, not a global mutable static).
struct Subsystems {
    frames: &'static FrameAllocator,
    sched: &'static Scheduler<Aarch64BinArch>,
    arch: &'static Aarch64BinArch,
    caps: &'static RwLock<CapTable>,
    peer_watch: &'static tairix_kernel_core::PeerWatch,
    ipc: &'static RwLock<PortRegistry>,
    aspaces: &'static RwLock<AddressSpaceRegistry>,
    rng: &'static RwLock<Box<dyn RandomReserve + Send + Sync>>,
    irq_table: &'static IrqTable,
}

/// Build the live kernel subsystems: the `kernel/mem` frame allocator over
/// the identity-mapped pool (so the spawn producer and the demand-fault
/// path draw their frames from the production path), the scheduler over
/// the production `KernelArch` wrapper, and the capability / port /
/// address-space / random / IRQ state the production hook borrows.
fn leak_subsystems(counter_hz: u64) -> Subsystems {
    let mut memory_map = BootMemoryMap::new();
    memory_map.push(MemoryRegion {
        start: PhysAddr::new(core::ptr::addr_of!(FRAME_POOL) as u64),
        length: (PAGE_SIZE * FRAME_COUNT) as u64,
        kind: RegionKind::Usable,
    });
    let Ok(frames) = FrameAllocator::new(&memory_map) else {
        qemu_exit::exit_failure(FAIL_FRAMES);
    };
    let frames: &'static FrameAllocator = Box::leak(Box::new(frames));

    let sched_arch = Arc::new(Aarch64BinArch::new(Aarch64Arch::new(
        &SCHED_STORAGE,
        BOOT_CPU,
        counter_hz,
    )));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), sched_arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    Subsystems {
        frames,
        sched: Box::leak(Box::new(sched)),
        arch: Box::leak(Box::new(Aarch64BinArch::new(Aarch64Arch::new(
            &HOOK_ARCH_STORAGE,
            BOOT_CPU,
            counter_hz,
        )))),
        caps: Box::leak(Box::new(RwLock::new(CapTable::new()))),
        peer_watch: Box::leak(Box::new(tairix_kernel_core::PeerWatch::new())),
        ipc: Box::leak(Box::new(RwLock::new(PortRegistry::new()))),
        aspaces: Box::leak(Box::new(RwLock::new(AddressSpaceRegistry::new()))),
        rng: Box::leak(Box::new(RwLock::new(
            Box::new(BootReserve::new()) as Box<dyn RandomReserve + Send + Sync>
        ))),
        irq_table: Box::leak(Box::new(IrqTable::new(0))),
    }
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `tairix_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 block-transport fault test: starting");

    let counter_hz = bring_up_board();

    // The fixture `rxe`'s baked relocations must target the bias the
    // production producer maps every child at; a drifted constant would
    // admit a child whose pointers do not match its mapping (fail closed).
    if USER_BIAS != USER_IMAGE_BIAS {
        qemu_exit::exit_failure(FAIL_BIAS);
    }

    let sys = leak_subsystems(counter_hz);

    // Publish the wait-queue arch hook so parked waiters are genuinely
    // unparked by their wake events — the same adapter the production boot
    // path installs.
    let wait_arch = SchedWaitQueueArch::leak(sys.sched, sys.arch);
    if tairix_kernel_core::waitq::install_wait_arch(wait_arch).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // The scheduler-side process-wait producer: records every parent/child
    // link the production spawn paths register, and is how this chassis
    // reaps the fixture's exit.
    let wait_producer: &'static KernelProcessWait<Aarch64BinArch> =
        Box::leak(Box::new(KernelProcessWait::new(sys.arch)));

    // The production live-space producer: serves the `mem_map` pair (the
    // `tairix-rt` heap) and the one-page-per-fault backing the stack-growth
    // resolver maps through it.
    let live: &'static LiveMemMap<Aarch64BinArch> = Box::leak(Box::new(LiveMemMap::new(sys.arch)));

    // Publish the production dispatch hook: every syscall the fixture issues
    // — `call_create`, the ticketed `call_post`/`call_reap`/`call_cancel`
    // trio, `call_recv`/`call_reply`, the wait-set trio, `clock_get`, and
    // `exit` — runs the production caller-context resolution and handler path.
    let hook: &'static KernelDispatchHook<'static, Aarch64BinArch> = Box::leak(Box::new(
        KernelDispatchHook::new(
            sys.sched,
            sys.caps,
            sys.arch,
            &SERIAL_SINK,
            sys.irq_table,
            &IRQ_CONTROLLER,
            sys.ipc,
            sys.aspaces,
            sys.rng,
            &UART_ONLY_CONSOLES,
            sys.frames,
            sys.frames,
            &PROGRAMS,
            wait_producer,
            &NULL_SEAT_REGISTRY,
            live,
            &NULL_MMIO_MAP_FACILITY,
            &NULL_DMA_ALLOC_FACILITY,
        )
        .with_peer_watch(sys.peer_watch),
    ));
    if DISPATCH_SLOT.install_dispatcher(hook).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // Publish the launch-services bundle the deferred child-load path reads:
    // the arch image builder builds the admitted image on the process's own
    // first slice, off this chassis's cooperative drive. The one shared
    // build+publish the production boot path uses.
    let _ = tairix_kernel_core::spawn_services::install_over(
        sys.arch,
        sys.frames,
        &SERIAL_SINK,
        &tairix_kernel_core::NULL_FILESYSTEM,
        None,
        sys.aspaces,
        sys.caps,
        sys.peer_watch,
        wait_producer,
        &AARCH64_PROCESS_SPAWN,
    );

    let init_ctx = KernelInitSpawner::new(
        sys.frames,
        &SERIAL_SINK,
        sys.sched,
        sys.caps,
        sys.peer_watch,
        sys.aspaces,
        sys.arch,
        wait_producer,
        sys.irq_table,
        &IRQ_CONTROLLER,
        &NULL_SHARED_MEM_FACILITY,
        KernelArch::cross_cpu_tlb_shootdown(sys.arch),
    );
    let Ok(fixture_pid) = init_ctx.spawn_driver_process(
        "/bin/blkio-fault",
        PROGRAM_RXE,
        fixture_caps(),
        &[],
        &[b"blkio-fault"],
        None,
    ) else {
        qemu_exit::exit_failure(FAIL_SPAWN);
    };
    note(
        TEST_SPAWNED,
        "aarch64 block-transport fault test: fixture spawned through the production seam",
    );

    // The budget-bounded cooperative drive: step the scheduler, deliver the
    // wakes a handler deferred, and poll the wait producer for the fixture's
    // exit between steps. A fixture exit of 0 is the PASS; anything else names
    // the failing step in the finisher.
    // A task id never exceeds the ABI's pid bound, so reinterpreting it as
    // the signed pid the wait ABI carries is exact.
    let fixture_pid = fixture_pid.cast_signed();
    let started_ns = KernelArch::monotonic_ns(sys.arch, BOOT_CPU);
    let mut steps = 0u64;
    loop {
        let _ = sys.sched.step(BOOT_CPU);
        steps += 1;

        // Stand in for the production timer tick. A chassis routes no timer
        // interrupt, so without this nothing would ever notice a deadline
        // elapse and the fixture's parked reaper — waiting on exactly that —
        // would never be woken. The tick handler's two halves are performed in
        // the same order the production port performs them: flag the sweep,
        // then let the drain do the real unparking in dispatcher context.
        tairix_kernel_core::timed_wake_sweep();
        let _ = tairix_kernel_core::waitq::drain_pending_wakes();

        match wait_producer.poll(ProcessId(0), fixture_pid, WaitFlags::empty()) {
            Ok(reaped) => match reaped.status {
                WaitStatus::Exited(0) => {
                    note(
                        TEST_PASS,
                        "aarch64 block-transport fault test: a wedged device failed closed at its \
                         deadline while the healthy device kept serving",
                    );
                    qemu_exit::exit_success();
                }
                WaitStatus::Exited(code) => {
                    qemu_exit::exit_failure(fail_code(FAIL_EXIT_BASE, code));
                }
                WaitStatus::Stopped(_) => {
                    qemu_exit::exit_failure(FAIL_FIXTURE_STOPPED);
                }
            },
            Err(Errno::WouldBlock) => {}
            Err(_) => qemu_exit::exit_failure(FAIL_POLL),
        }

        // A fully drained workload without a reapable fixture means it
        // vanished down a path that never recorded its exit; fail with a
        // distinct finisher rather than spinning out the watchdog.
        if sys.sched.live_task_count() == 0 {
            qemu_exit::exit_failure(FAIL_DRAINED);
        }

        if steps.is_multiple_of(STEPS_PER_CLOCK_READ)
            && KernelArch::monotonic_ns(sys.arch, BOOT_CPU).saturating_sub(started_ns)
                >= WATCHDOG_NS
        {
            qemu_exit::exit_failure(FAIL_DEADLOCK);
        }
    }
}
