//! Stateful property model for `WinterSun`'s client shell.
//!
//! The shell's invariants are the ones a unit test states one case of and
//! a randomised program states over every ordering:
//!
//! * the camera never shows ground outside the realm, whatever sequence
//!   of follows and zooms put it where it is;
//! * the degradation ladder never leaves its range, turns more than one
//!   knob at a time, moves more than one notch for a frame, or goes past
//!   the floor the window and the zoom set;
//! * a render target is always inside the software path's cap and always
//!   has pixels, at every window size and every ladder step;
//! * the bands a target is cut into tile its rows exactly once, for every
//!   width a runner could have;
//! * the clock never reports more ticks than its catch-up bound allows,
//!   and its fraction never leaves `0..=255`;
//! * every combination of held keys produces a direction the wire
//!   protocol will accept.
//!
//! Two things make it sharp. The workspace builds with overflow checks on
//! in every profile, and the projection is full of products of extents
//! and pixel spans at coordinates that reach the ends of `i32` — so
//! arithmetic that wrapped aborts the case rather than quietly answering
//! wrongly. And the commands are replayed against one live session, so a
//! state only reachable by a particular *order* of window events is
//! reachable here.

use proptest::prelude::*;
use tairix_abi::input::{KeyInput, KeyValue, Modifiers, NamedKeyCode};
use tairix_abi::window_ipc::WindowSizeState;
use tairix_parallel::Reversed;
use tairix_wintersun_app::budget::{FrameTimes, Governor, Pass, FRAME_NS};
use tairix_wintersun_app::camera::{realm_bounds, Camera, Zoom};
use tairix_wintersun_app::input::Controls;
use tairix_wintersun_app::pacing::{Pacer, MAX_CATCHUP_NS};
use tairix_wintersun_app::quality::Ladder;
use tairix_wintersun_app::shell::Shell;
use tairix_wintersun_app::view::{Viewport, MAX_RENDER_HEIGHT, MAX_RENDER_WIDTH};
use tairix_wintersun_net::bounds::MAX_DIRECTION_MAGNITUDE_SQ;
use tairix_wintersun_net::value::{Direction, WorldPoint};
use tairix_wintersun_rules::clock::TickRate;
use tairix_wintersun_world::params::{RealmParams, RealmSpec};

/// Sequences run once by a plain `cargo test` (no budget set).
const SMOKE_CASES: u32 = 96;

/// Sequences per batch under a wall-clock budget.
const BUDGET_BATCH_CASES: u32 = 192;

/// Commands in one generated program.
const PROGRAM_LEN: usize = 48;

/// The realm every case looks at.
const SEED: u64 = 0x5749_4E43_4C49_454E;

/// One legal thing a player or a compositor may do to the client.
#[derive(Copy, Clone, Debug)]
enum Cmd {
    /// Point the camera at a world position.
    Follow { x: i32, y: i32 },
    /// Move the zoom in or out a stop.
    Zoom { nearer: bool },
    /// The compositor answered with an extent and a state.
    Resized { width: u32, height: u32, state: u8 },
    /// A key went down or came up.
    Key { code: u8, down: bool },
    /// The window gained or lost focus.
    Focus { focused: bool },
    /// The seat came or went.
    Seat { seated: bool },
    /// The window was minimized.
    Minimize,
    /// A run of frames overran or came in comfortably, and the governor saw
    /// each.
    Frames { over: bool, count: u8 },
    /// The clock advanced.
    Tick { delta_ns: u64 },
}

/// The movement and command keys the model presses.
const KEYS: [KeyValue; 8] = [
    KeyValue::Named(NamedKeyCode::Up),
    KeyValue::Named(NamedKeyCode::Down),
    KeyValue::Named(NamedKeyCode::Left),
    KeyValue::Named(NamedKeyCode::Right),
    KeyValue::Char('w'),
    KeyValue::Char('a'),
    KeyValue::Named(NamedKeyCode::F11),
    KeyValue::Named(NamedKeyCode::Escape),
];

/// The three size states, so a generated byte names one of them.
const STATES: [WindowSizeState; 3] = [
    WindowSizeState::Restored,
    WindowSizeState::Maximized,
    WindowSizeState::Fullscreen,
];

fn params() -> RealmParams {
    RealmParams::new(RealmSpec {
        extent_chunks: 16,
        coarse_samples: 32,
        plates: 8,
        ..RealmParams::default_realm(SEED).spec()
    })
    .expect("the spec is within its own stated range")
}

/// The whole client state a program drives.
struct Session {
    camera: Camera,
    shell: Shell,
    controls: Controls,
    pacer: Pacer,
    governor: Governor,
    clock_ns: u64,
    params: RealmParams,
}

impl Session {
    fn new() -> Self {
        Self {
            camera: Camera::new(
                WorldPoint { x: 0, y: 0 },
                Zoom::DEFAULT,
                realm_bounds(params()),
            ),
            shell: Shell::new(),
            controls: Controls::new(),
            pacer: Pacer::new(TickRate::default_rate()),
            governor: Governor::new(),
            clock_ns: 0,
            params: params(),
        }
    }

    /// The extent the camera is projected through, which is the window's
    /// when one is open and the baseline before that.
    fn extent(&self) -> (u32, u32) {
        self.shell.extent().unwrap_or((1280, 720))
    }

    /// The deepest the ladder may go for the window and the zoom as they
    /// stand.
    fn floor(&self) -> Ladder {
        let (w, h) = self.extent();
        Ladder::floor(w.max(1), h.max(1), self.camera.zoom())
    }

    fn run(&mut self, command: Cmd) -> Result<(), TestCaseError> {
        match command {
            Cmd::Follow { x, y } => self.camera.look_at(WorldPoint { x, y }),
            Cmd::Zoom { nearer } => {
                let moved = if nearer {
                    self.camera.zoom().nearer()
                } else {
                    self.camera.zoom().further()
                };
                if let Some(zoom) = moved {
                    self.camera.set_zoom(zoom);
                }
            }
            Cmd::Resized {
                width,
                height,
                state,
            } => {
                let state = STATES[usize::from(state) % STATES.len()];
                self.shell.resized(width, height, state);
            }
            Cmd::Key { code, down } => {
                let key = KEYS[usize::from(code) % KEYS.len()];
                let input = if down {
                    KeyInput::Pressed {
                        key,
                        modifiers: Modifiers::default(),
                    }
                } else {
                    KeyInput::Released {
                        key,
                        modifiers: Modifiers::default(),
                    }
                };
                self.controls.apply_key(&input);
            }
            Cmd::Focus { focused } => {
                if self.shell.focus(focused) {
                    self.controls.release_all();
                }
            }
            Cmd::Seat { seated } => {
                self.shell.seat(seated);
            }
            Cmd::Minimize => self.shell.minimized(),
            Cmd::Frames { over, count } => {
                let mut times = FrameTimes::new();
                let cost = if over {
                    Pass::Terrain.budget_ns() * 8
                } else {
                    1_000_000
                };
                times.record(Pass::Terrain, cost);
                for _ in 0..count {
                    self.clock_ns = self.clock_ns.saturating_add(FRAME_NS);
                    let before = self.governor.ladder();
                    if self.governor.observe(&times, self.extent(), self.clock_ns) {
                        let after = self.governor.ladder();
                        let expected = if over {
                            before.shed()
                        } else {
                            before.restore()
                        };
                        prop_assert_eq!(
                            Some(after),
                            expected,
                            "a frame moved the ladder somewhere other than one notch"
                        );
                    }
                    self.governor.hold(self.floor());
                }
            }
            Cmd::Tick { delta_ns } => {
                self.clock_ns = self.clock_ns.saturating_add(delta_ns);
                let ticks = self.pacer.advance(self.clock_ns);
                let cap = MAX_CATCHUP_NS * u64::from(self.pacer.rate().hz()) / 1_000_000_000;
                prop_assert!(
                    u64::from(ticks) <= cap + 1,
                    "a {delta_ns} ns step produced {ticks} ticks, past the {cap}-tick bound"
                );
            }
        }
        // What the client does with its clock after every wake, and before
        // every frame it draws.
        if self.shell.running() {
            if self.pacer.paused() {
                self.pacer.resume(self.clock_ns);
            }
        } else if !self.pacer.paused() {
            self.pacer.pause();
        }
        self.governor.hold(self.floor());
        Ok(())
    }
}

/// Everything that must hold after every command.
fn check(session: &Session) -> Result<(), TestCaseError> {
    let (w, h) = session.extent();
    let ladder = session.governor.ladder();
    prop_assert!(ladder.step() <= Ladder::MAX_STEP);
    prop_assert!(
        ladder <= session.floor(),
        "the ladder stands at {:?}, past the floor {:?}",
        ladder,
        session.floor()
    );
    let view = Viewport::new(w.max(1), h.max(1), ladder.detail().resolution.scale())
        .expect("a window with pixels");

    let bounds = realm_bounds(session.params);
    let visible = session.camera.visible(&view);
    prop_assert!(
        visible.min_x >= bounds.min_x
            && visible.max_x <= bounds.max_x
            && visible.min_y >= bounds.min_y
            && visible.max_y <= bounds.max_y,
        "the camera shows {visible:?}, outside the realm's {bounds:?}"
    );

    let (rw, rh) = view.render();
    prop_assert!(
        rw >= 1 && rh >= 1,
        "a render target of {rw}x{rh} has no pixels"
    );
    prop_assert!(
        rw <= MAX_RENDER_WIDTH && rh <= MAX_RENDER_HEIGHT,
        "a render target of {rw}x{rh} is past the software path's cap"
    );
    prop_assert!(view.render_pixels() == (rw as usize) * (rh as usize));

    for width in [1usize, 2, 3, 5, 9] {
        let runner = Reversed::new(width);
        let rows = view.band_rows(&runner);
        let bands = rh.div_ceil(rows);
        prop_assert!(rows >= 1);
        prop_assert!(
            bands as usize <= view.band_count(&runner),
            "{} bands of {} rows for a runner {} wide",
            bands,
            rows,
            width
        );
        prop_assert!(
            rows * (bands - 1) < rh && rows * bands >= rh,
            "bands of {} rows did not tile {} rows",
            rows,
            rh
        );
    }

    let direction = session.controls.direction();
    prop_assert!(
        magnitude_sq(direction) <= MAX_DIRECTION_MAGNITUDE_SQ,
        "the held keys produced {direction:?}, which the wire refuses"
    );

    prop_assert_ne!(
        session.shell.running(),
        session.pacer.paused(),
        "the clock disagreed with whether anyone can see the window"
    );
    Ok(())
}

fn magnitude_sq(direction: Direction) -> i64 {
    i64::from(direction.x()) * i64::from(direction.x())
        + i64::from(direction.y()) * i64::from(direction.y())
}

fn command() -> impl Strategy<Value = Cmd> {
    prop_oneof![
        (any::<i32>(), any::<i32>()).prop_map(|(x, y)| Cmd::Follow { x, y }),
        any::<bool>().prop_map(|nearer| Cmd::Zoom { nearer }),
        (1u32..4000, 1u32..3000, any::<u8>()).prop_map(|(width, height, state)| Cmd::Resized {
            width,
            height,
            state,
        }),
        (any::<u8>(), any::<bool>()).prop_map(|(code, down)| Cmd::Key { code, down }),
        any::<bool>().prop_map(|focused| Cmd::Focus { focused }),
        any::<bool>().prop_map(|seated| Cmd::Seat { seated }),
        Just(Cmd::Minimize),
        (any::<bool>(), 1u8..=240).prop_map(|(over, count)| Cmd::Frames { over, count }),
        (0u64..5_000_000_000).prop_map(|delta_ns| Cmd::Tick { delta_ns }),
    ]
}

fn program() -> impl Strategy<Value = Vec<Cmd>> {
    proptest::collection::vec(command(), 1..=PROGRAM_LEN)
}

#[test]
fn no_sequence_of_legal_operations_breaks_an_invariant() {
    tairix_fuzzseed::prop::drive(
        "no_sequence_of_legal_operations_breaks_an_invariant",
        SMOKE_CASES,
        BUDGET_BATCH_CASES,
        program(),
        |commands| {
            let mut session = Session::new();
            check(&session)?;
            for command in commands {
                session.run(command)?;
                check(&session)?;
            }
            Ok(())
        },
    );
}

#[test]
fn the_ladder_turns_one_knob_per_step_from_every_starting_point() {
    // Shedding from an arbitrary step, not only from full: the rung
    // boundaries are computed from a running remainder, and an off-by-one
    // there would show as two knobs moving at one boundary and none at
    // another.
    tairix_fuzzseed::prop::drive(
        "the_ladder_turns_one_knob_per_step_from_every_starting_point",
        SMOKE_CASES,
        BUDGET_BATCH_CASES,
        0u8..Ladder::MAX_STEP,
        |step| {
            let here = Ladder::new(step);
            let next = here.shed().expect("below the bottom rung");
            let (a, b) = (here.detail(), next.detail());
            let moved = usize::from(a.lighting != b.lighting)
                + usize::from(a.shadows != b.shadows)
                + usize::from(a.ground != b.ground)
                + usize::from(a.resolution != b.resolution);
            prop_assert_eq!(moved, 1, "step {} turned {} knobs", step, moved);
            prop_assert_eq!(next.restore(), Some(here), "restore did not undo shed");
            Ok(())
        },
    );
}
