//! Build script for the `plans/PI.md` P11 Chunk B-2 root-mount->login
//! (aarch64) QEMU test.
//!
//! Two jobs, both done on the host where the toolchain and
//! `ed25519-dalek` are available:
//!
//! 1. Hand the aarch64 `virt` linker script to `rustc` on the
//!    freestanding `aarch64-unknown-none` target (the single per-arch
//!    linker script the architecture port owns).
//! 2. Sign a synthetic virtio-blk `.rxe` manifest requesting
//!    [`CapabilityId::MEM_DMA`] with a deterministic test seed, and emit
//!    a Rust source file the bin pulls in via `include!`.
//!
//! Re-running `build.rs` produces byte-identical output for the same
//! seed; the test is therefore deterministic.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;
use tairix_abi::{CapabilityId, DriverKind, DriverManifest, DRIVER_MANIFEST_MAGIC};
use tairix_crypto::Ed25519SecretKey;

/// Deterministic signing seed so the trust anchor is stable across
/// builds. Distinct from the other QEMU fixtures' seeds so the images
/// cannot be confused.
const TEST_SEED: [u8; 32] = [
    0x72, 0x6f, 0x6f, 0x74, 0x75, 0x6e, 0x6c, 0x6b, 0x21, 0x9d, 0x4c, 0xe7, 0x35, 0x8a, 0x16, 0xb3,
    0xc4, 0x57, 0x2e, 0x90, 0x6b, 0xa1, 0x3f, 0xd8, 0x05, 0x9c, 0x47, 0x12, 0xeb, 0x34, 0x88, 0x6d,
];

/// SHA-256 fingerprint of the host's syscall table. The concrete value
/// is irrelevant; both sides feed the same value into the `HostConfig`.
const SYS_HASH: [u8; 32] = [0x2B; 32];

fn main() {
    tairix_itest_harness::aarch64_virt_guest_build(1);

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR set by cargo");

    let signing_key = Ed25519SecretKey::from_seed(&TEST_SEED);
    let signer_pubkey: [u8; 32] = *signing_key.public_key().as_bytes();

    // The virtio-blk driver's `register` entry checks `CAP_DRV_LOAD`, and
    // the kernel virtio factory only mints a DMA host for a driver granted
    // `CAP_MEM_DMA`. The driver's effective set is the intersection of the
    // loading user's grants and this manifest request, so name both.
    let caps: &[u16] = &[
        CapabilityId::DRV_LOAD.as_u16(),
        CapabilityId::MEM_DMA.as_u16(),
    ];
    let mut manifest = DriverManifest {
        magic: DRIVER_MANIFEST_MAGIC,
        abi_version: tairix_abi::ABI_VERSION_CURRENT,
        kind: DriverKind::UserSpace,
        bind_key_count: 0,
        capability_count: u16::try_from(caps.len()).expect("caps fit in u16"),
        syscall_table_hash: SYS_HASH,
        signer_pubkey,
        signature: [0u8; 64],
    };
    let encoded = manifest.to_le_bytes();
    let mut signed_message = Vec::with_capacity(DriverManifest::WIRE_LEN - 64 + caps.len() * 2);
    signed_message.extend_from_slice(&encoded[..DriverManifest::WIRE_LEN - 64]);
    for c in caps {
        signed_message.extend_from_slice(&c.to_le_bytes());
    }
    let sig = signing_key.sign(&signed_message);
    manifest.signature = *sig.as_bytes();

    let mut image: Vec<u8> = Vec::new();
    image.extend_from_slice(&manifest.to_le_bytes());
    for c in caps {
        image.extend_from_slice(&c.to_le_bytes());
    }

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    out.push_str("/// Signed virtio-blk `.rxe` image bytes.\n");
    out.push_str("pub const RXE_IMAGE: &[u8] = &[");
    for (i, b) in image.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n\n");
    out.push_str("/// Trust-anchor public key the host's `HostConfig` accepts.\n");
    out.push_str("pub const TRUSTED_SIGNER_PUBKEY: [u8; 32] = [");
    for (i, b) in signer_pubkey.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n\n");
    out.push_str("/// SHA-256 fingerprint of the host's syscall table.\n");
    out.push_str("pub const SYSCALL_TABLE_HASH: [u8; 32] = [");
    for (i, b) in SYS_HASH.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n");

    let path = PathBuf::from(&out_dir).join("rxe_fixture.rs");
    fs::write(&path, out).expect("write rxe_fixture.rs");
}
