//! Bare-metal boot pipeline for the aarch64 (Raspberry Pi 4)
//! `tairix-kernel` binary — `plans/PI.md` Stage P1.
//!
//! [`boot`] is the single entry point. It is called from the binary's
//! `extern "C" fn kernel_main(dtb: u64)` after the arch crate's
//! [`tairix_arch_aarch64::entry`] trampoline (`boot.s` → `entry.rs`)
//! has dropped to EL1, parked the non-boot CPUs, established the boot
//! stack, and zeroed `.bss`.
//!
//! # Scope at Stage P1 (and what is deliberately staged later)
//!
//! P1 stands up the production aarch64 kernel *image*: the boot stub,
//! the Raspberry Pi 4 linker script (`aarch64-rpi4.ld`, load `0x8_0000`),
//! and this binary, with the aarch64 architecture port selected as the
//! kernel's arch (the single selection point).
//! On the boot CPU it enables FP/SIMD, brings up the console, constructs
//! the [`Aarch64Arch`] handle, records a boot audit line, and parks
//! fail-closed (never silently reset).
//!
//! The discovery-fed hand-off to [`tairix_kernel_core::kernel_main`] is
//! **staged**, not stubbed: bringing up the live allocator + scheduler
//! over the discovered map is `plans/PI.md` P4/P6 (fabricating a hardware
//! map would violate). Those stages add the QEMU
//! verticals that *prove* the runtime path.
//!
//! # P3: board-discovered interrupt controller + RAM window
//!
//! [`boot`] also points the GICv2 driver at the distributor / CPU-
//! interface bases the firmware tree describes
//! ([`tairix_arch_aarch64::gic::configure_from_fdt`]) — the QEMU `virt`
//! GICv2 or the Pi 4's GIC-400 — and reads the `/memory` window
//! (`first_memory_region`), so neither the interrupt-controller base nor
//! the RAM base is the `virt` assumption any longer. The byte-wise FDT
//! reader makes both walks MMU-off-safe (`plans/PI.md` W17); a missing or
//! malformed tree leaves the fail-safe `virt` defaults in place.
//!
//! # P2: board-discovered console
//!
//! Before logging, [`boot`] points the console at the UART the firmware
//! device tree describes ([`tairix_arch_aarch64::console::configure_from_fdt`]).
//! On the QEMU `virt` board this re-confirms the default PL011 base; on a
//! Raspberry Pi it selects the Pi's PL011 (or the BCM2835 AUX mini-UART)
//! at its high-peripheral base, so the boot line prints on real hardware
//! and under `-M raspi3b`. The FDT reader accesses the blob byte-wise, so
//! the walk is safe with the MMU still off (no multi-byte Device-memory
//! load — `plans/PI.md` W17). A missing or malformed tree leaves the
//! `virt` default in place (fail closed).

use alloc::boxed::Box;
use alloc::sync::Arc;
use alloc::vec::Vec;

use core::sync::atomic::{AtomicU64, AtomicU8};
use tairix_arch_aarch64::kernel_arch::{read_cntfrq, timer_frequency_hz, SecondaryStart};
use tairix_arch_aarch64::paging::{
    configure_device_gigapages, configure_kernel_gigapages, gigapage_mask_from_extents,
    identity_device_mask, install_boot_physmap, AddressSpace, PageTablePool, GIGAPAGE_MASK_WORDS,
};

use tairix_arch_aarch64::{
    console, enable_fp_el1, exceptions, fdt, firmware, gic, halt_current_cpu, paging, platform,
    serial, smp, syscall_entry, uart_init, video, Aarch64Arch, SERIAL_SINK,
};
use tairix_arch_api::{PlatformDiscovery, SchedulerArch, BOOT_CPU};
use tairix_fdt::Fdt;
use tairix_kernel_core::boot_audit_ring::{
    boot_audit_clock, BootAuditRing, BOOT_AUDIT_RING_CAPACITY,
};
use tairix_kernel_core::{kernel_main, BootInfo};
use tairix_kernel_sched_api::SchedulerConfig;
use tairix_log::{log, Event, EventId, Field, Level, Sink, TeeSink};

use tairix_arch_aarch64::irqmask::DaifIrqControl;
use tairix_util::fmt::{format_hex_u64, format_u64};

use crate::aarch64::arch_wrapper::{console_layout, Aarch64BinArch};
use crate::aarch64::dispatch::{
    production_dispatch, production_user_fault, production_user_fault_terminate, DISPATCH_SLOT,
};
use crate::mem_map::{build_memory_map, region_byte_totals};

// `KERNEL_BUILD_ID: &str` — the source + build identity, generated by
// `build.rs` and logged once on the boot line so a serial capture proves
// which build is running (measure, don't guess).
include!(concat!(env!("OUT_DIR"), "/build_id.rs"));

/// Number of 1 GiB identity gigapages the boot address space maps.
///
/// 512 covers the whole low canonical VA range (`[0, 512 GiB)`), so the
/// kernel image, stack, the firmware DTB, and the board MMIO window are
/// all reachable whatever their physical addresses — the QEMU `virt`
/// board (RAM at `0x4000_0000`, GIC/PL011 in the first GiB) and the
/// Raspberry Pi 4 (RAM at `0`, MMIO in gigapage 3) alike, with no
/// `cfg(board)` fork.
/// [`AddressSpace::new_identity_gigapages`] maps the gigapages holding
/// the *discovered* console/GIC MMIO Device and the rest — the kernel's
/// own image included — Normal, per the [`configure_device_gigapages`]
/// mask [`boot`] derives before enabling the MMU.
const IDENTITY_GIGABYTES: usize = 512;

/// Boot-time page-table frame source for the stage-1 identity map: one
/// frame, since a single root L1 table holds all 512 gigapage block
/// descriptors.
///
/// It lives in `.bss` for the lifetime of the kernel image, so `TTBR0_EL1`
/// keeps pointing at a valid table after [`enable_mmu_and_vectors`]
/// returns even though the transient [`AddressSpace`] handle is dropped
/// (the pool is monotonic and never freed). The real per-process page
/// tables are built over the `kernel/mem` frame allocator at a later
/// stage.
static BOOT_PAGE_TABLES: PageTablePool<1> = PageTablePool::new();

/// Audit event: the aarch64 production kernel reached its Stage-P1 boot
/// init point. Sits in the `kernel/core`-owned `4000..5000` range (per
/// `lib/log`'s subsystem ranges), just below the x86_64 boot pipeline's
/// `4098`/`4099`; the id is part of the audit contract and may not be
/// renumbered.
const KERNEL_BOOT_AARCH64_REACHED: EventId = EventId(4097);

/// Audit event: the boot path discovered the BCM2711 PCIe root complex
/// (the VL805 USB host's parent bridge) and recorded its address windows
/// for the keyboard-service bring-up. Logged once, post-MMU, so a metal
/// capture shows the discovered chipset windows the in-kernel USB chain
/// will program — the first half of "what hardware did we find" when a
/// keyboard is silent. Sits in the `kernel/core`-owned `4000..5000` range,
/// clear of the boot-reached id above and the x86_64 pipeline's
/// `4098`/`4099`; the id is part of the audit contract and may not be
/// renumbered.
const KERNEL_PCIE_DISCOVERED: EventId = EventId(4100);

/// Audit event: the boot path asked the `VideoCore` firmware to run the ARM
/// cores at their full rate, before anything else ran. Logged once, post-MMU,
/// so a metal capture states the speed the rest of boot actually ran at — the
/// firmware leaves the clock at `arm_freq_min` until something asks, and a
/// board silently stuck there is otherwise only visible as everything being
/// slow. Sits in the `kernel/core`-owned `4000..5000` range, clear of the ids
/// above; the id is part of the audit contract and may not be renumbered.
const KERNEL_CPU_CLOCK_RAISED: EventId = EventId(4101);

/// Audit event: a started secondary CPU left the kernel dispatch loop
/// (hand-off refused or scheduler stopped) and is parking fail-closed.
/// Sits in the `kernel/core`-owned `4000..5000` range, clear of the ids
/// above and of `kernel/core`'s own `40xx` block; the id is part of the
/// audit contract and may not be renumbered.
const KERNEL_SECONDARY_PARKED: EventId = EventId(4102);

/// Stable `"true"`/`"false"` audit-field value for a boolean condition.
/// Keeping the boot log to `&'static str` fields means the path takes no
/// allocation and cannot panic.
const fn yes_no(value: bool) -> &'static str {
    if value {
        "true"
    } else {
        "false"
    }
}

extern "C" {
    /// First byte of the kernel image — the board load address — defined
    /// by the board linker script (`aarch64-rpi4.ld` / `aarch64-virt.ld`).
    /// With [`__kernel_end`] it brackets the image extent whose identity
    /// gigapages must stay Normal (executable) whatever the discovered
    /// MMIO layout says ([`identity_device_mask`]).
    static __kernel_start: u8;
    /// One byte past the end of the kernel image, including the boot heap,
    /// defined by the board linker script (`aarch64-rpi4.ld` /
    /// `aarch64-virt.ld`). The usable physical-memory region the allocator
    /// receives begins at the next page boundary after this address.
    static __kernel_end: u8;
}

/// Address of the linker-provided `__kernel_start` symbol.
pub(crate) fn kernel_start_addr() -> u64 {
    // `addr_of!` reads the marker's address without forming a reference to
    // the zero-sized, never-dereferenced symbol.
    core::ptr::addr_of!(__kernel_start) as u64
}

/// Address of the linker-provided `__kernel_end` symbol.
fn kernel_end_addr() -> u64 {
    // `addr_of!` reads the marker's address without forming a reference to
    // the zero-sized, never-dereferenced symbol.
    core::ptr::addr_of!(__kernel_end) as u64
}

/// Enable the stage-1 identity MMU and install the EL1 exception
/// vectors on the boot CPU, returning the live boot [`AddressSpace`].
///
/// Returns `None` (leaving the MMU off) when the boot page-table pool
/// cannot satisfy the identity map — a fail-closed signal the caller
/// logs and parks on rather than running `kernel_main` over un-cacheable
/// Device memory.
///
/// The handle is returned, not dropped: it still owns `TTBR0_EL1`'s root
/// table ([`BOOT_PAGE_TABLES`]), which lives for the kernel's lifetime.
fn enable_mmu_and_vectors() -> Option<AddressSpace> {
    let space = AddressSpace::new_identity_gigapages(&BOOT_PAGE_TABLES, IDENTITY_GIGABYTES)?;
    // The tables were just written with the data cache off; sweep them
    // to the point of coherency so the walker's first *cacheable* reads
    // cannot hit stale firmware-era lines on real silicon.
    BOOT_PAGE_TABLES.clean_invalidate_to_poc();
    // SAFETY: `new_identity_gigapages` identity-maps every gigapage in
    // the configured Device and kernel-extent masks — the caller installed
    // both before this runs, and the kernel-extent mask is built over the
    // kernel image's own extent, the firmware DTB, and the scan-out
    // surface — so the currently-executing `pc`, the boot
    // stack, the firmware DTB, and the board MMIO window all keep their
    // physical addresses: enabling the MMU does not move the ground
    // under the running code, exactly as `AddressSpace::switch`'s
    // contract requires (unbacked gigapages are deliberately left
    // invalid so speculation cannot wander into them). `init_vectors`
    // then installs the EL1 vector base so a fault during the remaining
    // bring-up is taken to a handler rather than locking up silently.
    // Both run once, here, on the boot CPU with interrupts masked.
    unsafe {
        space.switch();
    }
    // SAFETY: covered by the block comment above — vectors are installed
    // once, on the boot CPU, immediately after the switch.
    unsafe {
        exceptions::init_vectors();
    }
    Some(space)
}

/// The retained, tail-able in-memory boot audit ring for this port.
///
/// Composed into the boot audit channel through [`AUDIT_SINK`], so every
/// audit record the kernel emits from the earliest boot onward is teed into
/// it and can be read back non-destructively — the store the pre-boot
/// Supervisor's `log` command tails (`plans/NEW-SUPERVISOR.md`). It is
/// guarded by the aarch64 [`DaifIrqControl`], so a record copy masks this
/// CPU's interrupts for its short, allocation-free duration and the ring is
/// safe to write from an interrupt handler that logs. It stamps each record
/// with the kernel's monotonic since-boot clock ([`boot_audit_clock`]).
pub static BOOT_AUDIT_RING: BootAuditRing<BOOT_AUDIT_RING_CAPACITY, DaifIrqControl> =
    BootAuditRing::new(boot_audit_clock);

/// The production boot **audit** channel: a fan-out delivering each record to
/// both the PL011 serial console ([`SERIAL_SINK`]) and the retained
/// [`BOOT_AUDIT_RING`].
///
/// `main.rs` passes this as [`BootInfo`]'s audit sink for the production
/// binary; the QEMU boot verticals substitute their own audit sink through
/// [`boot`] directly, so retaining the trail is a production-only wiring and
/// never disturbs a test's audit interception.
pub static AUDIT_SINK: TeeSink<'static, 2> = TeeSink::new([&SERIAL_SINK, &BOOT_AUDIT_RING]);

/// Boot the aarch64 kernel on the boot CPU and hand off to
/// [`tairix_kernel_core::kernel_main`].
///
/// `dtb` is the device-tree pointer the firmware/loader handed the boot
/// CPU (preserved verbatim by `boot.s`); it is parsed for the console
/// base, the GICv2/GIC-400 bases, the `/memory` window, the generic-timer
/// rate, and the PSCI conduit.
///
/// `log_sink` / `audit_sink` are the `&'static` sinks installed in the
/// [`BootInfo`]: in production both are the port's PL011-backed
/// [`tairix_arch_aarch64::SERIAL_SINK`]; the boot-completed QEMU vertical
/// substitutes an audit sink that exits QEMU on `AuditEvent::BootCompleted`.
///
/// `log_level` is the initial global log filter `kernel_main` installs
/// (`BootInfo::log_level`). Production passes [`Level::Info`]; an audit
/// observer vertical that must see the `Debug`-level allow records (e.g.
/// `SyscallInvoked`, `EventId(5000)`) passes [`Level::Debug`].
///
/// `hw_tree` is the [`HwTreeSource`] the `hw_tree_read` / `hw_tree_wait`
/// syscalls serve. In production it is the authoritative
/// [`crate::hwtree_store::HW_TREE_SOURCE`]; it is injected here — the same
/// dependency-injection seam the `log_sink`/`audit_sink` use — so the
/// device-manager reactive vertical can install a source that observes
/// `devmgr`'s own read/wait activity and drives its proof deterministically
/// off it, without a compiled-in test back-channel. Only the aarch64 port
/// takes this seam: it is the only one whose reactive-observe vertical needs
/// it, so adding it to the other ports would be an unused parameter.
///
/// Returns the bottom type. On success it enters
/// [`tairix_kernel_core::kernel_main`], which drives the init phases and
/// itself never returns. If the handover cannot be assembled (no usable
/// `/memory` window, the MMU could not be enabled, an unusable timer, or
/// `BootInfo::validate` rejects the hand-off) it records the boot line
/// and parks the CPU forever via [`halt_current_cpu`] (fail closed).
///
/// # SAFETY-INVARIANT
///
/// Called exactly once, on the boot CPU, from the arch trampoline after
/// `boot.s`'s invariants hold (EL1, interrupts masked, stack established,
/// `.bss` zeroed). FP/SIMD is enabled here before any code that the
/// compiler may lower to NEON runs.
pub fn boot(
    dtb: u64,
    heap: &'static tairix_kalloc::FreeListAllocator,
    log_sink: &'static (dyn Sink + Sync),
    audit_sink: &'static (dyn Sink + Sync),
    log_level: Level,
    hw_tree: &'static (dyn tairix_kernel_core::HwTreeSource + 'static),
) -> ! {
    // Enable FP/SIMD before the log formatter (which the compiler may
    // lower to NEON) runs. SAFETY: this is the boot CPU, called once,
    // before any FP/SIMD instruction executes (see `enable_fp_el1`).
    unsafe {
        enable_fp_el1();
    }

    // Make every kernel heap's lock interrupt-safe before anything can be
    // interrupted while holding one: install this port's per-CPU DAIF
    // mask/restore. Done here, at boot entry — before the first heap
    // allocation, before interrupts are ever enabled, and before any
    // secondary CPU is started — so no interrupt can ever fire on a CPU
    // mid-allocation and reenter the allocator, spinning forever on the lock
    // its own interrupted mainline holds (a single-CPU self-deadlock). One
    // install covers every core and every heap the binary holds: the hooks
    // mask the *current* CPU's interrupts and are read by the allocator
    // itself, so a heap the boot handover never names is covered too. It
    // stores two `fn` pointers and does not allocate, so it is safe before
    // the heap has grown.
    tairix_kalloc::install_irq_control(
        crate::aarch64::gic_irq::kalloc_irq_disable,
        crate::aarch64::gic_irq::kalloc_irq_restore,
    );

    // P2 + P3: discover the board's MMIO and type the identity map's
    // gigapages from it, both before translation is enabled.
    let (early, device_mask) = configure_identity_typing(dtb);

    // P6c-2: enable the stage-1 identity MMU and EL1 vectors before any
    // further work. The `kernel_core` allocator and scheduler use atomic
    // read-modify-write instructions, which are UNPREDICTABLE on the
    // MMU-off Device-typed memory the boot CPU may run on; the identity
    // map makes RAM Normal/cacheable so they behave (`plans/PI.md`
    // P6c-2). It also makes the full-tree FDT walks below
    // (`first_memory_region`) safe, which fault MMU-off under release
    // optimisation (`plans/PI.md` watch-out).
    //
    // This is the boot's sharpest cliff: enabling translation against a
    // mis-typed identity map wedged the metal Pi 4B the instant the MMU
    // came on.
    let boot_space = enable_mmu_and_vectors();
    let mmu_on = boot_space.is_some();

    // Route a fatal EL1 (kernel-mode) exception into the one fatal-report
    // path, now that the vectors above can deliver one and before any
    // further work can fault. With the slot empty the vector parks the CPU
    // with every interrupt masked and prints nothing, so a kernel fault
    // becomes a mute machine — and, if it lands inside a lock's critical
    // section, a system-wide deadlock behind the guard it never dropped.
    //
    // The slot is set-once and this call never overrides an occupant: a
    // QEMU vertical that observes its own deliberate faults publishes its
    // handler ahead of `boot` and keeps it, asserting its own install
    // succeeded. Either way the machine has exactly one fatal policy.
    let _ = crate::aarch64::panic_ctx::install_kernel_fault_handler();

    // The screen grids need the heap the cacheable identity map just made
    // usable, so they are attached here rather than at display discovery.
    let video_console = mmu_on && attach_video_console_grids();

    if let Some(pcie) = early.pcie {
        log_pcie_discovery(log_sink, &pcie);
    }

    if early.cpu_clock_hz != 0 {
        let mut rate_buf = [0u8; 20];
        log(
            log_sink,
            &Event {
                level: Level::Info,
                id: KERNEL_CPU_CLOCK_RAISED,
                message: "aarch64: firmware asked to run the ARM cores at full rate for boot",
                fields: &[Field {
                    key: "rate_hz",
                    value: tairix_log::FieldValue::Str(format_u64(
                        early.cpu_clock_hz,
                        &mut rate_buf,
                    )),
                }],
            },
        );
    }

    // Discover the rest of the board from the firmware device tree: the
    // `/memory` window, the timer rate, and the PSCI conduit (P3 + P4 +
    // P5) — full-tree walks that need the MMU on. A null, unreadable, or
    // incomplete tree leaves the `virt` defaults in place (fail closed).
    let discovered = configure_from_dtb(dtb);
    let installed_memory_bytes = crate::mem_map::window_byte_total(&discovered.ram_windows);
    let (ram_windows, direct_map) =
        install_direct_physical_map(&discovered.ram_windows, &device_mask, log_sink);

    let (arch, cpu_mpidrs) = build_cpu_topology_and_arch(&discovered, dtb, mmu_on);
    let (arch, smp_start_method) = select_secondary_start(arch, &discovered, &cpu_mpidrs);

    // Sanity-check that the constructed handle reports the boot CPU, and
    // that the generic-timer frequency is usable. A zero frequency would
    // make the monotonic clock unusable.
    let boot_cpu_ok = arch.current_cpu() == BOOT_CPU;
    let timer_present = discovered.timer_hz != 0;

    // Stage the secondary bring-up (stacks + entry + the dense-id →
    // affinity table the spin-table trampoline recovers identity from)
    // before the hand-off: `kernel_main` issues the starts (PSCI
    // `CPU_ON` or spin-table release) once every init phase is green,
    // and each start is refused fail-closed (and audited) unless this
    // preparation succeeded. Single-CPU boots prepare nothing.
    let smp_prepared = mmu_on && prepare_secondary_bringup(&cpu_mpidrs);

    // P6c-1: translate the firmware-discovered `/memory` windows into the
    // canonical physical-memory map `kernel_core::kernel_main` consumes,
    // with the firmware blob reserved out of it.
    let layout_result = build_boot_memory_layout(&ram_windows, dtb, early.dtb_len);
    let (mem_status, usable_bytes, reserved_bytes) = match &layout_result {
        Ok(map) => {
            let (usable, reserved) = region_byte_totals(map);
            ("built", usable, reserved)
        }
        Err(status) => (*status, 0, 0),
    };
    let mem_map_built = layout_result.is_ok();

    let ready = boot_cpu_ok && timer_present && mem_map_built && mmu_on && direct_map;

    log_boot_line(
        log_sink,
        &BootStatus {
            level: if ready { Level::Info } else { Level::Warn },
            boot_cpu_ok: yes_no(boot_cpu_ok),
            timer_present: yes_no(timer_present),
            dtb_present: yes_no(dtb != 0),
            console_discovered: yes_no(early.console),
            gic_discovered: yes_no(early.gic),
            video_console: yes_no(video_console),
            fb_base: early.video.map_or(0, |v| v.fb_base),
            fb_len: early.video.map_or(0, |v| v.fb_len_bytes),
            boot_root: boot_space.as_ref().map_or(0, AddressSpace::root_phys),
            device_gigapages: device_mask[0],
            ram_discovered: yes_no(!ram_windows.is_empty()),
            mem_map_built: yes_no(mem_map_built),
            direct_map: yes_no(direct_map),
            mem_status,
            usable_bytes,
            reserved_bytes,
            timer_hz_from_tree: yes_no(discovered.timer_hz_from_tree),
            timer_hz: discovered.timer_hz,
            smp_start_method,
            cpu_count: cpu_mpidrs.len(),
            smp_prepared: yes_no(smp_prepared),
            mmu_enabled: yes_no(mmu_on),
        },
    );

    // Hand off to the architecture-neutral kernel core when the handover
    // is sound; otherwise park fail-closed. The map is
    // moved into `BootInfo` here, so it is built exactly once.
    if ready {
        if let Ok(map) = layout_result {
            // Record the discovered tree and the root block binding before
            // entering the core. The early-discovered video facts ride along
            // so the boot display joins the same tree (`plans/DISPLAY.md` D7d).
            audit_root_storage_binding(dtb, early.video, log_sink);
            enter_kernel_core(
                arch,
                BootMemory {
                    map,
                    installed_bytes: installed_memory_bytes,
                },
                heap,
                log_sink,
                audit_sink,
                log_level,
                hw_tree,
            )
        }
    }

    // The handover was rejected (see the boot-log line's fields for which
    // check failed); park fail-closed.
    halt_current_cpu()
}

/// Point the console and the GICv2 driver at the bases the firmware tree
/// describes, then install the identity window's Device and kernel-extent
/// gigapage typing derived from them; returns the discovery and the Device
/// mask.
///
/// Runs entirely pre-MMU, and must: the discovered bases decide which
/// gigapages the map types Device, and on the Pi 4 the PL011/GIC-400 live
/// in gigapage 3 while the kernel image at `0x8_0000` must keep gigapage 0
/// Normal — executable — or the instruction fetch after `switch` faults
/// with the vectors not yet installed. Every other non-Device gigapage
/// stays *invalid*: on real silicon a Normal write-back executable mapping
/// of unbacked address space invites speculative fetches into windows
/// nothing answers, which wedged the metal Pi 4B at the instant
/// translation enabled while QEMU (which answers every address) stayed
/// green. A null, unreadable, or incomplete tree leaves the `virt`
/// defaults in place (fail closed); a facility with no discovered base
/// contributes the console base as a harmless duplicate input.
fn configure_identity_typing(dtb: u64) -> (EarlyDiscovered, [u64; GIGAPAGE_MASK_WORDS]) {
    let early = configure_mmio_from_dtb(dtb);
    let (console_base, _) = console::current();
    let (distributor_base, cpu_interface_base) = gic::current();
    let video_doorbell = early.video.map_or(console_base as u64, |v| v.doorbell_base);
    // The BCM2711 PCIe root complex's register block and outbound window
    // (where the enumerated VL805 BAR lives) are mapped by the autoloaded
    // user-space bus driver, so they must be typed Device like the UART/GIC.
    let (pcie_regs, pcie_outbound) = early
        .pcie
        .map_or((console_base as u64, console_base as u64), |p| {
            (p.regs_phys, p.outbound_cpu_base)
        });
    let device_mask = identity_device_mask(
        &[
            console_base as u64,
            distributor_base as u64,
            cpu_interface_base as u64,
            video_doorbell,
            pcie_regs,
            pcie_outbound,
        ],
        kernel_start_addr(),
        kernel_end_addr(),
    );
    configure_device_gigapages(device_mask);
    let (fb_base, fb_len) = early.video.map_or((0, 0), |v| (v.fb_base, v.fb_len_bytes));
    // Exactly what the kernel addresses *physically* — its own image and
    // boot heap, the firmware tree, the scan-out surface. Allocator RAM is
    // deliberately absent: it is reached through the direct physical map in
    // the kernel regime, so a process root carries no mapping of RAM in the
    // half user code addresses.
    configure_kernel_gigapages(gigapage_mask_from_extents(&[
        (
            kernel_start_addr(),
            kernel_end_addr().saturating_sub(kernel_start_addr()),
        ),
        (dtb, early.dtb_len),
        (fb_base, fb_len),
    ]));
    (early, device_mask)
}

/// Attach the framebuffer console's primary and alternate character-cell
/// grids, sized to the discovered geometry and leaked for the kernel's
/// lifetime.
///
/// Callable only once the MMU is on: the grids need the heap, which needs
/// the cacheable identity map. Reports whether the screen actually took the
/// console: with no display discovered, or a scan-out the active root does
/// not cover, the UART keeps it (fail closed) and the boot record says so
/// rather than claiming a console the machine never had.
fn attach_video_console_grids() -> bool {
    let Some(cells) = video::text_cell_count() else {
        return false;
    };
    let main = alloc::vec![video::Cell::BLANK; cells].into_boxed_slice();
    let alt = alloc::vec![video::Cell::BLANK; cells].into_boxed_slice();
    video::attach_console(Box::leak(main), Box::leak(alt))
}

/// Record the discovered PCIe root-complex windows once, post-MMU.
///
/// Purely a metal diagnostic: the windows themselves reach the autoloaded
/// user-space bus driver as resource grants on the discovered
/// `brcm,bcm2711-pcie` hardware-tree node, not through any kernel-side
/// stash (`plans/PI.md` P10 D5d). A capture then shows which register
/// block and inbound/outbound apertures were found, so a silent keyboard
/// can be bisected against the hardware actually present rather than
/// guessed at. Allocation-free hex rendering on the caller's stack.
fn log_pcie_discovery(log_sink: &'static (dyn Sink + Sync), pcie: &platform::PcieDiscovery) {
    let mut regs_base_buf = [0u8; 16];
    let mut regs_len_buf = [0u8; 16];
    let mut aperture_top_buf = [0u8; 16];
    let mut inbound_size_buf = [0u8; 16];
    let mut inbound_pcie_buf = [0u8; 16];
    let mut outbound_cpu_buf = [0u8; 16];
    let mut outbound_pcie_buf = [0u8; 16];
    let mut outbound_size_buf = [0u8; 16];
    log(
        log_sink,
        &Event {
            level: Level::Info,
            id: KERNEL_PCIE_DISCOVERED,
            message: "aarch64: discovered brcm,bcm2711-pcie root complex (vl805 usb host bridge)",
            fields: &[
                Field {
                    key: "regs_base_hex",
                    value: tairix_log::FieldValue::Str(format_hex_u64(
                        pcie.regs_phys,
                        &mut regs_base_buf,
                    )),
                },
                Field {
                    key: "regs_len_hex",
                    value: tairix_log::FieldValue::Str(format_hex_u64(
                        pcie.regs_len,
                        &mut regs_len_buf,
                    )),
                },
                Field {
                    key: "dma_aperture_top_hex",
                    value: tairix_log::FieldValue::Str(format_hex_u64(
                        pcie.dma_aperture_top,
                        &mut aperture_top_buf,
                    )),
                },
                Field {
                    key: "inbound_size_hex",
                    value: tairix_log::FieldValue::Str(format_hex_u64(
                        pcie.inbound_size,
                        &mut inbound_size_buf,
                    )),
                },
                Field {
                    key: "inbound_pcie_base_hex",
                    value: tairix_log::FieldValue::Str(format_hex_u64(
                        pcie.inbound_pcie_base,
                        &mut inbound_pcie_buf,
                    )),
                },
                Field {
                    key: "outbound_cpu_base_hex",
                    value: tairix_log::FieldValue::Str(format_hex_u64(
                        pcie.outbound_cpu_base,
                        &mut outbound_cpu_buf,
                    )),
                },
                Field {
                    key: "outbound_pcie_base_hex",
                    value: tairix_log::FieldValue::Str(format_hex_u64(
                        pcie.outbound_pcie_base,
                        &mut outbound_pcie_buf,
                    )),
                },
                Field {
                    key: "outbound_size_hex",
                    value: tairix_log::FieldValue::Str(format_hex_u64(
                        pcie.outbound_size,
                        &mut outbound_size_buf,
                    )),
                },
            ],
        },
    );
}

/// Size the direct physical map from the post-MMU-discovered `/memory`
/// windows, install it into the kernel translation regime, and return the
/// windows the allocator may use.
///
/// The windows are first clipped out of Device-typed gigapages: memory is
/// typed at 1 GiB granularity and Device wins for a shared gigapage (the
/// Pi 4's below-4 GiB window ends inside the gigapage holding its
/// UART/GIC/PCIe), so RAM there would be mapped Device — atomics on it are
/// unpredictable — and must never reach the map or the allocator.
/// Reclaiming those bytes needs 2 MiB-granular typing (`plans/APPS.md` I4
/// follow-up).
///
/// The map has to be live before anything reaches a *frame* by pointer:
/// every later frame view — the RAM self-test, the page-table frame
/// source, the slab page supply, the spawn image write, the root-unlock
/// DMA pool — resolves through it. It costs no page tables (each covered
/// gigabyte is one block descriptor) and no slot of any process root,
/// because it lives in the kernel regime every CPU carries permanently.
/// A zero-length window list, or a machine whose whole RAM lies in Device
/// gigapages, installs nothing and is reported to the caller, which refuses
/// the hand-off.
///
/// The boot record is written here rather than by the caller, so the one
/// place that sizes the map is the one place that states how wide it ended
/// up — a machine whose RAM outruns the architectural ceiling is visible in
/// the transcript rather than found later as a fail-closed allocation.
fn install_direct_physical_map(
    discovered_windows: &[(u64, u64)],
    device_mask: &[u64; GIGAPAGE_MASK_WORDS],
    log_sink: &'static (dyn Sink + Sync),
) -> (Vec<(u64, u64)>, bool) {
    let ram_windows = crate::mem_map::clip_windows_to_normal_ram(discovered_windows, device_mask);
    if ram_windows.is_empty() {
        return (ram_windows, false);
    }
    if !install_boot_physmap(&gigapage_mask_from_extents(&ram_windows)) {
        return (ram_windows, false);
    }
    // Every covered gigabyte is one L1 block descriptor, so the map costs
    // no page tables at all.
    crate::mem_map::log_direct_map(log_sink, paging::physmap_gigapages(), true);
    (ram_windows, true)
}

/// Build the [`Aarch64Arch`] handle — the single concrete-arch selection
/// point for the kernel image — and the dense `CpuId` → `MPIDR_EL1` map it
/// is sized from, then classify each core from the firmware tree.
///
/// Every per-CPU backing (the handle's slots, the preemption slices, the
/// secondary stacks, the scheduler's run queues) is sized from that one
/// validated list, exactly to the machine — no compile-time core ceiling.
/// A malformed `/cpus` list falls back closed to a single-CPU map; an
/// allocation failure or a topology wider than `CpuId` parks fail-closed.
/// The core-class walk (`capacity-dmips-mhz`) lets the scheduler place
/// background work on efficiency cores; a missing or malformed tree leaves
/// the homogeneous Performance default.
fn build_cpu_topology_and_arch(
    discovered: &Discovered,
    dtb: u64,
    mmu_on: bool,
) -> (Aarch64Arch, Vec<u64>) {
    let cpu_mpidrs =
        match crate::cpu_topology::order_cpus(&discovered.cpu_mpidrs, smp::current_affinity()) {
            Ok(cpus) => cpus,
            Err(crate::cpu_topology::CpuTopologyError::AllocationFailed) => {
                serial::beacon("pi-boot: CPU topology allocation FAILED, parking");
                halt_current_cpu()
            }
            Err(crate::cpu_topology::CpuTopologyError::TooManyCpus) => {
                serial::beacon("pi-boot: CPU topology exceeds CpuId, parking");
                halt_current_cpu()
            }
        };
    smp::install_current_cpu_index(BOOT_CPU);
    let arch = build_arch_handle(&cpu_mpidrs, discovered.timer_hz);
    if mmu_on && dtb != 0 {
        // SAFETY: `dtb` is the firmware pointer `Fdt::from_ptr` validated
        // for the pre-MMU walks (magic + `totalsize` bounds); the MMU is on,
        // so a whole-tree traversal is safe.
        if let Ok(fdt) = unsafe { Fdt::from_ptr(dtb as *const u8) } {
            arch.classify_from_fdt(&fdt);
            // The firmware boot seed is the only usable entropy source on an
            // emulated cortex-a72 (no `FEAT_RNG`, deterministic cycle
            // counter), so without it the CSPRNG would never seed. Input
            // material only, XOR-mixed and DRBG-conditioned kernel-side.
            if let Some(seed) = fdt.chosen_rng_seed() {
                tairix_kernel_core::random::capture_boot_entropy_seed(seed);
            }
            // CoreSight external debug is the one live observation a GIC-400
            // (secure-world FIQ) leaves reachable for a hard-wedged core
            // (`plans/WATCHDOG.md`). A base is installed only when its window
            // is *already* device-mapped, so a read on the lockup path can
            // never fault; with none discovered the sampler reports
            // `Unsupported` and the buddy detector runs unchanged.
            #[cfg(feature = "watchdog-diagnostics")]
            install_debug_component_bases(&fdt, &cpu_mpidrs);
        }
    }
    (arch, cpu_mpidrs)
}

/// Install the secondary-start mechanism the firmware tree declares
/// (`plans/PI.md` P5), never an assumed one (no `cfg(board)` fork).
///
/// A `/psci` node selects PSCI `CPU_ON` over its conduit (`hvc` at
/// EL2-hosted, `smc` at EL3-hosted — the Pi 4 with `armstub8.bin`); a
/// PSCI-less tree whose cpu nodes declare `enable-method = "spin-table"`
/// (the Pi 4's stock firmware) selects the spin-table release over the
/// declared per-CPU `cpu-release-addr` words, aligned to the dense ids. A
/// tree that declares neither leaves the mechanism unset, and bring-up
/// fails closed at the start site rather than guessing.
fn select_secondary_start(
    arch: Aarch64Arch,
    discovered: &Discovered,
    cpu_mpidrs: &[u64],
) -> (Aarch64Arch, &'static str) {
    if let Some(method) = discovered.psci_method {
        return (
            arch.with_secondary_start(SecondaryStart::Psci(method)),
            "psci",
        );
    }
    let Ok(release_addrs) =
        crate::cpu_topology::align_release_addrs(cpu_mpidrs, &discovered.cpu_spin_releases)
    else {
        serial::beacon("pi-boot: spin-table map allocation FAILED, parking");
        halt_current_cpu()
    };
    if release_addrs.iter().any(|&addr| addr != 0) {
        let release_addrs: &'static [u64] = Box::leak(release_addrs.into_boxed_slice());
        (
            arch.with_secondary_start(SecondaryStart::SpinTable { release_addrs }),
            "spin_table",
        )
    } else {
        (arch, "none")
    }
}

/// Translate the discovered RAM windows into the canonical physical-memory
/// map, with the firmware device-tree blob reserved out of it.
///
/// An absent or malformed discovery fails closed to a status string rather
/// than a panic. The blob must be reserved because the QEMU `virt`/Pi
/// firmware lands it high in RAM, above the kernel image the map already
/// reserves: left usable, the frame allocator or the early-boot RAM
/// self-test (which zeroes every usable byte) would clobber the tree the
/// later root-storage bind and device discovery re-parse. An absent tree
/// reserves nothing.
fn build_boot_memory_layout(
    ram_windows: &[(u64, u64)],
    dtb: u64,
    dtb_len: u64,
) -> Result<tairix_kernel_mem::BootMemoryMap, &'static str> {
    if ram_windows.is_empty() {
        return Err("no_memory_window");
    }
    let mut map = build_memory_map(ram_windows, kernel_end_addr())
        .map_err(crate::mem_map::MemoryMapError::as_str)?;
    crate::mem_map::reserve_blob_frames(&mut map, dtb, dtb_len);
    Ok(map)
}

/// The consolidated aarch64 boot line's report, rendered by [`boot`] so
/// the fields it logs are one record rather than a wall of arguments.
///
/// Each verdict is already the `yes`/`no` string it is logged as; the
/// numeric facts stay numbers and are hex-rendered into
/// [`log_boot_line`]'s own stack buffers.
struct BootStatus {
    /// `Info` on a sound hand-off, `Warn` when a check failed.
    level: Level,
    /// The constructed arch handle reports the boot CPU.
    boot_cpu_ok: &'static str,
    /// The generic-timer frequency is non-zero, so the monotonic clock is
    /// usable.
    timer_present: &'static str,
    /// Firmware handed over a device-tree pointer.
    dtb_present: &'static str,
    /// The direct physical map was sized from the discovered RAM and
    /// installed. Without it the kernel can reach no frame by pointer, so
    /// the hand-off is refused.
    direct_map: &'static str,
    /// A console UART was found in the tree.
    console_discovered: &'static str,
    /// A GICv2-class interrupt controller was found in the tree.
    gic_discovered: &'static str,
    /// The framebuffer boot console came up.
    video_console: &'static str,
    /// Physical base and byte length of the firmware scan-out, or zeros when
    /// no display came up.
    ///
    /// The console paints this range from arbitrary kernel contexts, so it
    /// must be translatable under whichever root is active. A capture that
    /// shows a fault address inside it says the scan-out was never mapped in
    /// that root; one past its end says a repaint overran
    /// (`plans/OPEN-DEFECTS.md` D81).
    fb_base: u64,
    /// Byte length of the scan-out named by [`Self::fb_base`].
    fb_len: u64,
    /// Physical root of the boot translation regime, or zero when the MMU
    /// stayed off.
    ///
    /// A fatal report names the root that was active (`root=`); comparing it
    /// against this says whether the faulting context was on the boot space
    /// or on some other root, which the address alone cannot distinguish —
    /// the boot tables are a `.bss` static, so their address is
    /// indistinguishable by magnitude from a frame-allocated one
    /// (`plans/OPEN-DEFECTS.md` D81).
    boot_root: u64,
    /// Low word of the Device gigapage mask (gigapages 0..64 — both
    /// supported boards keep their MMIO below 64 GiB), so a metal capture
    /// shows what the identity map typed Device (`virt`: 0x1; Pi 4: 0x8).
    device_gigapages: u64,
    /// At least one usable `/memory` window survived the Device clip.
    ram_discovered: &'static str,
    /// The physical-memory map was built.
    mem_map_built: &'static str,
    /// Stable cause string when it was not.
    mem_status: &'static str,
    /// Usable bytes in the built map.
    usable_bytes: u64,
    /// Reserved bytes in the built map.
    reserved_bytes: u64,
    /// The counter rate came from the tree rather than `CNTFRQ_EL0`.
    timer_hz_from_tree: &'static str,
    /// The generic-timer counter rate every `busy_delay_us` settle is
    /// measured against. A value far from the board crystal (the Pi 4's
    /// 54 MHz = `0x337_f980`) means firmware mis-programmed `CNTFRQ_EL0`,
    /// which stretches every bring-up settle proportionally.
    timer_hz: u64,
    /// Which secondary-start mechanism the tree selected.
    smp_start_method: &'static str,
    /// Dense CPU count every per-CPU structure was sized from.
    cpu_count: usize,
    /// Secondary bring-up staged successfully.
    smp_prepared: &'static str,
    /// Stage-1 translation is on.
    mmu_enabled: &'static str,
}

/// Emit the one consolidated aarch64 boot line.
///
/// Allocation-free: every numeric field is hex-rendered into a stack
/// buffer that outlives the borrowed `fields` slice.
fn log_boot_line(log_sink: &'static (dyn Sink + Sync), status: &BootStatus) {
    let mut usable_buf = [0u8; 16];
    let mut reserved_buf = [0u8; 16];
    let mut device_mask_buf = [0u8; 16];
    let mut timer_hz_buf = [0u8; 16];
    let mut cpu_count_buf = [0u8; 12];
    let mut fb_base_buf = [0u8; 16];
    let mut fb_len_buf = [0u8; 16];
    let mut boot_root_buf = [0u8; 16];
    // Every field of this line is a string, so they are listed as pairs
    // and mapped into the borrowed slice `log` renders.
    let pairs = [
        ("boot_cpu_ok", status.boot_cpu_ok),
        ("timer_present", status.timer_present),
        ("dtb_present", status.dtb_present),
        ("console_discovered", status.console_discovered),
        ("gic_discovered", status.gic_discovered),
        ("video_console", status.video_console),
        (
            "fb_base_hex",
            format_hex_u64(status.fb_base, &mut fb_base_buf),
        ),
        ("fb_len_hex", format_hex_u64(status.fb_len, &mut fb_len_buf)),
        (
            "boot_root_hex",
            format_hex_u64(status.boot_root, &mut boot_root_buf),
        ),
        (
            "device_gigapages_hex",
            format_hex_u64(status.device_gigapages, &mut device_mask_buf),
        ),
        ("ram_discovered", status.ram_discovered),
        ("mem_map_built", status.mem_map_built),
        ("mem_map_status", status.mem_status),
        (
            "usable_bytes_hex",
            format_hex_u64(status.usable_bytes, &mut usable_buf),
        ),
        (
            "reserved_bytes_hex",
            format_hex_u64(status.reserved_bytes, &mut reserved_buf),
        ),
        ("timer_hz_from_tree", status.timer_hz_from_tree),
        (
            "timer_hz_hex",
            format_hex_u64(status.timer_hz, &mut timer_hz_buf),
        ),
        ("smp_start_method", status.smp_start_method),
        (
            "cpu_count",
            tairix_util::fmt::format_usize(status.cpu_count, &mut cpu_count_buf),
        ),
        ("smp_prepared", status.smp_prepared),
        ("mmu_enabled", status.mmu_enabled),
        ("direct_map", status.direct_map),
        ("next_stage", "pi_p6c3_spawn_init_el0"),
        ("build_id", KERNEL_BUILD_ID),
    ];
    let fields = pairs.map(|(key, value)| Field {
        key,
        value: tairix_log::FieldValue::Str(value),
    });
    log(
        log_sink,
        &Event {
            level: status.level,
            id: KERNEL_BOOT_AARCH64_REACHED,
            message: "tairix-kernel aarch64 (raspberry pi 4): reached stage-p1 boot init point",
            fields: &fields,
        },
    );
}

/// Leak a zeroed `&'static [AtomicU64]` of `count` slots for the arch
/// handle's per-CPU bookkeeping, alive for the kernel's lifetime like
/// the leaked console grids.
fn leak_u64_slots(count: usize) -> Option<&'static [AtomicU64]> {
    let mut slots = Vec::new();
    slots.try_reserve_exact(count).ok()?;
    slots.resize_with(count, || AtomicU64::new(0));
    Some(Box::leak(slots.into_boxed_slice()))
}

/// Leak a zeroed `&'static [AtomicU8]` of `count` slots (the per-CPU
/// core-class table).
fn leak_u8_slots(count: usize) -> Option<&'static [AtomicU8]> {
    let mut slots = Vec::new();
    slots.try_reserve_exact(count).ok()?;
    slots.resize_with(count, || AtomicU8::new(0));
    Some(Box::leak(slots.into_boxed_slice()))
}

/// Build the [`Aarch64Arch`] handle over leaked per-CPU slices sized
/// exactly to the validated dense CPU map.
///
/// `cpu_mpidrs` comes from [`crate::cpu_topology::order_cpus`], which
/// guarantees a non-empty list with the running boot core at dense id
/// 0 — the only ways `with_cpu_slices` can refuse are therefore
/// programmer errors, on which the boot parks fail-closed with a serial
/// beacon rather than continuing over per-CPU state of the wrong shape.
fn build_arch_handle(cpu_mpidrs: &[u64], counter_hz: u64) -> Aarch64Arch {
    let count = cpu_mpidrs.len();
    let Some(cpu_to_mpidr) = leak_u64_slots(count) else {
        serial::beacon("pi-boot: CPU affinity slots allocation FAILED, parking");
        halt_current_cpu()
    };
    let Some(host_ipi_count) = leak_u64_slots(count) else {
        serial::beacon("pi-boot: IPI counter slots allocation FAILED, parking");
        halt_current_cpu()
    };
    let Some(core_classes) = leak_u8_slots(count) else {
        serial::beacon("pi-boot: core-class slots allocation FAILED, parking");
        halt_current_cpu()
    };
    Aarch64Arch::with_cpu_slices(
        cpu_to_mpidr,
        host_ipi_count,
        core_classes,
        BOOT_CPU,
        counter_hz,
        cpu_mpidrs,
    )
    .unwrap_or_else(|| {
        serial::beacon("pi-boot: arch handle construction FAILED, parking");
        halt_current_cpu()
    })
}

/// Leak a zeroed secondary-stack region of `count` slots (one per dense
/// CPU id; slot 0 belongs to the never-started boot CPU).
///
/// Zeroed in place in the heap — never built on the boot stack, whose
/// budget a 64 KiB-per-slot array would blow — and leaked for the kernel's
/// lifetime, exactly as the `smp.s` trampoline requires. An out-of-memory
/// boot heap parks fail-closed: without stacks no secondary may ever be
/// started.
fn leak_zeroed_secondary_stacks(count: usize) -> &'static [smp::SecondaryStack] {
    // Reserving as `Vec<SecondaryStack>` makes the block's 16-byte stack
    // alignment a property of the allocation itself rather than of a
    // byte-pointer cast, and keeps the out-of-memory path a value.
    let mut stacks: Vec<smp::SecondaryStack> = Vec::new();
    if stacks.try_reserve_exact(count).is_err() {
        serial::beacon("pi-boot: secondary stack allocation FAILED, parking");
        halt_current_cpu()
    }
    let spare = stacks.spare_capacity_mut();
    let spare_bytes = core::mem::size_of_val(spare);
    let spare_start = spare.as_mut_ptr().cast::<u8>();
    // SAFETY: `spare_start`/`spare_bytes` describe exactly `stacks`' own
    // uninitialised capacity, which the reservation above made at least
    // `count` slots long; all-zero is a valid `SecondaryStack` (a plain byte
    // array), so writing zeros over it initialises every slot `set_len`
    // then exposes. Zeroing in place never materialises a 64 KiB value on
    // the boot stack, whose budget that would blow.
    unsafe {
        core::ptr::write_bytes(spare_start, 0, spare_bytes);
        stacks.set_len(count);
    }
    // Leaked, not boxed: the `smp.s` trampoline reads the region with the
    // MMU off for the kernel's lifetime, and leaking the reservation as-is
    // avoids a shrink-to-fit copy of the whole stack pool.
    Vec::leak(stacks)
}

/// Stage the multi-core bring-up: size and publish the secondary stack
/// region, publish the dense-id → affinity table (the identity source a
/// spin-table-released core recovers its dense id from), and install
/// the production secondary entry, so the starts `kernel_main` issues
/// later — PSCI `CPU_ON` or spin-table release — find everything in
/// place.
///
/// `cpu_mpidrs` is the validated dense map from
/// [`crate::cpu_topology::order_cpus`] (entry `i` is dense id `i`'s
/// affinity). Returns `true` when the machine is ready to start
/// secondaries (or is single-CPU, where there is nothing to prepare).
/// Every install is set-once per boot and this is their only production
/// call site, so a refusal is a programmer error; it is reported
/// (`false` → the boot line's `smp_prepared` field) and every later
/// start fails closed and audited rather than releasing a core into a
/// half-published hand-off.
fn prepare_secondary_bringup(cpu_mpidrs: &[u64]) -> bool {
    let cpu_count = cpu_mpidrs.len();
    if cpu_count <= 1 {
        return true;
    }
    let stacks = leak_zeroed_secondary_stacks(cpu_count);
    if smp::register_secondary_stacks(stacks).is_err() {
        return false;
    }
    let mut affinities = Vec::new();
    if affinities.try_reserve_exact(cpu_count).is_err() {
        return false;
    }
    affinities.extend_from_slice(cpu_mpidrs);
    let affinities: &'static [u64] = Box::leak(affinities.into_boxed_slice());
    if smp::register_secondary_affinities(affinities).is_err() {
        return false;
    }
    smp::set_secondary_entry(production_secondary_entry).is_ok()
}

/// Discover each CPU's CoreSight external-debug component base from the
/// firmware tree and install the per-CPU registry the lockup watchdog's
/// cross-core PC sampler reads ([`tairix_arch_aarch64::coresight`]).
///
/// Runs post-MMU (it walks the whole tree) with the dense `cpu_mpidrs` map
/// and the device-gigapage mask already resolved. A discovered base is
/// installed **only** when its window sits in an already-Device-mapped
/// gigapage, so a read on the lockup path can never fault; a component in
/// an unmapped gigapage — or a tree that describes no debug components
/// (QEMU `virt`, the stock Pi 4 firmware DTB) — installs nothing, and the
/// sampler reports `Unsupported` (fail closed, the buddy detector runs
/// unchanged). Allocation failure or a table with no reachable component is
/// a silent no-op — a diagnostic aid never aborts the boot.
#[cfg(feature = "watchdog-diagnostics")]
fn install_debug_component_bases(fdt: &Fdt<'_>, cpu_mpidrs: &[u64]) {
    use tairix_arch_aarch64::coresight;
    use tairix_arch_aarch64::paging::{device_gigapages, gigapage_is_device};

    let mut bases = Vec::new();
    if bases.try_reserve_exact(cpu_mpidrs.len()).is_err() {
        return;
    }
    bases.resize(cpu_mpidrs.len(), coresight::NO_BASE);
    fdt::debug_component_bases(fdt, cpu_mpidrs, &mut bases);

    // Only keep a base whose gigapage is already Device-typed in the live
    // identity map; a component elsewhere is dropped rather than read
    // through an unmapped (or Normal, cacheable) window.
    let mask = device_gigapages();
    for base in &mut bases {
        if *base == coresight::NO_BASE {
            continue;
        }
        let gigapage = *base >> 30;
        if !gigapage_is_device(&mask, gigapage) {
            *base = coresight::NO_BASE;
        }
    }

    if bases.iter().any(|&b| b != coresight::NO_BASE) {
        let bases: &'static [usize] = Box::leak(bases.into_boxed_slice());
        coresight::install_debug_bases(bases);
    }
}

/// The entry every started secondary core runs (via the `smp.s`
/// trampoline): per-CPU hardware init, then join the live kernel's
/// dispatch loop.
///
/// Ordering is load-bearing:
///
/// 1. FP/SIMD on, before any code the compiler may lower to NEON.
/// 2. Adopt the boot identity map — the very first memory-system act,
///    while this core has performed no atomic read-modify-write (LDXR/
///    STXR exclusives are unreliable on MMU-off Device-typed DRAM).
/// 3. EL1 vectors + GICv2 CPU interface + per-CPU preemption/IPI arming
///    — each banked or per-core state that must be programmed on the
///    core that uses it.
/// 4. [`tairix_kernel_core::run_secondary`], which audits the arrival
///    and dispatches until the kernel stops.
///
/// The kernel-core hand-off was published before this core's `CPU_ON`
/// was issued, so a refusal from `run_secondary` is a genuine fault; it
/// is reported on the UART debug line and the core parks fail-closed.
extern "C" fn production_secondary_entry(cpu: u32) -> ! {
    // SAFETY: this secondary core's first action, exactly once, before
    // any FP/SIMD instruction executes on it.
    unsafe {
        enable_fp_el1();
    }
    // SAFETY: the trampoline hands over MMU-off with all interrupts
    // masked and this core has touched no exclusives yet; the boot CPU
    // published the park root before any `CPU_ON` (it enabled its own
    // MMU during `boot`), so the adopted tables are live and coherent.
    if !unsafe { tairix_arch_aarch64::paging::adopt_boot_translation() } {
        // No published boot root: nothing sane to run on — park.
        halt_current_cpu()
    }
    // SAFETY: per-CPU installs on this core, exactly once each, before
    // any interrupt source is armed here: the EL1 vector base and the
    // GICv2 CPU interface are banked per core (the distributor write in
    // `gic::init` idempotently re-enables what the boot CPU enabled).
    unsafe {
        exceptions::init_vectors();
        gic::init();
    }
    // Per-CPU tickless preemption + IPI arming (the callbacks and the
    // per-CPU backing were installed by the boot CPU before `CPU_ON`).
    crate::aarch64::gic_irq::init_secondary_preemption(cpu);

    // Join the live kernel. Returns only when this core must stop.
    let exit = tairix_kernel_core::run_secondary(cpu);
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Warn,
            id: KERNEL_SECONDARY_PARKED,
            message: "aarch64: secondary cpu left the dispatch loop; parking",
            fields: &[Field {
                key: "cause",
                value: tairix_log::FieldValue::Str(exit.as_str()),
            }],
        },
    );
    halt_current_cpu()
}

/// Collect the discovered hardware tree — the firmware tree, the
/// bootstrap-floor virtio-MMIO devices, and the boot display — and hand it to
/// the boot record ([`crate::unlock_service::record_boot`]), which resolves
/// the root block binding from it and moves it into the live inventory.
///
/// Runs with the MMU **on** (the caller enables it first; a whole-tree
/// traversal faults MMU-off, `plans/PI.md` watch-out). A null or unreadable
/// tree, or a malformed walk, records nothing: the root stays unbound and
/// the boot carries on.
///
/// `video` carries the framebuffer boot console's discovered scan-out
/// facts when one came up; the surface is published into the same
/// buffered tree as the boot display node (`plans/DISPLAY.md` D7d), so
/// the user-space display service autoloads against it. `None` (a
/// UART-only boot) publishes no display node.
fn audit_root_storage_binding(
    dtb: u64,
    video: Option<video::DiscoveredVideo>,
    log_sink: &'static (dyn Sink + Sync),
) {
    if dtb == 0 {
        return;
    }
    // SAFETY: on the boot hand-off `dtb` is the firmware/loader device-tree
    // pointer (`boot.s` preserves x0). `Fdt::from_ptr` validates the magic
    // and bounds the blob by its own `totalsize` before any further read.
    // The full-tree discovery walk below runs with the MMU on (the caller
    // enabled it), where a whole-tree traversal is safe; a bogus pointer
    // fails the magic check and returns `Err` rather than faulting.
    let Ok(fdt) = (unsafe { Fdt::from_ptr(dtb as *const u8) }) else {
        return;
    };
    // The validated blob's own length, captured before the walk consumes
    // the reader, so the virtio-MMIO probe below can reborrow the same
    // firmware bytes the bus builder needs.
    let total = fdt.total_size();
    let mut sink = crate::boot_hwtree::CollectingHwNodeSink::new();
    if platform::FdtDiscovery::new(fdt)
        .discover(&mut sink)
        .is_err()
    {
        // A malformed tree is not fatal: leave the root unbound — the mount
        // path fails closed without a binding.
        return;
    }

    // Bootstrap-floor virtio-MMIO bus enumeration: the raw `virtio,mmio` nodes the discovery walk emitted carry
    // only their `compatible` string, which binds no block driver — the
    // virtio-blk bind key is the device id read from the transport. Probe
    // each slot's `DeviceID` through the MMIO bus driver and emit a probed
    // virtio-block child node into the same buffered tree so the gate can
    // bind the root *and* the kthread's autoload sees a faithful tree. The
    // Raspberry Pi 4 tree describes no `virtio,mmio` node, so
    // `virtio_mmio_bus_from_dtb` returns `NotFound` and this is a no-op there
    // — it is the QEMU `virt`-board path, additive and metal-neutral.
    // SAFETY: `dtb`/`total` bound the firmware blob `Fdt::from_ptr` validated
    // above; it is identity-mapped and immutable for the kernel's life, and
    // the virtio-MMIO aperture it describes is identity-mapped Device memory
    // the probe alone reads (side-effect-free `DeviceID` registers, MMU on —
    // the caller enabled it, so this whole-tree walk is safe, `plans/PI.md`).
    let dtb_bytes = unsafe { core::slice::from_raw_parts(dtb as *const u8, total) };
    let probe = unsafe { tairix_drv_bus_mmio::virtio_mmio_bus_from_dtb(dtb_bytes) };
    if let Ok(bus) = probe {
        // A bus enumeration error (an over-full or malformed bus) leaves the
        // root unbound rather than aborting the boot.
        let _ = crate::hwdiscovery::observe_virtio_mmio_block_devices(&bus, &mut sink);
        // Bootstrap-floor virtio-MMIO input discovery: probe each slot's `DeviceID` for a virtio-input device and
        // emit a user-space-autoloadable `Input` node carrying its register
        // window as a grant request into the same buffered tree, so the
        // unlock kthread's `devmgr` autoload spawns the matching user-space
        // input driver with exactly that window (`plans/PI.md` P10 5d-2-ii).
        // The two reads of `bus` are sequential, so the immutable borrows do
        // not overlap. A no-op on the Pi tree (no `virtio,mmio` node), so it
        // is metal-neutral and additive. An enumeration
        // error leaves the input nodes undiscovered, never aborting the boot.
        // Resolve each virtio-input slot's GICv2 INTID from the firmware tree
        // (`device_spi` decodes the node's `interrupts` specifier — a
        // discovered value, never a board constant) so the emitted node carries the IRQ line its interrupt-driven
        // user-space driver parks on.
        let _ = crate::hwdiscovery::observe_virtio_mmio_input_devices(
            &bus,
            &|slot_base| {
                // Re-parse the validated blob per slot: the first `fdt` was
                // consumed by the discovery walk above, and there are only a
                // handful of virtio-input slots, so re-reading the FDT header
                // is negligible boot-time cost. A bogus
                // pointer fails the magic check and yields `None`, skipping
                // the slot fail-closed.
                // SAFETY: `dtb`/`total` bound the firmware blob `Fdt::from_ptr`
                // validated above; it is identity-mapped and immutable for the
                // kernel's life, and the MMU is on (the caller enabled it).
                let fdt = unsafe { Fdt::from_ptr(dtb as *const u8) }.ok()?;
                crate::aarch64::root_unlock::device_spi(&fdt, slot_base)
            },
            &mut sink,
            log_sink,
        );
        // Bootstrap-floor virtio-MMIO network discovery (`plans/NETWORK.md`
        // N4e-β): the exact sibling of the input probe above — probe each
        // slot's `DeviceID` for a virtio-net device and emit a
        // user-space-autoloadable `Network` node carrying its register
        // window, DMA constraint, and discovered GICv2 interrupt line, so
        // the autoload path spawns the matching user-space virtio-net driver
        // process (which then serves the `netchan` channel to `netstack`).
        // The IRQ line is resolved by the same per-slot `device_spi` decode
        // (a discovered value, never a board constant); a sequential
        // immutable read of `bus`, a no-op on the Pi tree, and fail-closed on
        // any enumeration error, exactly like the input probe.
        let _ = crate::hwdiscovery::observe_virtio_mmio_network_devices(
            &bus,
            &|slot_base| {
                // SAFETY: as the input probe's closure above — `dtb` bounds
                // the firmware blob validated at boot, identity-mapped and
                // immutable for the kernel's life, MMU on.
                let fdt = unsafe { Fdt::from_ptr(dtb as *const u8) }.ok()?;
                crate::aarch64::root_unlock::device_spi(&fdt, slot_base)
            },
            &mut sink,
            log_sink,
        );

        // A sound card is discovered by the same walk as a NIC: one slot's
        // register window, its coherent DMA constraint and its decoded
        // interrupt line, so the autoloaded user-space driver can park on the
        // device's own period interrupt.
        let _ = crate::hwdiscovery::observe_virtio_mmio_audio_devices(
            &bus,
            &|slot_base| {
                // SAFETY: as the probes above — `dtb` bounds the firmware
                // blob validated at boot, identity-mapped and immutable for
                // the kernel's life, MMU on.
                let fdt = unsafe { Fdt::from_ptr(dtb as *const u8) }.ok()?;
                crate::aarch64::root_unlock::device_spi(&fdt, slot_base)
            },
            &mut sink,
            log_sink,
        );
    }

    // Publish the framebuffer boot console's scan-out surface as the boot
    // display node (`plans/DISPLAY.md` D7d), into the same buffered tree the
    // block and input probes feed, so the pre-unlock autoload matches the
    // user-space display service against it. A degenerate mode is skipped
    // fail-closed inside the observer, and the collecting sink never fills,
    // so the emit cannot fail — the discard mirrors the observers above.
    if let Some(video) = video {
        let _ = crate::boot_display::observe_boot_display(
            &crate::boot_display::BootScanout {
                base: video.fb_base,
                width_px: video.width_px,
                height_px: video.height_px,
                stride_bytes: video.stride_bytes,
                format: video.format,
                memory: video.memory,
                binding: video.binding,
            },
            &mut sink,
        );
    }

    // The MMU is on here (the caller enabled it), as the boot record's
    // `SpinLock` stash requires.
    crate::unlock_service::record_boot(dtb, sink.into_vec(), log_sink);
}

/// The two memory figures the hand-off carries, which discovery produces
/// together and only [`BootInfo`] consumes: the physical map the frame
/// allocator is built from, and the platform's installed total *before* the
/// identity map's Device clip drops the bytes it cannot reach.
struct BootMemory {
    map: tairix_kernel_mem::BootMemoryMap,
    installed_bytes: u64,
}

/// Assemble the validated [`BootInfo`] hand-off and enter
/// [`tairix_kernel_core::kernel_main`].
///
/// Installs the production `svc` dispatch callback before user space can
/// be entered (the `kernel_core` `Syscall` phase publishes the resident
/// hook into [`DISPATCH_SLOT`]), wraps the validated [`Aarch64Arch`] in
/// the local [`Aarch64BinArch`] `KernelArch`, and installs the discovered
/// console list: with the framebuffer boot console active the video
/// console is the only console and the UART stays the session-free debug
/// log line (`plans/PI.md` P11); otherwise the UART is the only console.
/// A hand-off that `BootInfo::validate` rejects parks fail-closed rather
/// than entering the core.
fn enter_kernel_core(
    arch: Aarch64Arch,
    memory: BootMemory,
    heap: &'static tairix_kalloc::FreeListAllocator,
    log_sink: &'static (dyn Sink + Sync),
    audit_sink: &'static (dyn Sink + Sync),
    log_level: Level,
    hw_tree: &'static (dyn tairix_kernel_core::HwTreeSource + 'static),
) -> ! {
    // The arch port's `svc` trampoline fail-closes if it fires before a
    // callback is installed, so install it before any user thread runs.
    // No user space exists yet at P6c-2; pinning it here keeps the
    // ordering identical to the x86_64 boot path.
    syscall_entry::set_dispatch_callback(production_dispatch);

    // Arm the task-latency watchdog beside the dispatcher it observes: an
    // interactive surface that declares a frame budget then gets an overrun
    // report naming the blocking call and the user code that stalled. The
    // layout is this port's own frame-pointer convention, the same constant
    // its fault-path backtrace uses. Debug image only; a shippable image
    // installs no observer and the entry hook costs one relaxed load.
    #[cfg(feature = "watchdog-diagnostics")]
    tairix_kernel_core::latency::install(tairix_arch_aarch64::backtrace::Backtracer::LAYOUT);
    // Demand-paged file mappings resolve their EL0 data aborts through the
    // same resident hook; install the resolver beside the dispatch callback
    // so both are in place before user space exists. This single-entry boot
    // path installs exactly once; a second publish would be a programmer
    // error, so it parks fail-closed rather than running with an
    // unpredictable fault path.
    if tairix_arch_api::fault::set_user_fault_resolver(production_user_fault).is_err() {
        tairix_arch_aarch64::kernel_arch::halt_current_cpu();
    }
    // Beside the resolver, install the terminator the trap handler uses for
    // an EL0 exception it cannot resolve (an illegal instruction, an
    // alignment fault): it kills the offending task and keeps the CPU alive,
    // so one task's bad instruction can never park a core. Installed once,
    // before user space; a second publish is a programmer error that parks
    // fail-closed rather than running with an unpredictable fault path.
    if tairix_arch_api::fault::set_user_fault_terminator(production_user_fault_terminate).is_err() {
        tairix_arch_aarch64::kernel_arch::halt_current_cpu();
    }

    // The discovered dense CPU count sizes the scheduler's run queues
    // and names how many cores `kernel_main`'s SMP phase brings online.
    let cpu_count = arch.cpu_count();
    // Recover the firmware power-control conduit the boot path discovered
    // from the `/psci` node (the same method the secondary-core bring-up
    // uses) so the Supervisor's `reboot`/`poweroff` can drive PSCI
    // `SYSTEM_RESET` / `SYSTEM_OFF` through it. A tree with no `/psci` node
    // (spin-table bring-up) leaves it `None`, so both fail safe (unsupported).
    let psci_method = match arch.secondary_start() {
        Some(SecondaryStart::Psci(method)) => Some(method),
        _ => None,
    };
    let arch = Arc::new(Aarch64BinArch::new(arch).with_psci_method(psci_method));
    // Publish the arch handle for the panic-handler bridge before it is
    // moved into `BootInfo` (a panic after this point carries registers +
    // a backtrace; before it, the pre-init serial path runs).
    // SAFETY: `arch` is moved into `BootInfo` immediately below (which
    // `kernel_main` consumes and stores); `Arc::as_ptr` is stable for the
    // lifetime of any clone of the `Arc`.
    unsafe {
        crate::aarch64::panic_ctx::publish_arch(Arc::as_ptr(&arch));
    }
    // One decision for the console list and the seat registry, so the seat's
    // text sink, the console whose display surface its lease hands over, and
    // the console a descriptor's index names cannot disagree.
    let (consoles, seat_registry) = console_layout();
    let boot_info = BootInfo::new(
        BOOT_CPU,
        cpu_count,
        "",
        memory.map,
        SchedulerConfig::defaults_for(cpu_count),
        arch,
        log_sink,
        audit_sink,
        log_level,
        &DISPATCH_SLOT,
        heap,
    )
    // Install the discovered console list (`plans/PI.md` P11): when the
    // P7b framebuffer boot console came up, the display (with its
    // keyboard input seam) is the only console — the UART then carries
    // the debug log alone, with no session that would draw over it; with
    // no display, the discovered UART is the only console. Each entry is
    // a `stream_write`/`stream_read` backing pair.
    .with_consoles(consoles)
    // Record the firmware-discovered installed-RAM total so the core mints
    // the `boot_facts_get` machine summary from it.
    .with_installed_memory(memory.installed_bytes)
    // Install the kernel seat registry (`plans/DISPLAY.md` D2 — input
    // follows the surface owner): its text sink is that same console's
    // keyboard queue, so an injected key press reaches the login by
    // default, and the window manager's owner-checked `display_acquire`
    // later routes whole records to the desktop keyboard channel instead.
    // Acquiring the seat also hands the console's display surface to the
    // session, and every way the lease can end gives it back (D8).
    .with_seat_registry(seat_registry)
    // Install the PID 1 spawn seam (`plans/PI.md` P6c-3): once every init
    // phase has succeeded and `kernel_main` emits `BootCompleted`, the core
    // invokes it to build `init`'s EL0 image and drop into user mode.
    .with_init(&crate::aarch64::init_spawn::AARCH64_INIT_SPAWN)
    // Install the runtime `spawn` producer + embedded-program registry
    // (`plans/SPAWN.md` SP3b): the `spawn` syscall resolves a path against
    // the registry and drives the producer to build a fresh, isolated child
    // address space, so PID 1 `init` can launch the user's session.
    .with_spawn(
        &crate::spawn_layout::PROGRAM_REGISTRY,
        &crate::aarch64::spawn_producer::AARCH64_PROCESS_SPAWN,
    )
    // Install the on-disk application store (`plans/APPS.md` deliverable 8):
    // this port embeds no program rows, so every command app and service is
    // spawned from its verified `/System` store bundle. The storage bring-up
    // resolves the store's readiness latch on every outcome (mount installed
    // or given up), so a spawn racing the mount parks and always wakes.
    .with_app_store(&crate::app_store::APP_STORE)
    // Hand the syscall dispatch hook the shared set-once credential cell
    // (`plans/PI.md` P11 Chunk B-2): `users_db_read` reads it on every
    // call, and the in-kernel root-unlock kthread publishes the mounted
    // root volume's database into the *same* cell once the operator's
    // passphrase unlocks the encrypted root. Until that install the cell
    // fails every read closed, identical to the previous `NULL_USERS_DB`
    // default — so login refuses every attempt until a root is mounted, and the metal-confirmed boot is unaffected.
    .with_users_db(&crate::root_mount::LATE_USERS_DB)
    .with_groups_db(&crate::root_mount::LATE_GROUPS_DB)
    .with_users_admin(&crate::root_mount::LATE_USERS_ADMIN)
    // Serve the discovered hardware tree through the injected `hw_tree`
    // source: the `hw_tree_read` / `hw_tree_wait` syscalls read the one
    // authoritative `HW_TREE` the boot record seeds and user-space bus
    // drivers publish into (production installs `HW_TREE_SOURCE`), so the
    // user-space device manager observes the same inventory the kernel
    // discovered (Design D).
    .with_hw_tree(hw_tree)
    // Serve the `fs_*` syscalls through the production filesystem service
    // (`PREREQUISITES.md` P-A): it routes each operation through the secured
    // VFS against the late-installed read-only `/System` mount and resolves
    // caller groups against the late-installed identity table. Both cells
    // fail closed (`NotImplemented`) until the disk-owning task publishes the
    // `/System` window (`crate::system_mount::install_system_mount`) and the
    // encrypted-root unlock publishes the identity table, so wiring the hook
    // here changes no boot behaviour until those installs land.
    .with_filesystem(&crate::system_mount::FS_SERVICE)
    // Resolve `id::<volume-id>/…` paths against the volume forest the
    // mount/unlock tasks publish each mounted volume's stable identity
    // into (`plans/DEVICES.md` D3a). Until a volume is published every
    // `id::` path fails closed `NotFound`, so wiring the hook here changes
    // no boot behaviour until those installs land.
    .with_volumes(&crate::system_mount::VOLUME_FOREST)
    // Delegate runtime volume attach/detach (`plans/DEVICES.md` D3b) to
    // the production service; it fails closed `NotImplemented` until the
    // mount task wires its audit sink and pressure gauge, so this changes
    // no boot behaviour until that install lands.
    .with_volume_service(&crate::volume_service::VOLUME_SERVICE)
    // Resolve a spawn-as-user switch (`PREREQUISITES.md` P-C) against the
    // same set-once identity cell the filesystem service resolves caller
    // groups against and the root-unlock kthread publishes the on-disk
    // accounts into. Until that install a switch fails closed; the default
    // `spawn` (inherit) never consults it, so wiring the hook here changes no
    // boot behaviour until the unlock lands.
    .with_spawn_identity(&crate::root_mount::LATE_IDENTITY);
    if boot_info.validate().is_err() {
        halt_current_cpu()
    }
    kernel_main(boot_info)
}

/// What the pre-MMU boot phase resolved from the firmware device tree:
/// the MMIO facts the identity map's Device gigapage mask is derived
/// from ([`identity_device_mask`]).
struct EarlyDiscovered {
    /// A recognised console UART was found and the console base/model set.
    console: bool,
    /// A GICv2-class interrupt controller was found and its GICD/GICC
    /// bases set.
    gic: bool,
    /// The framebuffer boot console came up: a firmware mailbox was
    /// found, a display is attached, and the scan-out surface was
    /// allocated — console output now defaults to the screen, with the
    /// UART as the fallback (`plans/PI.md` P7b).
    video: Option<video::DiscoveredVideo>,
    /// Total byte length of the firmware device-tree blob (`totalsize`),
    /// `0` when no readable tree was found — the blob's RAM extent must
    /// stay in the identity map for the post-MMU walks.
    dtb_len: u64,
    /// The BCM2711 PCIe root-complex windows, when the tree describes a
    /// `brcm,bcm2711-pcie` bridge (`plans/PI.md` P10): the controller
    /// register block and outbound MMIO window must be folded into the
    /// identity Device mask, and the bring-up consumes all three windows.
    /// `None` on a board with no bridge (the QEMU `virt` shape).
    pcie: Option<platform::PcieDiscovery>,
    /// The rate in Hz the firmware was asked to run the ARM cores at, or `0`
    /// on a board with no firmware clock (the QEMU `virt` shape) or where the
    /// request failed. Recorded so the boot log can state the speed the rest
    /// of boot ran at rather than leaving it to be inferred.
    cpu_clock_hz: u64,
}

/// Point the console and the GICv2 driver at the bases the firmware tree
/// describes and bring up the framebuffer boot console, before the MMU
/// is enabled.
///
/// All three discoveries are early-returning, `ranges`-aware walks
/// ([`console::configure_from_fdt`] / [`gic::configure_from_fdt`] /
/// [`video::configure`] over
/// [`tairix_fdt::scan_translated`]), so they are safe with
/// the MMU off — and the video bring-up *requires* this phase: with the
/// data caches off the CPU↔firmware mailbox exchange is coherent without
/// cache maintenance, and its state cell needs the single-threaded boot
/// CPU. A null pointer, an unreadable/invalid blob, or a tree missing a
/// fact leaves the corresponding pre-discovery default untouched — for
/// video, the UART console (fail closed).
fn configure_mmio_from_dtb(dtb: u64) -> EarlyDiscovered {
    let mut out = EarlyDiscovered {
        console: false,
        gic: false,
        video: None,
        dtb_len: 0,
        pcie: None,
        cpu_clock_hz: 0,
    };
    if dtb == 0 {
        return out;
    }
    // SAFETY: on the boot hand-off `dtb` is the firmware/loader device-tree
    // pointer (`boot.s` preserves x0). `Fdt::from_ptr` validates the magic
    // and bounds the blob by its own `totalsize` before any further read,
    // and every read is a single byte, so the access is valid MMU-off. A
    // bogus pointer fails the magic check and returns `Err` rather than
    // faulting on structured data.
    let Ok(fdt) = (unsafe { Fdt::from_ptr(dtb as *const u8) }) else {
        return out;
    };
    out.dtb_len = fdt.total_size() as u64;
    out.console = console::configure_from_fdt(&fdt).is_some();
    // Bring the discovered console's line up before the first log byte:
    // on real Pi 4 silicon UART0 stays silent until GPIO 14/15 are muxed
    // to the PL011 and its line registers are programmed — QEMU's
    // powered-up PL011 masks the omission (`uart_init`).
    uart_init::init_from_fdt(&fdt);
    out.gic = gic::configure_from_fdt(&fdt).is_some();
    // Ask the firmware for full speed before anything else runs. On a Pi the
    // ARM clock is the firmware's, and it leaves it at `arm_freq_min` — 600
    // MHz on a board rated at 1.5 GHz — until an OS driver asks otherwise, so
    // mounting the root volume, unlocking it, and reaching a login would all
    // run at 40% of the machine's speed. The frequency driver `devmgr`
    // autoloads takes over from here; this is the floor beneath it, and it
    // fails closed to whatever rate the firmware had chosen.
    match firmware::find_mailbox(&fdt) {
        Some(mailbox) => {
            let _ = firmware::with_transport(mailbox, |transport| {
                out.cpu_clock_hz = firmware::raise_over(transport).map_or(0, u64::from);
                out.video = video::configure(&fdt, Some((mailbox, transport)));
            });
        }
        None => out.video = video::configure(&fdt, None),
    }
    // Discover the BCM2711 PCIe bridge's windows for the in-kernel
    // USB-keyboard service (`plans/PI.md` P10). The early-returning
    // `scan_translated` walk is MMU-off-safe (it reads only the matched
    // node's own properties), exactly like the console/GIC/video walks
    // above; the QEMU `virt` tree carries no such node, so this is `None`
    // there and the keyboard service is never started.
    out.pcie = platform::pcie_bringup(&fdt);
    out
}

/// What the post-MMU boot phase resolved from the firmware device tree.
struct Discovered {
    /// Every `/memory` window `(base, size)` discovered from the firmware
    /// tree, in tree order — the RAM extents the `BootMemoryMap`
    /// (`plans/PI.md` P6c-1) reserves the kernel image out of and hands
    /// the allocator. A machine like the Pi 4 (8 GiB) declares several
    /// (below the MMIO hole, 1 GiB..4 GiB, and above 4 GiB); reading only
    /// the first under-reported an 8 GiB board as ~1 GiB. Empty when the
    /// tree declares none (fail closed — no memory map is built).
    ram_windows: Vec<(u64, u64)>,
    /// The generic-timer counter frequency (Hz) to seed the handle and
    /// the P4 live timer with: the `/timer` `clock-frequency` override
    /// when the tree declares one, else the `CNTFRQ_EL0` register value.
    timer_hz: u64,
    /// `true` when `timer_hz` came from the device-tree override rather
    /// than the `CNTFRQ_EL0` register.
    timer_hz_from_tree: bool,
    /// The PSCI conduit (`hvc`/`smc`) the `/psci` node declares, used to
    /// issue `CPU_ON` for SMP bring-up (`plans/PI.md` P5). `None` when the
    /// tree declares no PSCI node; bring-up then rides the spin-table
    /// release when the cpu nodes declare one, else fails closed.
    psci_method: Option<fdt::PsciMethod>,
    /// Every `/cpus/cpu@*` `reg` affinity (`MPIDR_EL1` `Aff0`–`Aff2`)
    /// the firmware tree declares, in tree order — the CPU inventory
    /// [`crate::cpu_topology::order_cpus`] validates into the dense map
    /// every per-CPU structure is sized from. Empty when the tree
    /// declares none or the walk fails (the boot then falls back closed
    /// to a single-CPU map).
    cpu_mpidrs: Vec<u64>,
    /// `(affinity, cpu-release-addr)` for every cpu node that declares
    /// the `spin-table` enable method (the Pi 4's stock firmware), in
    /// tree order — aligned to the dense map by
    /// [`crate::cpu_topology::align_release_addrs`] and used for
    /// bring-up only when the tree declares no PSCI node. Empty when
    /// none are declared or the walk fails (fail closed).
    cpu_spin_releases: Vec<(u64, u64)>,
}

/// Discover the board's post-MMU facts from the device tree at `dtb`:
/// the `/memory` window, the timer rate, and the PSCI conduit. (The
/// console and GIC bases are configured MMU-off by
/// [`configure_mmio_from_dtb`], before the identity map is built.)
///
/// A null pointer, an unreadable/invalid blob, or a tree missing a fact
/// leaves the corresponding pre-discovery `virt` default untouched (fail
/// closed).
fn configure_from_dtb(dtb: u64) -> Discovered {
    let mut out = Discovered {
        ram_windows: Vec::new(),
        // With no usable tree the register is the only counter-rate
        // source; P4's tree override (if any) overwrites this below.
        timer_hz: read_cntfrq(),
        timer_hz_from_tree: false,
        psci_method: None,
        cpu_mpidrs: Vec::new(),
        cpu_spin_releases: Vec::new(),
    };
    if dtb == 0 {
        return out;
    }
    // SAFETY: on the boot hand-off `dtb` is the firmware/loader device-tree
    // pointer (`boot.s` preserves x0). `Fdt::from_ptr` validates the magic
    // and bounds the blob by its own `totalsize` before any further read,
    // and every read is a single byte. The full-tree walks below run with
    // the MMU on (the caller enables it first). A bogus pointer fails the
    // magic check and returns `Err` rather than faulting on structured
    // data.
    let Ok(fdt) = (unsafe { Fdt::from_ptr(dtb as *const u8) }) else {
        return out;
    };
    // Collect every declared RAM range (every `reg` pair of every
    // `/memory` node), skipping zero-length entries. A malformed tree
    // discards the partial collection: the boot path then builds no
    // memory map at all rather than trusting a truncated inventory,
    // exactly as the former single-window read failed closed to `None`.
    let mut windows = Vec::new();
    if fdt
        .each_memory_region(|base, size| {
            if size != 0 {
                windows.push((base, size));
            }
        })
        .is_err()
    {
        windows.clear();
    }
    out.ram_windows = windows;
    // P4: prefer the board's `/timer` `clock-frequency` over the
    // `CNTFRQ_EL0` register, so the Pi 4's 54 MHz crystal is honoured
    // when the firmware tree declares it (no
    // `cfg(board)` fork).
    out.timer_hz_from_tree = fdt::timer_clock_frequency(&fdt).is_some_and(|hz| hz != 0);
    out.timer_hz = timer_frequency_hz(&fdt);
    // P5: discover the PSCI conduit (`hvc`/`smc`) the firmware tree
    // declares, so secondary-core bring-up issues `CPU_ON` over the
    // board's conduit rather than an assumed one.
    out.psci_method = fdt::psci_method(&fdt);
    // Collect every `/cpus/cpu@*` affinity so the bring-up starts the
    // cores the board *declares* (the Pi 4's four Cortex-A72s), never an
    // assumed count — along with each node's spin-table release word,
    // the PSCI-less start channel. A malformed walk discards the
    // partial lists — the boot then sizes for the one running core
    // rather than trusting a truncated inventory (fail closed).
    let mut cpus = Vec::new();
    let mut spin_releases = Vec::new();
    if fdt
        .each_cpu(|cpu| {
            let affinity = cpu.reg & smp::MPIDR_AFFINITY_MASK;
            cpus.push(affinity);
            if let Some(addr) = cpu.spin_table_release {
                spin_releases.push((affinity, addr));
            }
        })
        .is_err()
    {
        cpus.clear();
        spin_releases.clear();
    }
    out.cpu_mpidrs = cpus;
    out.cpu_spin_releases = spin_releases;
    // Record the console UART's receive-interrupt line so the root-unlock
    // console handoff can switch `login`'s input from polled to
    // interrupt-driven (`crate::aarch64::gic_irq::enable_uart_console_irq`).
    // Done here (post-MMU) rather than beside the MMU-off console-base
    // discovery because storing it flips an atomic `OnceCell`, which is only
    // sound with the MMU on; and unconditionally, so the no-disk path (which
    // never runs the unlock kthread) still gets it. A tree without a
    // representable console interrupt leaves `login` on the polled path (fail
    // closed — `login` then keeps re-polling, never errors).
    if let Some(intid) = crate::aarch64::root_unlock::console_spi(&fdt) {
        crate::aarch64::gic_irq::set_uart_console_intid(intid);
    }
    // Configure the BCM2711 root-complex MSI controller the `msi_alloc`
    // syscall drives: point it at the discovered RC register base and record
    // the shared GIC SPI its internal MSI controller raises (the
    // `brcm,bcm2711-pcie` node's second `interrupts` entry). A tree with no
    // such node leaves the controller unconfigured and `msi_alloc` fails
    // closed (the QEMU `virt` shape). Done post-MMU because both the
    // register-base store and the SPI `OnceCell` need the MMU on, exactly
    // like the console-interrupt record above.
    #[cfg(all(freestanding, kernel_isa = "aarch64"))]
    if let (Some(pcie), Some(msi_intid)) = (
        platform::pcie_bringup(&fdt),
        crate::aarch64::root_unlock::pcie_msi_spi(&fdt),
    ) {
        if let Ok(base) = usize::try_from(pcie.regs_phys) {
            tairix_arch_aarch64::brcm_msi::configure(base, pcie.inbound_size);
            crate::aarch64::gic_irq::set_brcm_msi_spi(msi_intid);
        }
    }
    out
}
