//! The freestanding aarch64 test kernel: spawn a driver through the
//! production devmgr-driven spawn path, then tear it down through the
//! production driver-unload mechanism and assert every kernel-held piece of
//! it was reclaimed (`plans/USB.md` U1).
//!
//! The build script compiles the pure-Rust driver-stub fixture
//! (`tests/integration/driver_register_program`) position-independent and
//! wraps it as the signed payload of a `kind = UserSpace` driver image,
//! exactly as the driver-spawn vertical does. On boot the test discovers the
//! `virt` board, enables the identity MMU + EL1 vectors, builds the live
//! kernel registries, and autoloads the stub through the production
//! `DeviceManager::autoload` + `SpawnDriverLoader` +
//! `InitCtxDriverProcessSpawn` over the `Aarch64ProcessSpawn` image builder —
//! the driver is admitted as a parked **loading** task with its placeholder
//! capability record minted (its address space is built on the driver's own
//! first slice, which this teardown test never runs).
//!
//! It then drives the symmetric partner of the spawn seam,
//! `InitSpawnCtx::terminate_driver_process` (the mechanism the driver-store
//! server runs for `StoreRequest::Unload`), and asserts the driver task was
//! reaped (the scheduler's live-task count drops 1 → 0) and its capability
//! record and address-space entry reclaimed. A second unload of the now-gone
//! handle must fail closed with `NotFound` (the teardown is idempotent).
//! PASS once teardown reclaimed everything and the idempotent miss was
//! observed; any shortfall writes a distinct failure finisher (fail-loud).

use core::num::NonZeroU16;
use core::panic::PanicInfo;

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::hwtree::HwResource;
use tairix_abi::{
    CapabilityId, DriverBindKey, Errno, HwDeviceClass, HwMatchKey, HwNode, HW_NODE_ROOT,
};
use tairix_arch_aarch64::kernel_arch::timer_frequency_hz;
use tairix_arch_aarch64::paging::{
    configure_device_gigapages, configure_kernel_gigapages, install_boot_physmap,
    AddressSpace as ArchAddressSpace, PageTablePool, GIGAPAGE_MASK_WORDS,
};
use tairix_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, Aarch64Arch,
    Aarch64ArchStorage, SERIAL_SINK,
};
use tairix_arch_api::BOOT_CPU;
use tairix_caps::CapabilitySet;
use tairix_crypto::Ed25519PublicKey;
use tairix_devmgr::{DeviceManager, DriverCandidate};
use tairix_drvhost::ImageSource;
use tairix_fdt::Fdt;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel::aarch64::arch_wrapper::Aarch64BinArch;
use tairix_kernel::aarch64::spawn_producer::{AARCH64_PROCESS_SPAWN, USER_IMAGE_BIAS};
use tairix_kernel::driver_spawn_loader::{InitCtxDriverProcessSpawn, SpawnDriverLoader};
use tairix_kernel_core::{
    AddressSpaceRegistry, InitSpawnCtx, KernelArch, KernelInitSpawner, NULL_PROCESS_WAIT,
    NULL_SHARED_MEM_FACILITY,
};
use tairix_kernel_irq::{IrqTable, UnsupportedController};
use tairix_kernel_mem::{
    BootMemoryMap, FrameAllocator, MemoryRegion, PhysAddr, RegionKind, PAGE_SIZE,
};
use tairix_kernel_sched_cfq::{Scheduler, SchedulerConfig};
use tairix_kernel_sec::{CapTable, ProcessId, TaskId as SecTaskId};
use tairix_log::{log, Event, EventId, Level};
use tairix_sync::RwLock;

// `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// `DRIVER_IMAGE: &[u8]` (signed UserSpace manifest wrapping `PROGRAM_RXE`)
// and `DRIVER_SIGNER_PUBKEY: [u8; 32]`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/driver_image.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// Gigabytes of identity map the boot address space provides: `[0, 2 GiB)`
/// covers the `virt` board's device MMIO (GiB 0) and the RAM base at GiB 1
/// where this kernel, its heap, and the frame pool live.
const IDENTITY_GIB: usize = 2;

/// Base + length of the register window the driver-spawn path mints a
/// device-resource grant for (a `virt` virtio-MMIO transport). The driver is
/// never run here — this vertical proves teardown, not the device path — but
/// the grant is minted at spawn so its reclamation on unload is part of what
/// the address-space-registry withdrawal exercises.
const GRANT_MMIO_BASE: u64 = 0x0a00_0000;
const GRANT_MMIO_LEN: u64 = 0x200;

/// Physical frames the live allocator serves (8 MiB): the stub's image
/// pages, its 1.125 MiB user stack, the startup block, and its page tables.
const FRAME_COUNT: usize = 2048;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4310);
const TEST_SPAWNED: EventId = EventId(4311);
const TEST_UNLOADED: EventId = EventId(4312);
const TEST_PASS: EventId = EventId(4313);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_GIC: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_FRAMES: NonZeroU16 = fail_point!(4);
const FAIL_BIAS: NonZeroU16 = fail_point!(5);
const FAIL_TRUST: NonZeroU16 = fail_point!(6);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(7);
const FAIL_SPAWN: NonZeroU16 = fail_point!(8);
/// The freshly-autoloaded driver was not live (not admitted, or its caps /
/// address space were never registered) — the spawn half is broken.
const FAIL_NOT_LIVE: NonZeroU16 = fail_point!(9);
/// `terminate_driver_process` refused to tear down a live driver.
const FAIL_UNLOAD: NonZeroU16 = fail_point!(10);
/// The scheduler task survived the unload (was not reaped).
const FAIL_STILL_LIVE: NonZeroU16 = fail_point!(11);
/// The driver's capability record survived the unload.
const FAIL_CAPS_LEFT: NonZeroU16 = fail_point!(12);
/// The driver's address-space-registry entry survived the unload.
const FAIL_ASPACE_LEFT: NonZeroU16 = fail_point!(13);
/// A second unload of the now-gone handle did not fail closed with
/// `NotFound` — the teardown is not idempotent.
const FAIL_NOT_IDEMPOTENT: NonZeroU16 = fail_point!(14);
/// The direct physical map could not be installed over the board's RAM.
const FAIL_PHYSMAP: NonZeroU16 = fail_point!(15);

/// Size of the test's bump heap (4 MiB).
const HEAP_SIZE: usize = 4 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the boot identity space the test switches to so
/// the MMU is on before any atomic read-modify-write runs.
static BOOT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Identity-mapped physical-frame backing store the live [`FrameAllocator`]
/// serves.
#[repr(C, align(4096))]
struct FramePool([u8; PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; PAGE_SIZE * FRAME_COUNT]);

/// Per-CPU bookkeeping backing the scheduler's arch handle (single-CPU
/// vertical).
static SCHED_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// Per-CPU bookkeeping backing the spawn-context arch handle (a second
/// instance, mirroring the driver-spawn vertical's producer storage).
static SPAWN_ARCH_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn driver_unload_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// The capability set the device manager autoloads the driver under — the
/// *caller* set the gate intersects the driver manifest's request with.
fn autoload_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::DRV_LOAD);
    caps.insert(CapabilityId::MEM_DMA);
    caps.insert(CapabilityId::IRQ_BIND);
    caps
}

/// `/System/Drivers/` path the signed driver image is resolved under.
const DRIVER_PATH_STR: &str = "/System/Drivers/drvstub.rxe";

/// The discovered driver store: yields the build-signed [`DRIVER_IMAGE`] for
/// [`DRIVER_PATH_STR`]. The `SpawnDriverLoader` gate verifies it against
/// [`DRIVER_SIGNER_PUBKEY`] before the payload is ever spawned.
struct StaticImageSource;

impl ImageSource for StaticImageSource {
    fn read(&self, path: &str, buf: &mut alloc::vec::Vec<u8>) -> Result<(), Errno> {
        if path == DRIVER_PATH_STR {
            buf.extend_from_slice(DRIVER_IMAGE);
            Ok(())
        } else {
            Err(Errno::NotFound)
        }
    }
}

/// The leaked-`'static` kernel subsystems the spawn context and the unload
/// mechanism borrow — the vertical's analogue of `KernelState`.
struct Subsystems {
    frames: &'static FrameAllocator,
    sched: &'static Scheduler<Aarch64BinArch>,
    arch: &'static Aarch64BinArch,
    caps: &'static RwLock<CapTable>,
    peer_watch: &'static tairix_kernel_core::PeerWatch,
    aspaces: &'static RwLock<AddressSpaceRegistry>,
    irq_table: &'static IrqTable,
}

/// Build the live kernel subsystems the production spawn + unload path
/// borrow: the `kernel/mem` frame allocator over the identity-mapped pool,
/// the scheduler over the production `KernelArch` wrapper, and the capability
/// / address-space / IRQ state the `KernelInitSpawner` registers a spawned
/// driver with and reclaims on teardown.
fn leak_subsystems(counter_hz: u64) -> Subsystems {
    let mut memory_map = BootMemoryMap::new();
    memory_map.push(MemoryRegion {
        start: PhysAddr::new(core::ptr::addr_of!(FRAME_POOL) as u64),
        length: (PAGE_SIZE * FRAME_COUNT) as u64,
        kind: RegionKind::Usable,
    });
    let Ok(frames) = FrameAllocator::new(&memory_map) else {
        qemu_exit::exit_failure(FAIL_FRAMES);
    };
    let frames: &'static FrameAllocator = Box::leak(Box::new(frames));

    let sched_arch = Arc::new(Aarch64BinArch::new(Aarch64Arch::new(
        &SCHED_STORAGE,
        BOOT_CPU,
        counter_hz,
    )));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), sched_arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    Subsystems {
        frames,
        sched: Box::leak(Box::new(sched)),
        arch: Box::leak(Box::new(Aarch64BinArch::new(Aarch64Arch::new(
            &SPAWN_ARCH_STORAGE,
            BOOT_CPU,
            counter_hz,
        )))),
        caps: Box::leak(Box::new(RwLock::new(CapTable::new()))),
        peer_watch: Box::leak(Box::new(tairix_kernel_core::PeerWatch::new())),
        aspaces: Box::leak(Box::new(RwLock::new(AddressSpaceRegistry::new()))),
        irq_table: Box::leak(Box::new(IrqTable::new(0))),
    }
}

/// Bring the board up: FP/SIMD on, the `virt` device tree discovered (timer
/// rate, GICv2 bases), the identity MMU + EL1 vectors enabled, and the GIC
/// initialised. Returns the discovered generic-timer rate. No syscall
/// dispatch callback is installed: the spawned driver is torn down before it
/// is ever dispatched, so it issues no `svc`.
fn bring_up_board() -> u64 {
    // Enable FP/SIMD at EL1 before any code the compiler may lower to NEON.
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Configure the board's gigapage facts, exactly as the production boot
    // path derives them from discovery: Device GiB 0 is the `virt` MMIO
    // window, and GiB 1 holds both this kernel's image and its RAM. The
    // production spawn producer sizes every child's identity window from
    // these masks, so driving it under the unconfigured defaults would
    // request a window reaching the user bias and the spawn would fail
    // closed.
    let mut device_mask = [0u64; GIGAPAGE_MASK_WORDS];
    device_mask[0] = 0b01;
    configure_device_gigapages(device_mask);
    let mut ram_mask = [0u64; GIGAPAGE_MASK_WORDS];
    ram_mask[0] = 0b10;
    configure_kernel_gigapages(ram_mask);
    // The production spawn producer reaches a child's page tables through
    // the direct physical map in the kernel translation regime, so the
    // chassis stands it up over the same RAM before driving the producer.
    if !install_boot_physmap(&ram_mask) {
        qemu_exit::exit_failure(FAIL_PHYSMAP);
    }

    let Some(boot_space) =
        ArchAddressSpace::new_identity_gigapages(&BOOT_PAGE_TABLES, IDENTITY_GIB)
    else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
    // heap, the frame pool, and the device MMIO (all within `[0, 2 GiB)` on
    // the `virt` board), so switching it does not move the ground under the
    // running code; `init_vectors` runs once on the boot CPU with a stack
    // established.
    unsafe {
        boot_space.switch();
        exceptions::init_vectors();
    }
    // SAFETY: called once on the boot CPU after the GIC bases were
    // discovered above.
    unsafe {
        tairix_itest_gic::init_boot_cpu().expect("the GIC comes up");
    }
    counter_hz
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `tairix_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 driver-unload test: starting");

    let counter_hz = bring_up_board();

    // The stub `rxe`'s baked relocations must target the bias the production
    // producer maps every child at; a drifted constant would admit a child
    // whose pointers do not match its mapping (fail closed).
    if USER_BIAS != USER_IMAGE_BIAS {
        qemu_exit::exit_failure(FAIL_BIAS);
    }

    let sys = leak_subsystems(counter_hz);

    // The discovered hardware tree: a root and one device node carrying the
    // register window it exposes as a capability-grant request — the matched
    // node the privileged spawn mints a grant for.
    let match_key = HwMatchKey::virtio(0x1234);
    let mut device = HwNode::new(2, 1, HwDeviceClass::Input);
    if device.push_match_key(match_key).is_err()
        || device
            .push_resource(HwResource::mmio(GRANT_MMIO_BASE, GRANT_MMIO_LEN))
            .is_err()
    {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    let tree = [HwNode::new(1, HW_NODE_ROOT, HwDeviceClass::Root), device];
    // The inventory the node is matched in, which admission checks still
    // holds it once the driver's grants are minted.
    let inventory = tairix_kernel::hwtree_store::HwTreeStore::new();
    if inventory.seed(tree.to_vec()).is_err() {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }

    let bind_keys = [DriverBindKey::new(5, match_key)];
    let candidates = [DriverCandidate {
        path: DRIVER_PATH_STR,
        bind_keys: &bind_keys,
    }];

    let Ok(signer) = Ed25519PublicKey::from_bytes(&DRIVER_SIGNER_PUBKEY) else {
        qemu_exit::exit_failure(FAIL_TRUST);
    };
    let trusted = [signer];
    let source = StaticImageSource;
    // Drive the *production* driver-spawn seam through the kernel/core
    // `KernelInitSpawner` (owning the live registries and the IRQ table the
    // teardown reclaims from), reached via the bin crate's
    // `InitCtxDriverProcessSpawn` bridge over `Aarch64ProcessSpawn`.
    // Publish the launch-services bundle the deferred driver-load path reads
    // (the one shared build+publish the production boot path uses); the driver
    // is admitted as a parked loading task and would build its image on its
    // own first slice.
    let _ = tairix_kernel_core::spawn_services::install_over(
        sys.arch,
        sys.frames,
        &SERIAL_SINK,
        &tairix_kernel_core::NULL_FILESYSTEM,
        None,
        sys.aspaces,
        sys.caps,
        sys.peer_watch,
        &NULL_PROCESS_WAIT,
        &AARCH64_PROCESS_SPAWN,
    );
    let init_ctx = KernelInitSpawner::new(
        sys.frames,
        &SERIAL_SINK,
        sys.sched,
        sys.caps,
        sys.peer_watch,
        sys.aspaces,
        sys.arch,
        &NULL_PROCESS_WAIT,
        sys.irq_table,
        // No line is bound: the table holds none.
        &UnsupportedController,
        &NULL_SHARED_MEM_FACILITY,
        KernelArch::cross_cpu_tlb_shootdown(sys.arch),
    );
    let spawn = InitCtxDriverProcessSpawn::new(&init_ctx);
    let args: [&[u8]; 1] = [b"drvstub"];
    // The matched node id (the device node, id 2) the kernel records against
    // the spawned driver.
    let mut loader = SpawnDriverLoader::new(
        &trusted,
        &source,
        &SERIAL_SINK,
        &spawn,
        &args,
        Some(tairix_kernel_core::DriverNode {
            id: 2,
            tree: &inventory,
        }),
    );

    // Autoload: match the node, run the signed gate, and spawn the driver
    // with the matched node's MMIO grant — the production discovery path.
    let report = DeviceManager::new(&SERIAL_SINK).autoload(
        &tree,
        &candidates,
        &autoload_caps(),
        &mut loader,
    );
    if report.bindings.len() != 1 {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(
        TEST_SPAWNED,
        "aarch64 driver-unload test: driver autoloaded + spawned",
    );

    // The driver's PID is its scheduler task id and the numeric its security
    // id was minted under.
    let handle = report.bindings[0].handle.as_u64();
    let sec = SecTaskId(handle);

    // The driver was admitted as a parked **loading** task (never dispatched):
    // it is a live scheduler task carrying its admit-time placeholder
    // capability record. Its isolated address space is registered by the
    // loading body on the driver's own first slice, which this teardown test
    // never runs — so it is deliberately *not* yet in the address-space
    // registry, and terminating a still-loading driver must reclaim it just
    // the same (`plans/FIX-DESKTOP.md` DESK-1).
    if sys.sched.live_task_count() != 1
        || sys.caps.read().caps_for(sec).is_none()
        || sys.aspaces.read().contains(ProcessId(sec.0))
    {
        qemu_exit::exit_failure(FAIL_NOT_LIVE);
    }

    // Tear the driver down through the production unload mechanism — the
    // symmetric partner of the spawn seam the driver-store server drives for
    // `StoreRequest::Unload`.
    if init_ctx.terminate_driver_process(handle).is_err() {
        qemu_exit::exit_failure(FAIL_UNLOAD);
    }
    note(
        TEST_UNLOADED,
        "aarch64 driver-unload test: driver torn down via terminate_driver_process",
    );

    // The scheduler task was reaped and the driver's kernel-held state
    // reclaimed: live-task count back to zero, capability record gone,
    // address-space-registry entry withdrawn.
    if sys.sched.live_task_count() != 0 {
        qemu_exit::exit_failure(FAIL_STILL_LIVE);
    }
    if sys.caps.read().caps_for(sec).is_some() {
        qemu_exit::exit_failure(FAIL_CAPS_LEFT);
    }
    if sys.aspaces.read().contains(ProcessId(sec.0)) {
        qemu_exit::exit_failure(FAIL_ASPACE_LEFT);
    }

    // The teardown is idempotent: unloading the now-gone handle again is a
    // benign, fail-closed `NotFound`, never a panic or a double-reclaim.
    if init_ctx.terminate_driver_process(handle) != Err(Errno::NotFound) {
        qemu_exit::exit_failure(FAIL_NOT_IDEMPOTENT);
    }

    note(
        TEST_PASS,
        "aarch64 driver-unload test: teardown reclaimed everything and is idempotent",
    );
    qemu_exit::exit_success();
}
