//! The freestanding aarch64 test kernel: prove the `lib/sandbox`
//! parser-sandbox seam end to end over the S8a kernel sandbox spawn mode
//! (`docs/src/security/sandbox.md`; `plans/APPS.md` S8b).
//!
//! Unlike the bespoke micro-kernel harnesses, every syscall here runs the
//! production `KernelDispatchHook` / `KernelSyscallHandlers` path: the
//! chassis installs the hook through a `DispatchCallbackSlot`, binds the
//! production user-fault resolver to the same slot, wires the production
//! `LiveMemMap` producer (the `tairix-rt` heap's `mem_map` pair), a real
//! `KernelProcessWait`, and a `ProgramRegistry` carrying the fixture's
//! four worker paths. The parent role is spawned through the production
//! `InitSpawnCtx::spawn_driver_process` seam; it spawns each sandboxed
//! worker itself, through the seam's production launcher (`pipe_create` +
//! `SpawnAttach::sandbox` + `spawn` + `wait`), and drives:
//!
//! * container + instruction decode of valid and malformed inputs through
//!   a genuinely sandboxed decode worker;
//! * real crash containment — a worker that exits without serving yields a
//!   typed error, a logged crash event, and a surviving caller;
//! * the syscall wall from the inside — a probe worker's `fs_open` and
//!   `spawn` are refused inside the sandbox while its pipe reply crosses;
//! * the duplex session seam driven entirely from a wait-set holding
//!   `Stream` on the reply descriptor and `StreamRoom` on the request one:
//!   the parent pushes twice a pipe's worth of frames at a worker that
//!   answers none of them, which can only complete if the write-room wake
//!   fires.
//!
//! The chassis reaps the parent through the producer's non-blocking poll
//! and PASSes only on a parent exit of 0.

use core::num::NonZeroU16;
use core::panic::PanicInfo;

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::{CapabilityId, Errno, WaitFlags, WaitStatus, SYSCALL_MAX_ARGS};
use tairix_arch_aarch64::kernel_arch::timer_frequency_hz;
use tairix_arch_aarch64::paging::{
    configure_device_gigapages, configure_kernel_gigapages, install_boot_physmap,
    AddressSpace as ArchAddressSpace, PageTablePool, GIGAPAGE_MASK_WORDS,
};
use tairix_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, Aarch64Arch,
    Aarch64ArchStorage, SERIAL_SINK,
};
use tairix_arch_api::BOOT_CPU;
use tairix_caps::CapabilitySet;
use tairix_fdt::Fdt;
use tairix_itest_finisher::fail_code;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel::aarch64::arch_wrapper::{Aarch64BinArch, UART_ONLY_CONSOLES};
use tairix_kernel::aarch64::spawn_producer::{AARCH64_PROCESS_SPAWN, USER_IMAGE_BIAS};
use tairix_kernel::dispatch_core::{dispatch_via_slot, read_raw_args, resolve_user_fault_via_slot};
use tairix_kernel_core::{
    AddressSpaceRegistry, BootReserve, DispatchCallbackSlot, EmbeddedProgram, InitSpawnCtx,
    KernelArch, KernelDispatchHook, KernelInitSpawner, KernelProcessWait, LiveMemMap, ProcessWait,
    ProgramRegistry, RandomReserve, SchedWaitQueueArch, NULL_DMA_ALLOC_FACILITY,
    NULL_MMIO_MAP_FACILITY, NULL_SEAT_REGISTRY, NULL_SHARED_MEM_FACILITY,
};
use tairix_kernel_ipc::PortRegistry;
use tairix_kernel_irq::{IrqTable, UnsupportedController};
use tairix_kernel_mem::{
    BootMemoryMap, FrameAllocator, MemoryRegion, PhysAddr, RegionKind, PAGE_SIZE,
};
use tairix_kernel_sched_cfq::{Scheduler, SchedulerConfig};
use tairix_kernel_sec::{CapTable, ProcessId};
use tairix_log::{log, Event, EventId, Level};
use tairix_sync::RwLock;

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// Gigabytes of identity map the boot address space provides: `[0, 2 GiB)`
/// covers the `virt` board's device MMIO (GiB 0) and the RAM base at GiB 1
/// where this kernel, its heap, and the frame pool live.
const IDENTITY_GIB: usize = 2;

/// Physical frames the production spawn producer draws from: the parent
/// plus the sandboxed workers of the run (decode, dying, replacement, probe,
/// session, and the supervised stream worker with its replacement), of which
/// an exited one returns its frames — image, stack, page tables, and the
/// `tairix-rt` heap each), where the fixture links the whole decode stack
/// (`lib/sandbox` + `lib/binfmt` + `lib/disasm`). Sized from the observed
/// per-process appetite with generous headroom (40 MiB).
const FRAME_COUNT: usize = 10240;

/// Cooperative-loop watchdog: the elapsed time past which the workload is
/// declared deadlocked.
///
/// A time budget rather than a step count, because the supervised leg parks
/// for its replacement's paced delay while the loop steps an empty run queue
/// at a rate no test should depend on. Far above the workload's worst case,
/// and below the harness's own timeout, so only a genuine hang reaches it.
const WATCHDOG_NS: u64 = 30_000_000_000;

/// Scheduler steps between watchdog clock reads, so the budget check costs
/// nothing measurable on the drive loop.
const STEPS_PER_CLOCK_READ: u64 = 1024;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4350);
const TEST_SPAWNED: EventId = EventId(4351);
const TEST_PASS: EventId = EventId(4352);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_GIC: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_FRAMES: NonZeroU16 = fail_point!(4);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(5);
const FAIL_SPAWN: NonZeroU16 = fail_point!(6);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(7);
const FAIL_NO_DISPATCH: NonZeroU16 = fail_point!(8);
const FAIL_HOOK_INSTALL: NonZeroU16 = fail_point!(9);
const FAIL_RESOLVER_INSTALL: NonZeroU16 = fail_point!(10);
const FAIL_BIAS: NonZeroU16 = fail_point!(11);
const FAIL_POLL: NonZeroU16 = fail_point!(12);
const FAIL_DRAINED: NonZeroU16 = fail_point!(13);
const FAIL_PARENT_STOPPED: NonZeroU16 = fail_point!(14);
/// The direct physical map could not be installed over the board's RAM.
const FAIL_PHYSMAP: NonZeroU16 = fail_point!(15);
/// Base finisher for a non-zero parent exit; the parent's diagnostic exit
/// code is added so the failing role/site is identifiable in the finisher.
const FAIL_EXIT_BASE: NonZeroU16 = fail_point!(100);

/// Size of the test's bump heap. Lives in `.bss` (zeroed by the trampoline).
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the kernel's own boot identity map.
static BOOT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Identity-mapped physical-frame backing store the live [`FrameAllocator`]
/// serves the spawn producer and the live-space producer from; inside
/// the 2 GiB identity window the producer's page-table walk requires.
#[repr(C, align(4096))]
struct FramePool([u8; PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; PAGE_SIZE * FRAME_COUNT]);

/// The dispatch-callback slot the production [`KernelDispatchHook`] is
/// installed into (one slot per binary, set once). Both the syscall
/// callback and the user-fault resolver resolve through it.
static DISPATCH_SLOT: DispatchCallbackSlot = DispatchCallbackSlot::new();

/// Per-CPU storage backing the scheduler's arch handle.
static SCHED_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// Per-CPU storage backing the dispatch hook + spawn ctx arch handle.
static HOOK_ARCH_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// This vertical binds no IRQ lines; the fail-closed controller mirrors
/// what `kernel/core::init` installs when a port exposes no routing.
static IRQ_CONTROLLER: UnsupportedController = UnsupportedController;

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn sandbox_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// The syscall-dispatch callback every program's `svc` traps reach. It
/// mirrors the production bin-crate callback (`dispatch_aarch64`): read the
/// kernel-stack args frame and forward through the resident production
/// [`KernelDispatchHook`] via the shared `dispatch_via_slot` bridge. An
/// empty slot or a missing caller context fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the exception trampoline lays the frame out on the kernel
    // stack and only invokes us with a valid pointer; the array lives at
    // least until we return.
    let args = unsafe { read_raw_args(args_ptr) };
    match dispatch_via_slot(&DISPATCH_SLOT, number, args) {
        Some(value) => value,
        None => qemu_exit::exit_failure(FAIL_NO_DISPATCH),
    }
}

/// The user-fault resolver the EL1 data-abort path calls for every EL0
/// data abort: the exact production glue (`production_user_fault`), bound
/// to this vertical's own slot so an unresolvable access kills the
/// faulting task through the production fault-exit path instead of
/// wedging the machine.
// The callback matches the arch `UserFaultResolveFn` type (a bare safe
// `extern "C" fn`); the raw pointer is only forwarded into the guarded
// `unsafe` call below, which narrows it with `as_ref`.
#[allow(clippy::not_unsafe_ptr_arg_deref)]
extern "C" fn sandbox_user_fault(
    far: u64,
    write: bool,
    regs: *const tairix_arch_api::backtrace::UserRegisterFrame,
) -> bool {
    // SAFETY: the trap handler builds the frame on its kernel stack and
    // holds it live across this call, or passes null; the slot helper
    // narrows the pointer with `as_ref` and never dereferences null.
    unsafe { resolve_user_fault_via_slot(&DISPATCH_SLOT, far, write, regs) }
}

/// The capability set the parent role runs under: `PROC_SPAWN` for the
/// seam's worker spawns, nothing else — the workers themselves are
/// branded capability-empty by the sandbox spawn mode regardless of any
/// registry request.
fn parent_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::PROC_SPAWN);
    caps
}

/// The program registry the production `spawn` syscall resolves the
/// seam's worker paths against: one `rxe` image, six rows. The roles
/// ride on the *path* (`arg(0)`) and the marker (`arg(1)`) — the seam's
/// launchers always pass `[path, role-marker]` as the startup vector,
/// which replaces the registry defaults — so every row requests no
/// capability and pins no arguments.
static CHILD_PROGRAMS: [EmbeddedProgram; 6] = [
    EmbeddedProgram {
        path: b"/bin/sbx",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[],
    },
    EmbeddedProgram {
        path: b"/bin/sbx-die",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[],
    },
    EmbeddedProgram {
        path: b"/bin/sbx-probe",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[],
    },
    EmbeddedProgram {
        path: b"/bin/sbx-session",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[],
    },
    EmbeddedProgram {
        path: b"/bin/sbx-stream",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[],
    },
    EmbeddedProgram {
        path: b"/bin/sbx-hang",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[],
    },
];

/// The registry over [`CHILD_PROGRAMS`].
static PROGRAMS: ProgramRegistry = ProgramRegistry::new(&CHILD_PROGRAMS);

/// Bring the board up: FP/SIMD on, the `virt` device tree discovered
/// (timer rate, GICv2 bases), the identity-gigapage masks configured from
/// the board facts, the identity MMU + EL1 vectors enabled, the GIC
/// initialised, and the dispatch callback + user-fault resolver installed.
/// Returns the discovered generic-timer rate.
fn bring_up_board() -> u64 {
    // Enable FP/SIMD at EL1 before any code the compiler may lower to NEON
    // (the `rxe` decoder, the spawn image fills, the log formatter).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Configure the board's gigapage facts, exactly as the production boot
    // path derives them from discovery: Device GiB 0 is the `virt` MMIO
    // window, and GiB 1 holds both this kernel's image and its RAM. The
    // production spawn producer sizes every child's identity window from
    // these masks, so driving it under the unconfigured defaults would
    // request a window reaching the user bias and the spawn would fail
    // closed.
    let mut device_mask = [0u64; GIGAPAGE_MASK_WORDS];
    device_mask[0] = 0b01;
    configure_device_gigapages(device_mask);
    let mut ram_mask = [0u64; GIGAPAGE_MASK_WORDS];
    ram_mask[0] = 0b10;
    configure_kernel_gigapages(ram_mask);
    // The production spawn producer reaches a child's page tables through
    // the direct physical map in the kernel translation regime, so the
    // chassis stands it up over the same RAM before driving the producer.
    if !install_boot_physmap(&ram_mask) {
        qemu_exit::exit_failure(FAIL_PHYSMAP);
    }

    // Enable the identity MMU + EL1 vectors before any atomic
    // read-modify-write runs: the frame allocator, the scheduler, and every
    // registry the test builds use atomics, which are UNPREDICTABLE on
    // MMU-off Device-typed memory (`plans/PI.md` P6c-2).
    let Some(boot_space) =
        ArchAddressSpace::new_identity_gigapages(&BOOT_PAGE_TABLES, IDENTITY_GIB)
    else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
    // heap, the frame pool, and the device MMIO (all within `[0, 2 GiB)` on
    // the `virt` board), so switching it does not move the ground under the
    // running code; `init_vectors` runs once on the boot CPU with a stack
    // established.
    unsafe {
        boot_space.switch();
        exceptions::init_vectors();
    }
    // The boot space's tables live in the static `BOOT_PAGE_TABLES` pool
    // and the handle carries no `Drop`, so letting it fall out of scope
    // leaves the active translation regime untouched for the kernel's
    // lifetime (the kernel never returns).
    // SAFETY: called once on the boot CPU after the GIC bases were
    // discovered above.
    unsafe {
        tairix_itest_gic::init_boot_cpu().expect("the GIC comes up");
    }
    syscall_entry::set_dispatch_callback(dispatch);
    // Bind the production user-fault resolver to this vertical's slot so a
    // misbehaving program is fault-killed, never left wedging the run.
    if tairix_arch_api::fault::set_user_fault_resolver(sandbox_user_fault).is_err() {
        qemu_exit::exit_failure(FAIL_RESOLVER_INSTALL);
    }
    counter_hz
}

/// The leaked-`'static` kernel subsystems the production dispatch hook and
/// spawn context borrow — the vertical's analogue of `KernelState`, lifted
/// by one-shot `Box::leak` publishes exactly as `kernel_core::kernel_main`
/// does (a one-shot publish, not a global mutable static).
struct Subsystems {
    frames: &'static FrameAllocator,
    sched: &'static Scheduler<Aarch64BinArch>,
    arch: &'static Aarch64BinArch,
    caps: &'static RwLock<CapTable>,
    peer_watch: &'static tairix_kernel_core::PeerWatch,
    ipc: &'static RwLock<PortRegistry>,
    aspaces: &'static RwLock<AddressSpaceRegistry>,
    rng: &'static RwLock<Box<dyn RandomReserve + Send + Sync>>,
    irq_table: &'static IrqTable,
}

/// Build the live kernel subsystems: the `kernel/mem` frame allocator over
/// the identity-mapped pool (so the spawn producer and the demand-fault
/// path draw their frames from the production path), the scheduler over
/// the production `KernelArch` wrapper, and the capability / port /
/// address-space / random / IRQ state the production hook borrows.
fn leak_subsystems(counter_hz: u64) -> Subsystems {
    let mut memory_map = BootMemoryMap::new();
    memory_map.push(MemoryRegion {
        start: PhysAddr::new(core::ptr::addr_of!(FRAME_POOL) as u64),
        length: (PAGE_SIZE * FRAME_COUNT) as u64,
        kind: RegionKind::Usable,
    });
    let Ok(frames) = FrameAllocator::new(&memory_map) else {
        qemu_exit::exit_failure(FAIL_FRAMES);
    };
    let frames: &'static FrameAllocator = Box::leak(Box::new(frames));

    let sched_arch = Arc::new(Aarch64BinArch::new(Aarch64Arch::new(
        &SCHED_STORAGE,
        BOOT_CPU,
        counter_hz,
    )));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), sched_arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    Subsystems {
        frames,
        sched: Box::leak(Box::new(sched)),
        arch: Box::leak(Box::new(Aarch64BinArch::new(Aarch64Arch::new(
            &HOOK_ARCH_STORAGE,
            BOOT_CPU,
            counter_hz,
        )))),
        caps: Box::leak(Box::new(RwLock::new(CapTable::new()))),
        peer_watch: Box::leak(Box::new(tairix_kernel_core::PeerWatch::new())),
        ipc: Box::leak(Box::new(RwLock::new(PortRegistry::new()))),
        aspaces: Box::leak(Box::new(RwLock::new(AddressSpaceRegistry::new()))),
        rng: Box::leak(Box::new(RwLock::new(
            Box::new(BootReserve::new()) as Box<dyn RandomReserve + Send + Sync>
        ))),
        irq_table: Box::leak(Box::new(IrqTable::new(0))),
    }
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `tairix_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 sandbox test: starting");

    let counter_hz = bring_up_board();

    // The fixture `rxe`'s baked relocations must target the bias the
    // production producer maps every child at; a drifted constant would
    // admit a child whose pointers do not match its mapping (fail closed).
    if USER_BIAS != USER_IMAGE_BIAS {
        qemu_exit::exit_failure(FAIL_BIAS);
    }

    let sys = leak_subsystems(counter_hz);

    // Publish the wait-queue arch hook so parked waiters (the parent in
    // `wait`) are genuinely unparked by their wake events — the same
    // adapter the production boot path installs.
    let wait_arch = SchedWaitQueueArch::leak(sys.sched, sys.arch);
    if tairix_kernel_core::waitq::install_wait_arch(wait_arch).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // The scheduler-side process-wait producer: records every parent/child
    // link the production spawn paths register and backs the production
    // `wait` syscall the parent blocks in.
    let wait_producer: &'static KernelProcessWait<Aarch64BinArch> =
        Box::leak(Box::new(KernelProcessWait::new(sys.arch)));

    // The production live-space producer: serves the `mem_map` pair every
    // `tairix-rt` heap (the parent's and each worker's) draws on.
    let live: &'static LiveMemMap<Aarch64BinArch> = Box::leak(Box::new(LiveMemMap::new(sys.arch)));

    // The scheduler-side process-signal producer: the seam ends a worker that
    // will not end itself — one still parsing past its deadline — with a
    // `signal` kill before it reaps it, exactly as on a production boot.
    let signal_producer = Box::leak(Box::new(tairix_kernel_core::KernelProcessSignal::new(
        wait_producer,
        sys.sched,
        sys.caps,
    )));

    // Publish the production dispatch hook: every syscall the programs
    // issue — `pipe_create`, `spawn` (with the sandbox attach block),
    // `stream_read`/`stream_write`, `fs_read`/`fs_write`/`fs_close`,
    // `mem_map`/`mem_unmap`, `signal`, `wait`, `exit` — and every user-fault
    // resolution runs the production caller-context resolution and
    // handler path.
    let hook: &'static KernelDispatchHook<'static, Aarch64BinArch> = Box::leak(Box::new(
        KernelDispatchHook::new(
            sys.sched,
            sys.caps,
            sys.arch,
            &SERIAL_SINK,
            sys.irq_table,
            &IRQ_CONTROLLER,
            sys.ipc,
            sys.aspaces,
            sys.rng,
            &UART_ONLY_CONSOLES,
            sys.frames,
            sys.frames,
            &PROGRAMS,
            wait_producer,
            // No seat / MMIO / DMA surface in this vertical; those
            // producers stay fail-closed.
            &NULL_SEAT_REGISTRY,
            live,
            &NULL_MMIO_MAP_FACILITY,
            &NULL_DMA_ALLOC_FACILITY,
        )
        .with_peer_watch(sys.peer_watch)
        .with_process_signal(signal_producer),
    ));
    if DISPATCH_SLOT.install_dispatcher(hook).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }
    // The hook is the producer's landing seam, so a signalled kill tears the
    // worker down through the one shared process teardown.
    if signal_producer.install_task_reclaim(hook).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }
    if tairix_kernel_core::install_deferred_kill_lander(signal_producer).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // Spawn the parent role through the production runtime-spawn seam
    // (`KernelSpawnCtx` assembly inside `KernelInitSpawner`), recorded
    // against the kernel supervisor identity so this chassis can reap it.
    // Publish the launch-services bundle the deferred child-load path reads:
    // the arch image builder builds each admitted child's image on the
    // child's own first slice, off this chassis's cooperative drive. The one
    // shared build+publish the production boot path uses.
    let _ = tairix_kernel_core::spawn_services::install_over(
        sys.arch,
        sys.frames,
        &SERIAL_SINK,
        &tairix_kernel_core::NULL_FILESYSTEM,
        None,
        sys.aspaces,
        sys.caps,
        sys.peer_watch,
        wait_producer,
        &AARCH64_PROCESS_SPAWN,
    );

    let init_ctx = KernelInitSpawner::new(
        sys.frames,
        &SERIAL_SINK,
        sys.sched,
        sys.caps,
        sys.peer_watch,
        sys.aspaces,
        sys.arch,
        wait_producer,
        sys.irq_table,
        &IRQ_CONTROLLER,
        &NULL_SHARED_MEM_FACILITY,
        KernelArch::cross_cpu_tlb_shootdown(sys.arch),
    );
    let Ok(parent_pid) = init_ctx.spawn_driver_process(
        "/bin/sbx",
        PROGRAM_RXE,
        parent_caps(),
        &[],
        &[b"/bin/sbx"],
        None,
    ) else {
        qemu_exit::exit_failure(FAIL_SPAWN);
    };
    note(
        TEST_SPAWNED,
        "aarch64 sandbox test: parent spawned through the production seam",
    );

    // The budget-bounded cooperative drive: step the scheduler and poll the
    // wait producer for the parent's exit between steps. The parent runs
    // the whole decode / containment / probe sequence through the seam's
    // production spawn + pipe + wait path; a parent exit of 0 is the PASS,
    // anything else names the failing site through its diagnostic code.
    // A task id never exceeds the ABI's pid bound, so reinterpreting it as
    // the signed pid the wait ABI carries is exact.
    let parent_pid = parent_pid.cast_signed();
    let started_ns = KernelArch::monotonic_ns(sys.arch, BOOT_CPU);
    let mut steps = 0u64;
    loop {
        let _ = sys.sched.step(BOOT_CPU);
        steps += 1;

        // Stand in for the production timer tick, which a chassis routes no
        // interrupt for: without it a timed park, such as the supervised
        // leg's paced wait, would never expire. Then deliver every wake a
        // handler deferred, as the production dispatch loop does between
        // steps; without that a child's `exit` never unparks the parent.
        tairix_kernel_core::timed_wake_sweep();
        let _ = tairix_kernel_core::waitq::drain_pending_wakes();

        match wait_producer.poll(ProcessId(0), parent_pid, WaitFlags::empty()) {
            Ok(reaped) => match reaped.status {
                WaitStatus::Exited(0) => {
                    note(
                        TEST_PASS,
                        "aarch64 sandbox test: parent drove the whole seam and exited 0",
                    );
                    qemu_exit::exit_success();
                }
                WaitStatus::Exited(code) => {
                    qemu_exit::exit_failure(fail_code(FAIL_EXIT_BASE, code));
                }
                WaitStatus::Stopped(_) => {
                    qemu_exit::exit_failure(FAIL_PARENT_STOPPED);
                }
            },
            Err(Errno::WouldBlock) => {}
            Err(_) => qemu_exit::exit_failure(FAIL_POLL),
        }

        // A fully drained workload without a reapable parent means the
        // parent vanished down a path that never recorded its exit; fail
        // with a distinct finisher rather than spinning out the watchdog.
        if sys.sched.live_task_count() == 0 {
            qemu_exit::exit_failure(FAIL_DRAINED);
        }

        if steps.is_multiple_of(STEPS_PER_CLOCK_READ)
            && KernelArch::monotonic_ns(sys.arch, BOOT_CPU).saturating_sub(started_ns)
                >= WATCHDOG_NS
        {
            qemu_exit::exit_failure(FAIL_DEADLOCK);
        }
    }
}
