//! The freestanding aarch64 test kernel: prove the `mem_pin` / `mem_unpin`
//! pair end to end (`plans/STRESSTEST.md` ST2).
//!
//! Unlike the bespoke micro-kernel harnesses, every syscall and every user
//! fault here runs the production `KernelDispatchHook` /
//! `KernelSyscallHandlers` path: the chassis installs the hook through a
//! `DispatchCallbackSlot`, binds the production user-fault resolver to the
//! same slot, wires the production `LiveMemMap` producer (backing
//! `mem_map` and the stack-growth fault path), a real `KernelProcessWait`,
//! and a `ProgramRegistry` carrying the three child roles, their numeric
//! parameters derived from the one shared `spawn_layout` policy. The parent
//! role is spawned through the production
//! `InitSpawnCtx::spawn_driver_process` seam; it spawns and reaps the
//! children through the production `spawn` + `wait` syscalls:
//!
//! * `deny` — holds no `CAP_MEM_PIN`: `mem_pin` is refused
//!   `PermissionDenied` at the dispatcher gate while the ungated
//!   `mem_unpin` still answers success, exits 0;
//! * `pin` — lowers its own `pinned-memory-bytes` bound via `rlimit_set`,
//!   pins itself (idempotently), sees an over-budget `mem_map` refused
//!   `OutOfRange` and a within-budget one succeed, unpins, and sees the
//!   formerly refused map succeed, exits 0;
//! * `child` — spawned by the *pinned* parent: starts unpinned (the mark
//!   is never inherited even though the lowered limit is) so its
//!   over-budget map succeeds, exits 0.
//!
//! The shared source also drives a private production call endpoint. The
//! one-vCPU package is the control; the four-vCPU sibling starts real
//! secondary dispatchers and repeatedly pauses the observed source after the
//! caller blocks so another CPU must steal and resume it. Every reply is
//! checked together with integer/FP, stack, PC, and address-space-local state.

use core::num::NonZeroU16;
use core::panic::PanicInfo;
#[cfg(migration_smp)]
use core::sync::atomic::{AtomicPtr, AtomicU32};
use core::sync::atomic::{AtomicU64, Ordering};

use alloc::boxed::Box;
use alloc::sync::Arc;

#[cfg(migration_smp)]
use crate::progress::StallGuard;
use tairix_abi::{CapabilityId, Errno, WaitFlags, WaitStatus, SYSCALL_MAX_ARGS};
use tairix_arch_aarch64::context_hal::ContextSwitchHal;
use tairix_arch_aarch64::kernel_arch::timer_frequency_hz;
#[cfg(migration_smp)]
use tairix_arch_aarch64::kernel_arch::SecondaryStart;
use tairix_arch_aarch64::paging::{
    configure_device_gigapages, configure_kernel_gigapages, install_boot_physmap,
    AddressSpace as ArchAddressSpace, PageTablePool, GIGAPAGE_MASK_WORDS,
};
use tairix_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, Aarch64Arch,
    Aarch64ArchStorage, SERIAL_SINK,
};
#[cfg(migration_smp)]
use tairix_arch_aarch64::{preempt, smp};
use tairix_arch_api::BOOT_CPU;
#[cfg(migration_smp)]
use tairix_arch_api::{CpuId, SecondaryBringup};
use tairix_caps::CapabilitySet;
use tairix_fdt::Fdt;
use tairix_itest_finisher::fail_code;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel::aarch64::arch_wrapper::{Aarch64BinArch, UART_ONLY_CONSOLES};
use tairix_kernel::aarch64::spawn_producer::{AARCH64_PROCESS_SPAWN, USER_IMAGE_BIAS};
use tairix_kernel::dispatch_core::{dispatch_via_slot, read_raw_args, resolve_user_fault_via_slot};
use tairix_kernel::spawn_layout::USER_STACK_COMMIT_PAGES;
use tairix_kernel_core::{
    spawn_kthread, AddressSpaceRegistry, BootReserve, DispatchCallbackSlot, EmbeddedProgram,
    InitSpawnCtx, KernelArch, KernelDispatchHook, KernelInitSpawner, KernelProcessWait, LiveMemMap,
    ProcessWait, ProgramRegistry, RandomReserve, SchedWaitQueueArch, Yielder,
    NULL_DMA_ALLOC_FACILITY, NULL_MMIO_MAP_FACILITY, NULL_SEAT_REGISTRY, NULL_SHARED_MEM_FACILITY,
};
use tairix_kernel_ipc::{CallEndpoint, CallEndpointLimits, EndpointId, PortRegistry, RecvCall};
use tairix_kernel_irq::{IrqTable, UnsupportedController};
use tairix_kernel_mem::{
    BootMemoryMap, FrameAllocator, MemoryRegion, PhysAddr, RegionKind, PAGE_SIZE,
};
use tairix_kernel_sched_api::Priority;
#[cfg(migration_smp)]
use tairix_kernel_sched_api::{SchedulerArch, StepOutcome};
use tairix_kernel_sched_cfq::{Scheduler, SchedulerConfig};
use tairix_kernel_sec::{CapTable, ProcessId, TaskCapabilities, UserId};
use tairix_log::{log, Event, EventId, Level};
use tairix_sync::RwLock;

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

#[cfg(migration_smp)]
const CPU_COUNT: u32 = 4;
#[cfg(not(migration_smp))]
const CPU_COUNT: u32 = 1;
const CPU_MPIDRS: [u64; 4] = [0, 1, 2, 3];

/// Gigabytes of identity map the boot address space provides: `[0, 2 GiB)`
/// covers the `virt` board's device MMIO (GiB 0) and the RAM base at GiB 1
/// where this kernel, its heap, and the frame pool live.
const IDENTITY_GIB: usize = 2;

/// Physical frames the production spawn producer draws from: four spawned
/// processes (image, eagerly committed stack top, page tables,
/// identity-window tables) plus the fixture's successful anonymous maps
/// (one [`WITHIN_BYTES`] and two [`OVER_BYTES`] regions ≈ 4.25 MiB).
/// Sized from that appetite with generous headroom (16 MiB).
const FRAME_COUNT: usize = 4096;

/// The `pinned-memory-bytes` bound the `pin` role (and the parent) impose
/// on themselves: the eagerly committed stack top plus 1 MiB of headroom.
/// Derived from the one shared policy constant so the budget always sits
/// above the spawn-time footprint (the committed stack) with room for the
/// within-budget map, while every [`OVER_BYTES`] request decisively
/// crosses it.
const PIN_BOUND_BYTES: u64 = USER_STACK_COMMIT_PAGES * PAGE_SIZE as u64 + (1 << 20);

/// Bytes of the within-budget map the pinned `pin` role performs: far
/// inside the 1 MiB headroom above the spawn-time footprint.
const WITHIN_BYTES: u64 = 256 << 10;

/// Bytes of the over-budget map: with the spawn-time footprint at least
/// the committed stack, `footprint + OVER_BYTES` always crosses
/// [`PIN_BOUND_BYTES`] (2 MiB > 1 MiB headroom), while an unpinned
/// process maps it freely.
const OVER_BYTES: u64 = 2 << 20;

/// Longest decimal argument the rows below need (`u64::MAX` is 20 digits).
const DEC_MAX: usize = 20;

/// Render `value` as a fixed-width, zero-padded decimal byte string at
/// compile time. Leading zeroes are harmless: the fixture's parser accepts
/// them, and a fixed width lets the argument live in a `static` the
/// registry row borrows.
const fn dec_bytes(mut value: u64) -> [u8; DEC_MAX] {
    let mut out = [b'0'; DEC_MAX];
    let mut i = DEC_MAX;
    while i > 0 {
        i -= 1;
        out[i] = b'0' + (value % 10) as u8;
        value /= 10;
        if value == 0 {
            break;
        }
    }
    out
}

/// [`PIN_BOUND_BYTES`] as a decimal argument-vector value.
static PIN_BOUND_ARG: [u8; DEC_MAX] = dec_bytes(PIN_BOUND_BYTES);
/// [`WITHIN_BYTES`] as a decimal argument-vector value.
static WITHIN_ARG: [u8; DEC_MAX] = dec_bytes(WITHIN_BYTES);
/// [`OVER_BYTES`] as a decimal argument-vector value.
static OVER_ARG: [u8; DEC_MAX] = dec_bytes(OVER_BYTES);

/// Liveness budget for the cooperative driver loops, sized generously for
/// QEMU TCG. In the single-CPU `drive_process` loop, where the process
/// advances only when the boot CPU steps it, this bounds the total steps
/// before the run is declared deadlocked. In the four-vCPU migration driver,
/// where the child advances independently on the secondaries, it instead
/// bounds the *consecutive no-progress* iterations (the `StallGuard`), so the
/// give-up there measures the child's progress rather than the controller's
/// spin rate against a host-scheduled backdrop.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4460);
const TEST_SPAWNED: EventId = EventId(4461);
const TEST_PASS: EventId = EventId(4462);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_GIC: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_FRAMES: NonZeroU16 = fail_point!(4);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(5);
const FAIL_SPAWN: NonZeroU16 = fail_point!(6);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(7);
const FAIL_NO_DISPATCH: NonZeroU16 = fail_point!(8);
const FAIL_HOOK_INSTALL: NonZeroU16 = fail_point!(9);
const FAIL_RESOLVER_INSTALL: NonZeroU16 = fail_point!(10);
const FAIL_BIAS: NonZeroU16 = fail_point!(11);
const FAIL_POLL: NonZeroU16 = fail_point!(12);
const FAIL_PARENT_STOPPED: NonZeroU16 = fail_point!(14);
const FAIL_ENDPOINT: NonZeroU16 = fail_point!(15);
const FAIL_SERVER: NonZeroU16 = fail_point!(16);
const FAIL_IPC_CONTROL: NonZeroU16 = fail_point!(17);
#[cfg(migration_smp)]
const FAIL_SECONDARY: NonZeroU16 = fail_point!(18);
#[cfg(migration_smp)]
const FAIL_NO_MIGRATION: NonZeroU16 = fail_point!(19);
/// The direct physical map could not be installed over the board's RAM.
const FAIL_PHYSMAP: NonZeroU16 = fail_point!(20);
/// Base finisher for a non-zero parent exit; the parent's diagnostic exit
/// code is added so the failing role/site is identifiable in the finisher.
const FAIL_EXIT_BASE: NonZeroU16 = fail_point!(100);

/// Size of the test's bump heap. Lives in `.bss` (zeroed by the trampoline).
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the kernel's own boot identity map.
static BOOT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Identity-mapped physical-frame backing store the live [`FrameAllocator`]
/// serves the spawn producer and the stack-growth fault path from; inside
/// the 2 GiB identity window the producer's page-table walk requires.
#[repr(C, align(4096))]
struct FramePool([u8; PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; PAGE_SIZE * FRAME_COUNT]);

/// The dispatch-callback slot the production [`KernelDispatchHook`] is
/// installed into (one slot per binary, set once). Both the syscall
/// callback and the user-fault resolver resolve through it.
static DISPATCH_SLOT: DispatchCallbackSlot = DispatchCallbackSlot::new();

/// Per-CPU storage backing the scheduler's arch handle.
static SCHED_STORAGE: Aarch64ArchStorage<4> = Aarch64ArchStorage::new();

/// Per-CPU storage backing the dispatch hook + spawn ctx arch handle.
static HOOK_ARCH_STORAGE: Aarch64ArchStorage<4> = Aarch64ArchStorage::new();

#[cfg(migration_smp)]
static SMP_SCHEDULER: AtomicPtr<Scheduler<Aarch64BinArch>> = AtomicPtr::new(core::ptr::null_mut());
#[cfg(migration_smp)]
static SMP_ONLINE: AtomicU32 = AtomicU32::new(0);
#[cfg(migration_smp)]
static SMP_PAUSED: AtomicU32 = AtomicU32::new(0);

/// This vertical binds no IRQ lines; the fail-closed controller mirrors
/// what `kernel/core::init` installs when a port exposes no routing.
static IRQ_CONTROLLER: UnsupportedController = UnsupportedController;

/// Private call endpoint used only by the migration fixture role.
const MIGRATION_ENDPOINT: u64 = 0x4d49_4752_4154_4501;

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn mem_pin_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// The syscall-dispatch callback every program's `svc` traps reach. It
/// mirrors the production bin-crate callback (`dispatch_aarch64`): read the
/// kernel-stack args frame and forward through the resident production
/// [`KernelDispatchHook`] via the shared `dispatch_via_slot` bridge. An
/// empty slot or a missing caller context fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the exception trampoline lays the frame out on the kernel
    // stack and only invokes us with a valid pointer; the array lives at
    // least until we return.
    let args = unsafe { read_raw_args(args_ptr) };
    match dispatch_via_slot(&DISPATCH_SLOT, number, args) {
        Some(value) => value,
        None => qemu_exit::exit_failure(FAIL_NO_DISPATCH),
    }
}

/// The user-fault resolver the EL1 data-abort path calls for every EL0
/// data abort: the exact production glue (`production_user_fault`), bound
/// to this vertical's own slot so an in-span fault (read or write — a
/// stack push is a write) runs the resident production hook's
/// `resolve_stack_fault` growth path and an unresolvable fault (past the
/// bound, below the span) kills the faulting task through the production
/// fault-exit path.
// The callback matches the arch `UserFaultResolveFn` type (a bare safe
// `extern "C" fn`); the raw pointer is only forwarded into the guarded
// `unsafe` call below, which narrows it with `as_ref`.
#[allow(clippy::not_unsafe_ptr_arg_deref)]
extern "C" fn mem_pin_user_fault(
    far: u64,
    write: bool,
    regs: *const tairix_arch_api::backtrace::UserRegisterFrame,
) -> bool {
    // SAFETY: the trap handler builds the frame on its kernel stack and
    // holds it live across this call, or passes null; the slot helper
    // narrows the pointer with `as_ref` and never dereferences null.
    unsafe { resolve_user_fault_via_slot(&DISPATCH_SLOT, far, write, regs) }
}

/// The capability set the parent runs under: `PROC_SPAWN` for its `spawn`
/// calls and `MEM_PIN` for its own pin. The parent's set doubles as the
/// inherited ceiling the production spawn intersects each child's manifest
/// request with, so the `pin` child's `MEM_PIN` request is grantable while
/// `deny` and `child` (which request nothing) genuinely hold nothing.
fn parent_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::PROC_SPAWN);
    caps.insert(CapabilityId::MEM_PIN);
    caps
}

/// The program registry the production `spawn` syscall resolves the
/// parent's child paths against: one `rxe` image, three rows, each pinning
/// its role and its policy-derived numeric parameters through the
/// registered default argument vector. Only the `pin` role requests
/// `CAP_MEM_PIN`; `deny` exists precisely because it holds nothing.
static CHILD_PROGRAMS: [EmbeddedProgram; 3] = [
    EmbeddedProgram {
        path: b"/bin/mp-deny",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"mp", b"deny"],
    },
    EmbeddedProgram {
        path: b"/bin/mp-pin",
        rxe: PROGRAM_RXE,
        caps: &[CapabilityId::MEM_PIN],
        args: &[b"mp", b"pin", &PIN_BOUND_ARG, &WITHIN_ARG, &OVER_ARG],
    },
    EmbeddedProgram {
        path: b"/bin/mp-child",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"mp", b"child", &OVER_ARG],
    },
];

/// The registry over [`CHILD_PROGRAMS`].
static PROGRAMS: ProgramRegistry = ProgramRegistry::new(&CHILD_PROGRAMS);

/// Bring the board up: FP/SIMD on, the `virt` device tree discovered
/// (timer rate, GICv2 bases), the identity-gigapage masks configured from
/// the board facts, the identity MMU + EL1 vectors enabled, the GIC
/// initialised, and the dispatch callback + user-fault resolver installed.
/// Returns the discovered generic-timer rate.
fn bring_up_board() -> u64 {
    // Enable FP/SIMD at EL1 before any code the compiler may lower to NEON
    // (the `rxe` decoder, the spawn image fills, the log formatter).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Configure the board's gigapage facts, exactly as the production boot
    // path derives them from discovery: Device GiB 0 is the `virt` MMIO
    // window, and GiB 1 holds both this kernel's image and its RAM. The
    // production spawn producer sizes every child's identity window from
    // these masks, so driving it under the unconfigured defaults would
    // request a window reaching the user bias and the spawn would fail
    // closed.
    let mut device_mask = [0u64; GIGAPAGE_MASK_WORDS];
    device_mask[0] = 0b01;
    configure_device_gigapages(device_mask);
    let mut ram_mask = [0u64; GIGAPAGE_MASK_WORDS];
    ram_mask[0] = 0b10;
    configure_kernel_gigapages(ram_mask);
    // The production spawn producer reaches a child's page tables through
    // the direct physical map in the kernel translation regime, so the
    // chassis stands it up over the same RAM before driving the producer.
    if !install_boot_physmap(&ram_mask) {
        qemu_exit::exit_failure(FAIL_PHYSMAP);
    }

    // Enable the identity MMU + EL1 vectors before any atomic
    // read-modify-write runs: the frame allocator, the scheduler, and every
    // registry the test builds use atomics, which are UNPREDICTABLE on
    // MMU-off Device-typed memory (`plans/PI.md` P6c-2).
    let Some(boot_space) =
        ArchAddressSpace::new_identity_gigapages(&BOOT_PAGE_TABLES, IDENTITY_GIB)
    else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
    // heap, the frame pool, and the device MMIO (all within `[0, 2 GiB)` on
    // the `virt` board), so switching it does not move the ground under the
    // running code; `init_vectors` runs once on the boot CPU with a stack
    // established.
    unsafe {
        boot_space.switch();
        exceptions::init_vectors();
    }
    // The boot space's tables live in the static `BOOT_PAGE_TABLES` pool
    // and the handle carries no `Drop`, so letting it fall out of scope
    // leaves the active translation regime untouched for the kernel's
    // lifetime (the kernel never returns).
    // SAFETY: called once on the boot CPU after the GIC bases were
    // discovered above.
    unsafe {
        gic::init();
    }
    syscall_entry::set_dispatch_callback(dispatch);
    // Bind the production user-fault resolver to this vertical's slot — the
    // fault-driven growth heart this test exists to prove.
    if tairix_arch_api::fault::set_user_fault_resolver(mem_pin_user_fault).is_err() {
        qemu_exit::exit_failure(FAIL_RESOLVER_INSTALL);
    }
    counter_hz
}

/// The leaked-`'static` kernel subsystems the production dispatch hook and
/// spawn context borrow — the vertical's analogue of `KernelState`, lifted
/// by one-shot `Box::leak` publishes exactly as `kernel_core::kernel_main`
/// does (a one-shot publish, not a global mutable static).
struct Subsystems {
    frames: &'static FrameAllocator,
    sched: &'static Scheduler<Aarch64BinArch>,
    arch: &'static Aarch64BinArch,
    caps: &'static RwLock<CapTable>,
    peer_watch: &'static tairix_kernel_core::PeerWatch,
    ipc: &'static RwLock<PortRegistry>,
    aspaces: &'static RwLock<AddressSpaceRegistry>,
    rng: &'static RwLock<Box<dyn RandomReserve + Send + Sync>>,
    irq_table: &'static IrqTable,
}

/// Build the live kernel subsystems: the `kernel/mem` frame allocator over
/// the identity-mapped pool (so the spawn producer and the demand-fault
/// path draw their frames from the production path), the scheduler over
/// the production `KernelArch` wrapper, and the capability / port /
/// address-space / random / IRQ state the production hook borrows.
fn leak_subsystems(counter_hz: u64) -> Subsystems {
    let mut memory_map = BootMemoryMap::new();
    memory_map.push(MemoryRegion {
        start: PhysAddr::new(core::ptr::addr_of!(FRAME_POOL) as u64),
        length: (PAGE_SIZE * FRAME_COUNT) as u64,
        kind: RegionKind::Usable,
    });
    let Ok(frames) = FrameAllocator::new(&memory_map) else {
        qemu_exit::exit_failure(FAIL_FRAMES);
    };
    let frames: &'static FrameAllocator = Box::leak(Box::new(frames));

    let sched_inner = Aarch64Arch::with_cpus(
        &SCHED_STORAGE,
        BOOT_CPU,
        counter_hz,
        &CPU_MPIDRS[..CPU_COUNT as usize],
    );
    let hook_inner = Aarch64Arch::with_cpus(
        &HOOK_ARCH_STORAGE,
        BOOT_CPU,
        counter_hz,
        &CPU_MPIDRS[..CPU_COUNT as usize],
    );
    #[cfg(migration_smp)]
    let (sched_inner, hook_inner) = {
        let method = Fdt::new(DTB_BLOB)
            .ok()
            .and_then(|fdt| tairix_arch_aarch64::fdt::psci_method(&fdt))
            .unwrap_or_else(|| qemu_exit::exit_failure(FAIL_SECONDARY));
        (
            sched_inner.with_secondary_start(SecondaryStart::Psci(method)),
            hook_inner.with_secondary_start(SecondaryStart::Psci(method)),
        )
    };
    let sched_arch = Arc::new(Aarch64BinArch::new(sched_inner));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(CPU_COUNT), sched_arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    Subsystems {
        frames,
        sched: Box::leak(Box::new(sched)),
        arch: Box::leak(Box::new(Aarch64BinArch::new(hook_inner))),
        caps: Box::leak(Box::new(RwLock::new(CapTable::new()))),
        peer_watch: Box::leak(Box::new(tairix_kernel_core::PeerWatch::new())),
        ipc: Box::leak(Box::new(RwLock::new(PortRegistry::new()))),
        aspaces: Box::leak(Box::new(RwLock::new(AddressSpaceRegistry::new()))),
        rng: Box::leak(Box::new(RwLock::new(
            Box::new(BootReserve::new()) as Box<dyn RandomReserve + Send + Sync>
        ))),
        irq_table: Box::leak(Box::new(IrqTable::new(0))),
    }
}

/// Register the private migration endpoint and spawn its event-driven echo
/// server as a real scheduler kthread.
fn install_echo_server(sys: &Subsystems) {
    let empty = CapabilitySet::empty();
    let creator = TaskCapabilities::derive(
        ProcessId(0x4d49_4752),
        UserId(0),
        empty,
        empty,
        &SERIAL_SINK,
    );
    let endpoint = match CallEndpoint::create(
        EndpointId(MIGRATION_ENDPOINT),
        &creator,
        CapabilitySet::empty(),
        CapabilitySet::empty(),
        CallEndpointLimits {
            max_request: 8,
            max_reply: 8,
            capacity: 8,
        },
        &SERIAL_SINK,
    ) {
        Ok(endpoint) => Arc::new(endpoint),
        Err(_) => qemu_exit::exit_failure(FAIL_ENDPOINT),
    };
    if tairix_kernel_core::callreg::register(Arc::clone(&endpoint), &SERIAL_SINK).is_err() {
        qemu_exit::exit_failure(FAIL_ENDPOINT);
    }
    let server_id = Arc::new(AtomicU64::new(0));
    let body_id = Arc::clone(&server_id);
    let body_endpoint = Arc::clone(&endpoint);
    let server = spawn_kthread(
        sys.sched,
        ContextSwitchHal::new(),
        BOOT_CPU,
        Priority::High,
        move |yielder: &mut Yielder<ContextSwitchHal>| {
            let id = body_id.load(Ordering::Acquire);
            body_endpoint.record_server_task(id);
            loop {
                tairix_kernel_core::waitq::SERVE_WAITQ
                    .register(id, tairix_kernel_core::waitq::NO_DEADLINE);
                match body_endpoint.recv_call(8) {
                    RecvCall::Received(call) => {
                        tairix_kernel_core::waitq::SERVE_WAITQ.deregister(id);
                        let poster =
                            match body_endpoint.reply(call.ticket, &call.request, &SERIAL_SINK) {
                                Ok(poster) => poster,
                                Err(_) => qemu_exit::exit_failure(FAIL_SERVER),
                            };
                        tairix_kernel_core::waitq::call_wake_task(poster);
                    }
                    RecvCall::Empty => {
                        yielder.park();
                        tairix_kernel_core::waitq::SERVE_WAITQ.deregister(id);
                    }
                    RecvCall::TooLarge { .. } => qemu_exit::exit_failure(FAIL_SERVER),
                }
            }
        },
    );
    let Ok(server) = server else {
        qemu_exit::exit_failure(FAIL_SERVER);
    };
    server_id.store(server, Ordering::Release);
}

/// Drive CPU 0 until the kernel-parented `pid` exits and return its code.
fn drive_process(sys: &Subsystems, wait: &KernelProcessWait<Aarch64BinArch>, pid: u64) -> i32 {
    // A kernel-minted process id round-trips through the `i32` the wait ABI
    // carries.
    // A task id never exceeds the ABI's pid bound, so reinterpreting it as
    // the signed pid the wait ABI carries is exact.
    let pid = pid.cast_signed();
    for _ in 0..MAX_STEPS {
        let _ = sys.sched.step(BOOT_CPU);
        let _ = tairix_kernel_core::waitq::drain_pending_wakes();
        match wait.poll(ProcessId(0), pid, WaitFlags::empty()) {
            Ok(reaped) => match reaped.status {
                WaitStatus::Exited(code) => return code,
                WaitStatus::Stopped(_) => qemu_exit::exit_failure(FAIL_PARENT_STOPPED),
            },
            Err(Errno::WouldBlock) => {}
            Err(_) => qemu_exit::exit_failure(FAIL_POLL),
        }
    }
    qemu_exit::exit_failure(FAIL_DEADLOCK)
}

/// Secondary-core entry for the four-vCPU migration package.
#[cfg(migration_smp)]
extern "C" fn migration_secondary(cpu: CpuId) -> ! {
    // SAFETY: the boot core published the permanent identity root before
    // issuing CPU_ON; this secondary has not enabled interrupts yet.
    if !unsafe { tairix_arch_aarch64::paging::adopt_boot_translation() } {
        qemu_exit::exit_failure(FAIL_SECONDARY);
    }
    // SAFETY: per-CPU vector/GIC/SGI setup on this secondary, exactly once.
    unsafe {
        exceptions::init_vectors();
        gic::init();
        preempt::enable_ipi();
        exceptions::enable_irq();
    }
    SMP_ONLINE.fetch_or(1u32 << cpu, Ordering::Release);
    let scheduler = SMP_SCHEDULER.load(Ordering::Acquire);
    if scheduler.is_null() {
        qemu_exit::exit_failure(FAIL_SECONDARY);
    }
    // SAFETY: `start_migration_secondaries` publishes the leaked scheduler
    // before CPU_ON and it remains live for the kernel's lifetime.
    let scheduler = unsafe { &*scheduler };
    loop {
        if SMP_PAUSED.load(Ordering::Acquire) & (1u32 << cpu) != 0 {
            // Deliberately paused by the controller. Park until the release
            // IPI, closing the pause/wake race the same way the production
            // dispatch loop closes the idle/wake race: mask IRQ *taking*,
            // re-check the pause under the mask, and `wfi` only while still
            // paused. The release IPI then arrives pending-but-masked and
            // still wakes the `wfi`, so it is never dropped by the handler
            // acknowledging it just before the park. Restore taking
            // (dispatching the IPI) before re-checking at the loop top.
            //
            // SAFETY: `mask_irq`/`enable_irq` toggle `DAIF.I` only; this
            // secondary's vectors + GICv2 are live, so a taken IPI
            // dispatches through a valid handler.
            unsafe { exceptions::mask_irq() };
            if SMP_PAUSED.load(Ordering::Acquire) & (1u32 << cpu) != 0 {
                // SAFETY: `wfi` wakes on the pending-but-masked release IPI;
                // no lock is held across the park.
                unsafe { exceptions::wait_for_interrupt() };
            }
            // SAFETY: restore IRQ taking so the release IPI is dispatched.
            unsafe { exceptions::enable_irq() };
            continue;
        }
        let outcome = scheduler.step(cpu);
        if matches!(outcome, Ok(StepOutcome::Idle)) {
            // Tickless idle park under the production park/wake protocol
            // (`kernel_core::init::run_dispatch_loop`): mask IRQ taking,
            // then — under the mask — drain any flagged wake and re-check
            // both for ready work (a placement IPI landing during the step
            // enqueued a just-woken task here) and a fresh pause request,
            // and `wfi` only if still genuinely idle. A placement or release
            // IPI landing in the check->park window stays pending-but-masked
            // and wakes the `wfi`, so a readied task can never be stranded
            // on this sleeping CPU (the lost-wakeup that stalled this
            // vertical under the full matrix). Restore taking afterwards so
            // the pending IPI dispatches.
            //
            // SAFETY: `mask_irq`/`enable_irq` toggle `DAIF.I` only; vectors
            // + GICv2 are live on this CPU.
            unsafe { exceptions::mask_irq() };
            let woke = tairix_kernel_core::waitq::drain_pending_wakes();
            let ready = scheduler.has_ready_work(cpu).unwrap_or(false);
            let paused = SMP_PAUSED.load(Ordering::Acquire) & (1u32 << cpu) != 0;
            if !(woke || ready || paused) {
                // SAFETY: `wfi` wakes on a pending-but-masked interrupt (the
                // scheduler's placement IPI when work lands here, a device
                // IRQ, or the controller's release IPI); no lock is held.
                unsafe { exceptions::wait_for_interrupt() };
            }
            // SAFETY: restore IRQ taking so the pending interrupt dispatches.
            unsafe { exceptions::enable_irq() };
        } else {
            // A task ran (or a benign step error): drain deferred wakes in
            // dispatcher context with IRQ taking enabled, matching the
            // production loop's between-dispatch servicing.
            let _ = tairix_kernel_core::waitq::drain_pending_wakes();
        }
    }
}

/// Start CPUs 1..3 and wait until their dispatch loops are live.
#[cfg(migration_smp)]
fn start_migration_secondaries(sys: &Subsystems) {
    static STACKS: smp::SecondaryStackPool<4> = smp::SecondaryStackPool::new();
    SMP_SCHEDULER.store(sys.sched as *const _ as *mut _, Ordering::Release);
    if STACKS.register().is_err() || smp::set_secondary_entry(migration_secondary).is_err() {
        qemu_exit::exit_failure(FAIL_SECONDARY);
    }
    preempt::set_ipi_callback(tairix_kernel_core::on_reschedule_ipi);
    preempt::set_preempt_callback(tairix_kernel_core::on_user_preempt_point);
    // SAFETY: boot CPU vectors/GIC are live and callbacks are installed.
    unsafe {
        preempt::enable_ipi();
        exceptions::enable_irq();
    }
    for cpu in 1..CPU_COUNT {
        // SAFETY: topology, stack pool, and callback are published; each id
        // names a distinct parked QEMU CPU.
        if unsafe { sys.arch.arch().start_secondary(cpu) }.is_err() {
            qemu_exit::exit_failure(FAIL_SECONDARY);
        }
    }
    let expected = ((1u32 << CPU_COUNT) - 1) & !1;
    while SMP_ONLINE.load(Ordering::Acquire) != expected {
        core::hint::spin_loop();
    }
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `tairix_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 mem-pin test: starting");

    let counter_hz = bring_up_board();

    // The fixture `rxe`'s baked relocations must target the bias the
    // production producer maps every child at; a drifted constant would
    // admit a child whose pointers do not match its mapping (fail closed).
    if USER_BIAS != USER_IMAGE_BIAS {
        qemu_exit::exit_failure(FAIL_BIAS);
    }

    let sys = leak_subsystems(counter_hz);

    // Publish the wait-queue arch hook so parked waiters (the parent in
    // `wait`) are genuinely unparked by their wake events — the same
    // adapter the production boot path installs.
    let wait_arch = SchedWaitQueueArch::leak(sys.sched, sys.arch);
    if tairix_kernel_core::waitq::install_wait_arch(wait_arch).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }
    install_echo_server(&sys);

    // The scheduler-side process-wait producer: records every parent/child
    // link the production spawn paths register and backs the production
    // `wait` syscall the parent blocks in.
    let wait_producer: &'static KernelProcessWait<Aarch64BinArch> =
        Box::leak(Box::new(KernelProcessWait::new(sys.arch)));

    // The production live-space producer: serves the `mem_map` pair (the
    // `tairix-rt` heap) and — the point of this vertical — the one-page-
    // per-fault backing the stack-growth resolver maps through it.
    let live: &'static LiveMemMap<Aarch64BinArch> = Box::leak(Box::new(LiveMemMap::new(sys.arch)));

    // Publish the production dispatch hook: every syscall the programs
    // issue — `spawn`, `wait`, `rlimit_set`, `exit` — and every user-fault
    // resolution runs the production caller-context resolution and handler
    // path.
    let hook: &'static KernelDispatchHook<'static, Aarch64BinArch> = Box::leak(Box::new(
        KernelDispatchHook::new(
            sys.sched,
            sys.caps,
            sys.arch,
            &SERIAL_SINK,
            sys.irq_table,
            &IRQ_CONTROLLER,
            sys.ipc,
            sys.aspaces,
            sys.rng,
            &UART_ONLY_CONSOLES,
            sys.frames,
            sys.frames,
            &PROGRAMS,
            wait_producer,
            // No seat / MMIO / DMA surface in this vertical; those
            // producers stay fail-closed. No filesystem or file-map
            // producer either: the only faults this vertical exists to
            // exercise are stack growth, the `StackBytes` bound, and the
            // below-span guard.
            &NULL_SEAT_REGISTRY,
            live,
            &NULL_MMIO_MAP_FACILITY,
            &NULL_DMA_ALLOC_FACILITY,
        )
        .with_peer_watch(sys.peer_watch),
    ));
    if DISPATCH_SLOT.install_dispatcher(hook).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }
    #[cfg(migration_smp)]
    start_migration_secondaries(&sys);

    // Spawn the parent role through the production runtime-spawn seam
    // (`KernelSpawnCtx` assembly inside `KernelInitSpawner`), recorded
    // against the kernel supervisor identity so this chassis can reap it.
    // Publish the launch-services bundle the deferred child-load path reads:
    // the arch image builder builds each admitted child's image on the
    // child's own first slice, off this chassis's cooperative drive. The one
    // shared build+publish the production boot path uses.
    let _ = tairix_kernel_core::spawn_services::install_over(
        sys.arch,
        sys.frames,
        &SERIAL_SINK,
        &tairix_kernel_core::NULL_FILESYSTEM,
        None,
        sys.aspaces,
        sys.caps,
        sys.peer_watch,
        wait_producer,
        &AARCH64_PROCESS_SPAWN,
    );

    let init_ctx = KernelInitSpawner::new(
        sys.frames,
        &SERIAL_SINK,
        sys.sched,
        sys.caps,
        sys.peer_watch,
        sys.aspaces,
        sys.arch,
        wait_producer,
        sys.irq_table,
        &NULL_SHARED_MEM_FACILITY,
        KernelArch::cross_cpu_tlb_shootdown(sys.arch),
    );
    let Ok(parent_pid) = init_ctx.spawn_driver_process(
        "/bin/mp-parent",
        PROGRAM_RXE,
        parent_caps(),
        &[],
        &[b"mp", b"parent", &PIN_BOUND_ARG],
        None,
    ) else {
        qemu_exit::exit_failure(FAIL_SPAWN);
    };
    note(
        TEST_SPAWNED,
        "aarch64 mem-pin test: parent spawned through the production seam",
    );

    let parent_code = drive_process(&sys, wait_producer, parent_pid);
    if parent_code != 0 {
        qemu_exit::exit_failure(fail_code(FAIL_EXIT_BASE, parent_code));
    }

    let ipc_pid = match init_ctx.spawn_driver_process(
        "/bin/mp-ipc",
        PROGRAM_RXE,
        CapabilitySet::empty(),
        &[],
        &[b"mp", b"ipc"],
        None,
    ) {
        Ok(pid) => pid,
        Err(_) => qemu_exit::exit_failure(FAIL_SPAWN),
    };

    #[cfg(not(migration_smp))]
    let ipc_code = drive_process(&sys, wait_producer, ipc_pid);

    #[cfg(migration_smp)]
    let (ipc_code, observed_cpus) = {
        // A task id never exceeds the ABI's pid bound, so reinterpreting it
        // as the signed pid the wait ABI carries is exact.
        let poll_pid = ipc_pid.cast_signed();
        let mut observed = 0u32;
        let mut last_cpu = None;
        let mut migrations = 0u32;
        let mut exit_code = None;
        // Give up only on a genuine stall — a run of controller iterations in
        // which the child made no progress at all — never after a fixed count
        // of total iterations. This loop spins on the boot CPU while the child
        // advances on the secondaries, so a total-iteration budget would
        // measure how fast this loop spins relative to the child, a ratio the
        // host sets arbitrarily by how it schedules the four vCPU threads; a
        // busy or unevenly co-scheduled host could then exhaust it before a
        // healthy child finishes. Counting only consecutive no-progress
        // iterations makes the give-up independent of host load: any sign the
        // child is still advancing — a drained wake answering its blocking
        // IPC, the child seen running on a secondary, or a fresh forced
        // migration — resets the guard, so a slow-but-live run waits as long
        // as it needs and only a truly wedged child is declared deadlocked.
        let mut guard = StallGuard::new(MAX_STEPS);
        loop {
            let mut progressed = tairix_kernel_core::waitq::drain_pending_wakes();
            let mut running_cpu = None;
            for cpu in 1..CPU_COUNT {
                if sys.sched.current_task(cpu) == Some(ipc_pid) {
                    observed |= 1u32 << cpu;
                    running_cpu = Some(cpu);
                    break;
                }
            }
            if let Some(cpu) = running_cpu {
                progressed = true;
                if last_cpu != Some(cpu) {
                    if let Some(previous) = last_cpu {
                        migrations += 1;
                        SMP_PAUSED.fetch_and(!(1u32 << previous), Ordering::AcqRel);
                        SchedulerArch::send_ipi(sys.arch, previous);
                    }
                    SMP_PAUSED.store(1u32 << cpu, Ordering::Release);
                    last_cpu = Some(cpu);
                }
            }
            // Wake every unpaused secondary so one of them steals the ready
            // caller after its currently observed source dispatcher pauses.
            let paused = SMP_PAUSED.load(Ordering::Acquire);
            for cpu in 1..CPU_COUNT {
                if paused & (1u32 << cpu) == 0 {
                    SchedulerArch::send_ipi(sys.arch, cpu);
                }
            }
            match wait_producer.poll(ProcessId(0), poll_pid, WaitFlags::empty()) {
                Ok(reaped) => match reaped.status {
                    WaitStatus::Exited(code) => {
                        exit_code = Some(code);
                        break;
                    }
                    WaitStatus::Stopped(_) => qemu_exit::exit_failure(FAIL_PARENT_STOPPED),
                },
                Err(Errno::WouldBlock) => {}
                Err(_) => qemu_exit::exit_failure(FAIL_POLL),
            }
            if guard.observe(progressed) {
                break;
            }
        }
        SMP_PAUSED.store(0, Ordering::Release);
        (
            exit_code.unwrap_or_else(|| qemu_exit::exit_failure(FAIL_DEADLOCK)),
            (observed, migrations),
        )
    };

    if ipc_code != 0 {
        qemu_exit::exit_failure(fail_code(FAIL_IPC_CONTROL, ipc_code));
    }

    #[cfg(migration_smp)]
    if observed_cpus.0.count_ones() < 2 || observed_cpus.1 < 4 {
        // The observed-CPU mask is reported alongside the failure.
        qemu_exit::exit_failure(fail_code(FAIL_NO_MIGRATION, observed_cpus.0));
    }

    note(
        TEST_PASS,
        if cfg!(migration_smp) {
            "aarch64 mem-pin test: four-CPU blocking IPC migration passed"
        } else {
            "aarch64 mem-pin test: ST2 roles and one-CPU IPC control passed"
        },
    );
    qemu_exit::exit_success();
}
