//! The freestanding riscv64 test kernel: prove lightweight threads end to
//! end (`plans/THREADS.md` `T3b-u`; `docs/src/architecture/threads.md`).
//!
//! Every syscall and every user fault here runs the production
//! `KernelDispatchHook` / `KernelSyscallHandlers` path: the chassis installs the hook through a
//! `DispatchCallbackSlot` and binds the production user-fault resolver to the
//! same slot (load *and* store/AMO U-mode page faults), over the
//! production `LiveMemMap` producer (the `tairix-rt` heap and the
//! demand-backed thread stacks), a real `KernelProcessWait`, and a real
//! `KernelProcessSignal` — which threads genuinely need: a group `exit` has to
//! drive every sibling to its stopping point, and the process teardown lands
//! only once the last of them is down. The parent role of the fixture program
//! (`tests/integration/threads_program`) is spawned through the production
//! `InitSpawnCtx::spawn_driver_process` seam; it spawns and reaps each child
//! role through the production `spawn` + `wait` syscalls:
//!
//! * `counter` — N threads over one address space each increment a shared
//!   counter under a futex `Mutex`, and each is joined for its own tally, so
//!   both the shared heap and the kernel's clear-on-exit wake are proven;
//! * `rendezvous` — a `Condvar` wait that only completes because it genuinely
//!   *parked*: on this single-CPU cooperative drive a spinning wait would
//!   starve the very thread that has to notify it;
//! * `tls` — each thread reads its own magic through its psABI thread pointer,
//!   before and after a trap, so the register is proven per-thread;
//! * `exitearly` — a thread that ends itself with `thread_exit` releases its
//!   joiner (through the kernel's word, not a store of its own) and reports
//!   that it produced no value;
//! * `parallel` — a real `lib/parallel` worker pool runs a divided pass many
//!   times and every round matches the same pass run on one thread, proving the
//!   fork-join protocol on real threads: the epoch wake, the claim, the barrier
//!   over workers, the erased dispatch pointer's lifetime, nested dispatch, and
//!   the join at drop.
//! * `groupexit` — a sibling parked in the kernel on a condition variable
//!   nobody notifies, then `exit(code)`: the process is reapable only because
//!   the group exit reached that parked thread.
//!
//! The chassis reaps the parent through the wait producer's non-blocking poll
//! and PASSes only on a parent exit of 0.

use core::num::NonZeroU16;
use core::panic::PanicInfo;

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::{CapabilityId, Errno, WaitFlags, WaitStatus, SYSCALL_MAX_ARGS};
use tairix_arch_api::CpuId;
use tairix_arch_riscv64::fdt::Fdt;
use tairix_arch_riscv64::{
    handle_panic_via_serial, qemu_exit, syscall_entry, trap, RiscvArch, RiscvArchStorage,
    SERIAL_SINK,
};
use tairix_caps::CapabilitySet;
use tairix_itest_finisher::fail_code;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel::dispatch_core::{dispatch_via_slot, read_raw_args, resolve_user_fault_via_slot};
use tairix_kernel::riscv64::boot::{self as boot_riscv64, RiscvBinArch, RISCV_UART_CONSOLES};
use tairix_kernel::riscv64::spawn_producer::{CHILD_USER_BIAS, RISCV_PROCESS_SPAWN};
use tairix_kernel_core::{
    AddressSpaceRegistry, BootReserve, DispatchCallbackSlot, EmbeddedProgram, InitSpawnCtx,
    KernelArch, KernelDispatchHook, KernelInitSpawner, KernelProcessWait, LiveMemMap, ProcessWait,
    ProgramRegistry, RandomReserve, SchedWaitQueueArch, NULL_DMA_ALLOC_FACILITY,
    NULL_MMIO_MAP_FACILITY, NULL_SEAT_REGISTRY, NULL_SHARED_MEM_FACILITY,
};
use tairix_kernel_ipc::PortRegistry;
use tairix_kernel_irq::{IrqTable, UnsupportedController};
use tairix_kernel_mem::{
    BootMemoryMap, FrameAllocator, MemoryRegion, PhysAddr, RegionKind, PAGE_SIZE,
};
use tairix_kernel_sched_cfq::{Scheduler, SchedulerConfig};
use tairix_kernel_sec::{CapTable, ProcessId};
use tairix_log::{log, Event, EventId, Level};
use tairix_sync::RwLock;

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// The single-hart slice runs logical CPU 0 on the boot hart.
const BOOT_CPU: CpuId = 0;

/// Physical frames the production spawn producer and the demand-fault path
/// draw from: eight spawned processes — the parent's seven child roles plus
/// the child one of those roles spawns from a thread of its own — (image,
/// eagerly committed stack top, page
/// tables) plus each role's threads — every thread costs one eagerly backed
/// stack page, a kernel stack, and whatever its body faults in. Sized from
/// that appetite with generous headroom (16 MiB).
const FRAME_COUNT: usize = 4096;

/// Threads the `counter` role runs. Four is enough for genuine contention on
/// the shared counter's futex mutex while staying comfortably inside the
/// frame pool below.
const COUNTER_THREADS: u64 = 4;

/// Increments each `counter` thread performs. Large enough that an
/// unsynchronised increment would almost certainly lose an update, so a
/// correct total is real evidence the lock works.
const COUNTER_INCREMENTS: u64 = 250;

/// Threads the `tls` role runs, each with its own thread-local block.
const TLS_THREADS: u64 = 3;

/// Worker threads the `parallel` role's pool asks the kernel for. Three beside
/// the dispatching thread, so the fork-join barrier genuinely waits for several
/// acknowledgements while staying inside the frame pool below.
const PARALLEL_WORKERS: u64 = 3;

/// Rounds the `parallel` role runs its divided pass for. Enough repetitions that
/// a lost wake or a mis-claimed piece cannot pass by luck; the pass itself is
/// small.
const PARALLEL_ROUNDS: u64 = 32;

/// The status the `groupexit` role ends its process with. Named once here and
/// threaded into *both* the `groupexit` row (the code it exits with) and the
/// `parent` row (the code it must observe), so the two cannot drift.
const GROUP_EXIT_CODE: u64 = 41;

/// Longest decimal argument the rows below need (`u64::MAX` is 20 digits).
const DEC_MAX: usize = 20;

/// Render `value` as a fixed-width, zero-padded decimal byte string at
/// compile time. Leading zeroes are harmless: the fixture's parser accepts
/// them, and a fixed width lets the argument live in a `static` the
/// registry row borrows.
const fn dec_bytes(mut value: u64) -> [u8; DEC_MAX] {
    let mut out = [b'0'; DEC_MAX];
    let mut i = DEC_MAX;
    while i > 0 {
        i -= 1;
        out[i] = b'0' + (value % 10) as u8;
        value /= 10;
        if value == 0 {
            break;
        }
    }
    out
}

/// [`COUNTER_THREADS`] as a decimal argument-vector value.
static COUNTER_THREADS_ARG: [u8; DEC_MAX] = dec_bytes(COUNTER_THREADS);
/// [`COUNTER_INCREMENTS`] as a decimal argument-vector value.
static COUNTER_INCREMENTS_ARG: [u8; DEC_MAX] = dec_bytes(COUNTER_INCREMENTS);
/// [`TLS_THREADS`] as a decimal argument-vector value.
static TLS_THREADS_ARG: [u8; DEC_MAX] = dec_bytes(TLS_THREADS);
/// [`PARALLEL_WORKERS`] as a decimal argument-vector value.
static PARALLEL_WORKERS_ARG: [u8; DEC_MAX] = dec_bytes(PARALLEL_WORKERS);
/// [`PARALLEL_ROUNDS`] as a decimal argument-vector value.
static PARALLEL_ROUNDS_ARG: [u8; DEC_MAX] = dec_bytes(PARALLEL_ROUNDS);
/// [`GROUP_EXIT_CODE`] as a decimal argument-vector value.
static GROUP_EXIT_CODE_ARG: [u8; DEC_MAX] = dec_bytes(GROUP_EXIT_CODE);

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4494);
const TEST_SPAWNED: EventId = EventId(4495);
const TEST_PASS: EventId = EventId(4496);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_FDT: NonZeroU16 = fail_point!(2);
const FAIL_UNEXPECTED_HART: NonZeroU16 = fail_point!(3);
const FAIL_FRAMES: NonZeroU16 = fail_point!(4);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(5);
const FAIL_SPAWN: NonZeroU16 = fail_point!(6);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(7);
const FAIL_NO_DISPATCH: NonZeroU16 = fail_point!(8);
const FAIL_HOOK_INSTALL: NonZeroU16 = fail_point!(9);
const FAIL_RESOLVER_INSTALL: NonZeroU16 = fail_point!(10);
const FAIL_BIAS: NonZeroU16 = fail_point!(11);
const FAIL_POLL: NonZeroU16 = fail_point!(12);
const FAIL_DRAINED: NonZeroU16 = fail_point!(13);
const FAIL_PARENT_STOPPED: NonZeroU16 = fail_point!(14);
const FAIL_PAGING: NonZeroU16 = fail_point!(15);
/// Base finisher for a non-zero parent exit; the parent's diagnostic exit
/// code is added so the failing role/site is identifiable in the finisher.
const FAIL_EXIT_BASE: NonZeroU16 = fail_point!(100);

/// Size of the test's bump heap. Lives in `.bss` (zeroed by the trampoline).
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Identity-mapped physical-frame backing store the live [`FrameAllocator`]
/// serves the spawn producer and the stack-growth fault path from; inside
/// the 4 GiB identity window the producer's Sv39 page-table walk requires
/// (the `virt` board's RAM base at 2 GiB sits within it).
#[repr(C, align(4096))]
struct FramePool([u8; PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; PAGE_SIZE * FRAME_COUNT]);

/// The dispatch-callback slot the production [`KernelDispatchHook`] is
/// installed into (one slot per binary, set once). Both the syscall
/// callback and the user-fault resolver resolve through it.
static DISPATCH_SLOT: DispatchCallbackSlot = DispatchCallbackSlot::new();

/// Per-CPU storage backing the scheduler's arch handle.
static SCHED_STORAGE: RiscvArchStorage<1> = RiscvArchStorage::new();

/// Per-CPU storage backing the dispatch hook + spawn ctx arch handle.
static HOOK_ARCH_STORAGE: RiscvArchStorage<1> = RiscvArchStorage::new();

/// This vertical binds no IRQ lines; the fail-closed controller mirrors
/// what `kernel/core::init` installs when a port exposes no routing.
static IRQ_CONTROLLER: UnsupportedController = UnsupportedController;

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared riscv64 panic bridge (parks the hart; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn threads_qemu_riscv64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// The syscall-dispatch callback every program's `ecall` traps reach. It
/// mirrors the production bin-crate callback (`dispatch_riscv64`): read the
/// kernel-stack args frame and forward through the resident production
/// [`KernelDispatchHook`] via the shared `dispatch_via_slot` bridge. An
/// empty slot or a missing caller context fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the trap trampoline lays the frame out on the kernel
    // stack and only invokes us with a valid pointer; the array lives at
    // least until we return.
    let args = unsafe { read_raw_args(args_ptr) };
    match dispatch_via_slot(&DISPATCH_SLOT, number, args) {
        Some(value) => value,
        None => qemu_exit::exit_failure(FAIL_NO_DISPATCH),
    }
}

/// The user-fault resolver the S-mode trap path calls for every U-mode
/// load/store page fault: the exact production glue
/// (`production_user_fault`), bound to this vertical's own slot so an
/// in-span fault (load or store/AMO — a stack push is a store) runs the
/// resident production hook's `resolve_stack_fault` growth path and an
/// unresolvable fault (past the bound, below the span) kills the faulting
/// task through the production fault-exit path.
// The callback matches the arch `UserFaultResolveFn` type (a bare safe
// `extern "C" fn`); the raw pointer is only forwarded into the guarded
// `unsafe` call below, which narrows it with `as_ref`.
#[allow(clippy::not_unsafe_ptr_arg_deref)]
extern "C" fn threads_user_fault(
    stval: u64,
    write: bool,
    regs: *const tairix_arch_api::backtrace::UserRegisterFrame,
) -> bool {
    // SAFETY: the trap handler builds the frame on its kernel stack and
    // holds it live across this call, or passes null; the slot helper
    // narrows the pointer with `as_ref` and never dereferences null.
    unsafe { resolve_user_fault_via_slot(&DISPATCH_SLOT, stval, write, regs) }
}

/// The capability set the fixture programs run under: `PROC_SPAWN` for the
/// parent's `spawn` only. The parent's set doubles as the inherited
/// ceiling the production spawn intersects each child's manifest request
/// with, so a child's effective set is exactly its registry row's request
/// — and only the `reapchild` role requests anything (it spawns a child of
/// its own; stack growth, `rlimit_set` lowering, and faulting need no
/// capability).
fn parent_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::PROC_SPAWN);
    caps
}

/// The program registry the production `spawn` syscall resolves the
/// parent's child paths against: one `rxe` image, one row per role, each
/// pinning its role word and its numeric parameters through the registered
/// default argument vector.
static CHILD_PROGRAMS: [EmbeddedProgram; 7] = [
    EmbeddedProgram {
        path: b"/bin/th-counter",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[
            b"th",
            b"counter",
            &COUNTER_THREADS_ARG,
            &COUNTER_INCREMENTS_ARG,
        ],
    },
    EmbeddedProgram {
        path: b"/bin/th-rendezvous",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"th", b"rendezvous"],
    },
    EmbeddedProgram {
        path: b"/bin/th-tls",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"th", b"tls", &TLS_THREADS_ARG],
    },
    EmbeddedProgram {
        path: b"/bin/th-exitearly",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"th", b"exitearly"],
    },
    EmbeddedProgram {
        path: b"/bin/th-parallel",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[
            b"th",
            b"parallel",
            &PARALLEL_WORKERS_ARG,
            &PARALLEL_ROUNDS_ARG,
        ],
    },
    EmbeddedProgram {
        path: b"/bin/th-reapchild",
        rxe: PROGRAM_RXE,
        // The only child role that spawns: its reaping thread launches one of
        // its siblings, so its manifest asks for the spawn authority the
        // parent's ceiling already carries.
        caps: &[CapabilityId::PROC_SPAWN],
        args: &[b"th", b"reapchild"],
    },
    EmbeddedProgram {
        path: b"/bin/th-groupexit",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"th", b"groupexit", &GROUP_EXIT_CODE_ARG],
    },
];

/// The registry over [`CHILD_PROGRAMS`].
static PROGRAMS: ProgramRegistry = ProgramRegistry::new(&CHILD_PROGRAMS);

/// Bring the board up: parse the live `virt` device tree OpenSBI passed in
/// `a1` for the timebase, install the S-mode trap vector, and install the
/// dispatch callback + user-fault resolver. The kernel itself runs with
/// bring paging up through the one production sequence
/// (`boot_riscv64::enable_paging_and_direct_map`) — the boot identity space
/// plus the direct physical map — because the production spawn producer
/// reaches each child's Sv39 tables *through* that map. Returns the
/// discovered timebase.
fn bring_up_board(dtb: u64) -> u64 {
    // SAFETY: `dtb` is the verbatim `a1` pointer from OpenSBI; it addresses
    // a valid flattened device tree that lives for the life of the guest.
    let Ok(fdt) = (unsafe { Fdt::from_ptr(dtb as *const u8) }) else {
        qemu_exit::exit_failure(FAIL_FDT);
    };
    let Some(timebase_hz) = fdt.timebase_frequency() else {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    };
    if timebase_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }

    // Bring paging up before the trap vector, so the handler address the
    // vector names resolves under the regime that will be in force. A
    // refusal is fatal: the producer cannot reach a child's tables without
    // the map.
    // SAFETY: `dtb` is the verbatim `a1` pointer (as above), and this is the
    // boot hart's single call.
    if boot_riscv64::enable_paging_and_direct_map(dtb).is_err() {
        qemu_exit::exit_failure(FAIL_PAGING);
    }

    // Install the trap vector + the callbacks before any user task runs.
    // SAFETY: called once on the boot hart with a stack established.
    unsafe { trap::init_traps() };
    syscall_entry::set_dispatch_callback(dispatch);
    // Bind the production user-fault resolver to this vertical's slot — the
    // fault-driven growth heart this test exists to prove.
    if tairix_arch_api::fault::set_user_fault_resolver(threads_user_fault).is_err() {
        qemu_exit::exit_failure(FAIL_RESOLVER_INSTALL);
    }
    timebase_hz
}

/// The leaked-`'static` kernel subsystems the production dispatch hook and
/// spawn context borrow — the vertical's analogue of `KernelState`, lifted
/// by one-shot `Box::leak` publishes exactly as `kernel_core::kernel_main`
/// does (a one-shot publish, not a global mutable static).
struct Subsystems {
    frames: &'static FrameAllocator,
    sched: &'static Scheduler<RiscvBinArch>,
    arch: &'static RiscvBinArch,
    caps: &'static RwLock<CapTable>,
    peer_watch: &'static tairix_kernel_core::PeerWatch,
    ipc: &'static RwLock<PortRegistry>,
    aspaces: &'static RwLock<AddressSpaceRegistry>,
    rng: &'static RwLock<Box<dyn RandomReserve + Send + Sync>>,
    irq_table: &'static IrqTable,
}

/// Build the live kernel subsystems: the `kernel/mem` frame allocator over
/// the identity-mapped pool (so the spawn producer and the demand-fault
/// path draw their frames from the production path), the scheduler over
/// the production `KernelArch` wrapper, and the capability / port /
/// address-space / random / IRQ state the production hook borrows.
fn leak_subsystems(counter_hz: u64) -> Subsystems {
    let mut memory_map = BootMemoryMap::new();
    memory_map.push(MemoryRegion {
        start: PhysAddr::new(core::ptr::addr_of!(FRAME_POOL) as u64),
        length: (PAGE_SIZE * FRAME_COUNT) as u64,
        kind: RegionKind::Usable,
    });
    let Ok(frames) = FrameAllocator::new(&memory_map) else {
        qemu_exit::exit_failure(FAIL_FRAMES);
    };
    let frames: &'static FrameAllocator = Box::leak(Box::new(frames));

    let sched_arch = Arc::new(RiscvBinArch::new(
        RiscvArch::new(&SCHED_STORAGE, BOOT_CPU, counter_hz),
        None,
    ));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), sched_arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    Subsystems {
        frames,
        sched: Box::leak(Box::new(sched)),
        arch: Box::leak(Box::new(RiscvBinArch::new(
            RiscvArch::new(&HOOK_ARCH_STORAGE, BOOT_CPU, counter_hz),
            None,
        ))),
        caps: Box::leak(Box::new(RwLock::new(CapTable::new()))),
        peer_watch: Box::leak(Box::new(tairix_kernel_core::PeerWatch::new())),
        ipc: Box::leak(Box::new(RwLock::new(PortRegistry::new()))),
        aspaces: Box::leak(Box::new(RwLock::new(AddressSpaceRegistry::new()))),
        rng: Box::leak(Box::new(RwLock::new(
            Box::new(BootReserve::new()) as Box<dyn RandomReserve + Send + Sync>
        ))),
        irq_table: Box::leak(Box::new(IrqTable::new(0))),
    }
}

/// Boot entry point — the symbol the arch crate's boot trampoline calls
/// with the boot hart id in `a0` and the device-tree pointer in `a1`.
#[no_mangle]
pub extern "C" fn kernel_main(hartid: u64, dtb: u64) -> ! {
    note(TEST_START, "riscv64 threads test: starting");

    if hartid != u64::from(BOOT_CPU) {
        qemu_exit::exit_failure(FAIL_UNEXPECTED_HART);
    }
    let counter_hz = bring_up_board(dtb);

    // The fixture `rxe`'s baked relocations must target the bias the
    // production producer maps every child at; a drifted constant would
    // admit a child whose pointers do not match its mapping (fail closed).
    if USER_BIAS != CHILD_USER_BIAS {
        qemu_exit::exit_failure(FAIL_BIAS);
    }

    let sys = leak_subsystems(counter_hz);

    // Publish the wait-queue arch hook so parked waiters (the parent in
    // `wait`) are genuinely unparked by their wake events — the same
    // adapter the production boot path installs.
    let wait_arch = SchedWaitQueueArch::leak(sys.sched, sys.arch);
    if tairix_kernel_core::waitq::install_wait_arch(wait_arch).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // The scheduler-side process-wait producer: records every parent/child
    // link the production spawn paths register and backs the production
    // `wait` syscall the parent blocks in.
    let wait_producer: &'static KernelProcessWait<RiscvBinArch> =
        Box::leak(Box::new(KernelProcessWait::new(sys.arch)));

    // The production live-space producer: serves the `mem_map` pair (the
    // `tairix-rt` heap) and — the point of this vertical — the one-page-
    // per-fault backing the stack-growth resolver maps through it.
    let live: &'static LiveMemMap<RiscvBinArch> = Box::leak(Box::new(LiveMemMap::new(sys.arch)));

    // Publish the production dispatch hook: every syscall the programs
    // issue — `spawn`, `wait`, `rlimit_set`, `exit` — and every user-fault
    // resolution runs the production caller-context resolution and handler
    // path.
    // Size the futex bucket table from this chassis's CPU count, as the boot
    // path does: correctness never depends on the count, only contention, but
    // an unsized table would serialise unrelated keys.
    tairix_kernel_core::futex::init_buckets(1);

    // The scheduler-side process-signal producer, over the thread-group table.
    // Threads genuinely need it: a group `exit` drives every sibling to its
    // stopping point through this producer, and `thread_create` refuses to admit
    // a second thread without one (a group whose siblings cannot be stopped
    // could never be torn down). Built before the hook, which carries it; the
    // hook becomes its landing seam a few lines below, once it exists.
    let signal_producer = Box::leak(Box::new(tairix_kernel_core::KernelProcessSignal::new(
        wait_producer,
        sys.sched,
        sys.caps,
    )));

    let hook: &'static KernelDispatchHook<'static, RiscvBinArch> = Box::leak(Box::new(
        KernelDispatchHook::new(
            sys.sched,
            sys.caps,
            sys.arch,
            &SERIAL_SINK,
            sys.irq_table,
            &IRQ_CONTROLLER,
            sys.ipc,
            sys.aspaces,
            sys.rng,
            &RISCV_UART_CONSOLES,
            sys.frames,
            sys.frames,
            &PROGRAMS,
            wait_producer,
            // No seat / MMIO / DMA surface in this vertical; those
            // producers stay fail-closed. No filesystem or file-map producer
            // either: the only faults here are the demand-backed thread stacks
            // and the `tairix-rt` heap, both of which the live producer serves.
            &NULL_SEAT_REGISTRY,
            live,
            &NULL_MMIO_MAP_FACILITY,
            &NULL_DMA_ALLOC_FACILITY,
        )
        .with_peer_watch(sys.peer_watch)
        .with_process_signal(signal_producer),
    ));
    if DISPATCH_SLOT.install_dispatcher(hook).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // Publish the leaked hook as the signal producer's landing seam, so a
    // signalled kill, a fault kill, a `thread_exit`, and an `exit` all tear a
    // process down through the one shared rule — and never while a sibling is
    // still executing. The same producer is the dispatch loop's deferred-kill
    // lander, so a sibling caught mid-run lands its teardown once its own
    // dispatch retires it.
    if signal_producer.install_task_reclaim(hook).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }
    if tairix_kernel_core::install_deferred_kill_lander(signal_producer).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // Spawn the parent role through the production runtime-spawn seam
    // (`KernelSpawnCtx` assembly inside `KernelInitSpawner`), recorded
    // against the kernel supervisor identity so this chassis can reap it.
    // Publish the launch-services bundle the deferred child-load path reads:
    // the arch image builder builds each admitted child's image on the
    // child's own first slice, off this chassis's cooperative drive. The one
    // shared build+publish the production boot path uses.
    let _ = tairix_kernel_core::spawn_services::install_over(
        sys.arch,
        sys.frames,
        &SERIAL_SINK,
        &tairix_kernel_core::NULL_FILESYSTEM,
        None,
        sys.aspaces,
        sys.caps,
        sys.peer_watch,
        wait_producer,
        &RISCV_PROCESS_SPAWN,
    );

    let init_ctx = KernelInitSpawner::new(
        sys.frames,
        &SERIAL_SINK,
        sys.sched,
        sys.caps,
        sys.peer_watch,
        sys.aspaces,
        sys.arch,
        wait_producer,
        sys.irq_table,
        &NULL_SHARED_MEM_FACILITY,
        KernelArch::cross_cpu_tlb_shootdown(sys.arch),
    );
    let Ok(parent_pid) = init_ctx.spawn_driver_process(
        "/bin/th-parent",
        PROGRAM_RXE,
        parent_caps(),
        &[],
        &[b"th", b"parent", &GROUP_EXIT_CODE_ARG],
        None,
    ) else {
        qemu_exit::exit_failure(FAIL_SPAWN);
    };
    note(
        TEST_SPAWNED,
        "riscv64 threads test: parent spawned through the production seam",
    );

    // The budget-bounded cooperative drive: step the scheduler and poll the
    // wait producer for the parent's exit between steps. The parent runs
    // the whole grow / limit / guard sequence through production spawn +
    // wait; a parent exit of 0 is the PASS, anything else names the failing
    // site through its diagnostic code.
    // A task id never exceeds the ABI's pid bound, so reinterpreting it as
    // the signed pid the wait ABI carries is exact.
    let parent_pid = parent_pid.cast_signed();
    let mut steps = 0u64;
    while steps < MAX_STEPS {
        let _ = sys.sched.step(BOOT_CPU);
        steps += 1;

        // Deliver any wake a handler deferred while the task ran — the same
        // between-dispatches service the production loop performs; without
        // it a child's `exit` never unparks the parent blocked in `wait`.
        let _ = tairix_kernel_core::waitq::drain_pending_wakes();

        match wait_producer.poll(ProcessId(0), parent_pid, WaitFlags::empty()) {
            Ok(reaped) => match reaped.status {
                WaitStatus::Exited(0) => {
                    note(
                        TEST_PASS,
                        "riscv64 threads test: parent verified every thread role and exited 0",
                    );
                    qemu_exit::exit_success();
                }
                WaitStatus::Exited(code) => {
                    qemu_exit::exit_failure(fail_code(FAIL_EXIT_BASE, code));
                }
                WaitStatus::Stopped(_) => {
                    qemu_exit::exit_failure(FAIL_PARENT_STOPPED);
                }
            },
            Err(Errno::WouldBlock) => {}
            Err(_) => qemu_exit::exit_failure(FAIL_POLL),
        }

        // A fully drained workload without a reapable parent means the
        // parent vanished down a path that never recorded its exit; fail
        // with a distinct finisher rather than spinning out the watchdog.
        if sys.sched.live_task_count() == 0 {
            qemu_exit::exit_failure(FAIL_DRAINED);
        }
    }
    qemu_exit::exit_failure(FAIL_DEADLOCK);
}
