//! The freestanding aarch64 test kernel: build one isolated EL0 program,
//! hold its address space live behind the production
//! [`tairix_kernel_mem::LiveSpace`] + [`tairix_kernel_core::ProcessSpace`],
//! admit it through the production
//! [`tairix_kernel_core::spawn_user_kthread_with_stack_live`] path, and route
//! its `mmio_map` syscall to the granted device window through
//! [`tairix_kernel_core::with_current_live_space`] +
//! [`tairix_kernel_mem::LiveSpace::map_device_window`] (`plans/PI.md`
//! 5d-0-ii (b′)-2).

use core::num::NonZeroU16;
use core::panic::PanicInfo;
use core::sync::atomic::{AtomicBool, Ordering};

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::{
    i32_from_register, CapabilityId, CapabilityQuery, DmaCoherence, Errno, SyscallNumber,
    SYSCALL_MAX_ARGS,
};
use tairix_arch_aarch64::context_hal::ContextSwitchHal;
use tairix_arch_aarch64::kernel_arch::timer_frequency_hz;
use tairix_arch_aarch64::paging::{
    self, activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool,
};
use tairix_arch_aarch64::userentry::UserMode;
use tairix_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, SERIAL_SINK,
};
use tairix_arch_api::fatal::KernelFault;
use tairix_arch_api::{EnterUser, BOOT_CPU};
use tairix_fdt::Fdt;
use tairix_itest_finisher::fail_code;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel_core::dmaquarantine::DmaQuarantine;
use tairix_kernel_core::HwNodeLiveness;
use tairix_kernel_core::{
    spawn_image, spawn_user_kthread_with_stack_live, with_current_live_space, Admission, BoxStack,
    ProcessSpace, SpawnMode, SpawnRequest, Yielder,
};
use tairix_kernel_mem::{
    page_count_for, ActiveCpus, AddressSpace, BootMemoryMap, DirectPhysMap, DmaCustodian, Frame,
    FrameAllocator, LiveSpace, MemoryRegion, PhysAddr, RegionKind, SpaceTlb, Unpublished,
    UserStack, VirtAddr,
};
use tairix_kernel_sched_eevdf::{Priority, Scheduler, SchedulerConfig};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level};
use tairix_sync::Once;

// `PROGRAM_RXE: &[u8]`, `USER_BIAS: u64`, `GRANT_HANDLE: u64`,
// `GRANT_PHYS: u64`, and `GRANT_LEN: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// Gigabytes of identity map the EL0 address space provides: `[0, 2 GiB)`
/// covers the `virt` board's device MMIO (GiB 0 — including the virtio-MMIO
/// transports at [`GRANT_PHYS`]) and the RAM base at GiB 1 where this kernel
/// runs. [`USER_BIAS`] (64 GiB) and the device-window region sit far above.
const IDENTITY_GIB: usize = 2;

/// User stack base (1 MiB into the high user region) and size.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (256 KiB).
const USER_STACK_PAGES: u64 = 64;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Base of the program's device-window virtual region: the retained
/// [`LiveSpace`]'s [`tairix_kernel_mem::MmioWindowMap`] hands the `mmio_map`
/// a guard-bracketed window out of this range. 1 GiB above [`USER_BIAS`] —
/// clear of the image, stack, and startup block — mirroring the production
/// aarch64 spawn layout (`init_spawn.rs`).
const MMIO_WINDOW_BASE: u64 = USER_BIAS + 0x4000_0000;
/// Pages backing the device-window region (256 KiB).
const MMIO_WINDOW_PAGES: usize = 64;

/// Base of the program's non-`FIXED` anonymous-heap virtual region: the
/// retained [`LiveSpace`]'s [`tairix_kernel_mem::AnonWindowMap`] places each
/// non-`FIXED` `mem_map` out of this range. 2 GiB above [`USER_BIAS`] —
/// above the device window and clear of the image/stack — mirroring the
/// production aarch64 spawn layout (`spawn_layout::ANON_WINDOW_OFFSET`).
const ANON_WINDOW_BASE: u64 = USER_BIAS + 0x8000_0000;
/// Pages backing the anonymous-heap window (this vertical maps only a couple
/// of pages out of it; the window is address space, backed on demand).
const ANON_WINDOW_PAGES: usize = 64;

/// Base of the program's guarded DMA-buffer virtual region: the retained
/// [`LiveSpace`]'s [`tairix_kernel_mem::DmaWindowMap`] carves each
/// `dma_alloc` buffer out of this range. 3 GiB above [`USER_BIAS`] — above
/// the anonymous-heap window and clear of the image/stack — mirroring the
/// production aarch64 spawn layout (`spawn_layout::DMA_WINDOW_OFFSET`).
const DMA_WINDOW_BASE: u64 = USER_BIAS + 0xC000_0000;
/// Pages backing the DMA-buffer window (256 KiB).
const DMA_WINDOW_PAGES: usize = 64;

/// Base of the program's cross-process shared-memory virtual region: the
/// retained [`LiveSpace`]'s shared-window allocator maps each granted
/// `shm_map` region out of this range. 4 GiB above [`USER_BIAS`] - above the
/// DMA window and clear of the image/stack - mirroring the production
/// aarch64 spawn layout (`spawn_layout::SHARED_WINDOW_OFFSET`).
const SHARED_WINDOW_BASE: u64 = USER_BIAS + 0x1_0000_0000;
/// Pages backing the shared-memory window (256 KiB).
const SHARED_WINDOW_PAGES: usize = 64;

/// Base of the program's demand-paged file-mapping virtual region: 5 GiB
/// above [`USER_BIAS`] - above the shared-memory window and clear of the
/// image/stack - mirroring the production aarch64 spawn layout (the
/// dynamic window above the anonymous heap).
const FILE_WINDOW_BASE: u64 = USER_BIAS + 0x1_4000_0000;
/// Pages of address space in the file-mapping window (this vertical never
/// reserves out of it; it only has to be valid).
const FILE_WINDOW_PAGES: usize = 64;

/// Per-process stack-canary seed handed to the program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// Physical frames the test hands the spawn build.
const FRAME_COUNT: usize = 128;

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4290);
const TEST_SPAWNED: EventId = EventId(4291);
const TEST_PASS: EventId = EventId(4292);
const TEST_FAIL: EventId = EventId(4293);
const TEST_MMIO_ENTER: EventId = EventId(4294);
const TEST_MMIO_MAPPED: EventId = EventId(4295);
const TEST_FAULT: EventId = EventId(4296);
const TEST_MEM_MAPPED: EventId = EventId(4297);
const TEST_MEM_UNMAPPED: EventId = EventId(4298);
const TEST_DMA_MAPPED: EventId = EventId(4299);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_GIC: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_PARSE: NonZeroU16 = fail_point!(4);
const FAIL_BUILD: NonZeroU16 = fail_point!(5);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(6);
const FAIL_SPAWN: NonZeroU16 = fail_point!(7);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(8);
const FAIL_UNEXPECTED_SYSCALL: NonZeroU16 = fail_point!(9);
const FAIL_LIVE_BUILD: NonZeroU16 = fail_point!(10);
const FAIL_DRAINED: NonZeroU16 = fail_point!(11);
const FAIL_FAULT_INSTALL: NonZeroU16 = fail_point!(12);
const FAIL_FAULT: NonZeroU16 = fail_point!(13);
/// Base finisher for an `exit` with a non-zero code (a program-side
/// verification failure); the program's exit code is added so the failing
/// site is identifiable.
const FAIL_EXIT_BASE: NonZeroU16 = fail_point!(100);

/// `true` once an `mmio_map` call returned a mapped base to the program.
static MAP_OK: AtomicBool = AtomicBool::new(false);

/// `true` once a non-`FIXED` `mem_map` round-trip (map → write → read-back →
/// `mem_unmap`) completed for the program — the placement-allocator proof
/// (`plans/PI.md` 5d-0-ii (c)). The program's `mem_unmap` sets it; PASS
/// requires both this and [`MAP_OK`].
static MEM_OK: AtomicBool = AtomicBool::new(false);

/// `true` once a `dma_alloc` carve returned a coherent buffer to the program
/// — the DMA-carve proof (`plans/PI.md` 5d-0-ii (c) DMA half). Set when the
/// dispatch services the program's `dma_alloc`; PASS requires it too.
static DMA_OK: AtomicBool = AtomicBool::new(false);

/// The device-resource grant handle the program carves its DMA buffer
/// against (the second grant the vertical mints for the task). Must match
/// the fixture program's `DMA_GRANT_HANDLE`.
const DMA_GRANT_HANDLE: u64 = 2;

/// Fault handler: any EL0 fault here is unexpected (the program only maps a
/// window and reads a register), so report it as a failure rather than hang. The `esr`/`far` are logged so a diagnosing run can
/// tell a translation fault from an external abort.
fn on_fault(trap: KernelFault) -> ! {
    let mut esr_buf = [0u8; 16];
    let mut far_buf = [0u8; 16];
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Error,
            id: TEST_FAULT,
            message: "mmio_map test: unexpected EL0 fault",
            fields: &[
                tairix_log::Field {
                    key: "esr",
                    value: trap.syndrome.map_or(tairix_log::FieldValue::Null, |esr| {
                        tairix_log::FieldValue::Str(tairix_util::fmt::format_hex_u64(
                            esr,
                            &mut esr_buf,
                        ))
                    }),
                },
                tairix_log::Field {
                    key: "far",
                    value: trap.address.map_or(tairix_log::FieldValue::Null, |far| {
                        tairix_log::FieldValue::Str(tairix_util::fmt::format_hex_u64(
                            far,
                            &mut far_buf,
                        ))
                    }),
                },
            ],
        },
    );
    qemu_exit::exit_failure(FAIL_FAULT);
}

/// Size of the test's bump heap (startup block buffers + the user kthread's
/// kernel stack + control block + leaked allocator). Lives in `.bss`.
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the EL0 address space (the image mappings, the
/// device-window tables the retained `LiveSpace` walks).
static PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Physical-frame backing store the spawn builder draws user pages from.
/// `align(4096)` so each `PAGE_SIZE` slice is a valid page frame;
/// identity-mapped, so the builders reach it through [`DirectPhysMap::identity`].
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame.
static FRAME_CURSOR: core::sync::atomic::AtomicUsize = core::sync::atomic::AtomicUsize::new(0);

/// Hand out the next identity-mapped physical frame, or `None` when exhausted.
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(base)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn mmio_map_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires. It does not widen the program's
/// own authority.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// Encode a `Result<u64, Errno>` into the syscall return register following the
/// `abi-v1` signed convention: a non-negative value on success, `-errno` on
/// error (the encoding `tairix_rt::mmio_map` decodes).
fn encode(result: Result<u64, Errno>) -> u64 {
    match result {
        Ok(value) => value,
        Err(err) => {
            let neg = -i64::from(err.as_i32());
            neg as u64
        }
    }
}

/// The syscall-dispatch callback the EL0 program's `svc` traps reach.
///
/// `mmio_map` is routed through the retained live space: the handle is
/// owner-checked (it must be the [`GRANT_HANDLE`] the boot path minted — the
/// registry-backed owner-check against the caller is host-proven in
/// `kernel/core`), then the granted window is mapped into the
/// program's *own* address space through [`with_current_live_space`] +
/// [`LiveSpace::map_device_window`] — the production retained-space mechanism
/// (`plans/PI.md` 5d-0-ii (b′)). An `exit` with code `0` is the program's PASS
/// signal (it mapped the window and read the device magic back); a non-zero
/// code is a program-side verification failure. Any other syscall is
/// unexpected and fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: `args_ptr` points at the live `[u64; SYSCALL_MAX_ARGS]` the
    // exception handler built from the saved register frame; reading it for the
    // duration of this call is sound.
    let args = unsafe { &*args_ptr };
    let call = SyscallNumber::from_register(number).ok();

    if call == Some(SyscallNumber::MMIO_MAP) {
        note(TEST_MMIO_ENTER, "mmio_map test: dispatch handling mmio_map");
        let handle = args[0];
        // Owner-check the handle: only the minted grant resolves; any other
        // handle resolves to nothing and is refused (fail closed — the
        // registry-backed owner-check against the caller task is host-proven).
        if handle != GRANT_HANDLE {
            return encode(Err(Errno::NotFound));
        }
        // The program names a `[offset, offset + len)` sub-region of its
        // grant (`args[1]`/`args[2]`); confirm it lies wholly inside the
        // granted window before mapping, mirroring the production kernel
        // `mappable_subwindow` check (a driver maps
        // only inside a region it was granted).
        let offset = args[1];
        let sub_len = args[2];
        let in_bounds = sub_len != 0
            && offset
                .checked_add(sub_len)
                .is_some_and(|end| end <= GRANT_LEN);
        if !in_bounds {
            return encode(Err(Errno::OutOfRange));
        }
        // Map only the requested sub-region into the program's own retained
        // live space: the producer reads the current CPU's published live
        // space and maps that region, caching disabled, never executable. No published space (a task admitted without one)
        // fails closed.
        let result = match with_current_live_space(BOOT_CPU, |space| {
            // The sub-region length was bounded against the granted window
            // above, so it fits the host's pointer width.
            #[allow(clippy::cast_possible_truncation)]
            space.map_device_window(GRANT_PHYS + offset, sub_len as usize)
        }) {
            Some(Ok(va)) => Ok(va),
            Some(Err(_)) => Err(Errno::BadAddress),
            None => Err(Errno::NotImplemented),
        };
        if result.is_ok() {
            MAP_OK.store(true, Ordering::SeqCst);
            note(TEST_MMIO_MAPPED, "mmio_map test: granted window mapped");
        }
        encode(result)
    } else if call == Some(SyscallNumber::MEM_MAP) {
        // Non-`FIXED` `mem_map`: the program asks the kernel to place the
        // region, so route to the retained live space's placement allocator
        // (`plans/PI.md` 5d-0-ii (c)) — the production `LiveMemMap` non-`FIXED`
        // path. `args[0]` is the byte length; the flags/hint are ignored here
        // (the fixture only issues non-`FIXED` requests).
        let len = args[0] as usize;
        let result = match page_count_for(len) {
            Ok(pages) => {
                match with_current_live_space(BOOT_CPU, |space| space.map_anonymous_placed(pages)) {
                    Some(Ok(base)) => {
                        note(TEST_MEM_MAPPED, "mem_map test: placed anonymous region");
                        Ok(base)
                    }
                    Some(Err(_)) => Err(Errno::OutOfMemory),
                    None => Err(Errno::NotImplemented),
                }
            }
            Err(_) => Err(Errno::LengthOutOfRange),
        };
        encode(result)
    } else if call == Some(SyscallNumber::MEM_UNMAP) {
        // Release the placed region. `args[0]` is the base, `args[1]` the byte
        // length. The placement record is validated + released inside
        // `unmap_anonymous` (fail closed on a wrong base/extent).
        let base = args[0];
        let len = args[1] as usize;
        let result = match page_count_for(len) {
            Ok(pages) => {
                // This kernel serves no copy path, so the page table is the only view.
                let unmapped = with_current_live_space(BOOT_CPU, |space| {
                    space.unmap_anonymous(base, pages, &mut Unpublished)
                });
                match unmapped {
                    Some(Ok(())) => {
                        MEM_OK.store(true, Ordering::SeqCst);
                        note(TEST_MEM_UNMAPPED, "mem_map test: placed region released");
                        Ok(0)
                    }
                    Some(Err(_)) => Err(Errno::NotFound),
                    None => Err(Errno::NotImplemented),
                }
            }
            Err(_) => Err(Errno::LengthOutOfRange),
        };
        encode(result)
    } else if call == Some(SyscallNumber::DMA_ALLOC) {
        // Carve a coherent DMA buffer into the program's retained live space
        // via the production `LiveSpace::alloc_dma` (`plans/PI.md` 5d-0-ii (c)
        // DMA half). The registry-backed grant owner-check is host-proven in
        // kernel/core; this stand-in accepts only the minted DMA handle and
        // fails closed otherwise. The device-visible-base copy-out is
        // host-proven, so this returns only the CPU VA. `args[0]` is the grant
        // handle, `args[1]` the byte length; no addressing limit is declared
        // for the `virt` coherent stand-in.
        if args[0] != DMA_GRANT_HANDLE {
            return encode(Err(Errno::NotFound));
        }
        let Ok(Some(custody)) = DMA_CUSTODY.get() else {
            return encode(Err(Errno::NotImplemented));
        };
        let custodian =
            DmaCustodian::untranslated(DMA_NODE, DMA_GENERATION, custody, DmaCoherence::Unsnooped);
        let len = args[1] as usize;
        let result =
            match with_current_live_space(BOOT_CPU, |space| space.alloc_dma(len, 0, custodian)) {
                Some(Ok(mapping)) => {
                    DMA_OK.store(true, Ordering::SeqCst);
                    note(
                        TEST_DMA_MAPPED,
                        "dma_alloc test: coherent DMA buffer carved",
                    );
                    Ok(mapping.cpu_va)
                }
                Some(Err(_)) => Err(Errno::OutOfMemory),
                None => Err(Errno::NotImplemented),
            };
        encode(result)
    } else if call == Some(SyscallNumber::EXIT) {
        let exit_code = i32_from_register(args[0]);
        if exit_code == 0
            && MAP_OK.load(Ordering::SeqCst)
            && MEM_OK.load(Ordering::SeqCst)
            && DMA_OK.load(Ordering::SeqCst)
        {
            note(
                TEST_PASS,
                "mmio_map test: EL0 mapped the granted window, read the device magic, round-tripped a placed mem_map, and carved a coherent dma_alloc buffer",
            );
            qemu_exit::exit_success();
        }
        note(
            TEST_FAIL,
            if exit_code == 0 {
                "mmio_map test: program exited 0 with a step left unverified"
            } else {
                "mmio_map test: program exited with a failure code"
            },
        );
        qemu_exit::exit_failure(fail_code(FAIL_EXIT_BASE, exit_code));
    } else {
        note(
            TEST_FAIL,
            "mmio_map test: fixture issued an unexpected syscall",
        );
        qemu_exit::exit_failure(FAIL_UNEXPECTED_SYSCALL);
    }
}

/// A `'static` frame allocator over a dedicated window, supplied to the
/// retained [`LiveSpace`] for anonymous-map frames. The non-`FIXED`
/// `mem_map` round-trip the program performs draws its couple of pages from
/// here (the `mmio_map` device-window path draws page tables from the arch
/// space's own pool instead), so the pool only needs a handful of frames.
const ANON_POOL_PAGES: usize = 16;

#[repr(C, align(4096))]
struct AnonPool([u8; paging::PAGE_SIZE * ANON_POOL_PAGES]);

static mut ANON_POOL: AnonPool = AnonPool([0; paging::PAGE_SIZE * ANON_POOL_PAGES]);

/// The custody the program's DMA carves bind: the production quarantine,
/// returning frames to the same pool the retained space draws them from.
static DMA_CUSTODY: Once<DmaQuarantine> = Once::new();

/// The node the stand-in DMA grant belongs to, and the admission generation of
/// the one driver-shaped program this vertical runs.
const DMA_NODE: u32 = 1;
const DMA_GENERATION: u64 = 1;

/// The hardware tree this vertical stands in for: only the stand-in grant's
/// node is present.
struct StandInTree;

impl HwNodeLiveness for StandInTree {
    fn is_live(&self, node_id: u32) -> bool {
        node_id == DMA_NODE
    }
}

/// Build a leaked `'static` [`FrameAllocator`] over [`ANON_POOL`].
fn leaked_anon_frames() -> &'static FrameAllocator {
    let base = core::ptr::addr_of!(ANON_POOL) as u64;
    let mut map = BootMemoryMap::new();
    map.push(MemoryRegion {
        kind: RegionKind::Usable,
        start: PhysAddr::new(base),
        length: (paging::PAGE_SIZE * ANON_POOL_PAGES) as u64,
    });
    let alloc = FrameAllocator::new(&map).expect("anon pool builds an allocator");
    Box::leak(Box::new(alloc))
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `tairix_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 mmio_map test: starting");

    // Enable FP/SIMD at EL1 before any code that may use it (the `rxe` decoder
    // and the image fills compile to NEON `memcpy`/`memcmp`).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    // P3/P4: discover the board from the embedded `virt` device tree.
    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Parse the build-time `rxe` blob against the kernel's own CFI tag.
    let Ok(image) = tairix_abi::rxe::LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        qemu_exit::exit_failure(FAIL_PARSE);
    };

    // Build the EL0 address space and activate it (so the user mappings, and
    // later the device window, land in the active translation regime).
    let Some(arch) = ArchAddressSpace::new_identity_gigapages(&PAGE_TABLES, IDENTITY_GIB) else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    let root_phys = arch.root_phys();
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, heap,
    // frame pool, and device MMIO (all within `[0, 2 GiB)` on `virt`), so
    // switching it does not move the ground under the running code. Boot CPU.
    unsafe { arch.switch() };

    let mut space = AddressSpace::new(arch);
    // SAFETY: the boot code identity-maps this window and never unmaps it.
    let physmap = unsafe { DirectPhysMap::identity((IDENTITY_GIB as u64) << 30) }
        .expect("the boot direct map addresses its window");
    let request = SpawnRequest {
        image: &image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"mmio-map"],
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once the space is reactivated (via `pre_resume`) and
    // the trap path is installed. Frames are drawn from `FRAME_POOL`.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => qemu_exit::exit_failure(FAIL_BUILD),
    };

    // Retain the *same* arch space live behind the production `LiveSpace`, so
    // the program's `mmio_map` and non-`FIXED` `mem_map` mutate exactly the
    // active address space (`plans/PI.md` 5d-0-ii (b′)/(c)). The device-window
    // region sits 1 GiB above the image bias and the anonymous-heap window
    // 2 GiB above; the anonymous frame allocator backs the placed `mem_map`.
    // SAFETY: the boot code identity-maps this window and never unmaps it.
    let Some(identity) = (unsafe { DirectPhysMap::identity((IDENTITY_GIB as u64) << 30) }) else {
        qemu_exit::exit_failure(FAIL_LIVE_BUILD);
    };
    // SAFETY: as for `identity` above; the quarantine scrubs only frames it
    // was surrendered, all of which lie in this identity-mapped window.
    let Some(custody_map) = (unsafe { DirectPhysMap::identity((IDENTITY_GIB as u64) << 30) })
    else {
        qemu_exit::exit_failure(FAIL_LIVE_BUILD);
    };
    let custody_map: &'static DirectPhysMap = Box::leak(Box::new(custody_map));
    let frames = leaked_anon_frames();
    if DMA_CUSTODY
        .call_once_infallible(|| DmaQuarantine::new(frames, custody_map, &StandInTree))
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_LIVE_BUILD);
    }
    // One CPU runs this vertical, so no other needs reaching.
    let Ok(cpus) = ActiveCpus::new(1) else {
        qemu_exit::exit_failure(FAIL_LIVE_BUILD);
    };
    let Ok(live) = LiveSpace::new(
        space,
        SpaceTlb::new(cpus, None),
        identity,
        frames,
        VirtAddr::new(MMIO_WINDOW_BASE),
        MMIO_WINDOW_PAGES,
        VirtAddr::new(ANON_WINDOW_BASE),
        ANON_WINDOW_PAGES,
        VirtAddr::new(DMA_WINDOW_BASE),
        DMA_WINDOW_PAGES,
        VirtAddr::new(SHARED_WINDOW_BASE),
        SHARED_WINDOW_PAGES,
        VirtAddr::new(FILE_WINDOW_BASE),
        FILE_WINDOW_PAGES,
    ) else {
        qemu_exit::exit_failure(FAIL_LIVE_BUILD);
    };
    // The process's switch-in hook and its port's enter-user handle travel
    // with the space so a thread created later resumes the same way. This
    // vertical's program runs on the boot root with no root switch of its own,
    // so the hook only has to be a real, callable no-op.
    let live = Arc::new(ProcessSpace::new(
        Box::new(live),
        Arc::new(|_stack_top: u64, _tls_base: u64| {}),
        &tairix_arch_aarch64::userentry::USER_MODE,
    ));

    // Bring up the EL1 vectors + GICv2 and install the dispatch callback so the
    // program's `svc`s are handled. Interrupts stay masked — the cooperative
    // `step` loop is the only scheduling mechanism.
    // SAFETY: called once on the boot CPU with a stack established and the MMU
    // enabled (the address-space build switched it on).
    unsafe {
        exceptions::init_vectors();
        tairix_itest_gic::init_boot_cpu().expect("the GIC comes up");
    }
    syscall_entry::set_dispatch_callback(dispatch);
    if tairix_arch_api::fault::set_fault_handler(on_fault).is_err() {
        qemu_exit::exit_failure(FAIL_FAULT_INSTALL);
    }

    // Build the live scheduler over the arch port.
    static ARCH_STORAGE: tairix_arch_aarch64::Aarch64ArchStorage<1> =
        tairix_arch_aarch64::Aarch64ArchStorage::new();
    let arch = Arc::new(tairix_arch_aarch64::Aarch64Arch::new(
        &ARCH_STORAGE,
        BOOT_CPU,
        counter_hz,
    ));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    // Admit the EL0 program as a resumable user kthread that **retains** the
    // live space (`spawn_user_kthread_with_stack_live`, the production aarch64
    // spawn path): its `pre_resume` hook reactivates its page-table root before
    // every switch-in (isolation), the runtime publishes the retained space
    // on the per-CPU live-space slot while it runs, and its work body
    // `enter_user`s into EL0.
    let cs = ContextSwitchHal::new();
    let user_mode = UserMode::new();
    let pre_resume = move |_stack_top: u64| {
        // SAFETY: the MMU is enabled and `root_phys` is the L1 root of a space
        // that identity-maps the low kernel window — `activate_user_root`'s
        // contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |_yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: the entered space is active (the `pre_resume` hook just
        // reactivated it) and the EL1 trap vector + dispatch callback are
        // installed, so the program's `svc`s are handled.
        unsafe { user_mode.enter_user(entry) }
    };
    let Some(stack) = BoxStack::new() else {
        qemu_exit::exit_failure(FAIL_SPAWN);
    };
    if spawn_user_kthread_with_stack_live(
        &sched,
        cs,
        stack,
        BOOT_CPU,
        Priority::Normal,
        pre_resume,
        live,
        work,
        Admission::Runnable,
    )
    .is_err()
    {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(TEST_SPAWNED, "aarch64 mmio_map test: EL0 program spawned");

    // Drive `step` until the program runs. The program exits (0 on success)
    // through the dispatch callback, which finishes the run; a program that
    // drained without exiting, or a never-draining loop, fails loud.
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }

    if steps >= MAX_STEPS {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }
    // The program always exits through the dispatch callback (which finishes
    // the run); reaching here means it drained without exiting.
    qemu_exit::exit_failure(FAIL_DRAINED);
}
