//! The freestanding aarch64 test kernel: build one isolated EL0 program,
//! install a `MemMap` producer over its live address space, and route the
//! program's `mem_map`/`mem_unmap` syscalls through it (`plans/SPAWN.md`
//! `SP5b-2`).

use core::cell::UnsafeCell;
use core::num::NonZeroU16;
use core::panic::PanicInfo;
use core::sync::atomic::{AtomicBool, Ordering};

use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_abi::{
    i32_from_register, CapabilityId, CapabilityQuery, Errno, MapFlags, SyscallNumber,
    SYSCALL_MAX_ARGS,
};
use tairix_arch_aarch64::context_hal::ContextSwitchHal;
use tairix_arch_aarch64::kernel_arch::timer_frequency_hz;
use tairix_arch_aarch64::paging::{
    self, activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool,
};
use tairix_arch_aarch64::userentry::UserMode;
use tairix_arch_aarch64::{
    enable_fp_el1, exceptions, fault, gic, handle_panic_via_serial, qemu_exit, syscall_entry,
    SERIAL_SINK,
};
use tairix_arch_api::fatal::KernelFault;
use tairix_arch_api::{EnterUser, BOOT_CPU};
use tairix_fdt::Fdt;
use tairix_itest_finisher::fail_code;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel_core::{
    spawn_image, spawn_user_kthread, MemMap, SpawnMode, SpawnRequest, Yielder,
};
use tairix_kernel_mem::{
    map_anonymous, page_count_for, unmap_anonymous, AddressSpace, AnonError, DirectPhysMap, Frame,
    PhysAddr, Retire, Unpublished, UserStack,
};
use tairix_kernel_sched_eevdf::{Priority, Scheduler, SchedulerConfig};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level};

// `PROGRAM_RXE: &[u8]`, `USER_BIAS: u64`, `REGION_VA: u64`, and
// `REGION_LEN: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// Gigabytes of identity map the EL0 address space provides: `[0, 2 GiB)`
/// covers the `virt` board's device MMIO (GiB 0) and the RAM base at GiB 1
/// where this kernel runs. [`USER_BIAS`] (64 GiB) and the anonymous region
/// ([`REGION_VA`]) sit far above, on freshly walked tables.
const IDENTITY_GIB: usize = 2;

/// User stack base (1 MiB into the high user region) and size.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (256 KiB).
const USER_STACK_PAGES: u64 = 64;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// Physical frames the test hands the spawn build and the anonymous map.
const FRAME_COUNT: usize = 128;

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4280);
const TEST_SPAWNED: EventId = EventId(4281);
const TEST_PASS: EventId = EventId(4282);
const TEST_FAIL: EventId = EventId(4283);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_GIC: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_PARSE: NonZeroU16 = fail_point!(4);
const FAIL_BUILD: NonZeroU16 = fail_point!(5);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(6);
const FAIL_SPAWN: NonZeroU16 = fail_point!(7);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(8);
const FAIL_UNEXPECTED_SYSCALL: NonZeroU16 = fail_point!(9);
const FAIL_FAULT_MISMATCH: NonZeroU16 = fail_point!(10);
/// Base finisher for an early `exit` from the fixture (a verification failure);
/// the program's exit code is added so the site is identifiable.
const FAIL_EXIT_BASE: NonZeroU16 = fail_point!(100);

/// `true` once a `mem_map` call returned `Ok` to the program.
static MAP_OK: AtomicBool = AtomicBool::new(false);
/// `true` once a `mem_unmap` call returned `Ok` to the program.
static UNMAP_OK: AtomicBool = AtomicBool::new(false);

/// Size of the test's bump heap (startup block buffers + the user kthread's
/// kernel stack + control block). Lives in `.bss` (zeroed by the trampoline).
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the EL0 address space.
static PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Physical-frame backing store the spawn builder and the anonymous map draw
/// user pages from. `align(4096)` so each `PAGE_SIZE` slice is a valid page
/// frame; identity-mapped (its physical address equals its kernel virtual
/// address), so the builders reach it through [`DirectPhysMap::identity`].
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame.
static FRAME_CURSOR: core::sync::atomic::AtomicUsize = core::sync::atomic::AtomicUsize::new(0);

/// Hand out the next identity-mapped physical frame, or `None` when exhausted.
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(base)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn mem_map_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires. It does not widen the program's
/// own authority.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The live EL0 address space the anonymous map/unmap mutate, plus the kernel
/// direct-physical map used to zero frames on map and on free.
struct LiveSpace {
    space: AddressSpace<ArchAddressSpace>,
    physmap: DirectPhysMap,
}

/// The `MemMap` producer the test installs: it maps and unmaps anonymous `RW`
/// memory in the retained live EL0 space through the architecture-neutral
/// `kernel/mem` producer (`map_anonymous`/`unmap_anonymous`), exactly the seam
/// the production handler reaches (`plans/SPAWN.md` SP5b).
struct AnonProducer {
    inner: UnsafeCell<Option<LiveSpace>>,
}

// SAFETY: the test runs on a single CPU and the producer is reached only
// synchronously from the cooperative syscall-dispatch callback (never from
// interrupt context, never cross-CPU, never re-entrantly — one `svc` is
// serviced at a time), so the interior `&mut` the methods take out can never
// alias. This mirrors the single-CPU cooperative discipline the rest of the
// vertical relies on (the access is genuinely exclusive).
unsafe impl Sync for AnonProducer {}

impl AnonProducer {
    const fn new() -> Self {
        Self {
            inner: UnsafeCell::new(None),
        }
    }

    /// Install the retained live space. Called once at boot, before the
    /// dispatch callback can fire.
    ///
    /// # Safety
    ///
    /// Must be called exactly once on the boot CPU before any `mem_map`/
    /// `mem_unmap` is dispatched, so no `&mut` from [`Self::live`] is live.
    unsafe fn install(&self, live: LiveSpace) {
        // SAFETY: see the function contract; single CPU, called once before
        // any dispatch, so nothing aliases the cell.
        unsafe { *self.inner.get() = Some(live) };
    }

    /// Borrow the retained live space mutably, or [`Errno::NotImplemented`]
    /// if none was installed (fail closed).
    fn live(&self) -> Result<&mut LiveSpace, Errno> {
        // SAFETY: see the `unsafe impl Sync` justification — the dispatch path
        // is single-CPU and non-reentrant, so this exclusive borrow is unique.
        let slot = unsafe { &mut *self.inner.get() };
        slot.as_mut().ok_or(Errno::NotImplemented)
    }
}

/// The single installed producer.
static PRODUCER: AnonProducer = AnonProducer::new();

/// Map an [`AnonError`] onto a stable [`Errno`] for the syscall result, folding
/// allocator exhaustion onto [`Errno::OutOfMemory`] and a
/// not-mapped range onto [`Errno::NotFound`] (fail closed).
fn anon_to_errno(err: AnonError) -> Errno {
    match err {
        AnonError::ZeroLength => Errno::LengthOutOfRange,
        AnonError::Unaligned | AnonError::Overflow => Errno::OutOfRange,
        AnonError::OutOfMemory => Errno::OutOfMemory,
        AnonError::NotMapped => Errno::NotFound,
        AnonError::PhysUnmapped | AnonError::Map(_) => Errno::BadAddress,
        // `AnonError` is `#[non_exhaustive]`; a future variant maps to the
        // generic bad-address error rather than being silently dropped.
        _ => Errno::BadAddress,
    }
}

impl MemMap for AnonProducer {
    fn reserve(&self, len: usize, flags: MapFlags, addr_hint: u64) -> Result<u64, Errno> {
        // This harness is an arch-mechanism proving ground that drives
        // `map`/`unmap` directly (the demand-paged reserve-then-fault-in
        // policy lives in `kernel/core` and is covered by its host tests),
        // so a reservation here simply performs the eager map.
        self.map(len, flags, addr_hint)
    }

    fn commit(&self, _pages: u64) -> Result<(), Errno> {
        // This proving-ground producer maps eagerly and tracks no
        // no-overcommit budget, so a headroom reservation is a no-op that
        // permits the (rare) stack-growth path to proceed to `map`.
        Ok(())
    }

    fn map(&self, len: usize, flags: MapFlags, addr_hint: u64) -> Result<u64, Errno> {
        let page_count = page_count_for(len).map_err(anon_to_errno)?;
        // The fixture maps with FIXED placement so the kernel's fault check
        // knows the exact base; this producer maps only there (a placement
        // allocator is the production concern, not this proving ground).
        if !flags.is_fixed() {
            return Err(Errno::NotImplemented);
        }
        let live = self.live()?;
        map_anonymous(
            &mut live.space,
            &live.physmap,
            addr_hint,
            page_count,
            next_frame,
            |_frame| {},
        )
        .map_err(anon_to_errno)?;
        Ok(addr_hint)
    }

    fn unmap(&self, base: u64, len: usize, retire: &mut dyn Retire) -> Result<(), Errno> {
        let page_count = page_count_for(len).map_err(anon_to_errno)?;
        let live = self.live()?;
        unmap_anonymous(
            &mut live.space,
            &live.physmap,
            base,
            page_count,
            retire,
            &mut |_frame| {},
        )
        .map_err(anon_to_errno)
    }
}

/// Encode a `Result<u64, Errno>` into the syscall return register following the
/// `abi-v1` signed convention: a non-negative value on success, `-errno` on
/// error (the encoding `tairix_rt::mem_map`/`mem_unmap` decode).
fn encode(result: Result<u64, Errno>) -> u64 {
    match result {
        Ok(value) => value,
        Err(err) => {
            let neg = -i64::from(err.as_i32());
            neg as u64
        }
    }
}

/// The syscall-dispatch callback the EL0 program's `svc` traps reach.
///
/// `mem_map`/`mem_unmap` are routed through the installed [`PRODUCER`] (the
/// `MemMap` seam); a returned `Ok` records the corresponding progress flag so
/// the fault handler can confirm the program completed the map→verify→unmap
/// sequence before faulting. An `exit` means the fixture took a verification
/// failure branch (the success path is the deliberate fault, not an exit), so
/// it fails the test with the program's exit code. Any other syscall is
/// unexpected and fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: `args_ptr` points at the live `[u64; SYSCALL_MAX_ARGS]` the
    // exception handler built from the saved register frame; reading it for the
    // duration of this call is sound.
    let args = unsafe { &*args_ptr };
    let call = SyscallNumber::from_register(number).ok();

    if call == Some(SyscallNumber::MEM_MAP) {
        let len = args[0] as usize;
        if len == 0 {
            return encode(Err(Errno::LengthOutOfRange));
        }
        // The flags slot is a 32-bit word; `from_bits` then refuses any
        // reserved bit, so a bad word fails closed.
        #[allow(clippy::cast_possible_truncation)]
        let flags = match MapFlags::from_bits(args[1] as u32) {
            Ok(flags) => flags,
            Err(err) => return encode(Err(err)),
        };
        let result = PRODUCER.map(len, flags, args[2]);
        if result.is_ok() {
            MAP_OK.store(true, Ordering::SeqCst);
        }
        encode(result)
    } else if call == Some(SyscallNumber::MEM_UNMAP) {
        let base = args[0];
        let len = args[1] as usize;
        if len == 0 {
            return encode(Err(Errno::LengthOutOfRange));
        }
        // This kernel serves no copy path, so the page table is the only view.
        let result = PRODUCER.unmap(base, len, &mut Unpublished).map(|()| 0);
        if result.is_ok() {
            UNMAP_OK.store(true, Ordering::SeqCst);
        }
        encode(result)
    } else if call == Some(SyscallNumber::EXIT) {
        // The success path is the deliberate fault-on-use-after-unmap, never an
        // exit; an exit therefore means the fixture hit a verification failure
        // branch. Report it with the program's exit code so the failing step
        // is identifiable (fail loud).
        note(TEST_FAIL, "mem_map test: fixture exited before faulting");
        qemu_exit::exit_failure(fail_code(FAIL_EXIT_BASE, i32_from_register(args[0])));
    } else {
        note(
            TEST_FAIL,
            "mem_map test: fixture issued an unexpected syscall",
        );
        qemu_exit::exit_failure(FAIL_UNEXPECTED_SYSCALL);
    }
}

/// The fault handler: a data abort on the released region — after a successful
/// map and unmap — is the use-after-unmap the test proves, so it reports PASS.
/// Anything else is a failure (never returns).
fn on_fault(trap: KernelFault) -> ! {
    let region_end = REGION_VA.wrapping_add(REGION_LEN);
    if trap.syndrome.is_some_and(fault::is_abort)
        && MAP_OK.load(Ordering::SeqCst)
        && UNMAP_OK.load(Ordering::SeqCst)
        && trap
            .address
            .is_some_and(|far| far >= REGION_VA && far < region_end)
    {
        note(
            TEST_PASS,
            "mem_map test: EL0 mapped, verified, unmapped, then faulted on use",
        );
        qemu_exit::exit_success();
    }
    note(TEST_FAIL, "mem_map test: unexpected fault");
    qemu_exit::exit_failure(FAIL_FAULT_MISMATCH);
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `tairix_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 mem_map test: starting");

    // Enable FP/SIMD at EL1 before any code that may use it (the `rxe` decoder
    // and the image fills compile to NEON `memcpy`/`memcmp`).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    // P3/P4: discover the board from the embedded `virt` device tree.
    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Parse the build-time `rxe` blob against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        qemu_exit::exit_failure(FAIL_PARSE);
    };

    // Build the EL0 address space and activate it (so the user mappings, and
    // later the anonymous region, land in the active translation regime).
    let Some(arch) = ArchAddressSpace::new_identity_gigapages(&PAGE_TABLES, IDENTITY_GIB) else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    let root_phys = arch.root_phys();
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, heap,
    // frame pool, and device MMIO (all within `[0, 2 GiB)` on `virt`), so
    // switching it does not move the ground under the running code. Boot CPU.
    unsafe { arch.switch() };

    let mut space = AddressSpace::new(arch);
    // SAFETY: the boot code identity-maps this window and never unmaps it.
    let physmap = unsafe { DirectPhysMap::identity((IDENTITY_GIB as u64) << 30) }
        .expect("the boot direct map addresses its window");
    let request = SpawnRequest {
        image: &image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"mem-map"],
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once the space is reactivated (via `pre_resume`) and
    // the trap path is installed. Frames are drawn from `FRAME_POOL`.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => qemu_exit::exit_failure(FAIL_BUILD),
    };

    // Retain the live space behind the `MemMap` producer so the program's
    // `mem_map`/`mem_unmap` syscalls mutate exactly the active address space.
    // SAFETY: called once on the boot CPU before the dispatch callback (and
    // thus any `mem_map`) can fire.
    unsafe { PRODUCER.install(LiveSpace { space, physmap }) };

    // Bring up the EL1 vectors + GICv2 and install the dispatch + fault
    // callbacks so the program's `svc`s and its deliberate use-after-unmap data
    // abort are handled. Interrupts stay masked — the cooperative `step` loop
    // is the only scheduling mechanism.
    // SAFETY: called once on the boot CPU with a stack established and the MMU
    // enabled (the address-space build switched it on).
    unsafe {
        exceptions::init_vectors();
        gic::init();
    }
    syscall_entry::set_dispatch_callback(dispatch);
    if tairix_arch_api::fault::set_fault_handler(on_fault).is_err() {
        qemu_exit::exit_failure(FAIL_FAULT_MISMATCH);
    }

    // Build the live scheduler over the arch port.
    // Per-CPU bookkeeping backing for this single-CPU vertical.
    static ARCH_STORAGE: tairix_arch_aarch64::Aarch64ArchStorage<1> =
        tairix_arch_aarch64::Aarch64ArchStorage::new();
    let arch = Arc::new(tairix_arch_aarch64::Aarch64Arch::new(
        &ARCH_STORAGE,
        BOOT_CPU,
        counter_hz,
    ));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    // Admit the EL0 program as a resumable user kthread: its `pre_resume` hook
    // reactivates its page-table root before every switch-in (isolation),
    // and its work body `enter_user`s into EL0.
    let cs = ContextSwitchHal::new();
    let user_mode = UserMode::new();
    let pre_resume = move |_stack_top: u64| {
        // SAFETY: the MMU is enabled and `root_phys` is the L1 root of a space
        // that identity-maps the low kernel window — `activate_user_root`'s
        // contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |_yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: the entered space is active (the `pre_resume` hook just
        // reactivated it) and the EL1 trap vector + dispatch callback are
        // installed, so the program's `svc`s are handled.
        unsafe { user_mode.enter_user(entry) }
    };
    if spawn_user_kthread(&sched, cs, BOOT_CPU, Priority::Normal, pre_resume, work).is_err() {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(TEST_SPAWNED, "aarch64 mem_map test: EL0 program spawned");

    // Drive `step` until the program runs. The program never yields and never
    // exits on success — it faults on the use-after-unmap, which `on_fault`
    // reports as PASS (and exits QEMU). A program that returned, exited, or
    // never faulted trips a distinct finisher; a never-draining loop times out
    // (fail-loud).
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }

    // Reaching here means the program drained without faulting on the released
    // region — use-after-unmap was wrongly permitted, or the workload stalled.
    if steps >= MAX_STEPS {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }
    qemu_exit::exit_failure(FAIL_FAULT_MISMATCH);
}
