//! Build-time generator for the Stage 4 PS/2 QEMU integration fixture.
//!
//! The freestanding `x86_64-tairix-none` binary that runs under QEMU
//! cannot pull `ed25519-dalek` in directly (the charter forbids
//! hand-rolled crypto; `lib/crypto` is the only auditable surface that
//! exposes verification). This `build.rs` runs on the host where
//! `ed25519-dalek` is available, signs a synthetic PS/2-driver `.rxe`
//! manifest with a deterministic test seed, and emits a Rust source
//! file the main bin pulls in via `include!`. The emitted file declares
//! three consts:
//!
//! * `PS2_IMAGE: &[u8]` — the signed driver image bytes.
//! * `TRUSTED_SIGNER_PUBKEY: [u8; 32]` — the host's trust-anchor key
//!   that the binary registers on its `HostConfig`.
//! * `SYSCALL_TABLE_HASH: [u8; 32]` — the fingerprint both sides agree
//!   on.
//!
//! The manifest requests exactly `CAP_DRV_LOAD`:
//! `tairix_drv_input_ps2::register` gates on it, and the driver-visible
//! capability set the host installs at register time is the manifest's
//! requested set intersected with the caller's grants, so the capability must appear in *both*. The generator
//! mirrors `tests/integration/drvhost_qemu/build.rs`
//! (no duplication of intent, only the per-test seed
//! differs). Re-running it produces byte-identical output, so the test
//! is deterministic.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;
use tairix_abi::{CapabilityId, DriverKind, DriverManifest, DRIVER_MANIFEST_MAGIC};
use tairix_crypto::Ed25519SecretKey;

/// Deterministic Ed25519 seed for the PS/2 fixture signer. Distinct
/// from the `drvhost_qemu` seed so the two fixtures cannot be confused.
const TEST_SEED: [u8; 32] = [
    0x70, 0x73, 0x32, 0x6b, 0x12, 0x9a, 0x44, 0x7e, 0xc3, 0x05, 0x6d, 0x88, 0x2f, 0xb1, 0xe4, 0x10,
    0x55, 0x9c, 0x0d, 0x73, 0xa6, 0x21, 0x4f, 0x98, 0x3b, 0x60, 0xd2, 0x17, 0x84, 0xcc, 0x09, 0x5e,
];

/// SHA-256 fingerprint of the host's syscall table. Tests do not need
/// to track the real value; what matters is that both sides agree, so
/// we generate a fixed pattern and feed the same one into the host's
/// `HostConfig` from the bin.
const SYS_HASH: [u8; 32] = [0x22; 32];

fn main() {
    tairix_itest_harness::emit_target_cfg();
    println!("cargo:rerun-if-changed=build.rs");

    tairix_itest_harness::link_x86_64_kernel_layout();

    let signing_key = Ed25519SecretKey::from_seed(&TEST_SEED);
    let signer_pubkey: [u8; 32] = *signing_key.public_key().as_bytes();

    // The PS/2 driver's `register` gate consults the host-installed
    // capability bitmap for `CAP_DRV_LOAD`, which is the manifest's
    // requested set intersected with the caller's grants. The cap must
    // therefore be declared here as well as held by the caller.
    let caps: &[u16] = &[CapabilityId::DRV_LOAD.as_u16()];
    let mut manifest = DriverManifest {
        magic: DRIVER_MANIFEST_MAGIC,
        abi_version: tairix_abi::ABI_VERSION_CURRENT,
        kind: DriverKind::UserSpace,
        bind_key_count: 0,
        capability_count: u16::try_from(caps.len()).expect("caps fit in u16"),
        syscall_table_hash: SYS_HASH,
        signer_pubkey,
        signature: [0u8; 64],
    };
    let encoded = manifest.to_le_bytes();
    let mut signed_message = Vec::with_capacity(DriverManifest::WIRE_LEN - 64 + caps.len() * 2);
    signed_message.extend_from_slice(&encoded[..DriverManifest::WIRE_LEN - 64]);
    for c in caps {
        signed_message.extend_from_slice(&c.to_le_bytes());
    }
    let sig = signing_key.sign(&signed_message);
    manifest.signature = *sig.as_bytes();

    let mut image: Vec<u8> = Vec::new();
    image.extend_from_slice(&manifest.to_le_bytes());
    for c in caps {
        image.extend_from_slice(&c.to_le_bytes());
    }
    // No opaque payload bytes are needed: the spawner in the bin
    // returns its single registered entry regardless of payload
    // content.

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs. DO NOT EDIT.\n");
    out.push_str("/// Signed PS/2-driver `.rxe` image bytes.\n");
    out.push_str("pub const PS2_IMAGE: &[u8] = &[");
    for (i, b) in image.iter().enumerate() {
        if i % 16 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n\n");
    out.push_str("/// Trust-anchor public key the host's `HostConfig` is wired to accept.\n");
    out.push_str("pub const TRUSTED_SIGNER_PUBKEY: [u8; 32] = [");
    for (i, b) in signer_pubkey.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n\n");
    out.push_str("/// SHA-256 fingerprint of the host's syscall table.\n");
    out.push_str("pub const SYSCALL_TABLE_HASH: [u8; 32] = [");
    for (i, b) in SYS_HASH.iter().enumerate() {
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}, ").expect("write to String never fails");
    }
    out.push_str("\n];\n");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR set by cargo");
    let path = PathBuf::from(out_dir).join("ps2_fixture.rs");
    fs::write(&path, out).expect("write ps2_fixture.rs");
}
