//! The freestanding x86_64 test kernel: prove that a ring-3 exception the
//! kernel cannot resolve costs the faulting task and nothing else
//! (`plans/OPEN-DEFECTS.md` D42, D86), and that each kill's audit record
//! describes the cause it actually had (D87).
//!
//! The chassis runs the **shared production board bring-up**
//! (`tairix_kernel::x86_64::boot::bring_up_bsp`) — the exact per-CPU table /
//! exception-stub / `#PF` entry / NXE / LAPIC calibration / ACPI /
//! `syscall`+TSS / IO-APIC sequence the production `boot()` pipeline runs,
//! including the production syscall-dispatch callback, user-fault resolver
//! and user-fault terminator — and then installs the production
//! `KernelDispatchHook` into the production `DISPATCH_SLOT` those callbacks
//! already resolve through. Every syscall the programs issue and every
//! ring-3 fault therefore runs the production path.
//!
//! NXE matters here: the `#PF` error code's I/D bit is only set when
//! `IA32_EFER.NXE` is enabled (Intel SDM Vol 3A §4.7), so it is exactly the
//! production configuration in which a ring-3 instruction fetch escapes the
//! resolver's data-only gate — the D42 defect.
//!
//! The parent role is spawned through the production
//! `InitSpawnCtx::spawn_driver_process` seam; it spawns and reaps the three
//! faulting children through the production `spawn` + `wait` syscalls, and
//! the chassis PASSes only on a parent exit of 0 **and** three honestly
//! audited instruction-side kills ([`FaultAuditSink`]). The x86_64
//! `isa-debug-exit` device carries no per-site failure code, so every
//! failure site logs a distinct message (and the parent's diagnostic exit
//! code as a field) before flipping the failure exit.

use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU32, Ordering};

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::{CapabilityId, Errno, WaitFlags, WaitStatus};
use tairix_arch_api::{fatal::KernelFault, BOOT_CPU};
use tairix_arch_x86_64::kernel_arch::{X86_64Arch, X86_64ArchStorage};
use tairix_arch_x86_64::paging::KERNEL_VMA_BASE;
use tairix_arch_x86_64::{fault, qemu_exit};
use tairix_caps::CapabilitySet;
use tairix_kernel::kalloc::{Heap, HEAP_BYTES};
use tairix_kernel::spawn_layout::CHILD_USER_BIAS;
use tairix_kernel::x86_64::boot::{bring_up_bsp, BspBringUp};
use tairix_kernel::x86_64::serial_sink::COM1_CONSOLES;
use tairix_kernel::x86_64::spawn_producer::X86_64_PROCESS_SPAWN;
use tairix_kernel::{
    handle_panic_via_kernel_core, BinArch, FreeListAllocator, DISPATCH_SLOT, SERIAL_SINK,
};
use tairix_kernel_core::{
    AddressSpaceRegistry, AuditEvent, BootReserve, EmbeddedProgram, InitSpawnCtx, KernelArch,
    KernelDispatchHook, KernelInitSpawner, KernelProcessWait, LiveMemMap, ProcessWait,
    ProgramRegistry, RandomReserve, SchedWaitQueueArch, NULL_DMA_ALLOC_FACILITY,
    NULL_MMIO_MAP_FACILITY, NULL_SEAT_REGISTRY, NULL_SHARED_MEM_FACILITY,
};
use tairix_kernel_ipc::PortRegistry;
use tairix_kernel_irq::{IrqTable, UnsupportedController};
use tairix_kernel_mem::{
    BootMemoryMap, FrameAllocator, MemoryRegion, PhysAddr, RegionKind, PAGE_SIZE,
};
use tairix_kernel_sched_cfq::{Scheduler, SchedulerConfig};
use tairix_kernel_sec::{CapTable, ProcessId};
use tairix_log::{log, Event, EventId, Field, FieldValue, Level, Sink};
use tairix_sync::RwLock;

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// Physical frames the production spawn producer draws from: four spawned
/// processes (image, eagerly committed stack top, page tables, kernel
/// stacks) with generous headroom. No child grows its stack — each dies on
/// its first faulting instruction — so the appetite is the spawn cost alone.
const FRAME_COUNT: usize = 2048;

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the workload deadlocked. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4390);
const TEST_SPAWNED: EventId = EventId(4391);
const TEST_PASS: EventId = EventId(4392);
/// Every failure site logs through this id with a distinct message (the
/// x86_64 `isa-debug-exit` device carries no per-site exit code).
const TEST_FAIL: EventId = EventId(4393);

/// Static heap for the free-list allocator (per the production bin); the
/// chassis subsystems and the spawn producer's boxed state allocate from it.
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// Physical-frame backing store the live [`FrameAllocator`] serves the
/// spawn producer from. `align(4096)` so each `PAGE_SIZE` slice is a valid
/// page frame. A higher-half kernel static, so its physical address is its
/// virtual address minus [`KERNEL_VMA_BASE`] — inside the low identity
/// window the producer's page-table walk and each child's own root require.
#[repr(C, align(4096))]
struct FramePool([u8; PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; PAGE_SIZE * FRAME_COUNT]);

/// Per-CPU storage backing the scheduler's arch handle.
static SCHED_ARCH_STORAGE: X86_64ArchStorage<1> = X86_64ArchStorage::new();

/// Per-CPU storage backing the dispatch hook + spawn ctx arch handle.
static HOOK_ARCH_STORAGE: X86_64ArchStorage<1> = X86_64ArchStorage::new();

/// This vertical binds no IRQ lines; the fail-closed controller mirrors
/// what `kernel/core::init` installs when a port exposes no routing.
static IRQ_CONTROLLER: UnsupportedController = UnsupportedController;

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Log the failure site and flip the QEMU failure exit. The
/// `isa-debug-exit` device carries no per-site code, so the message is the
/// site identifier the transcript preserves.
fn fail(message: &'static str) -> ! {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Error,
            id: TEST_FAIL,
            message,
            fields: &[],
        },
    );
    qemu_exit::exit_failure()
}

/// Forward to the shared x86_64 panic bridge (logs to COM1 and parks the
/// CPU; the run then times out and the harness reports the failure).
#[panic_handler]
fn wild_fault_qemu_x86_64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_kernel_core(info)
}

/// The fatal-fault observer, claimed ahead of the production reporter so
/// this vertical owns the machine's fatal policy for this image.
///
/// Reaching it at all is the failure both defects produced: every fault
/// this test provokes is a *ring-3* exception that must be charged to its
/// task, so the kernel's own fatal report must never see one. Naming the
/// vector and the originating ring turns the regression into a diagnosis
/// (vector 14 from ring 3 is the instruction-fetch `#PF` escaping the
/// resolver's data-only gate; 6 or 13 from ring 3 is the missing exception
/// terminator) instead of a run that merely wedges until the harness
/// ceiling.
fn on_fatal_fault(trap: KernelFault) -> ! {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Error,
            id: TEST_FAIL,
            message: "wild-fault test: a fault reached the kernel's fatal report",
            fields: &[
                Field {
                    key: "vector",
                    value: trap.syndrome.map_or(FieldValue::Null, |syndrome| {
                        FieldValue::UnsignedInt(u64::from(fault::syndrome_vector(syndrome)))
                    }),
                },
                Field {
                    key: "from_user",
                    value: trap.syndrome.map_or(FieldValue::Null, |syndrome| {
                        FieldValue::Bool(fault::syndrome_from_user(syndrome))
                    }),
                },
                Field {
                    key: "error_code",
                    value: trap.syndrome.map_or(FieldValue::Null, |syndrome| {
                        FieldValue::UnsignedInt(fault::syndrome_error_code(syndrome))
                    }),
                },
                Field {
                    key: "faulting_addr",
                    value: trap
                        .address
                        .map_or(FieldValue::Null, FieldValue::UnsignedInt),
                },
                Field {
                    key: "rip",
                    value: FieldValue::UnsignedInt(trap.pc),
                },
            ],
        },
    );
    qemu_exit::exit_failure()
}

/// Fault-kill audit records this run produced, and how many of them
/// described the kill honestly (D87).
static FAULT_KILLS: AtomicU32 = AtomicU32::new(0);
static INSTRUCTION_SIDE_KILLS: AtomicU32 = AtomicU32::new(0);

/// The audit sink the production dispatch hook writes through: it replays
/// every record to serial (so the QEMU transcript is unchanged) and grades
/// each `TaskFaultKilled` record against the cause the kill actually had.
///
/// All three roles are killed by an exception the CPU raised on an
/// *instruction* — a fetch from a No-Execute page, an invalid opcode, a
/// privileged opcode — so none of them touched a data address. A record
/// that instead placed the faulting program counter among the task's data
/// mappings (the "stack overrun 40 KB below the guard" every one of these
/// used to audit as, because a program's text sits under its stack) is a
/// lie in a security-relevant record, and this grades it as one.
struct FaultAuditSink;

impl Sink for FaultAuditSink {
    fn write_event(&self, event: &Event<'_>) {
        SERIAL_SINK.write_event(event);
        if event.id != AuditEvent::TaskFaultKilled.id() {
            return;
        }
        FAULT_KILLS.fetch_add(1, Ordering::Relaxed);
        let says = |key: &str, want: &str| {
            event
                .fields
                .iter()
                .any(|f| f.key == key && matches!(f.value, FieldValue::Str(value) if value == want))
        };
        if says("access", "instruction")
            && says("fault_class", "instruction")
            && says("fault_offset", "no_data_address")
            && !event.fields.iter().any(|f| f.key == "region_offset")
        {
            INSTRUCTION_SIDE_KILLS.fetch_add(1, Ordering::Relaxed);
        }
    }
}

static AUDIT_SINK: FaultAuditSink = FaultAuditSink;

/// The capability set the fixture programs run under: `PROC_SPAWN` for the
/// parent's `spawn` only. The parent's set doubles as the inherited ceiling
/// the production spawn intersects each child's manifest request with, so a
/// child's effective set is exactly its registry row's request — and the
/// children request nothing (faulting needs no capability).
fn parent_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::PROC_SPAWN);
    caps
}

/// The program registry the production `spawn` syscall resolves the
/// parent's child paths against: one `rxe` image, three rows, each pinning
/// its faulting role through the registered default argument vector.
static CHILD_PROGRAMS: [EmbeddedProgram; 3] = [
    EmbeddedProgram {
        path: b"/bin/wf-jump",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"wf", b"jump"],
    },
    EmbeddedProgram {
        path: b"/bin/wf-ud",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"wf", b"ud"],
    },
    EmbeddedProgram {
        path: b"/bin/wf-gp",
        rxe: PROGRAM_RXE,
        caps: &[],
        args: &[b"wf", b"gp"],
    },
];

/// The registry over [`CHILD_PROGRAMS`].
static PROGRAMS: ProgramRegistry = ProgramRegistry::new(&CHILD_PROGRAMS);

/// The leaked-`'static` kernel subsystems the production dispatch hook and
/// spawn context borrow — the vertical's analogue of `KernelState`, lifted
/// by one-shot `Box::leak` publishes exactly as `kernel_core::kernel_main`
/// does (a one-shot publish, not a global mutable static).
struct Subsystems {
    frames: &'static FrameAllocator,
    sched: &'static Scheduler<BinArch>,
    arch: &'static BinArch,
    caps: &'static RwLock<CapTable>,
    peer_watch: &'static tairix_kernel_core::PeerWatch,
    ipc: &'static RwLock<PortRegistry>,
    aspaces: &'static RwLock<AddressSpaceRegistry>,
    rng: &'static RwLock<Box<dyn RandomReserve + Send + Sync>>,
    irq_table: &'static IrqTable,
}

/// Build the live kernel subsystems: the `kernel/mem` frame allocator over
/// the dedicated pool (so the spawn producer draws its frames from the
/// production path), the scheduler over the production `BinArch` wrapper,
/// and the capability / port / address-space / random / IRQ state the
/// production hook borrows. The two arch handles are built from the same
/// board facts the bring-up discovered.
fn leak_subsystems(board: &BspBringUp) -> Subsystems {
    let mut memory_map = BootMemoryMap::new();
    memory_map.push(MemoryRegion {
        // The pool is a higher-half kernel static; its physical address is
        // its virtual address minus the kernel window base, inside the low
        // identity window every child root maps.
        start: PhysAddr::new(core::ptr::addr_of!(FRAME_POOL) as u64 - KERNEL_VMA_BASE),
        length: (PAGE_SIZE * FRAME_COUNT) as u64,
        kind: RegionKind::Usable,
    });
    let Ok(frames) = FrameAllocator::new(&memory_map) else {
        fail("wild-fault test: frame allocator construction failed");
    };
    let frames: &'static FrameAllocator = Box::leak(Box::new(frames));

    let Ok(sched_arch) = X86_64Arch::new(
        &SCHED_ARCH_STORAGE,
        0,
        board.bsp_lapic_id,
        &board.cpu_to_lapic,
    ) else {
        fail("wild-fault test: scheduler arch handle construction failed");
    };
    let sched_arch = Arc::new(BinArch::new(
        sched_arch,
        board.calibration,
        board.irq_routing,
    ));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), sched_arch) else {
        fail("wild-fault test: scheduler construction failed");
    };

    let Ok(hook_arch) = X86_64Arch::new(
        &HOOK_ARCH_STORAGE,
        0,
        board.bsp_lapic_id,
        &board.cpu_to_lapic,
    ) else {
        fail("wild-fault test: hook arch handle construction failed");
    };

    Subsystems {
        frames,
        sched: Box::leak(Box::new(sched)),
        arch: Box::leak(Box::new(BinArch::new(
            hook_arch,
            board.calibration,
            board.irq_routing,
        ))),
        caps: Box::leak(Box::new(RwLock::new(CapTable::new()))),
        peer_watch: Box::leak(Box::new(tairix_kernel_core::PeerWatch::new())),
        ipc: Box::leak(Box::new(RwLock::new(PortRegistry::new()))),
        aspaces: Box::leak(Box::new(RwLock::new(AddressSpaceRegistry::new()))),
        rng: Box::leak(Box::new(RwLock::new(
            Box::new(BootReserve::new()) as Box<dyn RandomReserve + Send + Sync>
        ))),
        irq_table: Box::leak(Box::new(IrqTable::new(0))),
    }
}

/// Boot entry point — the symbol the arch crate's boot trampoline calls.
#[no_mangle]
pub extern "C" fn kernel_main(boot_info: u64) -> ! {
    note(TEST_START, "x86_64 wild-fault test: starting");

    // Claim the set-once fatal slot before the bring-up publishes the
    // production reporter into it: no fault this vertical provokes may
    // reach the kernel's own fatal report, so observing one is the failure.
    if tairix_arch_api::fault::set_fault_handler(on_fatal_fault).is_err() {
        fail("wild-fault test: fatal-fault slot already occupied");
    }

    // The shared production board bring-up: per-CPU tables, the per-vector
    // exception stubs, the dedicated `#PF` entry, NXE, LAPIC calibration,
    // ACPI, the production dispatch callback + user-fault resolver +
    // user-fault terminator (all resolving through the production
    // `DISPATCH_SLOT` this chassis fills below), `syscall`/TSS entry, and
    // the masked IO-APIC routing.
    let Ok(board) = bring_up_bsp(boot_info, &SERIAL_SINK) else {
        fail("wild-fault test: board bring-up failed");
    };

    // The fixture `rxe`'s baked relocations must target the bias the
    // production producer maps every child at; a drifted constant would
    // admit a child whose pointers do not match its mapping (fail closed).
    if USER_BIAS != CHILD_USER_BIAS {
        fail("wild-fault test: fixture bias drifted from the spawn layout");
    }

    let sys = leak_subsystems(&board);

    // Publish the wait-queue arch hook so parked waiters (the parent in
    // `wait`) are genuinely unparked by their wake events — the same
    // adapter the production boot path installs.
    let wait_arch = SchedWaitQueueArch::leak(sys.sched, sys.arch);
    if tairix_kernel_core::waitq::install_wait_arch(wait_arch).is_err() {
        fail("wild-fault test: wait-queue arch install failed");
    }

    // The scheduler-side process-wait producer: records every parent/child
    // link the production spawn paths register and backs the production
    // `wait` syscall the parent blocks in — including the fault-kill exit
    // status each child's termination records.
    let wait_producer: &'static KernelProcessWait<BinArch> =
        Box::leak(Box::new(KernelProcessWait::new(sys.arch)));

    // The production live-space producer serves the `mem_map` pair backing
    // each program's `tairix-rt` heap.
    let live: &'static LiveMemMap<BinArch> = Box::leak(Box::new(LiveMemMap::new(sys.arch)));

    // Publish the production dispatch hook into the production
    // `DISPATCH_SLOT` — the exact slot `bring_up_bsp`'s installed
    // `production_dispatch` / `production_user_fault` /
    // `production_user_fault_terminate` callbacks resolve through — so every
    // syscall the programs issue (`spawn`, `wait`, `exit`) and every ring-3
    // fault termination runs the production caller-context resolution and
    // handler path.
    let hook: &'static KernelDispatchHook<'static, BinArch> = Box::leak(Box::new(
        KernelDispatchHook::new(
            sys.sched,
            sys.caps,
            sys.arch,
            &AUDIT_SINK,
            sys.irq_table,
            &IRQ_CONTROLLER,
            sys.ipc,
            sys.aspaces,
            sys.rng,
            &COM1_CONSOLES,
            sys.frames,
            sys.frames,
            &PROGRAMS,
            wait_producer,
            // No seat / MMIO / DMA surface in this vertical; those producers
            // stay fail-closed. No filesystem or file-map producer either:
            // every fault this vertical exists to exercise is unresolvable
            // by construction.
            &NULL_SEAT_REGISTRY,
            live,
            &NULL_MMIO_MAP_FACILITY,
            &NULL_DMA_ALLOC_FACILITY,
        )
        .with_peer_watch(sys.peer_watch),
    ));
    if DISPATCH_SLOT.install_dispatcher(hook).is_err() {
        fail("wild-fault test: dispatch hook install failed");
    }

    // Publish the launch-services bundle the deferred child-load path reads:
    // the arch image builder builds each admitted child's image on the
    // child's own first slice, off this chassis's cooperative drive. The one
    // shared build+publish the production boot path uses.
    let _ = tairix_kernel_core::spawn_services::install_over(
        sys.arch,
        sys.frames,
        &SERIAL_SINK,
        &tairix_kernel_core::NULL_FILESYSTEM,
        None,
        sys.aspaces,
        sys.caps,
        sys.peer_watch,
        wait_producer,
        &X86_64_PROCESS_SPAWN,
    );

    // Spawn the parent role through the production runtime-spawn seam
    // (`KernelSpawnCtx` assembly inside `KernelInitSpawner`), recorded
    // against the kernel supervisor identity so this chassis can reap it.
    let init_ctx = KernelInitSpawner::new(
        sys.frames,
        &SERIAL_SINK,
        sys.sched,
        sys.caps,
        sys.peer_watch,
        sys.aspaces,
        sys.arch,
        wait_producer,
        sys.irq_table,
        &NULL_SHARED_MEM_FACILITY,
        KernelArch::cross_cpu_tlb_shootdown(sys.arch),
    );
    let Ok(parent_pid) = init_ctx.spawn_driver_process(
        "/bin/wf-parent",
        PROGRAM_RXE,
        parent_caps(),
        &[],
        &[b"wf", b"parent"],
        None,
    ) else {
        fail("wild-fault test: parent spawn failed");
    };
    note(
        TEST_SPAWNED,
        "x86_64 wild-fault test: parent spawned through the production seam",
    );

    // The spawn seam hands back a `u64` id and the wait ABI takes a signed
    // pid; convert rather than cast, so an id that could not be reaped fails
    // the run instead of being silently wrapped.
    let Ok(parent_pid) = i64::try_from(parent_pid) else {
        fail("wild-fault test: parent pid does not fit the wait ABI");
    };
    drive_to_parent_exit(sys.sched, wait_producer, parent_pid)
}

/// The budget-bounded cooperative drive: step the scheduler and poll the
/// wait producer for the parent's exit between steps.
///
/// The parent runs the whole jump / ud / gp sequence through production
/// spawn + wait; a parent exit of 0 is the PASS, anything else names the
/// failing site through the logged diagnostic exit code.
fn drive_to_parent_exit(
    sched: &Scheduler<BinArch>,
    wait_producer: &KernelProcessWait<BinArch>,
    parent_pid: i64,
) -> ! {
    let mut steps = 0u64;
    while steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;

        // Deliver any wake a handler deferred while the task ran — the same
        // between-dispatches service the production loop performs; without
        // it a child's fault-kill never unparks the parent blocked in
        // `wait`.
        let _ = tairix_kernel_core::waitq::drain_pending_wakes();

        match wait_producer.poll(ProcessId(0), parent_pid, WaitFlags::empty()) {
            Ok(reaped) => match reaped.status {
                WaitStatus::Exited(0) => {
                    // Each role died correctly; each must also have been
                    // *described* correctly. A kill audited against the
                    // task's data mappings still reaps at 139, so the exit
                    // status alone cannot catch the record lying about the
                    // cause.
                    let kills = FAULT_KILLS.load(Ordering::Relaxed);
                    let honest = INSTRUCTION_SIDE_KILLS.load(Ordering::Relaxed);
                    if kills != 3 {
                        fail("wild-fault test: expected exactly three fault-kill audit records");
                    }
                    if honest != kills {
                        fail("wild-fault test: a fault-kill was audited against the task's data mappings");
                    }
                    note(
                        TEST_PASS,
                        "x86_64 wild-fault test: all three ring-3 faults killed only their task",
                    );
                    qemu_exit::exit_success();
                }
                WaitStatus::Exited(code) => {
                    // The parent's diagnostic exit code names the failing
                    // role/site; log it as a field before the (code-less)
                    // x86_64 failure exit.
                    log(
                        &SERIAL_SINK,
                        &Event {
                            level: Level::Error,
                            id: TEST_FAIL,
                            message: "wild-fault test: parent exited non-zero",
                            fields: &[Field {
                                key: "parent_exit_code",
                                value: FieldValue::SignedInt(i64::from(code)),
                            }],
                        },
                    );
                    qemu_exit::exit_failure();
                }
                WaitStatus::Stopped(_) => {
                    fail("wild-fault test: parent stopped instead of exiting");
                }
            },
            Err(Errno::WouldBlock) => {}
            Err(_) => fail("wild-fault test: wait poll failed"),
        }

        // A fully drained workload without a reapable parent means the
        // parent vanished down a path that never recorded its exit; fail
        // with a distinct message rather than spinning out the watchdog.
        if sched.live_task_count() == 0 {
            fail("wild-fault test: workload drained without a reapable parent");
        }
    }
    fail("wild-fault test: watchdog expired (deadlock)");
}
