//! The freestanding aarch64 test kernel: spawn one SOLE EL0 spinner (no
//! competitor, so the tickless scheduler never arms the preemption timer),
//! have its kthread send itself a reschedule SGI just before entering EL0,
//! and prove that non-timer interrupt drives the return-to-EL0 preempt point
//! via the need-resched latch — the regression test for the
//! interrupt-return-to-EL0 need-resched fix.

use core::num::NonZeroU16;
use core::panic::PanicInfo;
use core::sync::atomic::{AtomicU64, AtomicUsize, Ordering};

use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_abi::{CapabilityId, CapabilityQuery, SyscallNumber, SYSCALL_MAX_ARGS};
use tairix_arch_aarch64::context_hal::ContextSwitchHal;
use tairix_arch_aarch64::kernel_arch::timer_frequency_hz;
use tairix_arch_aarch64::paging::{
    self, activate_user_root, AddressSpace as ArchAddressSpace, PageTablePool,
};
use tairix_arch_aarch64::preempt::{self, PreemptStorage};
use tairix_arch_aarch64::userentry::UserMode;
use tairix_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, SERIAL_SINK,
};
use tairix_arch_api::{CpuId, EnterUser, BOOT_CPU};
use tairix_fdt::Fdt;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel_core::{
    on_reschedule_ipi, preempt_current, preemption_count, reschedule_current, spawn_image,
    spawn_user_kthread, RescheduleAction, SpawnMode, SpawnRequest, Yielder,
};
use tairix_kernel_mem::{AddressSpace, DirectPhysMap, Frame, PhysAddr, UserStack};
use tairix_kernel_sched_eevdf::{Priority, Scheduler, SchedulerConfig};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level};

// `PROGRAM_RXE: &[u8]` and `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// Preemption quantum rate — the shared production rate. Only recorded here
/// (the timer is never armed, since the spinner is the sole task); the SGI,
/// not the timer, is what drives this test's preemption.
const PREEMPT_TICK_HZ: u64 = tairix_arch_api::timer::DEFAULT_PREEMPT_QUANTUM_HZ;

/// Gigabytes of identity map the EL0 address space provides: `[0, 2 GiB)`
/// covers the `virt` board device MMIO (GiB 0) and the RAM base at GiB 1.
const IDENTITY_GIB: usize = 2;

/// User stack base (1 MiB into the high user region) and size.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (256 KiB).
const USER_STACK_PAGES: u64 = 64;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to the program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// Physical frames the spawn build draws from.
const FRAME_COUNT: usize = 256;

/// `step`-loop watchdog: maximum iterations before declaring the workload
/// stuck. Sized generously for TCG.
const MAX_STEPS: u64 = 50_000_000;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4290);
const TEST_SPAWNED: EventId = EventId(4291);
const TEST_PASS: EventId = EventId(4292);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_GIC_NOT_DISCOVERED: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_PARSE: NonZeroU16 = fail_point!(4);
const FAIL_BUILD: NonZeroU16 = fail_point!(5);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(6);
const FAIL_SPAWN: NonZeroU16 = fail_point!(7);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(8);
const FAIL_NO_PREEMPT: NonZeroU16 = fail_point!(9);
const FAIL_PREEMPT_STORAGE: NonZeroU16 = fail_point!(10);
const FAIL_UNEXPECTED_SYSCALL: NonZeroU16 = fail_point!(11);

/// Count of latch-gated reschedules the preempt callback performed. The SGI
/// is the only need-resched source (no timer armed, no device IRQ), so this
/// counts SGI-driven EL0 preemptions.
static PREEMPTIONS: AtomicU64 = AtomicU64::new(0);
/// `exit` syscalls observed (the spinner exits exactly once on completion).
static EXITS: AtomicU64 = AtomicU64::new(0);

/// Bump-heap size: the spawn caller allocates the startup-vector block buffer
/// and the user kthread's kernel stack + control block from it.
const HEAP_SIZE: usize = 2 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the EL0 address space's stage-1 hierarchy.
static PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Per-CPU preemption backing for the single boot CPU.
static PREEMPT_STORAGE: PreemptStorage<1> = PreemptStorage::new();

/// Physical-frame backing store the spawn builder allocates user pages from.
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Hand out the next identity-mapped physical frame from [`FRAME_POOL`], or
/// `None` when the pool is exhausted (the spawn builder then fails closed).
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    let base = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(base)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn preempt_wake_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN` — the privilege the
/// spawn caller requires.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The EL0-preemption callback the IRQ path invokes on return-to-EL0 for any
/// interrupt — this drives the **real** production
/// [`tairix_kernel_core::preempt_current`] (the exact function the
/// production ports install as `on_user_preempt_point`), which reschedules only
/// when this
/// CPU owes one and, crucially, increments the kernel's per-CPU preemption
/// count on a real suspension. The local mirror records each true return so
/// the test asserts the kernel counter tracks it (the always-zero-counter
/// regression).
extern "C" fn preempt_dispatch(cpu: CpuId) {
    if preempt_current(cpu) {
        PREEMPTIONS.fetch_add(1, Ordering::SeqCst);
    }
}

/// The syscall-dispatch callback the spinner's final `exit` `svc` reaches.
///
/// The spinner issues no `yield`; its only syscall is the `exit` that
/// `tairix-rt` routes `main`'s return through. Any other syscall is unexpected
/// and fails the test loudly.
extern "C" fn dispatch(number: u64, _args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    let call = SyscallNumber::from_register(number).ok();
    if call == Some(SyscallNumber::EXIT) {
        EXITS.fetch_add(1, Ordering::SeqCst);
        // Reap the caller: this switches back to the dispatcher and never
        // resumes the task, so the `0` below is unreachable.
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Exit);
        0
    } else {
        note(TEST_START, "fixture program issued an unexpected syscall");
        qemu_exit::exit_failure(FAIL_UNEXPECTED_SYSCALL);
    }
}

/// Build the isolated EL0 address space from the fixture `image` over
/// [`PAGE_TABLES`], returning its stage-1 root and the entry register state.
fn build_el0_space(image: &LoadImage) -> (u64, tairix_arch_api::UserEntry) {
    let Some(arch) = ArchAddressSpace::new_identity_gigapages(&PAGE_TABLES, IDENTITY_GIB) else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    let root_phys = arch.root_phys();
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
    // heap, the frame pool, and the device MMIO (all within `[0, 2 GiB)` on the
    // `virt` board), so enabling it does not move the ground under the running
    // code. Called on the boot CPU.
    unsafe { arch.switch() };

    let mut space = AddressSpace::new(arch);
    // SAFETY: the boot code identity-maps this window and never unmaps it.
    let physmap = unsafe { DirectPhysMap::identity((IDENTITY_GIB as u64) << 30) }
        .expect("the boot direct map addresses its window");
    let request = SpawnRequest {
        image,
        image_bytes: PROGRAM_RXE,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"el0"],
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once its space is reactivated (via the `pre_resume`
    // hook) and the EL1 trap path is installed. The frame source draws
    // identity-mapped frames from `FRAME_POOL`.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => qemu_exit::exit_failure(FAIL_BUILD),
    };
    (root_phys, entry)
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `tairix_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 EL0 SGI-wake preemption test: starting");

    // Enable FP/SIMD at EL1 before any code that may use it (the `rxe` decoder
    // and `build_process_image`'s fills compile to NEON `memcpy`/`memcmp`).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    // Discover the board from the embedded `virt` device tree.
    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC_NOT_DISCOVERED);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC_NOT_DISCOVERED);
    }

    // Parse the build-time `rxe` blob once against the kernel's own CFI tag.
    let Ok(image) = LoadImage::parse(PROGRAM_RXE, &SYSCALL_TABLE_HASH) else {
        qemu_exit::exit_failure(FAIL_PARSE);
    };

    // Build the isolated EL0 address space (it leaves its own space active).
    let (root_phys, entry) = build_el0_space(&image);

    // Bring up the EL1 vectors + GICv2 and install the dispatch callback so the
    // spinner's `exit` `svc` is handled.
    // SAFETY: called once on the boot CPU with a stack established and the MMU
    // enabled (the address-space build switched it on).
    unsafe {
        exceptions::init_vectors();
        tairix_itest_gic::init_boot_cpu().expect("the GIC comes up");
    }
    syscall_entry::set_dispatch_callback(dispatch);

    // Wire the production preemption surface: register the per-CPU storage,
    // install the latch-gated EL0-preemption callback and the reschedule-IPI
    // callback, record the quantum interval, and enable the timer PPI (left
    // disarmed — the spinner is the sole task, so the scheduler never arms it).
    // Then enable the reschedule SGI so a self-directed IPI traps here.
    if PREEMPT_STORAGE.register().is_err() {
        qemu_exit::exit_failure(FAIL_PREEMPT_STORAGE);
    }
    preempt::set_preempt_callback(preempt_dispatch);
    preempt::set_ipi_callback(on_reschedule_ipi);
    let interval = preempt::interval_for_hz(counter_hz, PREEMPT_TICK_HZ);
    // SAFETY: the boot CPU (id 0); the callbacks are installed (above), the
    // per-CPU storage is registered (above), the EL1 vector table is installed
    // (`init_vectors`), and the GIC is up (`gic::init`). This records the
    // quantum, enables the timer PPI, and leaves the timer disarmed.
    unsafe {
        preempt::init_local_preempt(BOOT_CPU, interval);
        // Enable the reschedule SGI (INTID 0) at the GIC so a self-directed
        // IPI is delivered to this CPU's IRQ path.
        preempt::enable_ipi();
    }

    // Build the live scheduler over the arch port.
    static ARCH_STORAGE: tairix_arch_aarch64::Aarch64ArchStorage<1> =
        tairix_arch_aarch64::Aarch64ArchStorage::new();
    let arch = Arc::new(tairix_arch_aarch64::Aarch64Arch::new(
        &ARCH_STORAGE,
        BOOT_CPU,
        counter_hz,
    ));
    if tairix_kernel_core::initialize_cpu_state(1).is_err() {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    }
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    // Admit the spinner as the SOLE resumable user kthread: its `pre_resume`
    // hook reactivates its page-table root (isolation), and its work body
    // sends itself a reschedule SGI and then `enter_user`s into EL0. Being the
    // only runnable task, the scheduler keeps the timer disarmed, so the SGI —
    // a non-timer interrupt taken on the first EL0 instruction — is the only
    // thing that can drive the return-to-EL0 preempt point.
    let cs = ContextSwitchHal::new();
    let user_mode = UserMode::new();
    let pre_resume = move |_stack_top: u64| {
        // SAFETY: the MMU is enabled and `root_phys` is the L1 root of a space
        // that identity-maps the low kernel window the running kernel executes
        // from — exactly `activate_user_root`'s contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |_yielder: &mut Yielder<ContextSwitchHal>| {
        // Post a self-directed reschedule SGI while IRQs are masked at EL1: it
        // stays pending until `enter_user`'s `eret` unmasks IRQ in EL0, where
        // it is taken on the first EL0 instruction. This closure runs only on
        // the first dispatch; after an involuntary preemption the task resumes
        // its saved EL0 trap context, not this body, so exactly one SGI fires.
        // SAFETY: the GIC is initialised and the reschedule SGI is enabled
        // (`enable_ipi`), so `send_sgi` posts a deliverable INTID 0.
        gic::send_sgi(BOOT_CPU).expect("the boot CPU's interface is up");
        // SAFETY: the entered space is active (the `pre_resume` hook just
        // reactivated it) and the EL1 trap vector + dispatch callback are
        // installed, so the program's `exit` `svc` is handled and the pending
        // SGI traps to `LOWER_IRQ`.
        unsafe { user_mode.enter_user(entry) }
    };
    if spawn_user_kthread(&sched, cs, BOOT_CPU, Priority::Normal, pre_resume, work).is_err() {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(
        TEST_SPAWNED,
        "aarch64 EL0 SGI-wake preemption test: spinner spawned",
    );

    // Dispatch loop: drive `step` until the spinner finishes. The self-SGI is
    // taken on EL0 entry, latches need-resched, and the return-to-EL0 preempt
    // point reschedules the spinner (the preempt callback `reschedule_current`s
    // back here). The spinner then resumes mid-loop and runs to its `exit`. If
    // the non-timer interrupt failed to drive the preempt point (the pre-fix
    // bug), the sole spinner would run unpreempted forever inside EL0 and the
    // harness would time out (fail-loud).
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }
    if sched.live_task_count() != 0 {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }
    // The SGI, taken from EL0, must have driven the return-to-EL0 preempt point
    // at least once — the regression assertion. Before the fix this stayed 0
    // (the preempt point ran only for the timer PPI) and the run timed out.
    let observed = PREEMPTIONS.load(Ordering::SeqCst);
    if observed == 0 {
        qemu_exit::exit_failure(FAIL_NO_PREEMPT);
    }
    // The kernel's own per-CPU preemption counter — the value sysmon reports —
    // must have advanced by exactly the real preemptions performed. This is the
    // end-to-end regression for the "preempt counter stuck at 0" defect: the
    // counter now lives in the preemption mechanism and moves under real
    // preemption, not in the tickless scheduler where it never incremented.
    if preemption_count(BOOT_CPU) != observed {
        qemu_exit::exit_failure(FAIL_NO_PREEMPT);
    }
    // The spinner resumed correctly after the preemption and ran to its final
    // `exit` exactly once.
    if EXITS.load(Ordering::SeqCst) != 1 {
        qemu_exit::exit_failure(FAIL_DEADLOCK);
    }

    note(
        TEST_PASS,
        "aarch64 EL0 SGI-wake preemption test: non-timer IRQ preempted the sole task",
    );
    qemu_exit::exit_success();
}
