//! The freestanding aarch64 test kernel: spawn the driver-stub program
//! through the production parameterised spawn path and complete the
//! Stage 4.HW register handshake over production IPC (`PLAN.md` Stage 4.HW).

use core::num::NonZeroU16;
use core::panic::PanicInfo;

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::hwtree::HwResource;
use tairix_abi::{
    CapabilityId, DriverBindKey, DriverRegisterReply, Errno, HwDeviceClass, HwMatchKey, HwNode,
    PortName, HW_NODE_ROOT, SYSCALL_MAX_ARGS,
};
use tairix_arch_aarch64::kernel_arch::timer_frequency_hz;
use tairix_arch_aarch64::paging::{
    configure_device_gigapages, configure_kernel_gigapages, install_boot_physmap,
    AddressSpace as ArchAddressSpace, PageTablePool, GIGAPAGE_MASK_WORDS,
};
use tairix_arch_aarch64::{
    enable_fp_el1, exceptions, gic, handle_panic_via_serial, qemu_exit, syscall_entry, Aarch64Arch,
    Aarch64ArchStorage, SERIAL_SINK,
};
use tairix_arch_api::BOOT_CPU;
use tairix_caps::CapabilitySet;
use tairix_crypto::Ed25519PublicKey;
use tairix_devmgr::{DeviceManager, DriverCandidate};
use tairix_drvhost::ImageSource;
use tairix_fdt::Fdt;
use tairix_itest_finisher::fail_point;
use tairix_kalloc::FreeListAllocator;
use tairix_kernel::aarch64::arch_wrapper::{Aarch64BinArch, UART_ONLY_CONSOLES};
use tairix_kernel::aarch64::spawn_producer::{AARCH64_PROCESS_SPAWN, USER_IMAGE_BIAS};
use tairix_kernel::dispatch_core::{dispatch_via_slot, read_raw_args};
use tairix_kernel::driver_spawn_loader::{InitCtxDriverProcessSpawn, SpawnDriverLoader};
use tairix_kernel_core::AddressSpaceRegistry;
use tairix_kernel_core::{
    BootReserve, DispatchCallbackSlot, KernelArch, KernelDispatchHook, KernelInitSpawner,
    RandomReserve, EMPTY_PROGRAM_REGISTRY, NULL_DMA_ALLOC_FACILITY, NULL_MEM_MAP,
    NULL_MMIO_MAP_FACILITY, NULL_PROCESS_WAIT, NULL_SEAT_REGISTRY, NULL_SHARED_MEM_FACILITY,
};
use tairix_kernel_ipc::{EndpointId, Port, PortRegistry};
use tairix_kernel_irq::{IrqTable, UnsupportedController};
use tairix_kernel_mem::{
    BootMemoryMap, FrameAllocator, MemoryRegion, PhysAddr, RegionKind, PAGE_SIZE,
};
use tairix_kernel_sched_cfq::{Scheduler, SchedulerConfig};
use tairix_kernel_sec::{CapTable, ProcessId, TaskCapabilities, UserId};
use tairix_log::{log, Event, EventId, Level};
use tairix_sync::RwLock;

// `USER_BIAS: u64`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));
// `DRIVER_IMAGE: &[u8]` (signed UserSpace manifest wrapping `PROGRAM_RXE`)
// and `DRIVER_SIGNER_PUBKEY: [u8; 32]`, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/driver_image.rs"));
// The canonical QEMU `virt` device tree, dumped and embedded at build time.
include!(concat!(env!("OUT_DIR"), "/dtb_fixture.rs"));

/// Gigabytes of identity map the boot address space provides: `[0, 2 GiB)`
/// covers the `virt` board's device MMIO (GiB 0) and the RAM base at GiB 1
/// where this kernel, its heap, and the frame pool live.
const IDENTITY_GIB: usize = 2;

/// Reply endpoint id the host binds and hands the spawned stub. Any unused
/// id works; `arg(1)` carries its ASCII decimal form ("7").
const REPLY_ENDPOINT: EndpointId = EndpointId(7);

/// ASCII decimal form of [`REPLY_ENDPOINT`] passed as the stub's `arg(1)`.
const REPLY_ENDPOINT_ARG: &[u8] = b"7";

/// Well-known port name the reply endpoint is published under, passed to
/// the stub as `arg(2)`. The stub resolves it through the production
/// `port_resolve` syscall and refuses to reply unless the resolved
/// endpoint matches `arg(1)` — proving the publish → resolve → send path
/// end to end (the way a driver or desktop client finds a well-known
/// service port it was not handed directly).
const REPLY_PORT_NAME: &[u8] = b"drvhost.reply";

/// Raw handle value the stub reports — pinned to the fixture program's
/// `STUB_HANDLE_RAW` (`driver_register_program/src/main.rs`); the PASS check
/// asserts the decoded reply round-tripped it.
const STUB_HANDLE_RAW: u64 = 0x00D8_0001;

/// Base + length of the register window the driver-spawn path mints a
/// device-resource grant for (a `virt` virtio-MMIO transport). The stub
/// enumerates the grant through `resource_grants` and refuses to reply
/// unless exactly one well-formed MMIO grant (handle 1, non-zero length)
/// was delivered — so the host PASS proves the spawn minted and delivered
/// it. The stub does not map it: the `mmio_map` mapping mechanism is proven
/// by the `mmio_map_qemu_aarch64` vertical, and this vertical's dispatch
/// hook holds `NULL_MMIO_MAP_FACILITY` (one proof each).
const GRANT_MMIO_BASE: u64 = 0x0a00_0000;
const GRANT_MMIO_LEN: u64 = 0x200;

/// Cooperative-loop watchdog: maximum `step` iterations before the test
/// declares the handshake stalled. Sized generously for QEMU TCG.
const MAX_STEPS: u64 = 5_000_000;

/// Physical frames the live allocator serves (8 MiB): the stub's image
/// pages, its 1.125 MiB user stack, the startup block, its page tables, and
/// the 2 MiB arena block the kthread-stack allocator may chain.
const FRAME_COUNT: usize = 2048;

/// Stable audit-event ids for the QEMU transcript.
const TEST_START: EventId = EventId(4300);
const TEST_SPAWNED: EventId = EventId(4301);
const TEST_PASS: EventId = EventId(4302);

/// Failure finisher codes, distinct per failure site.
const FAIL_ZERO_FREQ: NonZeroU16 = fail_point!(1);
const FAIL_GIC: NonZeroU16 = fail_point!(2);
const FAIL_POOL: NonZeroU16 = fail_point!(3);
const FAIL_FRAMES: NonZeroU16 = fail_point!(4);
const FAIL_BIAS: NonZeroU16 = fail_point!(5);
const FAIL_TRUST: NonZeroU16 = fail_point!(6);
const FAIL_PORT: NonZeroU16 = fail_point!(7);
const FAIL_SCHED_NEW: NonZeroU16 = fail_point!(8);
const FAIL_HOOK_INSTALL: NonZeroU16 = fail_point!(9);
const FAIL_SPAWN: NonZeroU16 = fail_point!(10);
const FAIL_NO_DISPATCH: NonZeroU16 = fail_point!(11);
const FAIL_REPLY_DECODE: NonZeroU16 = fail_point!(12);
const FAIL_REPLY_OUTCOME: NonZeroU16 = fail_point!(13);
const FAIL_DRAINED_NO_REPLY: NonZeroU16 = fail_point!(14);
const FAIL_DEADLOCK: NonZeroU16 = fail_point!(15);
/// The direct physical map could not be installed over the board's RAM.
const FAIL_PHYSMAP: NonZeroU16 = fail_point!(16);

/// Size of the test's bump heap (4 MiB): the frame-allocator bitmap + buddy
/// lists, the leaked scheduler/hook/registries, and the spawn staging
/// buffers. Lives in `.bss` (zeroed by the boot trampoline).
const HEAP_SIZE: usize = 4 * 1024 * 1024;

/// Page-aligned backing store for the bump heap.
#[repr(C, align(4096))]
struct HeapStore([u8; HEAP_SIZE]);

static mut HEAP: HeapStore = HeapStore([0; HEAP_SIZE]);

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_SIZE) };

/// Page-table pool backing the boot identity space the test switches to so
/// the MMU is on before any atomic read-modify-write runs (the allocator,
/// the scheduler, and the registries all use them).
static BOOT_PAGE_TABLES: PageTablePool = PageTablePool::new();

/// Identity-mapped physical-frame backing store the live [`FrameAllocator`]
/// serves; `align(4096)` so each `PAGE_SIZE` slice is a whole frame, inside
/// the 2 GiB identity window the spawn producer's page-table walk requires.
#[repr(C, align(4096))]
struct FramePool([u8; PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; PAGE_SIZE * FRAME_COUNT]);

/// The dispatch-callback slot the production [`KernelDispatchHook`] is
/// published into — the vertical's analogue of the bin crate's
/// `DISPATCH_SLOT` (one slot per binary, set once).
static DISPATCH_SLOT: DispatchCallbackSlot = DispatchCallbackSlot::new();

/// Per-CPU bookkeeping backing the scheduler's arch handle (single-CPU
/// vertical).
static SCHED_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// Per-CPU bookkeeping backing the dispatch hook + spawn ctx arch handle
/// (a second instance, mirroring `wait_qemu_aarch64`'s producer storage).
static HOOK_ARCH_STORAGE: Aarch64ArchStorage<1> = Aarch64ArchStorage::new();

/// The conservative no-external-IRQ controller, exactly the shape
/// `kernel/core::init` installs when a port exposes no routing.
static IRQ_CONTROLLER: UnsupportedController = UnsupportedController;

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared aarch64 panic bridge (parks the CPU; the run then
/// times out and the harness reports the failure).
#[panic_handler]
fn driver_spawn_qemu_aarch64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_serial(info)
}

/// The syscall-dispatch callback the stub's `svc` traps reach. It mirrors
/// the production bin-crate callback (`dispatch_aarch64`): read the
/// kernel-stack args frame and forward through the resident production
/// [`KernelDispatchHook`] via the shared `dispatch_via_slot` bridge, which
/// resolves the caller context, runs the dispatch sequence, and turns
/// a yield/exit outcome into a `reschedule_current` context switch. An
/// empty slot or a missing caller context fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: the exception trampoline lays the frame out on the kernel
    // stack and only invokes us with a valid pointer; the array lives at
    // least until we return.
    let args = unsafe { read_raw_args(args_ptr) };
    match dispatch_via_slot(&DISPATCH_SLOT, number, args) {
        Some(value) => value,
        None => qemu_exit::exit_failure(FAIL_NO_DISPATCH),
    }
}

/// The capability set the device manager autoloads the driver under — the
/// *caller* set the gate intersects the driver manifest's request with.
/// `DRV_LOAD` is the gate's hard admission gate; `MEM_DMA` (the reply port's
/// send gate) and `IRQ_BIND` are the driver-class grants the signed manifest
/// requests, so the spawned stub's granted set is exactly `{MEM_DMA,
/// IRQ_BIND}` (manifest∩caller). A task without the
/// driver grant cannot forge a reply (fail closed).
fn autoload_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::DRV_LOAD);
    caps.insert(CapabilityId::MEM_DMA);
    caps.insert(CapabilityId::IRQ_BIND);
    caps
}

/// The reply port's required send capability — drawn from the driver's
/// granted set above.
fn reply_send_caps() -> CapabilitySet {
    let mut caps = CapabilitySet::empty();
    caps.insert(CapabilityId::MEM_DMA);
    caps
}

/// `/System/Drivers/` path the signed driver image is resolved under. Byte-for-byte; no alias resolution.
const DRIVER_PATH_STR: &str = "/System/Drivers/drvstub.rxe";

/// The discovered driver store: yields the build-signed [`DRIVER_IMAGE`]
/// (the `kind = UserSpace` manifest wrapping the stub `rxe` payload) for
/// [`DRIVER_PATH_STR`]. The `SpawnDriverLoader` gate verifies it against
/// [`DRIVER_SIGNER_PUBKEY`] before the payload is ever spawned.
struct StaticImageSource;

impl ImageSource for StaticImageSource {
    fn read(&self, path: &str, buf: &mut alloc::vec::Vec<u8>) -> Result<(), Errno> {
        if path == DRIVER_PATH_STR {
            buf.extend_from_slice(DRIVER_IMAGE);
            Ok(())
        } else {
            Err(Errno::NotFound)
        }
    }
}

/// Reply-port bound: comfortably one [`DriverRegisterReply`] record.
const REPLY_MAX_PAYLOAD: u32 = 64;

/// Reply-port mailbox depth: one in-flight reply plus headroom.
const REPLY_MAILBOX_CAPACITY: usize = 4;

/// Bring the board up for the handshake: FP/SIMD on, the `virt` device
/// tree discovered (timer rate, GICv2 bases), the identity MMU + EL1
/// vectors enabled, the GIC initialised, and the dispatch callback
/// installed. Returns the discovered generic-timer rate.
fn bring_up_board() -> u64 {
    // Enable FP/SIMD at EL1 before any code the compiler may lower to NEON
    // (the `rxe` decoder, `build_process_image`'s fills, the log formatter).
    // SAFETY: this is the boot CPU, called once, before any FP/SIMD executes.
    unsafe { enable_fp_el1() };

    // P3/P4: discover the board from the embedded `virt` device tree using
    // the early-returning node walks, which stay safe MMU-off.
    let Ok(fdt) = Fdt::new(DTB_BLOB) else {
        qemu_exit::exit_failure(FAIL_GIC);
    };
    let counter_hz = timer_frequency_hz(&fdt);
    if counter_hz == 0 {
        qemu_exit::exit_failure(FAIL_ZERO_FREQ);
    }
    if gic::configure_from_fdt(&fdt).is_none() {
        qemu_exit::exit_failure(FAIL_GIC);
    }

    // Configure the board's gigapage facts, exactly as the production boot
    // path derives them from discovery: Device GiB 0 is the `virt` MMIO
    // window, and GiB 1 holds both this kernel's image and its RAM. The
    // production spawn producer sizes every child's identity window from
    // these masks, so driving it under the unconfigured defaults would
    // request a window reaching the user bias and the spawn would fail
    // closed.
    let mut device_mask = [0u64; GIGAPAGE_MASK_WORDS];
    device_mask[0] = 0b01;
    configure_device_gigapages(device_mask);
    let mut ram_mask = [0u64; GIGAPAGE_MASK_WORDS];
    ram_mask[0] = 0b10;
    configure_kernel_gigapages(ram_mask);
    // The production spawn producer reaches a child's page tables through
    // the direct physical map in the kernel translation regime, so the
    // chassis stands it up over the same RAM before driving the producer.
    if !install_boot_physmap(&ram_mask) {
        qemu_exit::exit_failure(FAIL_PHYSMAP);
    }

    // Enable the identity MMU + EL1 vectors before any atomic
    // read-modify-write runs: the frame allocator, the scheduler, and every
    // registry the test builds use atomics, which are UNPREDICTABLE on
    // MMU-off Device-typed memory (`plans/PI.md` P6c-2).
    let Some(boot_space) =
        ArchAddressSpace::new_identity_gigapages(&BOOT_PAGE_TABLES, IDENTITY_GIB)
    else {
        qemu_exit::exit_failure(FAIL_POOL);
    };
    // SAFETY: the identity map covers the kernel's current `pc`, `sp`, the
    // heap, the frame pool, and the device MMIO (all within `[0, 2 GiB)` on
    // the `virt` board), so switching it does not move the ground under the
    // running code; `init_vectors` runs once on the boot CPU with a stack
    // established.
    unsafe {
        boot_space.switch();
        exceptions::init_vectors();
    }
    // The boot space's tables live in the static `BOOT_PAGE_TABLES` pool
    // and the handle carries no `Drop`, so letting it fall out of scope
    // leaves the active translation regime untouched for the kernel's
    // lifetime (the kernel never returns).
    // SAFETY: called once on the boot CPU after the GIC bases were
    // discovered above.
    unsafe {
        tairix_itest_gic::init_boot_cpu().expect("the GIC comes up");
    }
    syscall_entry::set_dispatch_callback(dispatch);
    counter_hz
}

/// The leaked-`'static` kernel subsystems the production dispatch hook and
/// spawn context borrow — the vertical's analogue of `KernelState`, lifted
/// by one-shot `Box::leak` publishes exactly as `kernel_core::kernel_main`
/// does, never a global mutable static.
struct Subsystems {
    frames: &'static FrameAllocator,
    sched: &'static Scheduler<Aarch64BinArch>,
    arch: &'static Aarch64BinArch,
    caps: &'static RwLock<CapTable>,
    peer_watch: &'static tairix_kernel_core::PeerWatch,
    ipc: &'static RwLock<PortRegistry>,
    aspaces: &'static RwLock<AddressSpaceRegistry>,
    rng: &'static RwLock<Box<dyn RandomReserve + Send + Sync>>,
    irq_table: &'static IrqTable,
}

/// Build the live kernel subsystems: the `kernel/mem` frame allocator over
/// the identity-mapped pool (so `spawn_with` draws its image, stack, and
/// page-table frames from the production path), the
/// scheduler over the production `KernelArch` wrapper, and the capability /
/// port / address-space / random / IRQ state the production hook borrows.
fn leak_subsystems(counter_hz: u64) -> Subsystems {
    let mut memory_map = BootMemoryMap::new();
    memory_map.push(MemoryRegion {
        start: PhysAddr::new(core::ptr::addr_of!(FRAME_POOL) as u64),
        length: (PAGE_SIZE * FRAME_COUNT) as u64,
        kind: RegionKind::Usable,
    });
    let Ok(frames) = FrameAllocator::new(&memory_map) else {
        qemu_exit::exit_failure(FAIL_FRAMES);
    };
    let frames: &'static FrameAllocator = Box::leak(Box::new(frames));

    let sched_arch = Arc::new(Aarch64BinArch::new(Aarch64Arch::new(
        &SCHED_STORAGE,
        BOOT_CPU,
        counter_hz,
    )));
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), sched_arch) else {
        qemu_exit::exit_failure(FAIL_SCHED_NEW);
    };

    Subsystems {
        frames,
        sched: Box::leak(Box::new(sched)),
        arch: Box::leak(Box::new(Aarch64BinArch::new(Aarch64Arch::new(
            &HOOK_ARCH_STORAGE,
            BOOT_CPU,
            counter_hz,
        )))),
        caps: Box::leak(Box::new(RwLock::new(CapTable::new()))),
        peer_watch: Box::leak(Box::new(tairix_kernel_core::PeerWatch::new())),
        ipc: Box::leak(Box::new(RwLock::new(PortRegistry::new()))),
        aspaces: Box::leak(Box::new(RwLock::new(AddressSpaceRegistry::new()))),
        rng: Box::leak(Box::new(RwLock::new(
            Box::new(BootReserve::new()) as Box<dyn RandomReserve + Send + Sync>
        ))),
        irq_table: Box::leak(Box::new(IrqTable::new(0))),
    }
}

/// Bind the reply port into the live registry: the host pseudo-task holds
/// exactly the bind authority a send-restricted port requires, and the port's send gate is a capability from the driver's
/// granted set, so only the spawned driver can complete the handshake.
fn bind_reply_port(ipc: &RwLock<PortRegistry>) {
    let mut host_grant = CapabilitySet::empty();
    host_grant.insert(CapabilityId::IPC_BIND_PRIVILEGED);
    let host_caps = TaskCapabilities::derive(
        ProcessId(0),
        UserId(0),
        host_grant,
        host_grant,
        &SERIAL_SINK,
    );
    let Ok(port) = Port::create(
        REPLY_ENDPOINT,
        &host_caps,
        reply_send_caps(),
        CapabilitySet::empty(),
        REPLY_MAX_PAYLOAD,
        REPLY_MAILBOX_CAPACITY,
        &SERIAL_SINK,
    ) else {
        qemu_exit::exit_failure(FAIL_PORT);
    };
    match ipc.write().register(port, &SERIAL_SINK) {
        Ok(id) if id == REPLY_ENDPOINT => {}
        _ => qemu_exit::exit_failure(FAIL_PORT),
    }
    // Publish the endpoint under its well-known name so the stub can
    // resolve it over the production `port_resolve` syscall.
    let Ok(name) = PortName::from_ascii(REPLY_PORT_NAME) else {
        qemu_exit::exit_failure(FAIL_PORT);
    };
    if ipc
        .write()
        .publish_name(name, REPLY_ENDPOINT, &SERIAL_SINK)
        .is_err()
    {
        qemu_exit::exit_failure(FAIL_PORT);
    }
}

/// Boot entry point — the symbol the arch crate's `boot.s` trampoline calls
/// (via `tairix_arch_aarch64_main`).
#[no_mangle]
pub extern "C" fn kernel_main(_dtb: u64) -> ! {
    note(TEST_START, "aarch64 driver-spawn test: starting");

    let counter_hz = bring_up_board();

    // The stub `rxe`'s baked relocations must target the bias the
    // production producer maps every child at; a drifted constant would
    // admit a child whose pointers do not match its mapping (fail closed).
    if USER_BIAS != USER_IMAGE_BIAS {
        qemu_exit::exit_failure(FAIL_BIAS);
    }

    let sys = leak_subsystems(counter_hz);

    bind_reply_port(sys.ipc);

    // Publish the production dispatch hook so the stub's syscalls run the
    // production caller-context resolution, copy-in, and `Port::send` path.
    let hook: &'static KernelDispatchHook<'static, Aarch64BinArch> = Box::leak(Box::new(
        KernelDispatchHook::new(
            sys.sched,
            sys.caps,
            sys.arch,
            &SERIAL_SINK,
            sys.irq_table,
            &IRQ_CONTROLLER,
            sys.ipc,
            sys.aspaces,
            sys.rng,
            &UART_ONLY_CONSOLES,
            sys.frames,
            sys.frames,
            // The stub is autoloaded + spawned through `SpawnDriverLoader`,
            // not the `spawn` syscall, so the hook's program registry is
            // unused here (the empty registry fails any
            // `spawn` closed).
            &EMPTY_PROGRAM_REGISTRY,
            &NULL_PROCESS_WAIT,
            // This test exercises the driver-spawn / IPC path, not keyboard
            // input; the seat registry stays fail-closed.
            &NULL_SEAT_REGISTRY,
            // This test exercises the driver-spawn / IPC path, not
            // `mem_map` / `mmio_map` / `dma_alloc`; those producers stay
            // fail-closed.
            &NULL_MEM_MAP,
            &NULL_MMIO_MAP_FACILITY,
            &NULL_DMA_ALLOC_FACILITY,
        )
        .with_peer_watch(sys.peer_watch),
    ));
    if DISPATCH_SLOT.install_dispatcher(hook).is_err() {
        qemu_exit::exit_failure(FAIL_HOOK_INSTALL);
    }

    // The discovered hardware tree: a root and one
    // device node carrying the register window it exposes as a
    // capability-grant request. On a real boot `FdtDiscovery` builds this;
    // here a virtio device stands in for the metal controller (§0.4 — no
    // Pi-board QEMU vertical exists). The node's `HwResource` is the matched
    // node's request the privileged spawn mints a grant for.
    let match_key = HwMatchKey::virtio(0x1234);
    let mut device = HwNode::new(2, 1, HwDeviceClass::Input);
    if device.push_match_key(match_key).is_err()
        || device
            .push_resource(HwResource::mmio(GRANT_MMIO_BASE, GRANT_MMIO_LEN))
            .is_err()
    {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    let tree = [HwNode::new(1, HW_NODE_ROOT, HwDeviceClass::Root), device];
    // The inventory the node is matched in, which admission checks still
    // holds it once the driver's grants are minted.
    let inventory = tairix_kernel::hwtree_store::HwTreeStore::new();
    if inventory.seed(tree.to_vec()).is_err() {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }

    // The driver candidate the discovered store yields: the signed image at
    // `DRIVER_PATH_STR` with a bind table that matches the node.
    let bind_keys = [DriverBindKey::new(5, match_key)];
    let candidates = [DriverCandidate {
        path: DRIVER_PATH_STR,
        bind_keys: &bind_keys,
    }];

    // The signed driver store, its sole trust anchor, and the production
    // spawn adapter the device manager reaches through the
    // `SpawnDriverLoader` seam. A corrupt embedded trust anchor fails closed.
    let Ok(signer) = Ed25519PublicKey::from_bytes(&DRIVER_SIGNER_PUBKEY) else {
        qemu_exit::exit_failure(FAIL_TRUST);
    };
    let trusted = [signer];
    let source = StaticImageSource;
    // Drive the *production* driver-spawn seam: the kernel/core
    // `KernelInitSpawner` owns the live registries and assembles the
    // `KernelSpawnCtx` internally, so this vertical reaches it through the bin
    // crate's `InitCtxDriverProcessSpawn` bridge rather than re-implementing
    // the context assembly. `NULL_PROCESS_WAIT`:
    // this vertical does not reap the long-lived spawned driver.
    // Publish the launch-services bundle the deferred driver-load path reads:
    // the arch image builder builds the autoloaded driver's image on the
    // driver task's own first slice. The one shared build+publish the
    // production boot path uses.
    let _ = tairix_kernel_core::spawn_services::install_over(
        sys.arch,
        sys.frames,
        &SERIAL_SINK,
        &tairix_kernel_core::NULL_FILESYSTEM,
        None,
        sys.aspaces,
        sys.caps,
        sys.peer_watch,
        &NULL_PROCESS_WAIT,
        &AARCH64_PROCESS_SPAWN,
    );
    let init_ctx = KernelInitSpawner::new(
        sys.frames,
        &SERIAL_SINK,
        sys.sched,
        sys.caps,
        sys.peer_watch,
        sys.aspaces,
        sys.arch,
        &NULL_PROCESS_WAIT,
        sys.irq_table,
        &IRQ_CONTROLLER,
        &NULL_SHARED_MEM_FACILITY,
        KernelArch::cross_cpu_tlb_shootdown(sys.arch),
    );
    let spawn = InitCtxDriverProcessSpawn::new(&init_ctx);
    let args: [&[u8]; 3] = [b"drvstub", REPLY_ENDPOINT_ARG, REPLY_PORT_NAME];
    // The matched node id (the device node, id 2) the kernel records against
    // the spawned driver so its `hw_emit_node` children parent under it.
    let mut loader = SpawnDriverLoader::new(
        &trusted,
        &source,
        &SERIAL_SINK,
        &spawn,
        &args,
        Some(tairix_kernel_core::DriverNode {
            id: 2,
            tree: &inventory,
        }),
    );

    // The autoload walk: match each node against the candidates, run
    // the signed `Host::load` gate on the winner, and spawn it with the
    // matched node's MMIO resource as its sole device-resource grant — the
    // production "drivers in user space" discovery path (`plans/PI.md` P10
    // 5d-2-ii). A node that fails to match or load binds nothing, so the
    // run fails closed below.
    let report = DeviceManager::new(&SERIAL_SINK).autoload(
        &tree,
        &candidates,
        &autoload_caps(),
        &mut loader,
    );
    if report.bindings.len() != 1 {
        qemu_exit::exit_failure(FAIL_SPAWN);
    }
    note(
        TEST_SPAWNED,
        "aarch64 driver-spawn test: driver autoloaded + spawned with reply endpoint",
    );

    // The budget-bounded cooperative wait: step the scheduler and poll the
    // reply port between steps. The stub runs, sends its register reply
    // over production `ipc_send`, and exits; a missing, malformed, or
    // wrong-handle reply fails loudly.
    let mut steps = 0u64;
    while steps < MAX_STEPS {
        let _ = sys.sched.step(BOOT_CPU);
        steps += 1;

        let message = sys
            .ipc
            .read()
            .lookup(REPLY_ENDPOINT)
            .and_then(tairix_kernel_ipc::Port::recv);
        if let Some(message) = message {
            // Fail-closed decode: an inconsistent record is rejected whole.
            let Ok(reply) = DriverRegisterReply::from_bytes(message.payload.as_bytes()) else {
                qemu_exit::exit_failure(FAIL_REPLY_DECODE);
            };
            match reply.outcome() {
                Ok(handle) if handle.as_u64() == STUB_HANDLE_RAW => {
                    note(
                        TEST_PASS,
                        "aarch64 driver-spawn test: register reply received and verified",
                    );
                    qemu_exit::exit_success();
                }
                _ => qemu_exit::exit_failure(FAIL_REPLY_OUTCOME),
            }
        }

        // A drained workload without a reply means the stub exited down a
        // diagnostic path (or never sent); fail with a distinct finisher.
        if sys.sched.live_task_count() == 0 {
            qemu_exit::exit_failure(FAIL_DRAINED_NO_REPLY);
        }
    }
    qemu_exit::exit_failure(FAIL_DEADLOCK);
}
