//! The x86_64 X4 test kernel: boot the production pipeline, then on
//! `BootCompleted` build a child and a parent ring-3 program, register their
//! parent/child link with a `KernelProcessWait` producer, and prove the parent
//! reaps the child's exit code under the live scheduler (`plans/PI.md` X4 —
//! the cross-port sibling of the aarch64 `wait_qemu_aarch64`).

use core::panic::PanicInfo;
use core::sync::atomic::{AtomicBool, AtomicU64, AtomicUsize, Ordering};

use alloc::boxed::Box;
use alloc::sync::Arc;

use tairix_abi::rxe::LoadImage;
use tairix_abi::{
    CapabilityId, CapabilityQuery, Errno, SyscallNumber, WaitFlags, WaitStatus, WaitStatusRecord,
    SYSCALL_MAX_ARGS,
};
use tairix_arch_api::{EnterUser, UserEntry, BOOT_CPU};
use tairix_arch_x86_64::context_hal::ContextSwitchHal;
use tairix_arch_x86_64::kernel_arch::{X86_64Arch, X86_64ArchStorage};
use tairix_arch_x86_64::paging::{self, activate_user_root, KERNEL_VMA_BASE};
use tairix_arch_x86_64::userentry::UserMode;
use tairix_arch_x86_64::{qemu_exit, smp, syscall_entry};
use tairix_kernel::kalloc::{Heap, HEAP_BYTES};
use tairix_kernel::{
    boot, handle_panic_via_kernel_core, FreeListAllocator, SerialSink, SERIAL_SINK,
};
use tairix_kernel_core::{
    reschedule_current, spawn_image, spawn_user_kthread, KernelProcessWait, ProcessWait,
    RescheduleAction, SpawnMode, SpawnRequest, Yielder,
};
use tairix_kernel_mem::{
    copy_out, AddressSpace, DirectPhysMap, Frame, PhysAddr, PhysMap, UserAddressSpace, UserStack,
    VirtAddr,
};
use tairix_kernel_sched_cfq::{Priority, Scheduler, SchedulerConfig};
use tairix_kernel_sec::{ProcessId, TaskId};
use tairix_kernel_syscall::SYSCALL_TABLE_HASH;
use tairix_log::{log, Event, EventId, Level, Sink};
use tairix_sync::SpinLock;

// `CHILD_RXE`, `PARENT_RXE`, `USER_BIAS`, and `CHILD_EXIT_CODE`, generated by
// `build.rs`.
include!(concat!(env!("OUT_DIR"), "/program_rxe.rs"));

/// `EventId` emitted when every boot init phase completed.
const BOOT_COMPLETED_EVENT_ID: EventId = EventId(4004);

/// User stack base (1 MiB into the high user region) and size.
const USER_STACK_BASE: u64 = USER_BIAS + 0x10_0000;
/// User stack pages (256 KiB) — generous headroom for `tairix-rt`'s heap arena.
const USER_STACK_PAGES: u64 = 64;
/// User virtual address the startup-vector block is written at (3 MiB up).
const USER_BLOCK_BASE: u64 = USER_BIAS + 0x30_0000;

/// Per-process stack-canary seed handed to each program.
const CANARY: u64 = 0x5520_C000_D15E_A5ED;

/// `IA32_EFER` MSR number and its No-Execute-Enable bit (bit 11).
const IA32_EFER: u32 = 0xC000_0080;
const EFER_NXE: u64 = 1 << 11;

/// Physical frames the test hands each spawn build.
const FRAME_COUNT: usize = 256;

/// Cooperative-loop watchdog: maximum `step` iterations before deadlock.
const MAX_STEPS: u64 = 5_000_000;

/// Stable audit-event ids for the QEMU transcript (clear of the boot range
/// and the X1/X2 ids).
const TEST_START: EventId = EventId(4330);
const TEST_SPAWNED: EventId = EventId(4331);
const TEST_PASS: EventId = EventId(4332);
const TEST_FAIL: EventId = EventId(4333);

/// Set once the round-trip has been driven so a duplicate `BootCompleted`
/// cannot re-enter the test logic.
static TEST_DRIVEN: AtomicUsize = AtomicUsize::new(0);

/// Set once the producer reaped a child whose code matched [`CHILD_EXIT_CODE`].
static REAP_OK: AtomicBool = AtomicBool::new(false);
/// Scheduler task id of the parent (the program that calls `wait`).
static PARENT_TID: AtomicU64 = AtomicU64::new(u64::MAX);

/// Static heap for the bump allocator (per the production bin).
static mut HEAP: Heap = Heap::ZERO;

/// Global allocator backed by [`HEAP`].
///
/// SAFETY: the page-aligned `HEAP` static outlives the binary and the
/// allocator is its only consumer.
#[global_allocator]
static ALLOCATOR: FreeListAllocator =
    unsafe { FreeListAllocator::new(core::ptr::addr_of!(HEAP) as *mut u8, HEAP_BYTES) };

/// Per-space page-table pools (one per ring-3 address space).
static PAGE_TABLE_POOL_CHILD: paging::PageTablePool = paging::PageTablePool::new();
static PAGE_TABLE_POOL_PARENT: paging::PageTablePool = paging::PageTablePool::new();

/// Physical-frame backing store the spawn builders draw user pages from.
#[repr(C, align(4096))]
struct FramePool([u8; paging::PAGE_SIZE * FRAME_COUNT]);

static mut FRAME_POOL: FramePool = FramePool([0; paging::PAGE_SIZE * FRAME_COUNT]);

/// Monotonic index of the next free [`FRAME_POOL`] frame, shared by both builds.
static FRAME_CURSOR: AtomicUsize = AtomicUsize::new(0);

/// Hand out the next physical frame from [`FRAME_POOL`], or `None` when
/// exhausted. The pool is a higher-half kernel static, so its physical address
/// is its virtual address minus [`KERNEL_VMA_BASE`].
fn next_frame() -> Option<Frame> {
    let idx = FRAME_CURSOR.fetch_add(1, Ordering::SeqCst);
    if idx >= FRAME_COUNT {
        FRAME_CURSOR.store(FRAME_COUNT, Ordering::SeqCst);
        return None;
    }
    let offset = idx * paging::PAGE_SIZE;
    let virt = core::ptr::addr_of!(FRAME_POOL) as u64 + offset as u64;
    Some(Frame::containing(PhysAddr::new(virt - KERNEL_VMA_BASE)))
}

fn note(id: EventId, message: &'static str) {
    log(
        &SERIAL_SINK,
        &Event {
            level: Level::Info,
            id,
            message,
            fields: &[],
        },
    );
}

/// Forward to the shared bridge in `tairix_kernel`.
#[panic_handler]
fn wait_qemu_x86_64_panic(info: &PanicInfo<'_>) -> ! {
    handle_panic_via_kernel_core(info)
}

/// A [`CapabilityQuery`] granting exactly `CAP_PROC_SPAWN`.
struct SpawnAuthority;
impl CapabilityQuery for SpawnAuthority {
    fn holds(&self, cap: CapabilityId) -> bool {
        cap == CapabilityId::PROC_SPAWN
    }
}

/// The single installed process-wait producer, set once before dispatch fires.
static PRODUCER: SpinLock<Option<&'static KernelProcessWait<X86_64Arch>>> = SpinLock::new(None);
/// The live scheduler, leaked `'static` so the dispatch callback can resolve
/// the current task id.
static SCHED: SpinLock<Option<&'static Scheduler<X86_64Arch>>> = SpinLock::new(None);
/// The parent's frozen address space + direct map, used to copy the reaped
/// child's exit code out to the parent's `status` pointer.
#[allow(clippy::type_complexity)]
static PARENT_SPACE: SpinLock<
    Option<(
        Box<dyn UserAddressSpace + Send + Sync>,
        Box<dyn PhysMap + Send + Sync>,
    )>,
> = SpinLock::new(None);

/// Outer audit sink: replays every event to serial and, on the single
/// [`BOOT_COMPLETED_EVENT_ID`], drives [`run_wait`].
struct BootCompletedSink;

impl Sink for BootCompletedSink {
    fn write_event(&self, event: &Event<'_>) {
        SerialSink::new().write_event(event);

        if event.id == BOOT_COMPLETED_EVENT_ID
            && TEST_DRIVEN
                .compare_exchange(0, 1, Ordering::AcqRel, Ordering::Acquire)
                .is_ok()
        {
            run_wait();
        }
    }
}

static AUDIT_SINK: BootCompletedSink = BootCompletedSink;

/// Resolve the scheduler's current task id on [`BOOT_CPU`], failing the test if
/// none is set (it always is inside a dispatched task's `syscall`).
fn current_task_id() -> u64 {
    let sched = match *SCHED.lock() {
        Some(s) => s,
        None => {
            note(TEST_FAIL, "X4 test: no scheduler installed");
            qemu_exit::exit_failure();
        }
    };
    match sched.current_task(BOOT_CPU) {
        Some(id) => id,
        None => {
            note(TEST_FAIL, "X4 test: no current task on the boot CPU");
            qemu_exit::exit_failure();
        }
    }
}

/// Encode a `Result<u64, Errno>` into the syscall return register following the
/// `abi-v1` signed convention (non-negative on success, `-errno` on error).
fn encode(result: Result<u64, Errno>) -> u64 {
    match result {
        Ok(value) => value,
        Err(err) => (-i64::from(err.as_i32())) as u64,
    }
}

/// The syscall-dispatch callback both ring-3 programs' `syscall` traps reach.
///
/// `wait` is routed through the installed [`PRODUCER`] (the `ProcessWait` seam,
/// exactly as the production handler does): the producer parks the parent until
/// the child is reapable, then the callback copies the reaped exit code out to
/// the parent's `status` pointer and records whether the round-trip matched.
/// `exit` records the caller's exit code with the producer and reaps the caller
/// (`reschedule_current`); a parent that exits 0 after a verified reap is the
/// PASS. Any other syscall is unexpected and fails the test loudly.
extern "C" fn dispatch(number: u64, args_ptr: *const [u64; SYSCALL_MAX_ARGS]) -> u64 {
    // SAFETY: `args_ptr` points at the live `[u64; SYSCALL_MAX_ARGS]` the
    // syscall entry stub built from the saved register frame.
    let args = unsafe { &*args_ptr };
    let call = SyscallNumber::from_register(number).ok();
    let producer = match *PRODUCER.lock() {
        Some(p) => p,
        None => {
            note(TEST_FAIL, "X4 test: no process-wait producer installed");
            qemu_exit::exit_failure();
        }
    };
    let cur = current_task_id();

    if call == Some(SyscallNumber::WAIT) {
        // The slot is decoded exactly as the dispatcher decodes it: a pid
        // occupies the whole register.
        let pid = args[0].cast_signed();
        // Decode the flags fail-closed, exactly as the production dispatcher
        // does (a reserved bit never reaches the producer).
        #[allow(clippy::cast_possible_truncation)]
        let flags = match WaitFlags::from_bits(args[2] as u32) {
            Ok(flags) => flags,
            Err(err) => return encode(Err(err)),
        };
        match producer.wait(ProcessId(cur), TaskId(cur), pid, flags) {
            Ok(reaped) => {
                // Copy the typed status record out to the parent's `status`
                // pointer through the validated boundary, exactly as the
                // production `wait` handler does.
                if !copy_status_to_parent(args[1], reaped.status) {
                    note(TEST_FAIL, "X4 test: could not copy status to parent");
                    qemu_exit::exit_failure();
                }
                if reaped.status == WaitStatus::Exited(CHILD_EXIT_CODE) {
                    REAP_OK.store(true, Ordering::SeqCst);
                }
                encode(Ok(u64::from(reaped.pid)))
            }
            Err(err) => encode(Err(err)),
        }
    } else if call == Some(SyscallNumber::EXIT) {
        // The slot is decoded exactly as the dispatcher decodes it: the
        // register carries the argument sign-extended to 32 bits.
        #[allow(clippy::cast_possible_truncation)]
        let code = args[0] as i32;
        producer.record_exit(ProcessId(cur), code);
        if cur == PARENT_TID.load(Ordering::SeqCst) {
            // The parent verified the reaped code and returned 0 on success.
            if code == 0 && REAP_OK.load(Ordering::SeqCst) {
                note(
                    TEST_PASS,
                    "x86_64 wait test: parent reaped the child, read its code, and exited 0",
                );
                qemu_exit::exit_success();
            }
            note(TEST_FAIL, "X4 test: parent exited without a verified reap");
            qemu_exit::exit_failure();
        }
        // A child exited: re-ready the parent on *this* vertical's own
        // scheduler. `record_exit` above asks for the wake through the global
        // `procwait_wake` hook, but the boot pipeline already bound that hook
        // to the *production* scheduler it built
        // (`kernel_core::init::publish_wait_queue_arch`, a set-once
        // `OnceCell`), which knows nothing of the scheduler `run_wait` leaks
        // here. Without this the producer parks a parent whose `wait` ran
        // before the child exited and nothing ever wakes it, so the workload
        // drains with the parent stuck parked — the intermittent
        // "drained without a verified reap" failure. Driving `unpark` on this
        // scheduler is the harness's equivalent of the production wait path's
        // wake (`SchedWaitQueueArch::unpark`), so the parent resumes from its
        // cooperative park (the X4 deliverable). `unpark` is cancellation-safe: on a parent not yet parked it records a
        // wake-pending token its next park commit consumes, and an
        // already-reaped/exited parent id is a benign no-op.
        if let Some(sched) = *SCHED.lock() {
            let _ = sched.unpark(PARENT_TID.load(Ordering::SeqCst));
        }
        // The child (or a parent on the failure path): reap the caller. This
        // switches back to the dispatcher and never resumes the task.
        let _ = reschedule_current(BOOT_CPU, RescheduleAction::Exit);
        0
    } else {
        note(TEST_FAIL, "X4 test: fixture issued an unexpected syscall");
        qemu_exit::exit_failure();
    }
}

/// Copy the typed wait-status record out to the parent's `status`
/// pointer through the retained frozen parent space. Returns `false` on a
/// faulting or unmapped pointer (fail closed).
fn copy_status_to_parent(status_va: u64, status: WaitStatus) -> bool {
    let guard = PARENT_SPACE.lock();
    let Some((space, physmap)) = guard.as_ref() else {
        return false;
    };
    let bytes = WaitStatusRecord::encode(status).to_ne_bytes();
    copy_out(
        space.as_ref(),
        physmap.as_ref(),
        VirtAddr::new(status_va),
        &bytes,
    )
    .is_ok()
}

/// Build one isolated ring-3 address space from `rxe` over the per-space
/// `pool`, returning its PML4 root and the entry register state. The new space
/// carries the live identity window and the higher-half kernel window; it is
/// activated (so the user mappings land in it) and the image is built through
/// the production capability-checked, audited `spawn_image` caller. Fails the
/// test loudly on any error.
fn build_el0_space(
    pool: &'static paging::PageTablePool,
    image: &LoadImage,
    rxe: &[u8],
    is_parent: bool,
) -> (u64, UserEntry) {
    let Some(arch_space) = paging::AddressSpace::new_boot_identity(pool) else {
        note(TEST_FAIL, "X4 test: page-table pool exhausted");
        qemu_exit::exit_failure();
    };
    let root_phys = arch_space.pml4_phys();
    // SAFETY: the new space carries the live identity window and the
    // higher-half kernel window, so the executing RIP, the current stack, the
    // per-CPU `swapgs` TLS, the page-table pools, the frame pool, the heap,
    // `dispatch`, and every LAPIC MMIO access stay mapped across the CR3
    // switch.
    unsafe { arch_space.switch() };

    let mut space = AddressSpace::new(arch_space);
    // SAFETY: the boot code installs this direct map and never unmaps it.
    let physmap = unsafe { DirectPhysMap::new(KERNEL_VMA_BASE, 1 << 30) }
        .expect("the boot direct map addresses its window");
    let request = SpawnRequest {
        image,
        image_bytes: rxe,
        bias: USER_BIAS,
        stack: UserStack {
            base: USER_STACK_BASE,
            page_count: USER_STACK_PAGES,
        },
        start_block_base: USER_BLOCK_BASE,
        args: &[b"wait"],
        env: &[],
        canary: CANARY,
    };

    // SAFETY: building the image is itself safe; the returned `UserEntry` is
    // only entered later, once its space is reactivated (via `pre_resume`) and
    // the GDT user selectors / TSS / `syscall` entry + dispatch callback are
    // installed. Frames are drawn from `FRAME_POOL` through the shared cursor.
    let entry = match unsafe {
        spawn_image(
            &SpawnAuthority,
            SpawnMode::General,
            &SERIAL_SINK,
            &mut space,
            &physmap,
            &request,
            next_frame,
        )
    } {
        Ok(entry) => entry,
        Err(_) => {
            note(TEST_FAIL, "X4 test: spawn_image failed");
            qemu_exit::exit_failure();
        }
    };

    // Retain the *parent's* frozen space so the `wait` handler can copy the
    // reaped child's exit code out to the parent's `status` pointer. Only the
    // parent calls `wait`, so only its space is kept.
    if is_parent {
        let frozen: Box<dyn UserAddressSpace + Send + Sync> = Box::new(space.freeze());
        let pm: Box<dyn PhysMap + Send + Sync> = Box::new(physmap);
        *PARENT_SPACE.lock() = Some((frozen, pm));
    }

    (root_phys, entry)
}

/// Admit `entry` as a resumable user kthread whose `pre_resume` hook reloads
/// `root_phys` (CR3) and repoints the per-CPU syscall entry stack at the task's
/// own kernel stack before every switch-in (isolation). Returns its task id.
fn admit(sched: &Scheduler<X86_64Arch>, root_phys: u64, entry: UserEntry) -> u64 {
    let cs = ContextSwitchHal::new();
    let user_mode = UserMode::new();
    let pre_resume = move |kernel_stack_top: u64| {
        // `set_kernel_rsp0` repoints **both** this task's `syscall` entry
        // stack (`gs:0`) and its trap entry stack (`TSS.RSP0`) at its own
        // kernel stack, so an involuntary LAPIC-timer preemption (P-1c) taken
        // from ring 3 (delivered through the IDT interrupt gate, which reads
        // `TSS.RSP0`) lands on this task's own stack and the parent's and
        // child's preemptions never collide (one per-task
        // kernel stack for both entry kinds). A rejected value leaves the
        // slots unchanged and the next entry faults loudly — fail closed.
        if syscall_entry::set_kernel_rsp0(BOOT_CPU as usize, kernel_stack_top).is_err() {
            note(TEST_FAIL, "X4 test: set_kernel_rsp0 rejected the stack top");
            qemu_exit::exit_failure();
        }
        // SAFETY: paging is enabled and `root_phys` is the PML4 of the task's
        // space, which maps the low identity + higher-half kernel window the
        // running dispatcher executes from — `activate_user_root`'s contract.
        unsafe { activate_user_root(root_phys) };
    };
    let work = move |_yielder: &mut Yielder<ContextSwitchHal>| {
        // SAFETY: by the time this body runs the task has been dispatched, so
        // its `pre_resume` hook reloaded CR3 + repointed the entry stack, and
        // the GDT user selectors / TSS / `syscall` entry + dispatch callback
        // are installed; the program's first `syscall` is handled.
        unsafe { user_mode.enter_user(entry) }
    };
    match spawn_user_kthread(sched, cs, BOOT_CPU, Priority::Normal, pre_resume, work) {
        Ok(id) => id,
        Err(_) => {
            note(TEST_FAIL, "X4 test: spawn_user_kthread failed");
            qemu_exit::exit_failure();
        }
    }
}

/// Build the child + parent ring-3 images, install the producer, register the
/// link, admit both as resumable user kthreads, and drive the cooperative
/// `step` loop until the parent reaps the child. Never returns.
fn run_wait() -> ! {
    note(TEST_START, "x86_64 X4 wait test: starting");

    // Enable `IA32_EFER.NXE` so the W^X No-Execute leaf bit the adapter sets on
    // data/rodata pages is honoured rather than treated as reserved.
    // SAFETY: reading and writing `IA32_EFER` is the documented enable
    // sequence; it runs once on the BSP and only sets bit 11, preserving
    // `SCE`/`LME`/`LMA` the boot pipeline established.
    unsafe {
        let lo: u32;
        let hi: u32;
        core::arch::asm!(
            "rdmsr",
            in("ecx") IA32_EFER,
            out("eax") lo,
            out("edx") hi,
            options(nostack, preserves_flags),
        );
        let efer = (((hi as u64) << 32) | lo as u64) | EFER_NXE;
        core::arch::asm!(
            "wrmsr",
            in("ecx") IA32_EFER,
            in("eax") efer as u32,
            in("edx") (efer >> 32) as u32,
            options(nostack, preserves_flags),
        );
    }

    syscall_entry::set_dispatch_callback(dispatch);

    // Parse the two build-time `rxe` blobs against the kernel's own CFI tag.
    let Ok(child_image) = LoadImage::parse(CHILD_RXE, &SYSCALL_TABLE_HASH) else {
        note(TEST_FAIL, "X4 test: child rxe image failed to parse");
        qemu_exit::exit_failure();
    };
    let Ok(parent_image) = LoadImage::parse(PARENT_RXE, &SYSCALL_TABLE_HASH) else {
        note(TEST_FAIL, "X4 test: parent rxe image failed to parse");
        qemu_exit::exit_failure();
    };

    // Build the two isolated ring-3 address spaces (child first; each task's
    // `pre_resume` reactivates the correct root on dispatch).
    let (child_root, child_entry) =
        build_el0_space(&PAGE_TABLE_POOL_CHILD, &child_image, CHILD_RXE, false);
    let (parent_root, parent_entry) =
        build_el0_space(&PAGE_TABLE_POOL_PARENT, &parent_image, PARENT_RXE, true);

    // Build the live scheduler over the production arch handle. Interrupts stay
    // masked, so dispatch is the cooperative `step` loop below.
    let bsp_id = smp::bsp_lapic_id();
    // Single-CPU vertical (BSP, dense id 0): both arch handles size their
    // per-CPU bookkeeping to one slot (no baked-in
    // `MAX_CPUS`).
    let cpu_to_lapic: [Option<u8>; 1] = [Some(bsp_id)];
    // The arch handle borrows its per-CPU bookkeeping from a caller-sized
    // `&'static` backing; this vertical is single-CPU,
    // and `run_wait` runs once, so a function-local `static` per handle is
    // sound and needs no allocator.
    static SCHED_ARCH_STORAGE: X86_64ArchStorage<1> = X86_64ArchStorage::new();
    let Ok(arch) = X86_64Arch::new(&SCHED_ARCH_STORAGE, 0, bsp_id, &cpu_to_lapic) else {
        note(TEST_FAIL, "X4 test: X86_64Arch::new failed");
        qemu_exit::exit_failure();
    };
    let arch = Arc::new(arch);
    let Ok(sched) = Scheduler::new(SchedulerConfig::defaults_for(1), arch) else {
        note(TEST_FAIL, "X4 test: Scheduler::new failed");
        qemu_exit::exit_failure();
    };
    let sched: &'static Scheduler<X86_64Arch> = Box::leak(Box::new(sched));
    *SCHED.lock() = Some(sched);

    // Build the process-wait producer over its own leaked arch handle.
    static PRODUCER_ARCH_STORAGE: X86_64ArchStorage<1> = X86_64ArchStorage::new();
    let Ok(producer_arch) = X86_64Arch::new(&PRODUCER_ARCH_STORAGE, 0, bsp_id, &cpu_to_lapic)
    else {
        note(TEST_FAIL, "X4 test: producer X86_64Arch::new failed");
        qemu_exit::exit_failure();
    };
    let producer_arch: &'static X86_64Arch = Box::leak(Box::new(producer_arch));
    let producer: &'static KernelProcessWait<X86_64Arch> =
        Box::leak(Box::new(KernelProcessWait::new(producer_arch)));
    *PRODUCER.lock() = Some(producer);

    // Admit the **parent first** so the cooperative `step` loop dispatches it
    // before the child: the parent's `wait` then runs while the child is still
    // registered-but-unexited, forcing the producer to *park* the parent
    // (`Reap::Blocked` → `reschedule_current`). The child then runs and exits,
    // and the parent is re-dispatched to reap it — exercising the
    // resume-after-cooperative-park return-state path on the x86_64 trap (the
    // X4 deliverable), not the immediate-reap shortcut a child-first order
    // would take.
    let parent_tid = admit(sched, parent_root, parent_entry);
    let child_tid = admit(sched, child_root, child_entry);
    PARENT_TID.store(parent_tid, Ordering::SeqCst);
    if producer
        .register_child(
            ProcessId(parent_tid),
            ProcessId(child_tid),
            tairix_kernel_core::ChildListing::Listed,
        )
        .is_err()
    {
        note(TEST_FAIL, "X4 test: the child registration was refused");
        qemu_exit::exit_failure();
    }
    note(TEST_SPAWNED, "x86_64 X4 wait test: parent + child spawned");

    // Cooperative dispatch loop. The parent's `wait` parks it until the child
    // exits; the parent's verified `exit(0)` is the PASS (raised from the
    // dispatch callback). A never-draining loop times out (fail-loud).
    let mut steps = 0u64;
    while sched.live_task_count() != 0 && steps < MAX_STEPS {
        let _ = sched.step(BOOT_CPU);
        steps += 1;
    }

    // Reaching here means the workload drained without the parent's verified
    // exit raising PASS — a missed reap or a stall.
    note(
        TEST_FAIL,
        "X4 test: workload drained without a verified reap",
    );
    qemu_exit::exit_failure();
}

/// The symbol the arch crate's boot trampoline calls.
#[no_mangle]
pub extern "C" fn kernel_main(multiboot_info: u64) -> ! {
    boot(
        multiboot_info,
        &ALLOCATOR,
        &SERIAL_SINK,
        &AUDIT_SINK,
        tairix_log::Level::Info,
    )
}
